### ISSUE TITLE
Border style settings gets more ignored than used

### ISSUE THREAD

**Issue by weilbith** [glepnir/lspsaga.nvim#10]
Hey,
I adopted the style of the borders in the init function. But while starting to use the plugin, I realized that the border style does not always get applied. Then I looked into the code and saw that the users configuration gets most likely never respected. Instead it is chosen random like all other the place, individual for each use case.
Why is that? Did I got this configuration option wrong?

**Comment by glepnir** [comment]
fixed

**Comment by weilbith** [comment]
Perfect! :partying_face:
