### ISSUE TITLE
Getting error `vim.keymap.lua lhs: expected string, got number`

### ISSUE THREAD

**Issue by farzadmf** [glepnir/lspsaga.nvim#1002]
### Describe the bug

When I open `peek_definition` in LspSaga, I get the following error:
```
Error executing vim.schedule lua callback: vim/keymap.lua:0: lhs: expected string, got number
stack traceback:
	[C]: in function 'error'
	vim/shared.lua: in function 'validate'
	vim/keymap.lua: in function 'set'
	...y/data/nvim/lazy/lspsaga.nvim/lua/lspsaga/definition.lua:89: in function 'apply_aciton_keys'
	...y/data/nvim/lazy/lspsaga.nvim/lua/lspsaga/definition.lua:258: in function 'callback'
	...w/Cellar/neovim/0.8.3/share/nvim/runtime/lua/vim/lsp.lua:1952: in function 'handler'
	...w/Cellar/neovim/0.8.3/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps to reproduce

Sorry, I have quite a few plugins and it's a bit hard to create a minimal config.

Let me know if that's absolutely necessary, and I can provide one.

### Expected behavior

LspSaga was working fine.

I tried going back in time and the commit that breaks seems to be [8518a03](https://github.com/glepnir/lspsaga.nvim/commit/8518a03ab36be2baf95ba6b3e5d5066dc5203c2f)

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

a86ff8f

### Terminal name/version

wezterm 20230326-111934-3666303c

**Comment by farzadmf** [comment]
This is my config (using `lazy.nvim`):
```
{
  url = 'https://github.com/glepnir/lspsaga.nvim',
  name = 'lspsaga.nvim',
  event = { 'BufRead', 'BufNew' },
  opts = {
    ui = {
      border = 'rounded',
    },
    -- definition = {
    --   edit = '<C-c><cr>',
    --   quit = 'q',
    --   split = '<C-c><C-x>',
    --   tabe = '<C-c><C-t>',
    --   vsplit = '<C-c><C-v>',
    -- },
    finder = {
      keys = {
        expand_or_jump = '<C-c><cr>',
        vsplit = '<C-c><C-v>',
        split = '<C-c><C-x>',
        tabe = '<C-c><C-t>',
        quit = { 'q', '<ESC>' },
        close_in_preview = '<ESC>',
      },
    },
    beacon = {
      enable = true,
      frequency = 16,
    },
  },
  config = function(_, opts)
    local keymap = vim.keymap.set
    require('lspsaga').setup(opts)

    keymap('n', 'gd', '<cmd>Lspsaga peek_definition<CR>')
    keymap('n', 'gh', '<cmd>Lspsaga lsp_finder<CR>')
    keymap('n', 'K', '<cmd>Lspsaga hover_doc ++keep<CR>')
    keymap('n', '<leader>o', '<cmd>Lspsaga outline<CR>')
  end,
}
```

The `definition` part is commented out since I thought it's an issue with my config, but the error happens no matter what whether it's enabled or not

**Comment by farzadmf** [comment]
@glepnir is the `definition` section of my config the correct way to assign key bindings for `peek_definition`?

I do `gd` (which is mapped to `Lspsaga peek_definition`), but seems like the only keybinding that works is the default `q` to close the window.

If I keep the section commented and try the default ones (`<C-c>v`, `<C-c>i`, etc.), those don't seem to do anything either

**Comment by glepnir** [comment]
should be fixed.
