### ISSUE TITLE
finder cannot peek

### ISSUE THREAD

**Issue by st0nie** [glepnir/lspsaga.nvim#1007]
### Describe the bug

E5108: Error executing lua: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:578: Failed to 
switch to window 1013
stack traceback:
        [C]: in function 'nvim_set_current_win'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:578: in function <...te/pack/packer
/start/lspsaga.nvim/lua/lspsaga/finder.lua:576>
Press ENTER or type command to continue

### Steps to reproduce

min.lua
```lua
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.stdpath("config"))
vim.opt.packpath:remove(vim.fn.stdpath("data") .. "/site")
vim.opt.termguicolors = true
vim.opt.laststatus = 0

-- append test directory
local test_dir = "/tmp/nvim-config"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
	vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
	vim.cmd("packadd packer.nvim")
	install_plugins = true
end

local packer = require("packer")

packer.init({
	package_root = test_dir .. "/pack",
	compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

packer.startup(function(use)
	-- Packer can manage itself
	use("wbthomason/packer.nvim")
	use("neovim/nvim-lspconfig")
	use("glepnir/lspsaga.nvim")
	if install_plugins then
		packer.sync()
	end
end)

local lspconfig = require("lspconfig")

lspconfig.clangd.setup({})

require("lspsaga").setup({})
```

nvim --clean -u min.lua test.c

:Lspsaga lsp_finder

press p

### Expected behavior

The peek window should open and the cursor will move to the peek window

But,no window is actually open, and the error is reported as above

`:Lspsaga peek_definition` works

### Neovim version (nvim -v)

NVIM v0.8.3

### lspsaga commit

a3556e1faf1842669570bf1d7587ef8f8ea1fe19

### Terminal name/version

konsole 22.12.3

**Comment by glepnir** [comment]
looks like recently change break again ?

**Comment by glepnir** [comment]
should be fixed.
