### ISSUE TITLE
lspsaga not work in neovim

### ISSUE THREAD

**Issue by kayuxcodes** [glepnir/lspsaga.nvim#1009]
its supposed to `lspsaga` looks like this when you install it and setup it simply:
[https://preview.redd.it/wn6lgpmj6ve91.gif?format=mp4&v=enabled&s=b67bc9c773d758f3ce61f49d163660750d0faea3](url)
instead of this its looks like this:
[https://preview.redd.it/98hvymr73dsa1.png?width=688&format=png&auto=webp&v=enabled&s=1576eec3f5fbec7c38b90264b741ccc4ae18da6f](url)
im using windows, and this didn't work

**Comment by glepnir** [comment]
diagnostic jump and hover is different function
