### ISSUE TITLE
[Idea]Add an option to set the lsp diagnostic signs virtual text

### ISSUE THREAD

**Issue by BigfootN** [glepnir/lspsaga.nvim#101]
Hello,

Since the option doesn't seem to be available, maybe one should be able to set the lsp virtual text signs

For example:

```lua
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
  vim.lsp.diagnostic.on_publish_diagnostics, { virtual_text = { prefix = "foo" } }
)
```

with just a simple variable/setting.

Thank you very much advance for any response.

**Comment by glepnir** [comment]
@BigfootN  At the very beginning lspsaga supports callbacks for custom diagnostics. But some users did not like to set through lspsaga , so I removed it
