### ISSUE TITLE
How to change position of winbar

### ISSUE THREAD

**Issue by kaykhan** [glepnir/lspsaga.nvim#1013]
I am using lualine and lspsaga. I am trying to get both winbar's to coexist. In lualine i set buffers to be in winbar.

![image](https://user-images.githubusercontent.com/5202527/230897662-52d00196-0f57-4058-b441-fe977eaad4a0.png)

How can i get lspsaga winbar to be below the buffers ( above they are hidden behind buffers)

![image](https://user-images.githubusercontent.com/5202527/230897696-7083c47a-17be-4291-8659-c43bb6f3715a.png)

like this:

![image](https://user-images.githubusercontent.com/5202527/230897725-b190c9a8-67fc-4534-9a24-e1103428915d.png)

```
Buffer1 | Buffer2
src > app1.ts
```

**Comment by glepnir** [comment]
hmm IDK what you mean.. `winbar` is window option so one window one bar. if you split file in two window it show two winbar.  in default it works like the last pic you post ?

![image](https://user-images.githubusercontent.com/41671631/230898943-0611dbd2-e693-4cbb-bdaf-97446bcf5244.png)

**Comment by kaykhan** [comment]
Mine is like this when i split

![image](https://user-images.githubusercontent.com/5202527/230899114-902a1205-c4cd-449a-9e66-c66a2d5f3773.png)

I want lspsaga winbar to show below buffers. ( see i have tree open also)

**Comment by glepnir** [comment]
so you mean the winbar not work ?

**Comment by kaykhan** [comment]
it works, but i want it to work togeather lualine like this

![image](https://user-images.githubusercontent.com/5202527/230900088-0ae329a9-dcb3-4af0-bdcc-acf8ce17fe2a.png)

**Comment by glepnir** [comment]
hmm does lualine handle winbar ? idk i don't use that plugin.  if it handle winbar you should disable it then use lspsaga winbar instead or use lspsaga symbols api in lualine winbar. see doc `use in custom winbar`.

**Comment by kaykhan** [comment]
Yes maybe i need to configure lualine to use lspsaga. b ut dont know how to customise it. 

```
	winbar = {
		lualine_a = { "buffers" },
		lualine_z = { "tabs" },
	},
```	

```
require("lualine").setup({
	options = {
		icons_enabled = true,
		theme = custom_codedark,
		component_separators = { left = "|", right = "|" },
		section_separators = { left = "", right = "" },
		disabled_filetypes = {
			statusline = { "neo-tree" },
			winbar = { "neo-tree" },
		},
		ignore_focus = {},
		always_divide_middle = true,
		globalstatus = false,
		refresh = {
			statusline = 1000,
			tabline = 1000,
			winbar = 1000,
		},
	},
	sections = {
		lualine_a = { "mode" },
		lualine_b = { "branch", "diff", "diagnostics" },
		lualine_c = { { "filename", path = 3 } },
		lualine_x = { "encoding", "fileformat", "filetype" },
		lualine_y = { "progress" },
		lualine_z = { "location" },
	},
	inactive_sections = {
		lualine_a = {},
		lualine_b = {},
		lualine_c = { "filename" },
		lualine_x = { "location" },
		lualine_y = {},
		lualine_z = {},
	},
	winbar = {
		lualine_a = { "buffers" },
		lualine_z = { "tabs" },
	},
	inactive_winbar = {
		lualine_a = { "buffers" },
		lualine_z = { "tabs" },
	},
	extensions = {},
})
```

**Comment by lalitmeeq** [comment]
@kaykhan, you are using the wrong thing in `winbar`. `buffers` and `tabs` should go inside `tabline` table.
