### ISSUE TITLE
Signature help on cursor hold throws errors with EFM language server

### ISSUE THREAD

**Issue by akinsho** [glepnir/lspsaga.nvim#103]
### Description

When using `lua require('lspsaga.signaturehelp').signature_help()` inside a `CursorHold` autocommand if I move to a buffer using only [EFM](https://github.com/mattn/efm-langserver) language server, in my case a markdown file like my README. I get
```
Error detected while processing CursorHoldI Autocommands for "*":
E5108: Error executing lua .../packer/start/lspsaga.nvim/lua/lspsaga/signaturehelp.lua:90: attempt to index local 'result' (a number value)
E5108: Error executing lua .../packer/start/lspsaga.nvim/lua/lspsaga/signaturehelp.lua:90: attempt to index local 'result' (a number value)
```
I understand that signature can't be expected to work if the server doesn't support it, but I don't expect it to error. I could theoretically move this autocommand inside the buffer attach for my lspconfig setup and check if client supports it before adding the autocommand but I'm trying to keep my various plugin configs separate where possible.

**Expected Behavior**

Lspsaga should check if the client supports a behaviour before carrying out the action (maybe it generally already does). If not supported do nothing, don't error, don't log anything.
Alternatively allow for a way to specify `lspsaga` behaviour for only attached buffers with clients that support certain behaviour 🤷🏿‍♂️ 

**Actual Behavior**

### Details

<details><summary>Reproduce</summary>

1. install `efm` -> `go get github.com/mattn/efm-langserver`

```lua
vim.cmd [[packadd nvim-lspconfig]]
vim.cmd [[packadd lspsaga]]
require('lspsaga').init_lsp_saga {}
require('lspconfig').efm.setup{
  init_options = {documentFormatting = true},
  filetypes = {"markdown"},
  settings = {
    rootMarkers = {".git/"},
    languages = {
     markdown = {{formatCommand = "prettier"},
    }
   }
 }
vim.cmd [[autocmd! CursorHoldI * lua require('lspsaga.signaturehelp').signature_help()]]
```

1. nvim -u test.lua the min config that only lspsaga
2. `:edit README.md` (any markdown file)
3.  go into insert mode and type
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-zFiKej/neovim-0.5.0+ubuntu2+git202102150234-dc3ca16a9-d569569c9=. -fstack-protector-strong -Wformat -Werror=f
ormat-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissin
g-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOA
T32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-zFiKej/neovim-0.5.0+ubuntu2+git202102150234-dc3ca16a9-d569569c9/build/config -I/build/neovim-zFiKej/neovim-0.5
.0+ubuntu2+git202102150234-dc3ca16a9-d569569c9/src -I/build/neovim-zFiKej/neovim-0.5.0+ubuntu2+git202102150234-dc3ca16a9-d569569c9/.deps/usr/include -I/usr/include -I/build/n
eovim-zFiKej/neovim-0.5.0+ubuntu2+git202102150234-dc3ca16a9-d569569c9/build/src/nvim/auto -I/build/neovim-zFiKej/neovim-0.5.0+ubuntu2+git202102150234-dc3ca16a9-d569569c9/buil
d/include
Compiled by buildd@lcy01-amd64-026
```
- Operating system:  `Ubuntu 20.10`
- lspsaga commit:  `latest`

</details>

**Comment by glepnir** [comment]
yep should be check the client support feature

**Comment by akinsho** [comment]
@glepnir it now looks like I get
```
E5108: Error executing lua .../packer/start/lspsaga.nvim/lua/lspsaga/signaturehelp.lua:16: attempt to index global 'libs' (a nil value)
```
It looks like `libs` is not available in that file where you are now using it

**Comment by glepnir** [comment]
yep ..lua server need 5 mins to startup so I miss the diagnostic..

**Comment by akinsho** [comment]
@glepnir I don't actually think this worked, I had disabled `efm` for the affected files and just restarted it today and am seeing the same issues crop up 😭

**Comment by glepnir** [comment]
Aha got it. I will install efm to check it :)

**Comment by glepnir** [comment]
@akinsho  only run efm in markdwon right?

**Comment by akinsho** [comment]
I actually run it in `yaml`, `markdown`, `lua`, basically I'm trying to use it for any language where the `lsp` server doesn't support formatting

**Comment by akinsho** [comment]
Just tried and this is still happening after updating to the latest commit. I'm not sure what the implementation difference is between lspsaga's signature help and native lsp but there doesn't seem to be any error if I just use the basic lsp signature help. Maybe there is some error checking logic you can copy paste from it

**Comment by glepnir** [comment]
got it.

**Comment by glepnir** [comment]
check the default handler of signature.. I think we both have a same logic ..

**Comment by akinsho** [comment]
Hmm I just switched my config to use `vim.lsp.buf.signature_help()` on cursor hold and tested in a markdown file and I don't see any errors. I think maybe the check for if supported isn't working correctly somewhere

**Comment by akinsho** [comment]
I actually noticed a new error now
```
Error detected while processing CursorHoldI Autocommands for "*":
E5108: Error executing lua .../packer/start/lspsaga.nvim/lua/lspsaga/signaturehelp.lua:22: attempt to index field 'default_config' (a nil value)

```

**Comment by glepnir** [comment]
only efm-langserver running right?

**Comment by akinsho** [comment]
```

 Configured servers: html, efm, sumneko_lua, tsserver, jsonls, flow, vimls, rust_analyzer, dartls, gopls 
   
  1 client(s) attached to this buffer: efm 
   
    Client: efm (id 1) 
    	root:      /home/akin/.dotfiles 
    	filetypes: yaml, json, html, css, markdown, lua 
    	cmd:       efm-langserver 
   
  1 active client(s):  
   
    Client: efm (id 1) 
    	root:      /home/akin/.dotfiles 
    	filetypes: yaml, json, html, css, markdown, lua 
    	cmd:       efm-langserver 
   
  Clients that match the filetype markdown: 
     
    Config: efm 
    	cmd:               efm-langserver 
    	cmd is executable: True 
    	identified root:   /home/akin/.dotfiles 
    	custom handlers:    

```

**Comment by glepnir** [comment]
now should be work

**Comment by akinsho** [comment]
Yep seems to have stopped erroring now 💯 👍🏿 thanks for your hard work on this 🚀

**Comment by glepnir** [comment]
Because I am lazy not install efm to check it :)

**Comment by kristijanhusak** [comment]
@glepnir I'm having a bit different issue with diagnosticls language server + tsserver. Sometimes something happens with the `vim.lsp.buf_get_clients()` list, and it stops returning a valid array, but instead it returns a hash.

Initially I get something like this for `vim.lsp.buf_get_clients()`:
```lua
{ {                                                                                                                                                                                                                                             
    _on_attach = <function 1>,                                                                                                                                                                                                                  
    cancel_request = <function 2>,
  }, {                                                                                                                                                                                                                                          
    _on_attach = <function 15>,                                                                                                                                                                                                                 
    cancel_request = <function 16>,  
}}
```

And after some time I get this:

```lua
{                                                                                                                                                                                                                                               
  [2] = {                                                                                                                                                                                                                                       
    _on_attach = <function 1>,                                                                                                                                                                                                                  
    cancel_request = <function 2>
  },
 [3] = {                                                                                                                                                                                                                                       
    _on_attach = <function 15>,                                                                                                                                                                                                                 
    cancel_request = <function 16>,
  }                  
}
```

This breaks the `ipairs` and it doesn't enter the for loop for clients in `check_server_support_signaturehelp` function, which makes signature help always hidden.

Fix is just to switch `ipairs` to `pairs`.
Could you please fix that? Thanks!

**Comment by glepnir** [comment]
of course
