### ISSUE TITLE
Characters not appearing correctly

### ISSUE THREAD

**Issue by mirosval** [glepnir/lspsaga.nvim#105]
### Description
Some characters (emojis?) are not displaying properly.

**Expected Behavior**
The gifs in the readme show stars or other emojis in e.g. the finder view, but I just see `?`s

**Actual Behavior**
<img width="206" alt="Screenshot 2021-02-16 at 14 45 44" src="https://user-images.githubusercontent.com/1315417/108071404-fd620780-7065-11eb-93b1-d32c298c8b33.png">

### Details
I could not find any mention of a specific font that should be installed, so maybe this is just a doc issue.

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-dev+nightly-585-gdc3ca16a9
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210216-14549-b4107t/build/config -I/tmp/neovim-20210216-14549-b4107t/src -I/usr/local/include -I/usr/local/opt/luv/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210216-14549-b4107t/build/src/nvim/auto -I/tmp/neovim-20210216-14549-b4107t/build/include
Compiled by miroslav@Miroslavs-MacBook-Pro-2.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-dc3ca16_1/share/nvim"

Run :checkhealth for more info
```
- Operating system: macOS 11.2.1 
- lspsaga commit: 13a2ad637973f1e3f78fc8cf069be944a538f781
- I'm using Alacritty with JuliaMono font

**Comment by glepnir** [comment]
emoji seems like your terminal not support this ?

**Comment by glepnir** [comment]
works for me  my env macos bigsur terminal is kitty

![image](https://user-images.githubusercontent.com/41671631/108085683-8f8efd80-70b0-11eb-86bf-be05d7dc4725.png)

**Comment by mirosval** [comment]
Alacritty does support emojis in general, it seems that this problem is related to the Alacritty-tmux-neovim combo
<img width="191" alt="Screenshot 2021-02-16 at 18 43 59" src="https://user-images.githubusercontent.com/1315417/108100988-f13a7200-7086-11eb-99d2-80477064e3dd.png">

**Comment by mirosval** [comment]
I can actually also see emojis inside vim inside tmux on Alacritty. 
<img width="349" alt="Screenshot 2021-02-16 at 19 44 25" src="https://user-images.githubusercontent.com/1315417/108107333-63af5000-708f-11eb-81d7-ccff945e9bde.png">

**Comment by glepnir** [comment]
But I don't think this is a problem with lspsaga. lspsaga is just a neovim plugin. neovim is a terminal application which uses terminal fonts.

**Comment by mirosval** [comment]
Indeed. The issue appears to have been that the `JuliaMono` font I was using was not patched. When I switched to `Hasklug Nerd Font` (https://www.nerdfonts.com/), it started working again.

**Comment by glepnir** [comment]
Aha glad to see it works for you.
