### ISSUE TITLE
Add border for floaterm triggered by open_floaterm? 

### ISSUE THREAD

**Issue by yech1990** [glepnir/lspsaga.nvim#107]

**Comment by glepnir** [comment]
```lua
lua require('lspsaga.floaterm').open_float_terminal('',1 -- mean lspsaga border_style)
```

**Comment by yech1990** [comment]
Hi @glepnir 

There is still no border after setting the second argument.

![image](https://user-images.githubusercontent.com/5415510/108303468-ed226780-71e0-11eb-9722-35cf577edbfd.png)

**Comment by glepnir** [comment]
hmm  i found there has a problem so I removed window height and width of border . fixed it later.

**Comment by yech1990** [comment]
Thank you @glepnir
