### ISSUE TITLE
Using lsp finder on certain symbols cause reference uri error

### ISSUE THREAD

**Issue by akinsho** [glepnir/lspsaga.nvim#108]
### Description

Using `Lspsaga finder` on certain symbols causes an error resolving `reference_uri` whilst working with `dartls`. It might not be specific to this language server but other than lua atm I'm mostly writing dart.

![dartls-lspsaga](https://user-images.githubusercontent.com/22454918/108269217-9297f580-7165-11eb-8a7f-4cc48a28dfc1.png)

Using `debug = true` shows no additional data. This doesn't reproduce with all symbols a lot of symbols work fine some do not not sure what the difference is. Also note when this error has occurred the window opens but is empty and the highlighting for the current line replaced and does not clear

**Expected Behavior**

The finder window should open with the definition and references of the symbol or print a message if it couldn't not error out

**Actual Behavior**

### Details

<details><summary>Reproduce</summary>

```lua
vim.cmd [[packadd nvim-lspconfig]]
vim.cmd [[packadd lspsaga]]
require('lspsaga').init_lsp_saga {}
require('lspconfig').dartls.setup{}
```

#### Prerequisite:
Install dart (I have flutter installed but it uses the dart lsp), the lsp is included with the sdk

1. nvim -u test.lua
2. post your program language min code snippet that can reproduce your issue
3. create `test.dart`

```dart
void main() {
  // This is some logic
  final value = 2 + 3;
  print(value);
}
```

4. Trigger `Lspsaga lsp_finder` on the `print` call.
</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: Ubuntu 20.10
- lspsaga commit: latest 

</details>

**Comment by glepnir** [comment]
It's wired I only got it when I first run this command .. then I do it many times works fine.

![image](https://user-images.githubusercontent.com/41671631/108299255-0fb08280-71d9-11eb-94cb-82449646f8ba.png)

**Comment by glepnir** [comment]
add a patch to make sure the ref uri is number value.

**Comment by akinsho** [comment]
@glepnir yeah I saw the error sometimes only the first time but sometimes depending on the symbol it would happen consistently. Anyway I just tried it (briefly) now on the same example and on some others and it seems to work fine 🙌🏿 👍🏿

**Comment by glepnir** [comment]
Good to know. so close it ?

**Comment by akinsho** [comment]
As a side note/bad habit since you have been testing with dart also wanted to point out that sometimes the windows overlap. Dart lsp tends to send huge amounts of information in the docs. I will open another issue about window stuff

![image](https://user-images.githubusercontent.com/22454918/108327283-2350ee80-71c3-11eb-82aa-2d4923055ee7.png)

**Comment by glepnir** [comment]
BTW found you use the nvim-lighlub. why not use lspsaga codeaction. I mean saga's codeaction gives you a bad experience？

**Comment by glepnir** [comment]
found a problem look your pic the file path is too long should truncate.

**Comment by glepnir** [comment]
what is your root dir of your pic?

**Comment by akinsho** [comment]
It's an open source monorepo project I've cloned locally https://github.com/gql-dart/ferry

the dir in the pic is
`[1] Desktop/projects/contributing/ferry/ferry/test/typed_links/request_controller_typed_link_test.dart`

**Comment by akinsho** [comment]
> BTW found you use the nvim-lighlub. why not use lspsaga codeaction. I mean saga's codeaction gives you a bad experience？

Lightbulb does a different thing to `lspsaga code_action`. That plugin just shows a lightbulb *if* a code action is available at a certain position in the buffer, it doesn't actually show code action UI.

**Comment by glepnir** [comment]
Okay i will check it and improve saga codeaction. now I had add a patch to reduce the length of file path
