### ISSUE TITLE
Window sizing issues using DartLS

### ISSUE THREAD

**Issue by akinsho** [glepnir/lspsaga.nvim#109]
### Description

When using `dartls` the window of the `signature_help` menu can be too large.

![image](https://user-images.githubusercontent.com/22454918/108416766-12d25f80-7227-11eb-82a0-f9167859a6e5.png)

2. Truncation of text - this is occasionally mid signature or mid word which makes things less readable
![image](https://user-images.githubusercontent.com/22454918/108419348-5084b780-722a-11eb-983b-7c0140bfacde.png)

**Expected Behavior**

The window sizing should be truncated similar to the lsp finder and definition preview windows

**Actual Behavior**

### Details

<details><summary>Reproduce</summary>
Ensure `dartls` installed see #108 for details on minimal init.lua

1. nvim -u test.vim the min config that only lspsaga
2. trigger signature in the `listen` method of a stream.
```dart
 Stream.value(null).listen(<cursor-here>)
```

</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: 
- lspsaga commit: 

</details>

As a side note it would be great to remove the `no signatures available` log it's quite spammy and not really needed

**Comment by tami5** [comment]
> As a side note it would be great to remove the no signatures available log it's quite spammy and not really needed

Oh I had to disable my autocmd because of that. It's so annoying :laughing: , but I think its something builtin.

btw we had some discussion regarding this in nvim-compe#191

**Comment by glepnir** [comment]
Now signaturehelp window has a limit height, also can use `smart_scroll_with_saga` to scroll and there has public function to check has saga signature help win and scroll in it ,these funtion that useful for someone want to custom scroll keymap.

About second question I need the diagnostic msg.

**Comment by akinsho** [comment]
Looks much better now thanks @glepnir 👍🏿
