### ISSUE TITLE
Allow to not overwrite diagnostics handler

### ISSUE THREAD

**Issue by weilbith** [glepnir/lspsaga.nvim#11]
Hi :wave: 
Its me again :see_no_evil: 
I saw that you overwrite the lsp handler for the diagnostics. I guess you do so to provide the user with some in your opinion good defaults. And also I personally would argue that this shouldn't be in the scope of this plugin. But besides that, the big downside is that it overwrites what the user maybe already personalized. So do I for example prefer to get diagnostics live while I'm typing. You disable this. 
As I can tell from the code, on a first glance it does not look like customizing the handler as you do it (with `vim.lsp.with()`) this is not required to make the rest of your plugin working. Right? So if you insist (and that might make sense, plus it is your plugin) to keep the handler, would it be possible to make this optional? I would rather stick with my handler, but still take profit from your plugins nice visual additions in the floating window.
Thanks for the feedback in advanced!

**Comment by glepnir** [comment]
Add this keyowrd `use_saga_diagnostic_handler` to allow not overwrite.

**Comment by weilbith** [comment]
Awesome! Thanks for your fast adoption. :upside_down_face:
