### ISSUE TITLE
Use more space for hover

### ISSUE THREAD

**Issue by kuznetsss** [glepnir/lspsaga.nvim#110]
Thank you for the plugin!

In some languages like C++ there could be really long strings in hover, so it is more comfortable to read it in bigger window.
Hover window of lspsaga has size to fit into vim window. But it could use all space of the OS window `vim.lsp.buf.hover()`.
Here are screenshots what I'm talking about:

<details><summary>Lspsaga hover:</summary>

![lspsaga hover](https://user-images.githubusercontent.com/15742918/108417314-da3f7f80-7240-11eb-9dbc-030a09fc85b6.png)
</details>

<details><summary>Default hover:</summary>

![default vim hover](https://user-images.githubusercontent.com/15742918/108417324-de6b9d00-7240-11eb-8e7c-e954d5c8ea72.png)
</details>

I think the size of the default hover window is more comfortable. Maybe you could add an option to control the behavior?

**Comment by gshpychka** [comment]
@glepnir can you expose this to the user? I'm using my monitors in a vertical orientation and 50% width is too narrow. Thanks.

**Comment by glepnir** [comment]
aha ..can you show a pic about current behavior.

**Comment by gshpychka** [comment]
Right now it cannot be wider than 50% of the window, as you can see in #46c07b0
