### ISSUE TITLE
highlighting mismatch (signature_help/hover)

### ISSUE THREAD

**Issue by tami5** [glepnir/lspsaga.nvim#111]
### Description

The highlighting of hove mismatch the highlighting of hover window. Also when docs the signature highlight breaks, can anyone one confirm that? 

#### Hover
![](https://i.imgur.com/zdDyqq9.png)

with docs 
![](https://i.imgur.com/XD5QpS2.png)

#### signature 
![](https://i.imgur.com/mnZiZ36.png)

with docs 
![](https://i.imgur.com/drcTLUc.png)

**Expected Behavior**

highlights of functions in lspsaga stay consistent with signature_help highlights

**Actual Behavior**

Mismatch of highlight depending on what lspaga function was called

### Details

</details>

<details><summary>Environment</summary>

- nvim --version output: last
- Operating system: arch
- lspsaga commit: ef1997d

</details>

**Comment by tami5** [comment]
Also, after the most recent commit highlights in hover totally broke

**Comment by glepnir** [comment]
reproduce step.

**Comment by glepnir** [comment]
because the signature help use current filetype then you use treesitter to highligh it. hover will load buil-in highlight vim file

**Comment by glepnir** [comment]
now both use built-in syntax .
