### ISSUE TITLE
Float window doesn't close on buffer change

### ISSUE THREAD

**Issue by kuznetsss** [glepnir/lspsaga.nvim#113]
Open 2 buffers. One is visible in the current window and one is not visible. Call hover to see floating window. Type `:bnext` to switch to another buffer. You will be switched to another buffer but the floating window stays on top until you change buffer again or close it manually.

I think expected behavior is to close floating window on buffer or window switching.

**Comment by tamago324** [comment]
I think it would be useful to be able to move the cursor to the hover_doc window, but it disappears when `BufLeave` occurs.
I thought it would be useful to have the following function available.

```lua
M.render_or_into_hover_doc = function()
  if hover.has_saga_hover() then
    a.nvim_command [[noautocmd wincmd p]]
  else
    hover.render_hover_doc()
  end
end
```
