### ISSUE TITLE
Rename is broken

### ISSUE THREAD

**Issue by kuznetsss** [glepnir/lspsaga.nvim#114]
When I try to use rename, input new name and press `<CR>` nothing happens. I'm using default config. It worked fine a few days ago.

**Comment by glepnir** [comment]
I can't reproduce .your should completion the issue template with reproduce step.

**Comment by kuznetsss** [comment]
I've realized that the line `autocmd BufLeave * update` in my config breaks the rename.

**Comment by kuznetsss** [comment]
Could you add `setlocal buftype=nofile` for floating windows?

**Comment by Keating950** [comment]
I've encountered the same issue, despite not having any `BufLeave` autocommands. (I'm sure it's some other one I have set up that's causing the issue.) Is the above suggestion being considered?

**Comment by kuznetsss** [comment]
I've realized that rename buffer has `buftype` `prompt`, so if there is `autocmd BufLeave * update` in config, vim tries to save buffer without file and gives error. My solution is to save only buffers with empty `buftype` on `BufLeave`.

**Comment by rodhash** [comment]
Faced this issue but only for Python files, JS or C++ seems okay .. I couldn't find any au commands that could be causing this.
