### ISSUE TITLE
Highlighting issues in hover documentation

### ISSUE THREAD

**Issue by ryantking** [glepnir/lspsaga.nvim#117]
### Description

A lot of the formatting in the hover documentation window seems to be off:

<img width="578" alt="Hover window" src="https://user-images.githubusercontent.com/1883041/108632288-18ed5980-743c-11eb-9dc3-692ae002482a.png">

**Expected Behavior**
- The hover window should not have trailing space at the end of lines.
- Highlighting should be maintained on line wrap

**Actual Behavior**
- Each line has a trailing space
- Line wrapping breaks syntax highlighting

**Neovim Built in Behavior**
N/a

### Details

<details><summary>Reproduce</summary>

1. Using [your dotfiles](http://github.com/glepnir/nvim/tree/master/lua/core)
2. Open a go file, and open the hover documentation on a struct def, my example uses `github.com/spf13/cobra.Command`, but any struct with comments on the fields should demonstrate the second issue I highlighted.
3. Switch to [this colorscheme](https://github.com/ChristianChiarulli/nvcode-color-schemes.vim) then look at the hover documentation again to see the highlighted trailing space characters.
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-dev+nightly-18-g1caf58578
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210220-65353-1w3oesq/build/config -I/tmp/neovim-20210220-65353-1w3oesq/src -I/usr/local/include -I/usr/local/opt/luv/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210220-65353-1w3oesq/build/src/nvim/auto -I/tmp/neovim-20210220-65353-1w3oesq/build/include
Compiled by rking@SnackBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-1caf585_1/share/nvim"

Run :checkhealth for more info
```
- Operating system: macOS 11.2.1
- lspsaga commit: `cace36b3d5f196eda8f1528e45296fe4649f888d`

</details>

**Comment by glepnir** [comment]
About the highlight whitespace I can't reproduce .looks like your colorscheme issue.

![image](https://user-images.githubusercontent.com/41671631/108686215-11a77800-7530-11eb-9f49-73f875b42888.png)

**Comment by bbenzikry** [comment]
Hi @glepnir, just ran into the space highlight issue and noticed https://github.com/glepnir/lspsaga.nvim/issues/15  + https://github.com/neovim/neovim/issues/13746

I've added the same hotfix you used ( pad_right = 0) to the following, and while it loses spacing it's much better.

https://github.com/glepnir/lspsaga.nvim/blob/27c7a4796869e155ecec48eb3f8e66694c1708e2/lua/lspsaga/window.lua#L290 

https://github.com/glepnir/lspsaga.nvim/blob/27c7a4796869e155ecec48eb3f8e66694c1708e2/lua/lspsaga/signaturehelp.lua#L73

As this can also be solved ( while preserving spacing ) with something like ``:hi clear Error`` for now, Is this something that can / should be added or is this pending something like https://github.com/neovim/neovim/pull/14207 ?

**Comment by glepnir** [comment]
I will take a look at upsteam pr.

**Comment by mjlbach** [comment]
I've updated the upstream PR, to summarize, what was happening is that the trim/pad feature adds whitespace on the left and right of the code block, which causes the syntax rule to detect a whitespace error. The new version of the floating window (in the PR) uses the native border feature to paint borders to give the illusion of padding, which fixes the issue.
