### ISSUE TITLE
Hover handler - alternatives approaches?

### ISSUE THREAD

**Issue by weilbith** [glepnir/lspsaga.nvim#12]
Hey, :smiley: 
Sorry for opening that many issues. You plugin is really appealing, so I would love to use it and not just quit because I'm not 100% happy with it. I hope that is fine and you understand it as constructive critics. This is actually the "weakest" of all the issues I opened. 
While starting to setup and use your plugin I was a bit confused about the hover functionality. It kinda stands out to all the rest. In first place because everything else has a custom function, but here you fall back to use NeoVims default and only customize the handler. This makes sense, as for other functions like `vim.lsp.diagnostic.goto_next()` can't be overwritten. So you must provide new functions for them.
But as this kinda stands out, why not letting the user decide? So maybe he agrees with you that this is the most comfortable approach and wants to customize the handler. Or he disagrees and prefers a custom function by this plugin.
For the first case it would be simple enough to provide the user with the simple docs hint how to set the handler to a function fo your plugin. Its basically a one-liner. You could even make use of `vim.lsp.with()` and make it configurable (although that might be bad with configurations at two different places).
The advantage of a separate command would be for example lazy loading. Many plugin/package manager provide the feature to lazy load a plugin when necessary. With the LSP handler this is hardly possible. It would be great if it could make use of the `FuncUndefined` event like lazy loads. But as this is a Lua function and not VimScript, this won't work. Therefore the only option I see would be to have a separate command. There might be even more advantages/opinions why having a separate command available if necessary might be of interest.

I'm curious what you thoughts are in regards of this.. I like the idea to empower the user who he would like to use the cool features your plugin provide. Thanks for reading!

**Comment by glepnir** [comment]
This is easy to implement, just wrap some Lua functions into commands. Just as I did in telescope. Support it later.

**Comment by glepnir** [comment]
Now support command.

**Comment by weilbith** [comment]
That's great. Now i can use lazy loading for this plugin! :rocket: 

But just to make sure I'm not blind, this still does not provide a command for the hover function right? And it still always overwrites the handler.

**Comment by glepnir** [comment]
About hover.. it's rewrite the built-in lsp default handler..so need refactor this. but now I have a new idea for finder window. so when i work done.

**Comment by glepnir** [comment]
@weilbith  Now I had rewrite it not overwrite the default buil-in lsp handler. usage

```lua
nnoremap <silent>K :LspSagaHoverDoc<CR>
```

**Comment by weilbith** [comment]
Thanks! :pray:

**Comment by glepnir** [comment]
My pleasure.
