### ISSUE TITLE
[Feature] hover_doc markdown rendering

### ISSUE THREAD

**Issue by gshpychka** [glepnir/lspsaga.nvim#121]
**Is your feature request related to a problem? Please describe.**
The LSP server I'm using (pyright) is converting docstrings to markdown, and it's not shown properly in the hover_doc. Looks like this: https://i.imgur.com/R1i1irp.png
I'm mostly talking about `$nbsp;` and `\`. 
To be clear, the built-in hover doc has the same problem, which is why this is a feature request and not a bug report.

**Describe the solution you'd like**
Rendering markdown properly, like in VScode

**Describe alternatives you've considered**
I've tried forking pyright and changing the code to send plain text instead of markdown, but that is not a good option - it doesn't respect comments and other hidden text.

**Comment by glepnir** [comment]
yep we already talk this in upstream. this has some troublesome.

**Comment by gshpychka** [comment]
Would make sense to fix upstream. Can you link the relevant issue upstream?

**Comment by glepnir** [comment]
https://github.com/neovim/neovim/pull/13803

**Comment by gshpychka** [comment]
Thank you.

**Comment by saxocellphone** [comment]
I'm having the same issue, but it seems like the built-in hover doc is fixed, but lspsaga's hover doc still isn't
LspSaga:
![LspSaga](https://user-images.githubusercontent.com/7075286/129484653-392ab9c6-f3a3-4ae3-aa4c-a219111f08fb.png)
BuiltIn:
![BuiltIn](https://user-images.githubusercontent.com/7075286/129484658-94e344c0-aae7-463e-a15f-018391b2dd5c.png)
