### ISSUE TITLE
render_hover_doc is causing a crash with tsserver

### ISSUE THREAD

**Issue by phelipetls** [glepnir/lspsaga.nvim#123]
### Description
`render_hover_doc` causes neovim to be unresponsive and use 100% of cpu. In Python it works, it only happened to me with tsserver.

**Expected Behavior**
It does not crash.

**Actual Behavior**
It crashes.

**Neovim Built in Behavior**
The built-in hover handler works fine.

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: 
- lspsaga commit: 8e0526a

</details>

**Comment by phelipetls** [comment]
I just bisected it. This is the commit that introduced the bug: 50816a115f8a15da0cfb9c31418604c277ef6bae.

**Comment by glepnir** [comment]
hmm I can't reproduce this..

**Comment by phelipetls** [comment]
I think it depends on the window width/number of columns? `vim.api.nvim_win_get_width(0)` and `set columns?`  gives me 192, for example.

**Comment by glepnir** [comment]
should be works now
