### ISSUE TITLE
`lsp_finder` TargetWord for References uses ReferencesIcon

### ISSUE THREAD

**Issue by Iron-E** [glepnir/lspsaga.nvim#125]
# Introduction

Thank you so much for this plugin! It really puts the polish on the base LSP client that I was looking for.

In attempting to implement highlighting of this plugin for my colorscheme [`nvim-highlite`](https://github.com/Iron-E/nvim-highlite), I noticed that the `lsp_finder` provider doesn't quite use the highlights in the way I expected.

# Reproduction

1. Link the following highlight groups:
	```vim
	hi! link DefinitionCount Number
	hi! link DefinitionIcon Special
	hi! link ReferencesCount Number
	hi! link ReferencesIcon DefinitionIcon
	hi! link TargetFileName Directory
	hi! link TargetWord Title
	```
2. Open the `lsp_finder`:
	![screenshot](https://user-images.githubusercontent.com/36409591/109186451-ed7dae00-775e-11eb-86e9-6535dc1cb8c2.png)

From the screnshot I notice the following things:

* The icons are properly highlighted.
* The `TargetWord` for Definitions is properly highlighted.
* The `TargetWord` for References uses the `ReferencesIcon` highlight group instead of the specified link.

Further, running `:hi <group>` commands shows that the highlight group is being properly set. For example, this is what `TargetWord` shows:

```vim
:hi TargetWord
TargetWord     xxx links to Title
```

**Comment by glepnir** [comment]
give it a test. looks like works for me.

![image](https://user-images.githubusercontent.com/41671631/109587170-92263400-7b41-11eb-9511-5d68e20307a9.png)

**Comment by Iron-E** [comment]
Must be something on my end :/

**Comment by glepnir** [comment]
And test it in my colorschme zephyr. works fine. you can check [zephyr](https://github.com/glepnir/zephyr-nvim)
