### ISSUE TITLE
Increase max hover dimensions

### ISSUE THREAD

**Issue by gshpychka** [glepnir/lspsaga.nvim#126]
**Is your feature request related to a problem? Please describe.**
Hover_doc window is too narrow on my vertical monitor, it wraps lines mid-word most of the time.

**Describe the solution you'd like**
Not limiting the hover_doc width (this is the built-in behavior), or allowing the user to customize max width/height

**Describe alternatives you've considered**
Using the built-in hoverdoc.

**Additional context**
![image](https://user-images.githubusercontent.com/23005347/109261769-0773cb00-7809-11eb-90b7-704c2d1c18ae.png)

#110 was about this, but it was not solved.

https://github.com/glepnir/lspsaga.nvim/commit/46c07b0225c90bac208f0166db42597dc40665c2#commitcomment-47556394

**Comment by glepnir** [comment]
....you should comment on #124 not open a new issue..

**Comment by gshpychka** [comment]
Uhm no, those are separate issues. That one is about incosistent width, this one is about inability to increase max hoverdoc dimensions. Please reopen.

**Comment by gshpychka** [comment]
@glepnir can you reopen? This issue is not related to #124. That one is a bug report about inconsistent width, this one is a feature request to be able to change hoverdoc dimensions.
