### ISSUE TITLE
preview_definition does not work with multiple lsp clients

### ISSUE THREAD

**Issue by 22mahmoud** [glepnir/lspsaga.nvim#127]
### Description
II have both tsserver and efm servers running, when using preview_definition I get this error 
```
E5108: Error executing lua .../pack/packer/start/lspsaga.nvim/lua/lspsaga/provider.lua:450: attempt to index a nil value
```

**Expected Behavior**
The Preview definition pop up without errors.

**Comment by 22mahmoud** [comment]
#128

**Comment by glepnir** [comment]
now closed.because #128 had merge.
