### ISSUE TITLE
Preview window should include comments for function/variable

### ISSUE THREAD

**Issue by ray-x** [glepnir/lspsaga.nvim#129]
**Describe the solution you'd like**
Would be great the preview windows could include the comments for the function/variable. At the moment, the first line of preview is where the func/var was defined. The preview buffer could scroll down but can not scroll up to show the comments.

**Describe alternatives you've considered**
Provides 3~5 lines above where the function was defined in preview buffer.

**Comment by glepnir** [comment]
support it later.

**Comment by ray-x** [comment]
I updated the code and it was solve.
Maybe one more request. Is it possible hight where the var/fun was defined.  Yes, I know it is 3 lines from the top. :-P
