### ISSUE TITLE
Code Actions menu gets stuck when there are no available actions

### ISSUE THREAD

**Issue by lynndylanhurley** [glepnir/lspsaga.nvim#13]
These empty boxes are left stuck to the screen and there doesn't appear to be a way to get rid of them:

<img width="328" alt="Screen Shot 2021-01-25 at 11 57 43 AM" src="https://user-images.githubusercontent.com/468037/105746162-b7050700-5f04-11eb-81d9-1f3e4419449b.png">

**Comment by glepnir** [comment]
Maybe fixed. Please test.

**Comment by lynndylanhurley** [comment]
Will test today. Thx @glepnir !
