### ISSUE TITLE
bug: too fast keypressing and buffer switch leaves floating window open

### ISSUE THREAD

**Issue by matu3ba** [glepnir/lspsaga.nvim#131]
### Description
Floating window does not get closed, when keys for jumping are pressed too fast.

**Expected Behavior**
The floating window should never stay open, when the shown buffer changes.

**Actual Behavior**
The floating window remains open until one closes neovim with `:q!`.

**Neovim Built in Behavior**

Not sure. Do I need to setup omnicomplete for that? Default keybindings for lspconfig dont show anything.

### Details

<details><summary>Reproduce</summary>

1. setup lsp server, ie clang
2. `nnoremap <silent> gh <cmd>lua require'lspsaga.provider'.lsp_finder()<CR>` to configure keybinding
tmp.h:
```cpp
int alpha = 22;
```
tmp.cpp:
```cpp
#include "tmp.h"
int testing(int a)
{
  return alpha + a;
}
```
3. press very fast gh+o (it might not work every time, so just repeat a few times)
4. have a static floating window during neovim staying open
</details>
press 

<details><summary>Environment</summary>

- nvim --version output:
VIM v0.5.0-dev+1116-gbda12927b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Übersetzt von runner@fv-az36-775

Features: +acl +iconv +tui
See ":help feature-compile"

          System-vimrc-Datei: "$VIM/sysinit.vim"
     Voreinstellung für $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

- Operating system: Linux
- lspsaga commit: 4081ce51725b080bd59c3a8987d95fa481160dbf

</details>

Is this a known problem?

**Comment by glepnir** [comment]
reproduce.

**Comment by matu3ba** [comment]
![floatingwindow](https://user-images.githubusercontent.com/13089667/110131883-ea239b80-7dca-11eb-82c8-9133b364da1b.png)

**Comment by glepnir** [comment]
Please update and give it  test

**Comment by matu3ba** [comment]
nope.
![no](https://user-images.githubusercontent.com/13089667/110132301-51d9e680-7dcb-11eb-9e78-6f0baeb4ce17.png)

**Comment by glepnir** [comment]
my mistake. now works fine

**Comment by matu3ba** [comment]
> my mistake. now works fine

Humm. Is this a bug in plenary or popup maybe?

**Comment by glepnir** [comment]
no. lspsaga has own window api to create float window with border. did you still get this issue? I had test it works fine on my machine

**Comment by matu3ba** [comment]
> no. lspsaga has own window api to create float window with border. did you still get this issue? I had test it works fine on my machine

yes. Is it maybe some buffer change stuff that is broken, so do I need to close all buffers?

**Comment by glepnir** [comment]
did you update? which commit ?

**Comment by glepnir** [comment]
commit afbe401bf8e8b02e4b61459d012bf2c1c70b7cf0  I test it in my local works well. if you still got this problem . I need reproduce step.

**Comment by matu3ba** [comment]
my son keeps me away from keyboard :( I will get back to this later.

**Comment by matu3ba** [comment]
My init.lua for this:
```lua
require('packer').startup(
  function()
    use 'wbthomason/packer.nvim'
    use 'neovim/nvim-lspconfig'
    use 'glepnir/lspsaga.nvim'
  end
)
require'lspconfig'.clangd.setup{}
local opts = { noremap=true, silent=true }
vim.api.nvim_set_keymap('n', 'gh',    [[<cmd>lua require'lspsaga.provider'.lsp_finder()<CR>]], opts)
```

What further do you miss for reproducing?

**Comment by glepnir** [comment]
can't reproduce ..


https://user-images.githubusercontent.com/41671631/110205947-f3d5fd80-7eb5-11eb-9ea1-fbdfa5a94686.mov

**Comment by matu3ba** [comment]
> can't reproduce ..
> Screen.Recording.2021-03-06.at.7.55.20.PM.mov

I can only record this with asciinema. termtosvg is not fast enough on recording for the bug to occur?!?

![Peek 2021-03-08 21-32](https://user-images.githubusercontent.com/13089667/110378627-1acb3580-8056-11eb-9429-94f0b278f4c7.gif)

**Comment by glepnir** [comment]
it's wried .I can't reproduce it. you can confirm you used the latest version of lspsaga right?

**Comment by matu3ba** [comment]
> it's wried .I can't reproduce it. you can confirm you used the latest version of lspsaga right?

yes.
