### ISSUE TITLE
How to override default handlers

### ISSUE THREAD

**Issue by pianocomposer321** [glepnir/lspsaga.nvim#132]
I would like to show lspsaga's function help popup instead of the built in one. I tried:

```lua
vim.lsp.handlers["textDocument/signatureHelp"] = require('lspsaga.signaturehelp').signature_help()
```

but I get `[lspsaga] No lsp client available`.

How do I do this?

**Comment by glepnir** [comment]
lspsaga do rpc request self. it not callback for vim.lsp.handlers. you can't do this. you can use lspsaga signature help as default.

**Comment by pianocomposer321** [comment]
> lspsaga do rpc request self. it not callback for vim.lsp.handlers. you can't do this. you can use lspsaga signature help as default.

I'm not sure I follow...did you mean I _can't_ use lspsaga signature help as default? Or how do I do this, it's not in the readme.

If this isn't possible, then consider this issue a feature request. TBH, it doesn't make much sense to make a nice-looking signature help popup window that can only be called from a keybinding...

If you need inspiration on how to add handlers for vim.lsp.handlers, you could take a peek at https://github.com/RishabhRD/nvim-lsputils.

**Comment by glepnir** [comment]
what do you want ? the usage as same defaulf handler.  you can call lspsaga signature help everywhere

**Comment by glepnir** [comment]
don't know what do you mean.

**Comment by pianocomposer321** [comment]
The default function signature popup opens automatically while typing in insert mode (e.g. when you type opening parenthesis and a comma). If you overrode the default handler with one that would instead open the popup provided by this plugin, it would automatically open this plugin's signature help window while typing, right?

**Comment by glepnir** [comment]
it is an autocmd event.  and it not in upstream some completion plugin use it.  you can set lspsaga signature to autocmd

**Comment by pianocomposer321** [comment]
Ohhh, you're right...I'm using completion-nvim and it has `g:completion_enable_auto_signature`, which is automatically enabled. I assumed this was something built into lsp-config. I'm still not sure how I would get it to use this plugin's signature help window though, like what autocommands to use...I looked through the source code for completion-nvim, but it's a bit confusing...do you have any idea what autocommands I should use?

Thanks

**Comment by glepnir** [comment]
looks like completion-nvim do it in this function https://github.com/nvim-lua/completion-nvim/blob/master/lua/completion.lua#L232
it use own hook to run it.

**Comment by pianocomposer321** [comment]
> looks like completion-nvim do it in this function https://github.com/nvim-lua/completion-nvim/blob/master/lua/completion.lua#L232
> it use own hook to run it.

Ok, I may just fork completion-nvim and make `signature.autoOpenSignatureHelp` point to `lspsaga.signaturehelp.signature_help`. Seems like that may be the simplest thing to do.

**Comment by dimascyriaco** [comment]
@pianocomposer321 did you get this working?

**Comment by pianocomposer321** [comment]
> @pianocomposer321 did you get this working?

Not yet, I'm still not 100% sure how to go about it. If you have any ideas LMK.

**Comment by pianocomposer321** [comment]
@dimascyriaco This is a really naive approach, but it works - just replace the entire body of the function completion.signature_help.autoOpenSignatureHelp with require("lspsaga.signaturehelp").signature_help().

I'm not a git expert, so I don't know how you would do something like this while still keeping up to date with updates pushed to the upstream repo...I probably won't be using this myself for this reason, because the upstream repo is still being actively developed and maintained. @glepnir if you know more about this, I welcome your input.

**Comment by dimascyriaco** [comment]
@pianocomposer321 I was trying something like this:

```
autocmd InsertEnter * lua require("lspsaga.signaturehelp").signature_help()
```

It kind of works, but it only shows on enter. But it's better than nothing, I guess.

I'm not sure if this kind of logic should be responsibility of a completion plugin, since it has nothing to do with the completion itself.

**Comment by pianocomposer321** [comment]
@dimascyriaco yeah, I agree.

@glepnir In case you have any idea how to help with this, the ideal would be to show the popup:
On insert enter, but only if inside parens for a function call
When typing opening paren to call a function (or initialize a class, etc), but not for the condition in an if statement etc
When moving to a new argument in a function call or class initialization
After confirming a completion for a function or class initialization

I know it's a lot to ask, just outlining what would be the ideal situation.

**Comment by dimascyriaco** [comment]
@pianocomposer321 I think this logic depends on the language. Some languages don't need the parens. I think the `lsp` itself should be doing this logic (it's probably doing it when we call `signature_help()` in fact). I don't know if we could just call `signature_help()` on `InsertCharPre` (maybe async) or if it would tank performance. I'll try to look on 'completion-nvim' code how they do it.

**Comment by dimascyriaco** [comment]
If I understand correctly, they just set an [infinite loop](https://github.com/nvim-lua/completion-nvim/blob/master/lua/completion.lua#L187) and keep watching for changes with `api.nvim_buf_get_changedtick(0)`. I'll try to do something like this.

**Comment by pianocomposer321** [comment]
> If I understand correctly, they just set an [infinite loop](https://github.com/nvim-lua/completion-nvim/blob/master/lua/completion.lua#L187) and keep watching for changes with `api.nvim_buf_get_changedtick(0)`. I'll try to do something like this.

Ok, I'll definitely be interested to know how you do it if/when you figure it out.

Might also be worth opening an issue in completion-nvim and/or the lsp repo about this.
