### ISSUE TITLE
Diagnostic type not shown in line diagnostic

### ISSUE THREAD

**Issue by gshpychka** [glepnir/lspsaga.nvim#135]
### Description
All line diagnostic hover windows just say "Diagnostics:" and dont' specify the type (Warn, Error, Info)

**Expected Behavior**
Like in the docs
![image](https://user-images.githubusercontent.com/23005347/110693787-80532980-81f0-11eb-9459-3d9b24f0d108.png)

**Actual Behavior**

![image](https://user-images.githubusercontent.com/23005347/110693595-4a15aa00-81f0-11eb-9e93-1a74d8dcf646.png)

**Neovim Built in Behavior**

![image](https://user-images.githubusercontent.com/23005347/110693646-5863c600-81f0-11eb-84db-a07c2339e719.png)

### Details

Using pyright LS, latest neovim and lspsaga.

**Comment by glepnir** [comment]
hmm because the image of readme is old. about the new behavior .it should be highlight.

![image](https://user-images.githubusercontent.com/41671631/110721190-f6847a00-824a-11eb-9f52-5874f9f7dc66.png)

**Comment by glepnir** [comment]
maybe your colorscheme clear the highlight of lspsaga.

`hi LspDiagnosticsFloatingError` to check it.

**Comment by gshpychka** [comment]
Why did you remove the diagnostics type from the title? It's much more useful that way, is it possible to bring it back?

**Comment by glepnir** [comment]
yep . when i implement jump to next/prev in neovim upstream in this weekend .i will refactor diagnsotic of lspsaga.

**Comment by gshpychka** [comment]
Great to hear!

**Comment by gshpychka** [comment]
@glepnir can you link to the upstream issue/PR so I could follow the progress? Thanks.

**Comment by glepnir** [comment]
when i create pr I will link here :)

**Comment by gshpychka** [comment]
@glepnir any updates on this?

**Comment by glepnir** [comment]
yep. will improve later.

**Comment by gshpychka** [comment]
@glepnir any updates on this?

**Comment by gshpychka** [comment]
@glepnir any updates on this?
