### ISSUE TITLE
Code action throws error which moving between buffers

### ISSUE THREAD

**Issue by akinsho** [glepnir/lspsaga.nvim#137]
### Description

When using lsp saga with the code action light bulb enabled, occasionally when moving between buffers it throws this error
```
Error executing vim.schedule lua callback: .../pack/packer/opt/lspsaga.nvim/lua/lspsaga/codeaction.lua:42: line value outside range
```
It seems to happen most frequently when you start in say `dart` or `lua` and then move to an empty buffer or to a different filetype like a markdown readme

**Expected Behavior**

No Error

#### config:

```lua
  saga.init_lsp_saga {
    use_saga_diagnostic_sign = false,
    finder_action_keys = {
      vsplit = "v",
      split = "s",
      quit = {"q", "<ESC>"}
    },
    code_action_icon = "💡",
    code_action_prompt = {
      enable = true,
      sign = false,
      virtual_text = true
    }
  }

```

**Comment by akinsho** [comment]
@glepnir I don't think this is actually fixed I still get this a lot whilst developing in dart. For context I move between my `log` buffer which has running process output and my `dart` code and see this issue quite a lot since the lightbulb was added.

**Comment by glepnir** [comment]
hmm check it now.

**Comment by glepnir** [comment]
@akinsho  can you provide a min dart code can reproduce this issue ?

**Comment by akinsho** [comment]
@glepnir I've just tried moving through some buffers in my work repo and I think it happens when moving from a supported buffer i.e. one that has code actions to another that doesn't. I move between graphql and log filetypes to dart in my project and I think that triggers the error, the first time you enter a new filetype that doesn't have code actions

**Comment by akinsho** [comment]
I think currently lspsaga is using a manual block list but I think that means anytime it encounters a new file type that doesnt support code actions it will error. Maybe rather than a hard coded list it should check if there is an active client that supports code actions before trying to show the lightbulb

**Comment by glepnir** [comment]
@akinsho  okay got it. another question .got this with bufferline 
![image](https://user-images.githubusercontent.com/41671631/112645770-cb706c00-8e81-11eb-9afa-b7a0c51da884.png)

**Comment by akinsho** [comment]
It's happening because bufferline got reloaded during the same neovim session i.e. the setup function got called twice so it's trying to create commands twice in that screenshot. The commands I create should use `command!` rather than `command` tbh, didn't forsee people reloading it during the same session

**Comment by glepnir** [comment]
yep so can fix this ?

**Comment by akinsho** [comment]
Will do when next I get a chance 👍🏿

**Comment by glepnir** [comment]
hmm codeaction prompt check the lsp client . so I don't think problem is here 

```lua
lspaction.code_action_prompt = function ()
  if special_buffers[vim.bo.filetype] then return end
  local active_lsp,_ = libs.check_lsp_active()
  if not active_lsp then return end

  local diagnostics = vim.lsp.diagnostic.get_line_diagnostics()
  local winid = get_current_winid()
  Action[winid] = Action[winid] or {}
  Action[winid].lightbulb_line = Action[winid].lightbulb_line or 0
  Action:code_action(action_vritual_call_back,diagnostics)
end

```

**Comment by akinsho** [comment]
Hmm 🤔  so the specific error is coming from setting the `extmark` the `line value outside range`. Could it be a race condition so if you switch buffers too fast the it tries to draw an extmark when the file is no longer the correct one?

Side note: The extmarks I think should use the new `hl_mode` arg that @.bfredl added since the highlights override things like cursorline unless the `hl_mode = "combine"` or one of those options (sorry this is a different issue, not to add too many just remembered since I'm looking at it closely now)

**Comment by akinsho** [comment]
> yep so can fix this ?
BTW this is hopefully fixed now. If you are still getting it please raise an issue on my repo 👍🏿

**Comment by glepnir** [comment]
I have been very busy these days, I have not paid attention to the progress of neovim . can take a link of `hl_mode` ？

**Comment by akinsho** [comment]
No worries @glepnir it's not a big issue at all, was just mentioning in as an FYI heres the PR https://github.com/neovim/neovim/pull/14065.

Anyway thanks for all your work on this plugin btw 💪🏿 , I've started using it for work which is why I raise so many issues 😅 sorry

**Comment by glepnir** [comment]
I can't reproduce it in my local . So if you have time, I hope you can provide a small  dart code that I can use to test Thanks .

**Comment by akinsho** [comment]
@glepnir I'm not sure it's specifically about dart, it's mainly happening when I'm switching around buffers all the time. I initially mentioned dart because I work mostly in dart and I thought that's where the problem was coming from. It doesnt happen if I'm just staying inside a dart buffer. It's only when I do things like open telescope or go between a bunch of different buffers.

I'll see if I can narrow it down further when I get some time

**Comment by glepnir** [comment]
Okay thanks for your report:)

**Comment by akinsho** [comment]
Think this might be fixed now 🤞🏿 haven't seen it in a few days

**Comment by glepnir** [comment]
glad to hear that.
