### ISSUE TITLE
Unified window system? 

### ISSUE THREAD

**Issue by mhartington** [glepnir/lspsaga.nvim#138]
**Is your feature request related to a problem? Please describe.**
When showing both line diagnostics and a hover window, two window will be created and overlap one another. This can make it hard to read one window.

<img width="1003" alt="Screen Shot 2021-03-15 at 3 32 33 PM" src="https://user-images.githubusercontent.com/2835826/111210610-d256cf00-85a3-11eb-8cda-c6970fb7edbb.png">

**Describe the solution you'd like**
Make use of a one window approach. When showing a hover, create a window. When a diagnostic request comes in, instead of creating a new window, just update the existing window and its content.

**Describe alternatives you've considered**
Another option would be to use a different location all together, which could also be do-able.

**Comment by mhartington** [comment]
Just tested this...not sure, but is this the intended result? 

<img width="892" alt="Screen Shot 2021-03-16 at 8 47 19 AM" src="https://user-images.githubusercontent.com/2835826/111311131-3a54f600-8634-11eb-8790-b5fcf6c73bd4.png">

**Comment by glepnir** [comment]
how about now.

**Comment by mhartington** [comment]
I mean, it's better, but still not what I had in mind. So I had this working in nvim-typescript like so...



With only diagnostics showing: 

<img width="688" alt="Screen Shot 2021-03-16 at 9 04 42 AM" src="https://user-images.githubusercontent.com/2835826/111313367-a6d0f480-8636-11eb-8c50-ff5a35436e47.png">


If diagnostics or any window exist and new data comes in...append it the exist window and add a separator.

<img width="653" alt="Screen Shot 2021-03-16 at 9 04 21 AM" src="https://user-images.githubusercontent.com/2835826/111313329-9ae53280-8636-11eb-8d68-a575e5ae7747.png">

Similar how vscode shows things, they append the new incoming text or diagnostics to the existing floating window

**Comment by glepnir** [comment]
this behavior more friendly. can you open an feature request about this append text to exist window?  and one question if the hover doc too long vscode still append diagnostic text to it ? like `foreach` keyword? it has a long hover doc.

**Comment by mhartington** [comment]
Tough to test that in vscode as they only show diagnostics for the cursor position, not the whole line. But I'll open up an issue for the append text

**Comment by glepnir** [comment]
Thanks  I would like implement it.
