### ISSUE TITLE
Any way to change the float shape?

### ISSUE THREAD

**Issue by ckipp01** [glepnir/lspsaga.nvim#14]
While looking at the readme and looking at the hover example, they look great. In my situation however without any custom settings I'm seeing the hovers as extremely long and tall. Is there anything that I could check or edit to keep this from happening. As you can see in the screenshot, there is a lot of space available, so I'm confused why it's so tall and narrow.

<img width="1587" alt="Screenshot 2021-01-25 at 19 18 16" src="https://user-images.githubusercontent.com/13974112/105748390-5bf20500-5f42-11eb-8ea8-707d609e776a.png">

**Comment by elianiva** [comment]
maybe try #6? It was causing Neovim to freeze previously but I think I've fixed it

**Comment by glepnir** [comment]
config `max_hover_width` to change the widht. thanks @elianiva
