### ISSUE TITLE
Code action visual range opens with all options visually selected

### ISSUE THREAD

**Issue by akinsho** [glepnir/lspsaga.nvim#142]
### Description

When using `<cmd>'<,'>lua require('lspsaga.codeaction').range_code_action()<CR>` on an identifier the code action menu has all of it's content visually selected.

![lsp_saga_visual](https://user-images.githubusercontent.com/22454918/111230026-d48a4f00-85de-11eb-9b82-4f07445d64cb.gif)

**Expected Behavior**

Open without visual selection since there is no use selecting everything in the window

**Actual Behavior**

**Neovim Built in Behavior**

Doesn't show a floating window by default so doesn't have the same problem

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: 
- lspsaga commit: 

</details>

**Comment by glepnir** [comment]
can you test this map ?
```
vnoremap <silent><leader>ca :<C-U>Lspsaga range_code_action<CR>
```

**Comment by akinsho** [comment]
That works 🚀 , I guess using a command (`<Cmd>`) mapping somehow breaks things 🤔

**Comment by glepnir** [comment]
yep a wrong description in reademe :)
