### ISSUE TITLE
LspSaga Hover window is closed too quickly

### ISSUE THREAD

**Issue by akinsho** [glepnir/lspsaga.nvim#144]
### Description

When using lspsaga's hover doc command to visual some info on a symbol, it closes itself very quickly which is quite frustrating because it becomes quite hard to read through the information it shows especially for languages that include a lot of docs

#### LSP Saga
![lsp_saga_hover_timeout](https://user-images.githubusercontent.com/22454918/111500334-c867d400-873b-11eb-8f3a-e6fe2b56e72b.gif)

#### Native LSP handler
![native_lsp_hover](https://user-images.githubusercontent.com/22454918/111500353-d158a580-873b-11eb-8674-3dbf2d7ef46c.gif)

**Expected Behavior**

It should remain open till the user performs an action

**Actual Behavior**

It closes after about 2 seconds

**Neovim Built in Behavior**

`vim.lsp.buf.hover()` stays open till the user moves as I've described

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: 
- lspsaga commit: 

</details>

**Comment by glepnir** [comment]
hmm did you use some autocmd for show line diagnostic or something else ?

**Comment by akinsho** [comment]
Yeah I have
```lua
  require("as.autocommands").augroup(
    "LspSagaCursorCommands",
    {
      {
        events = {"CursorHold"},
        targets = {"*"},
        command = "lua require('lspsaga.diagnostic').show_line_diagnostics()"
      }
  }
```

Are they interacting? I would have thought that they were separate so one shouldn't close the other

**Comment by glepnir** [comment]
I saw it in your dotfiles :) . a logic bug of saga .

**Comment by glepnir** [comment]
@akinsho  sorry for bother you. can you confirm now works or not?

**Comment by akinsho** [comment]
@glepnir that fixed it 👍🏿 thanks

**Comment by akinsho** [comment]
It still closes if there is a diagnostic window on the line but thats fine I saw #138 and some other chat about unifying the windows which I think would be helpful in the future (if you decide to do it) but this is good for now

**Comment by glepnir** [comment]
yep I need refactor the window api of lspsaga later

**Comment by glepnir** [comment]
now should be works  :)

**Comment by akinsho** [comment]
Just noticed this now not sure how old it is but if you scroll to the bottom of the window with the smart scroll binding and press it again at the end you get
`E5108: Error executing lua .../site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/hover.lua:47: attempt to index a number value`

**Comment by glepnir** [comment]
fixed
