### ISSUE TITLE
Automatically open and close the signature window

### ISSUE THREAD

**Issue by akinsho** [glepnir/lspsaga.nvim#145]
**Is your feature request related to a problem? Please describe.**
Currently the signature window has to be triggered manually, which is a pain.
If not triggered manually e.g. using `CompleteDone` or `CursorHold` it will appear and disappear constantly which looks like a flicker and is annoying to try to read.

Whilst using coc or completion-nvim (historically) this would open at the right time and close at the right time without the user having to manage it or remembering to press it. Recently a plugin that implements this was created -> https://github.com/ray-x/lsp_signature.nvim. Unfortunately it doesn't integrate with lspsaga which I use for my other lsp related windows.

**Describe the solution you'd like**
It would be great to get similar functionality as that plugin provides natively in lspsaga. The code it uses is essentially cut out of completion.nvim which provides this functionality and I think can more or less copied and adapted here.

**Describe alternatives you've considered**
I considered using that plugin and that is still an option if it doesn't fit with lspsaga but that won't integrate with this plugin and would mean overriding if possible it's handling of the signature window. Also this isn't something that can be implemented elsewhere since `nvim-compe` will not support it and completion-nvim is defunct. But more importantly if it was implemented elsewhere the signature wouldn't match the rest of the lsp UI.

**Comment by glepnir** [comment]
@akinsho  I had think about this. need talk with nvim-compe author. If it can provide a hook will be easy to do that.

**Comment by glepnir** [comment]
relate https://github.com/hrsh7th/nvim-compe/issues/267

**Comment by seblj** [comment]
Any updates on this @glepnir?

**Comment by danielnehrig** [comment]
Would really like seeing this implemented

**Comment by ray-x** [comment]
Did anyone try:
1) install  both lspsaga and lsp_signature 
2)  hook the callback of signature help to lspsaga (not lsp_signature). 
3) Insert your function
I think in this case it should show saga signature. The only thing I am not sure is will it be auto-close or not.

**Comment by matbme** [comment]
I managed to implement this by shamelessly borrowing some things from [lsp_signature.nvim](https://github.com/ray-x/lsp_signature.nvim). I created a file called lspsaga_config.lua in my lua folder with the following code:

``` lua
local M = {}

require('lspsaga').init_lsp_saga()

function M.check_trigger_char(line_to_cursor, trigger_character)
  if trigger_character == nil then
    return false
  end
  for _, ch in ipairs(trigger_character) do
    local current_char = string.sub(line_to_cursor, #line_to_cursor - #ch + 1, #line_to_cursor)
    if current_char == ch then
      return true
    end
    if current_char == " " and #line_to_cursor > #ch + 1 then
      local pre_char = string.sub(line_to_cursor, #line_to_cursor - #ch, #line_to_cursor - 1)
      if pre_char == ch then
        return true
      end
    end
  end
  return false
end

function M.lspsaga_open_signature_help()
	local clients = vim.lsp.buf_get_clients(0)
	if clients == nil or clients == {} then return end

	local triggered = false
	for _, client in pairs(clients) do
		local triggers = client.server_capabilities.signatureHelpProvider.triggerCharacters

		local pos = vim.api.nvim_win_get_cursor(0)
		local line = vim.api.nvim_get_current_line()
		local line_to_cursor = line:sub(1, pos[2])

		if triggered == false then
			triggered = M.check_trigger_char(line_to_cursor, triggers)
		end
	end

	if triggered then
		require('lspsaga.signaturehelp').signature_help()
	end
end

vim.cmd "augroup Signature"
vim.cmd "autocmd! * <buffer>"
vim.cmd "autocmd InsertCharPre * lua require'lspsaga_config'.lspsaga_open_signature_help()"
vim.cmd "augroup end"

return M
```

And then calling `require('lspsaga_config')` in my init.lua.

I'm still testing it out, but I could create a PR to implement this into the plugin itself if @glepnir's fine with it.

**Comment by MonstrousOgre** [comment]
@matbme  I had to make a small change since I got an error that signatureHelpProvider was a nil value, but it works fine otherwise. I'd love for this to be merged into the plugin.

**Comment by Vanderscycle** [comment]
@matbme,

Thank you for the signature config. I got it to work yesterday, but I'm getting this error now.
```lua
Error detected while processing InsertCharPre Autocommands for "*":
E5108: Error executing lua /home/henri/.config/nvim/lua/lspsaga_config.lua:30: attempt to index field 'signatureHelpProvider' (a nil value)
```
Not sure if anyone experienced the same problem.

**Comment by MonstrousOgre** [comment]
@Vanderscycle I was facing that error. I just had to check if `signatureHelpProvider` was nil.

Try this
```
function M.lspsaga_open_signature_help()
  local clients = vim.lsp.buf_get_clients(0)
  if clients == nil or clients == {} then
    return
  end

  local triggered = false
  for _, client in pairs(clients) do
    if (client.server_capabilities.signatureHelpProvider) then
      local triggers = client.server_capabilities.signatureHelpProvider.triggerCharacters

      local pos = vim.api.nvim_win_get_cursor(0)
      local line = vim.api.nvim_get_current_line()
      local line_to_cursor = line:sub(1, pos[2])

      if triggered == false then
        triggered = M.check_trigger_char(line_to_cursor, triggers)
      end
    end
  end

  if triggered then
    require('lspsaga.signaturehelp').signature_help()
  end
end
```
