### ISSUE TITLE
Odd color when there are multiple new lines

### ISSUE THREAD

**Issue by ckipp01** [glepnir/lspsaga.nvim#15]
I've noticed that in floats when there are multiple new lines there is an odd highlight for a couple of characters.

<img width="204" alt="Screenshot 2021-01-25 at 19 22 26" src="https://user-images.githubusercontent.com/13974112/105748796-e63a6900-5f42-11eb-90e6-3c772084e840.png">

Here is another minimal one with what the markdown looks like:

<img width="658" alt="Screenshot 2021-01-25 at 19 22 10" src="https://user-images.githubusercontent.com/13974112/105748829-f05c6780-5f42-11eb-8dd6-d467b4d61c5a.png">

```
[Trace - 07:21:24 PM] Sending response 'textDocument/hover - (26)'. Processing request took 5ms
Result: {
  "contents": {
    "kind": "markdown",
    "value": "```scala\nval partitions: scala.collection.immutable.Iterable[SetBreakpointsArguments]\n```\n\n**With synthetics added**:\n```scala\nval currentClassNames \u003d partitions.map(_.getSource().getPath())(scala.collection.immutable.Iterable.canBuildFrom[java.lang.String]).toSet\n```"
  }
}
```

**Comment by akinsho** [comment]
Just to spare some time looking into this, there is a similar issue using the native lsp without any plugins. In this case it is the `mkdLineBreak` highlight group which is applied by the markdown syntax file. There are similar issues with golang and maybe more. There is a neovim issue about this but I forget the number. Essentially the bundled syntax files for a few languages have whitespace highlights. Not sure what a good general solution is but a quickfix is to `syntax clear mkdLineBreak` and others as they crop up

**Comment by glepnir** [comment]
It looks a bit troublesome. So I will solve it after solving other important window problems

**Comment by glepnir** [comment]
https://github.com/neovim/neovim/pull/13803  seems like this pr can do this better?

**Comment by glepnir** [comment]
@ckipp01  I checked the picture carefully, it looks like the highlight of the indentation plugin？

**Comment by ckipp01** [comment]
> @ckipp01 I checked the picture carefully, it looks like the highlight of the indentation plugin？If you used indent-guides.nvim It built in support lspsaga hover.

No, I don't use `indent-guides.nvim`.

**Comment by glepnir** [comment]
which indent plugin do you used?  in pic is scala? need a code snippet that can reproduce it ..I don't write scala..

**Comment by mjlbach** [comment]
@ckipp01 Try removing this line https://github.com/glepnir/lspsaga.nvim/blob/c8923d9b070521ccb66b4999f4e53ac3f34d9b9e/lua/lspsaga/window.lua#L273

**Comment by ckipp01** [comment]
> @ckipp01 Try removing this line 

Ahhhh bingo! Yes, that does remove it!

For example with this minimal config:

```lua
local cmd = vim.cmd
----------------------------------
-- PLUGINS -----------------------
----------------------------------
cmd [[packadd packer.nvim]]
require('packer').startup(function(use)
  use {'wbthomason/packer.nvim', opt = true}

  use {'glepnir/lspsaga.nvim'}
  use 'scalameta/nvim-metals'

end)

local saga = require 'lspsaga'
saga.init_lsp_saga()
----------------------------------
-- OPTIONS -----------------------
----------------------------------
vim.o.shortmess = string.gsub(vim.o.shortmess, 'F', '') .. 'c'

local function map(mode, lhs, rhs, opts)
  local options = {noremap = true, silent = true}
  if opts then
    options = vim.tbl_extend('force', options, opts)
  end
  vim.api.nvim_set_keymap(mode, lhs, rhs, options)
end

map('n', 'K', '<cmd>lua require"lspsaga.hover".render_hover_doc()<CR>')
----------------------------------
-- COMMANDS ----------------------
----------------------------------
-- LSP
cmd [[augroup lsp]]
cmd [[autocmd!]]
cmd [[autocmd FileType scala setlocal omnifunc=v:lua.vim.lsp.omnifunc]]
cmd [[autocmd FileType scala,sbt lua require("metals").initialize_or_attach({})]]
cmd [[augroup end]]
```

Doing a hover right now looks like this:

<img width="1113" alt="Screenshot 2021-02-02 at 09 50 18" src="https://user-images.githubusercontent.com/13974112/106575480-6d3ba280-653c-11eb-9a15-f3f367df3280.png">

Removing the line that you mention @mjlbach fixes the odd highlight and it now looks like this:

<img width="1113" alt="Screenshot 2021-02-02 at 09 52 01" src="https://user-images.githubusercontent.com/13974112/106575563-82b0cc80-653c-11eb-94d4-263580caadab.png">

**Comment by mjlbach** [comment]
Yeah it's a known issue that I've been on and off trying to fix, that has to do with the whitespace padding. Glepnir is using the same function as from core, which adds whitespace which your colorscheme is highlighting. This can also causes a variety of highlighting rules to trigger.

**Comment by glepnir** [comment]
Thanks for help .removed .

**Comment by mjlbach** [comment]
The main issue with just removing the line, is that the text will run right up to the border of the floating window. I think a better solution is to implement padding in the floating window api, instead of hacking it by adding padding in the text.

**Comment by glepnir** [comment]
> I think a better solution is to implement padding in the floating window api, instead of hacking it by adding padding in the text.

If do this `vim.lsp.util._trim_and_pad(contents,{pad_left=0,pad_right=0})` also can solved this issue. but as you said it not a better way

**Comment by mjlbach** [comment]
Right, that will still trim, but not pad (which avoids the issue, but leads to the lack of spacing. 

Another hack is to draw two floating windows, where the top floating window containing the text is one row/column smaller than the parent floating window.

**Comment by glepnir** [comment]
I current use two float window . one is border one is content.
