### ISSUE TITLE
`<c-w><c-w>` does not move to floating window

### ISSUE THREAD

**Issue by phelipetls** [glepnir/lspsaga.nvim#151]
### Description
`<c-w><c-w>` does not go inside a floating window. Clicking with the mouse also does not work.

**Expected Behavior**
It should.

**Actual Behavior**
It does not.

**Neovim Built in Behavior**
When I press `<c-w><c-w>` after `:lua vim.lsp.buf.hover()`, it moves to the floating window.

### Details

<details><summary>Reproduce</summary>

1. Press the hover command and then `<c-w><c-w>`
</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: 
- lspsaga commit: 855a8d816fa4f

</details>

**Comment by glepnir** [comment]
yep . you can't jump into it. but you can use smart scroll to scroll the hover window.

**Comment by Melkster** [comment]
I often find myself wanting to yank error messages from the floating window. Is this possible currently?
