### ISSUE TITLE
Allow for using a table of action_keys for more than only the quit key

### ISSUE THREAD

**Issue by mortepau** [glepnir/lspsaga.nvim#156]
**Is your feature request related to a problem? Please describe.**
Allow for defining a table for all the action keys and not only the `quit` key.

**Describe the solution you'd like**
Would be nice if something like this was allowed
```lua
require('lspsaga').init_lsp_saga({
  finder_action_keys = {
    open = { 'o', '<CR>' }, -- This is currently not supported
    quit = { 'q', '<ESC>' },
  }
})
```

Currently a table is only supported for the `quit` key.

**Comment by glepnir** [comment]
support it later.
