### ISSUE TITLE
Disable devicons (nerdfont icons)

### ISSUE THREAD

**Issue by timsofteng** [glepnir/lspsaga.nvim#158]
Hello. I don't have devicons and nerdfont. I've installed `lspsaga` and noticed this
![image](https://user-images.githubusercontent.com/51912173/113190414-eddcfd80-9264-11eb-93f1-25b0f2ad4b7b.png)

Is it any way to disable icons to regular letters which supported by any font?

**Comment by gshpychka** [comment]
https://github.com/glepnir/lspsaga.nvim#usage

**Comment by timsofteng** [comment]
![image](https://user-images.githubusercontent.com/51912173/113407639-60112780-93b6-11eb-9d89-436f2b7b8367.png)
That doesn't help.

**Comment by gshpychka** [comment]
Just read the `Usage` portion of the doc, I linked to it. The very first code block is what you seem to have missed.

**Comment by timsofteng** [comment]
> Just read the `Usage` portion of the doc, I linked to it. The very first code block is what you seem to have missed.

What block you mean? I don't understand.

**Comment by gshpychka** [comment]
![image](https://user-images.githubusercontent.com/23005347/113434505-c3687d00-93e9-11eb-90e7-4c504c614a48.png)

This blocks explains the configuration parameters, including the sign glyphs.

**Comment by glepnir** [comment]
like doc say

**Comment by timsofteng** [comment]
@gshpychka is it possible to add option like `disable_iconst = true` instead of configure every sign?
