### ISSUE TITLE
Large function signature causes window overflow

### ISSUE THREAD

**Issue by akinsho** [glepnir/lspsaga.nvim#159]
### Description

Sorry me again 😅 .

This issue relates to window sizing which is much improved generally, in this case though I've found when using dart which provides huge amount of useful docs in the hover windows that if the function signature is large then the hover window can easily overflow. I don't know for certain that it is only due to the signature and that if the content was longer it wouldn't also break 🤷🏿 .

![image](https://user-images.githubusercontent.com/22454918/113200379-262e0d00-9260-11eb-9e00-3ca9a7f40334.png)

**Expected Behavior**

The window should have a max height and if the combined signature *and* content extend beyond the height allow scrolling it all as one. I tried to show an example for vscode but the wretched thing disappears when I put my screenshot tool on top of it

**Actual Behavior**

As above

**Neovim Built in Behavior**

### Details

<details><summary>Reproduce</summary>

1. Create a test dart file and post the sample code in it.
1. Install `flutter` -> https://flutter.dev/docs/get-started/install
1. Enable flutter/dart lsp using `lspconfig.dartls.setup{}`
1. With the cursor on top of `TextFormField` trigger `Lspsaga hover`
</details>

```dart
import 'package:flutter/material.dart';

class Test extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return TextFormField(    
       onChanged: () {},
       validator: (_) {}
     ),
  }
}
                

```

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: 
- lspsaga commit: 

</details>

**Comment by glepnir** [comment]
reproduce.

**Comment by akinsho** [comment]
@glepnir I left the instructions to reproduce it as well as a code snippet you can use in the issue description. You need to use `hover` doc command on any `TextFormField` in a dart file actually sorry I left the import statement out in the snippet I'll edit it. The widget comes from flutter
