### ISSUE TITLE
intermittent error from lua/lspsaga/codeaction.lua:52

### ISSUE THREAD

**Issue by MagicDuck** [glepnir/lspsaga.nvim#161]
### Description
When triggering `:LspSaga code_action`, there is an intermittent error from the following line:
https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/codeaction.lua#L52
Seems like `Action[winid]` sometimes ends up being `nil`.

I can usually reproduce the behaviour by moving around a bit, or switching windows and back to the line with the code action.
    
For now I have modified that file and added a workaround:
(sorry, I don't understand enough about it to provide a PR 😢 )
```
    if (Action[winid] ~= nil) then
      Action[winid].lightbulb_line = line
    end
```

Other details:
I have 2 lsp clients connected to the buffer:
![image](https://user-images.githubusercontent.com/95201/113384226-72e61680-933a-11eb-8810-cb67d9950ff9.png)

My saga config:
```lua
local saga = require 'lspsaga'
saga.init_lsp_saga({
  rename_action_keys = {
    quit = '<ESC>',
    exec = '<CR>'
  },
  code_action_keys = {
    quit = '<ESC>',
    exec = '<CR>'
  },
  code_action_prompt = {
    enable = true,
    sign = true,
    sign_priority = 20,
    virtual_text = false,
  },
  use_saga_diagnostic_sign = false,
  -- error_sign = "",
  -- warn_sign = "",
  -- hint_sign = "",
  -- infor_sign = "✘",
  dianostic_header_icon = '   ',
  code_action_icon = ' '
})
```

**Expected Behavior**
No error.

**Actual Behavior**
Errors out. code actions  popup looks ugly:
![image](https://user-images.githubusercontent.com/95201/113384091-2a2e5d80-933a-11eb-9d0d-486da020eab9.png)

**Neovim Built in Behavior**
Builtin works, just doesn't look as pretty as saga :)

**Comment by MagicDuck** [comment]
might be a `winid` vs `winnr` thing. When I print out `Actions` it has window numbers (1, 2, ...) as keys

**Comment by MagicDuck** [comment]
Looks like winid ends up being the id of the code actions content window.
Here's a `vim.inspect` printout of `Action` and `winid`
```
<1>{
  [1000] = {
    lightbulb_line = 1753
  },
  __index = <table 1>,
  action_callback = <function 1>,
  actions = { {
  ....  omitted...
  }}
  apply_action_keys = <function 2>,
  border_winid = 1002,
  bufnr = 2,
  clear_tmp_data = <function 3>,
  code_action = <function 4>,
  contents_bufnr = 6,
  contents_winid = 1003,  <---------------- contents winid
  do_code_action = <function 5>,
  quit_action_window = <function 6>,
  range_code_action = <function 7>,
  render_action_virtual_text = <function 8>,
  set_cursor = <function 9>
}
1003           <------------------    winid

Error executing vim.schedule lua callback: ...are/nvim/plugged/lspsaga.nvim/lua/lspsaga/codeaction.lua:72: attempt to index a nil value
``` 
Note, line number is different because of my print statements and formatting.

**Comment by glepnir** [comment]
aha ...should be a bug

**Comment by glepnir** [comment]
@MagicDuck  can you provide a reproduce step and min code?

**Comment by glepnir** [comment]
hi there ?

**Comment by nghialm269** [comment]
I can sometimes reproduce the error but at different line (https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/codeaction.lua#L31) since I have `virtual_text` enable instead of `sign`:
```lua
code_action_prompt = {
  enable = true,
  sign = false,
  virtual_text = true,
},
```
Reproduce (not reliably):
1. Open a buffer and place the cursor in a line that has code action
2. Open an empty buffer in a new split: `:sp | :enew`
3. Spam (same pace as your `updatetime`) `<C-w><C-w>` till you see the error.

![image](https://user-images.githubusercontent.com/13317164/113672611-328feb00-96e2-11eb-8536-abe520b78c16.png)

**Comment by CallumHoward** [comment]
I am able to reproduce an error that seems like it might be related.
Steps:
1. Open file with code actions
2. Trigger `Lspsaga code_action` with mapping
3. Close the popup window with `<C-W>c`

After this, if I try to trigger `Lspsaga code_action` again on any line with a code action I get
```
Error executing vim.schedule lua callback: ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:123: Invalid buffer id: 39
```
(in this case the number of the current buffer shown by `:ls` was 37).

**Comment by J-E-Mc** [comment]
I quite often get the error `Error executing vim.schedule lua callback: lspsaga.nvim/lua/lspsaga/codeaction.lua:52: attempt to index a nil value` when I open an embedded terminal with `split term://...`, the error is due to `Action[winid]` being `nil`

**Comment by academo** [comment]
I can also often reproduce the error when working with typescript

![image](https://user-images.githubusercontent.com/227916/128014224-fe73dbc3-f961-4d73-84a6-7db21831fab0.png)

it happens with most of the code actions I try to perform.

**Comment by EthanJWright** [comment]
FWIW as a workaround for this error, I'm simply disabling the code action prompt in the lsp saga config like so:
```
    code_action_prompt = {
      enable = false,
      sign = false,
      virtual_text = false,
    },
```

And then I'm using [nvim-lightbulb](https://github.com/kosayoda/nvim-lightbulb) to manage the code action icon instead.
