### ISSUE TITLE
Code action sign on gutter doesn't take priority

### ISSUE THREAD

**Issue by zlksnk** [glepnir/lspsaga.nvim#167]
### Description

Whenever code action lightbulb sign needs to appear on the same line where a warning is present, warning sign takes priority on gutter over code action even if its priority is high.

**Expected Behavior**

`code_action_prompt.sign_priority` should prioritize code action icon over other diagnostics when its priority value is increased.

**Actual Behavior**

`code_action_prompt.sign_priority` does not prioritizes lightbulb icon on gutter. You can see flicker of lightbulb and warning sign taking over the gutter after first navigation over that line.

![tre (0)](https://user-images.githubusercontent.com/26769888/113790427-34fc4000-96f6-11eb-98e0-4cfc0097dae5.gif)

### Details

<details><summary>Reproduce</summary>

- [Open this CodeSandbox](https://codesandbox.io/s/boring-sea-6hid8?file=/src/App.js:173-175) and download it using File -> Export to ZIP
- Extract the zip and install packages using `npm i` or any Node.js package manager
- Open `App.js` and navigate to line 9 to see a warning and code action

You'll need to install and setup ESLint to provide code action, [LSP installer plugin](https://github.com/williamboman/nvim-lsp-installer/) can help here. Alternatively, try to emulate a line which has both a code-action and a warning sign.

Minimal Lua file:

```lua
local saga = require 'lspsaga'

saga.init_lsp_saga {
  error_sign = '🔥',
  warn_sign = '🐛',
  code_action_icon = '💡',
  code_action_prompt = {
    sign_priority = 60,
    virtual_text = false
  },
  hint_sign = '🌿',
  dianostic_header_icon = "👀 "
}

```
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1221-g9b2d4ff62 \ Build type: RelWithDebInfo
- Operating system: Ubuntu 20.04.2 LTS on Windows 10 x86_64
- lspsaga commit: 27c7a4796869e155ecec48eb3f8e66694c1708e2

</details>

**Comment by glepnir** [comment]
because  it only show on wrong line. so you see the diagnostic icon. when you move the wrong line. you see the lightbulb icon

**Comment by lrvpxl** [comment]
By wrong line I believe you mean line 9 in the GIF above. I'm talking about the same line. If you notice, if I go to the line below or above it and come back, warning icon doesn't gets replaced by lightbulb icon.

Update: with latest Neovim and LSP Saga, code lightbulb icon does not appear at all as it gets shadowed by warning icon. It of course does appear if there are no diagnostics on the same line.
![ss12](https://user-images.githubusercontent.com/26769888/114191549-64cb6380-9901-11eb-99da-ea0a589d281d.gif)

**Comment by lrvpxl** [comment]
Update: with latest Neovim and LSP Saga, code lightbulb icon does not appear at all as it gets shadowed by warning icon.

![ss12](https://user-images.githubusercontent.com/26769888/114191549-64cb6380-9901-11eb-99da-ea0a589d281d.gif)

It of course does appear if there are no diagnostics on the same line.

**Comment by glepnir** [comment]
got it. will fix in #163

**Comment by glepnir** [comment]
about icon .works for me like this

![Untitled](https://user-images.githubusercontent.com/41671631/114268898-2d120800-9a36-11eb-934d-5afcca399863.gif)

**Comment by lrvpxl** [comment]
Hmm, I’ll try to replicate this issue on another machine and will get back to you tomorrow. Let’s keep this issue open till then.

**Comment by glepnir** [comment]
maybe you can set the priority to max 9999

**Comment by zlksnk** [comment]
Okay, so I am facing some issue with installing eslintls on my other machine but still in your GIF I can see a lightbulb appearing for line `console.log(s)` which I believe is coming from tsserver. I don't see a lightbulb for that `console.log` line at my side. This is with a fresh installation of Neovim and plugins.

**Comment by glepnir** [comment]
maybe fixed.

**Comment by zlksnk** [comment]
Yes it is fixed, although it take time to appear.

**Comment by glepnir** [comment]
> although it (lightbulb) takes time to appear.

hmm @zlksnk  what does this mean?

**Comment by zlksnk** [comment]
![ss12](https://user-images.githubusercontent.com/26769888/114867226-5ec5fe80-9da9-11eb-8880-bebeab78794c.gif)

The lightbulb doesn't appears immediately on the line that I'm on, rather it takes few seconds to update itself.

**Comment by zlksnk** [comment]
^ Turns out this was happening due to [CursorHold](https://github.com/glepnir/lspsaga.nvim/blob/333178b4e941eb19d9c97c0b0b5640c76363b0ad/lua/lspsaga/init.lua#L65) which is a fine behaviour.
