### ISSUE TITLE
Code action from multiple LSPs breaks popup 

### ISSUE THREAD

**Issue by zlksnk** [glepnir/lspsaga.nvim#170]
### Description

When code action is received from multiple LSPs, Saga shows actions from only one LSP at first and then breaks when `q` is pressed to exit out of the first popup that appears.

**Expected Behavior**

Actions from different LSPs should appear in a single popup to avoid UI issues and to make it easy to select a code action in one go. There is a relevant [PR in Telescope](https://github.com/nvim-telescope/telescope.nvim/pull/722) for the same.

**Actual Behavior**

![ss1](https://user-images.githubusercontent.com/26769888/114145562-64b07100-98cb-11eb-91f3-1b086cd811d5.gif)

**Neovim's built in Behavior**

![ss12](https://user-images.githubusercontent.com/26769888/114147252-60855300-98cd-11eb-99ee-3e4b00e4a0dc.gif)

### Details

<details><summary>Reproduce</summary>

Minimal LSP Saga config:

```lua
local saga = require 'lspsaga'

saga.init_lsp_saga {
  code_action_icon = '💡',
  hint_sign = '🌿',
  dianostic_header_icon = "👀 "
}
```

You'll need to install tsserver and ESLint to provide code actions which can be done using [LSP installer plugin](https://github.com/williamboman/nvim-lsp-installer/). Alternatively, try to emulate code-actions coming from two different LSPs on the same piece of code. 

1. [Clone this repository](https://github.com/lrvpxl/lspsaga-min-repro-170)
2. `cd` into it and run `npm install`.
3. [Go to this line](https://github.com/lrvpxl/lspsaga-min-repro-welp/blob/main/src/App.tsx#L10)

</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1221-g9b2d4ff62 \ Build type: RelWithDebInfo
- Operating system: Ubuntu 20.04.2 LTS on Windows 10 x86_64
- lspsaga commit: 27c7a4796869e155ecec48eb3f8e66694c1708e2

</details>

**Comment by glepnir** [comment]
We can get all actions from multiple servers into one window. what do you think?

**Comment by glepnir** [comment]
which client do you used? efm with tsserver?

**Comment by lrvpxl** [comment]
No, [EFM does not provides code action](https://github.com/mattn/efm-langserver/issues/102#issuecomment-803577076). As I've mentioned in reproduce section of the first comment in this issue, [an external plugin is used](https://github.com/williamboman/nvim-lsp-installer/) to install and setup ESLint. This internally uses VS Code's ESLint language server to give code actions.

**Comment by glepnir** [comment]
ah I found it is eslintls

**Comment by glepnir** [comment]
@lrvpxl  I can't get eslintls work... how do you config lspinstaller?  I had run `LspInstall eslintls`

**Comment by lrvpxl** [comment]
Have you initialised it?

```lua
local installed_servers = require'nvim-lsp-installer'.get_installed_servers()
for _, server in pairs(installed_servers) do
	opts = {}

	if server.name == "eslintls" then
		opts.settings = {
			codeAction = {
				disableRuleComment = {
					location = "separateLine"
				},
				showDocumentation = {
					enable = false
				}
			}
		}
	end

	server:setup(opts)
end
```

**Comment by glepnir** [comment]
![Untitled](https://user-images.githubusercontent.com/41671631/114271471-196d9e00-9a44-11eb-8910-9201daaba555.gif)
2

**Comment by lrvpxl** [comment]
Yes, this looks great! 

Just one question, when I first used Saga's code action popup I expected that I need to press a number to apply an action but then I found out that I manually need to navigate to that action and press enter. Were there any dicussions happened to not to opt for a numeric keypress?  Did it happened because there is no way to hide the cursor?
