### ISSUE TITLE
Canceling rename requires :q buffer

### ISSUE THREAD

**Issue by gshpychka** [glepnir/lspsaga.nvim#173]
### Description
If I trigger the `rename` action and then change my mind, I have to do `:q` to close the window.

**Expected Behavior**
Pressing `Esc` should close the rename window.

**Actual Behavior**
Pressing `Esc` does not close the rename window

**Neovim Built in Behavior**
Pressing `Esc` quits the rename

**Comment by glepnir** [comment]
config `rename_action_keys`
