### ISSUE TITLE
finder_action_keys open should be <CR> 

### ISSUE THREAD

**Issue by dagadbm** [glepnir/lspsaga.nvim#174]
The actions  use <CR> to open  so it is very odd that  by default the finder_action_keys open key is o and  not CR.
The default should be <CR> for consistency  with how most users will use this.

**Comment by dagadbm** [comment]
Additionally, I  have <CR> mapped to other things  in my vim as well so it  would be nice if  the <CR> from lspsaga could override it temporarily for this popup window.

**Comment by glepnir** [comment]
you can custom it. i think this is not problem right ..
