### ISSUE TITLE
cursor line around text highlight

### ISSUE THREAD

**Issue by tami5** [glepnir/lspsaga.nvim#175]
### Description

I'm not sure if this is caused by neovim or my recent update of lspsaga but now when I call `show_line_diagnostics` or to jump to diagnostics line the error msg get highlighted with cursor line or background color

**Expected Behavior**

no cursor line or background color for diagnostics messages inside the popup

**Actual Behavior**

diagnostic message highlighted or cursor line is enabled
 
**Neovim Built in Behavior**

Not sure how to that with lsp handlers 

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: 
- lspsaga commit: 

</details>

**Comment by glepnir** [comment]
hmm can you show a image .

**Comment by tami5** [comment]
![21-04-16_01:19 34](https://user-images.githubusercontent.com/65782666/114945348-d485a500-9e51-11eb-853b-1d5700fde41e.png)

**Comment by glepnir** [comment]
`:hi NormalFloat` now default link to normal maybe fixed

**Comment by tami5** [comment]
Hmm this issue is still ongoing, even with recent changes I still have this annoying cursorline. I can confirm that my NormalFloat has background color

**Comment by tami5** [comment]
Also @glepnir I no longer have borders, are they deprecated?

**Comment by tami5** [comment]
Okay

> Hmm this issue is still ongoing, even with recent changes I still have this annoying cursorline. I can confirm that my NormalFloat has background color

Okay even when I have changed the highlight of NormalFloat to not have background color I still have it

**Comment by tami5** [comment]
Finally I found what the issue was. It may worth noting for other users.

Basically, there are highlights for floating lsp I had to change those in order to fix this annoying issue.

```
    LspDiagnosticsFloatingError
    LspDiagnosticsFloatingWarning 
    LspDiagnosticsFloatingInformation
    LspDiagnosticsFloatingHint

```
