### ISSUE TITLE
I get error when I use hover

### ISSUE THREAD

**Issue by jsatk** [glepnir/lspsaga.nvim#176]
### Description
This is in my `init.lua`.
```lua
local function map(mode, lhs, rhs, opts)
  local options = { noremap = true, silent = true }
  if opts then
    options = vim.tbl_extend("force", options, opts)
  end
  vim.api.nvim_set_keymap(mode, lhs, rhs, options)
end
require("lspsaga").init_lsp_saga({
  server_filetype_map = { metals = { "sbt", "scala" } },
  code_action_prompt = { virtual_text = false },
})
map("n", "K", [[<cmd>lua require"lspsaga.hover".render_hover_doc()<CR>]])
```
**Expected Behavior**
When I press K in normal mode I'd expect to see a hover pop-up window.

**Actual Behavior**
I get this error message:
```
Error executing vim.schedule lua callback: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/window.lua:290: attempt to call field '_trim' (a nil value)
```

### Details

<details><summary>Environment</summary>

- nvim --version output:

NVIM v0.5.0-dev+9f5c8226b
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210323-89866-nmyed9/build/config -I/tmp/neovim-20210323-89866-nmyed9/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210323-89866-nmyed9/build/src/nvim/auto -I/tmp/neovim-20210323-89866-nmyed9/build/include
Compiled by jesse.atkinson@C02ZH2XRLVDR

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-9f5c822_2/share/nvim"

Run :checkhealth for more info

- Operating system: 

macOS 11.2.3

- lspsaga commit: https://github.com/glepnir/lspsaga.nvim/commit/b77a08be564ccba4bd8c68cca89aa87e5520b3c3

</details>

**Comment by mjlbach** [comment]
9f5c822 is 21 days old. Update to the latest nightly.

**Comment by jsatk** [comment]
> 9f5c822 is 21 days old. Update to the latest nightly.

Apparently I needed to update with `--fetch-HEAD` flag.

**Comment by ziulev** [comment]
@jsatk 
I have the same issue. What did you mean by `Apparently I needed to update with --fetch-HEAD flag.` ?

**Comment by jsatk** [comment]
> @jsatk
> I have the same issue. What did you mean by `Apparently I needed to update with --fetch-HEAD flag.` ?

`brew update neovim` will pull the latest. But this needs 0.5. The latest nightly.
