### ISSUE TITLE
"Attempt to compare number with nil" error on very latest nvim

### ISSUE THREAD

**Issue by chroth7** [glepnir/lspsaga.nvim#177]
### Description
When I use the very latest nvim 0.5.0 pull from master I get "Attempt to compare number with nil" on a lot of functions (defintions, diagnostics...)

See below for nvim versions.

**Expected Behavior**
Normal operation

**Actual Behavior**
See below.

**Neovim Built in Behavior**

### Details

If I build my nvim from this commit: https://github.com/neovim/neovim/commit/e652b2987a35b85a239740c6d591792bcf5de412
... it breaks

If I build from this one here:
https://github.com/neovim/neovim/commit/e652b2987a35b85a239740c6d591792bcf5de412
... it works like a charm

Looking at the commit messages in between, it seems that some line numbering is off
![image](https://user-images.githubusercontent.com/6230368/114681299-4c4ab700-9d0e-11eb-9f82-7285aa4eb654.png)

Sadly, I am not good enough at Lua to investigate deeper

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: see above, it varies
- Operating system: Mac 11.2.3
- lspsaga commit: 

</details>

**Comment by neelkarma** [comment]
Same with me on Windows.
Here's the error message I get:
```
Error executing vim.schedule lua callback: ...ls\neovim\Neovim\share\nvim\runtime\lua\vim\lsp\util.lua:1223: attempt to compare number with boolean
```

**Comment by kristijanhusak** [comment]
I think this commit broke it https://github.com/neovim/neovim/commit/2001ba2c6a1dacf54fa697cb4584c6d677aad0ac.

**Comment by akinsho** [comment]
I think this has now been fixed by the most recent upstream changes https://github.com/neovim/neovim/commit/cd3e74201a8fcbe5ba04000a57e05f102c04496c

**Comment by kristijanhusak** [comment]
Yeah seems like that fixes it.

**Comment by glepnir** [comment]
fixed by last commit of neovim

**Comment by chroth7** [comment]
wow, now that was fast and responsive! thanks a lot all, thanks for the great plugin @glepnir
