### ISSUE TITLE
`lsp_finder()` preview window goes off the top of the screen.

### ISSUE THREAD

**Issue by ckipp01** [glepnir/lspsaga.nvim#18]
When you are using the `lsp_finder()` close to the top of the buffer it goes right off the screen.

<img width="674" alt="Screenshot 2021-01-25 at 20 08 29" src="https://user-images.githubusercontent.com/13974112/105753690-606dec00-5f49-11eb-83c4-f6b0f956a661.png">

In this situation could the preview maybe go below or something?

**Comment by weilbith** [comment]
For me it is the same, just at the bottom of the screen...

**Comment by glepnir** [comment]
I had rewrite it. should better than before .. but i am not sure work well with any window size..

**Comment by weilbith** [comment]
Could you eventually try to phrase in words what the intended placement strategy is?

**Comment by ayushsherpa111** [comment]
![image](https://user-images.githubusercontent.com/35552818/125198585-2340b080-e282-11eb-830b-10f06e9c77a2.png)

how do i get the preview pane to display to the side just like in the demo? is there an option flag that i'm missing?
