### ISSUE TITLE
LSP Finder no longer shows the preview

### ISSUE THREAD

**Issue by folke** [glepnir/lspsaga.nvim#182]
### Description

LSP Finder no longer shows the preview

**Expected Behavior**

The preview to appear

**Actual Behavior**

![image](https://user-images.githubusercontent.com/292349/115207958-eca72f80-a0b0-11eb-857c-7a7ced19d57f.png)

**Neovim Built in Behavior**

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: 
- lspsaga commit: 

</details>

**Comment by xeho91** [comment]
I am encountering the same problem.

Neovim version:
```
NVIM v0.5.0-dev+1272-g4570d04b1
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/sbin/cc -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/xeho91/neovim/build/config -I/home/xeho91/neovim/src -I/home/xeho91/neovim/.deps/usr/include -I/usr/include -I/home/xeho91/neovim/build/src/nvim/auto -I/home/xeho91/neovim/build/include
Compiled by xeho91@ANAQUEM

Features: +acl +iconv +tui
See ":help feature-compile"
```

And the latest commit fetched with `packer` is 333178b

**Comment by glepnir** [comment]
hmm because the cursor in `0 defintion`

**Comment by JoseConseco** [comment]
I have similar issue - no preview unless cursor is on definition.
But if  I have definition it  is placed in wrong spot: 
![image](https://user-images.githubusercontent.com/13521338/115990064-9743b480-a5c1-11eb-974e-35e6fcd11587.png)

**Comment by glepnir** [comment]
Aha it's fixed on my local I will update some new feature later.

**Comment by cj** [comment]
@glepnir hope you're having a great weekend!  Any update on this?

**Comment by ampatzid** [comment]
I have the issue shown at JoseConseco's image, preview window is small and and shown below the results window. Would it be possible to be next to result window if the window size is enough?  Moreover, It would be awesome if both floating windows popup near the cursor. In my case it is always shown at hight 20 and width 45.

**Comment by wizard-28** [comment]
I am having the same issue
![i](https://0x0.st/-OeD.png)
