### ISSUE TITLE
Custom highlight group to override NormalFloat

### ISSUE THREAD

**Issue by cooper-anderson** [glepnir/lspsaga.nvim#183]
In https://github.com/glepnir/lspsaga.nvim/commit/2752af4f3ccf9728dfc08a0079aaadc87ed066c4 all popup windows use `NormalFloat` instead of `Normal`. I have `NormalFloat` set to have a slightly different background color to `Normal`, but like having lspsaga's windows to be the same as the main background. Instead of using `NormalFloat` directly could it be changed to something like `LspSagaNormalFloat` that by default links to `NormalFloat`?

**Comment by akinsho** [comment]
Or alternatively us an `ftplugin` file for lspsaga windows and set the highlights in there so they only apply to lspsaga buffers. Would be great to have this stop overwriting the rest of my floating windows 🙏🏿
