### ISSUE TITLE
lspsaga popups do not have borders

### ISSUE THREAD

**Issue by ssoriche** [glepnir/lspsaga.nvim#188]
### Description
At some point I've lost the borders around lspsaga pop up windows. It makes it impossible to differentiate what's in the main window and what the pop up is showing.

Sorry, I'm not sure how to debug this and can find no other mentions.

I have tried in wezterm (my default terminal), terminal.app, and kitty. I've also tried different fonts in each terminal including Nerd Font variants to ensure the characters exist. None produce lspsaga pop ups with borders.
telescope has proper borders, `lua vim.lsp.buf.hover()` shows its limited borders.

**Expected Behavior**

There should be a border around the popup window to differentiate content as per the screenshots.

**Actual Behavior**
Pop up window with no border.

**Neovim Built in Behavior**
These should be set to whatever lspconfig sets them to, the only settings I've done are for lspsaga, and they are listed below.

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
```
local saga = require 'lspsaga'
saga.init_lsp_saga {
    error_sign = '💩',
    warn_sign = '🔥',
    hint_sign = '💡',
    border_style = 1,
}
```
this is my lspsaga configuration. I know that it is being read because there are errors and warnings in the code and they have the appropriate symbols, which I haven't defined anywhere else.

2. post your program language min code snippet that can reproduce your issue
```
func main() {
	viper.SetConfigName("ipscromp")       // name of config file (without extension)
	viper.AddConfigPath("/etc/appname/")  // path to look for the config file in
	viper.AddConfigPath("$HOME/.appname") // call multiple times to add many search paths
	viper.AddConfigPath(".")              // optionally look for config in the working directory
	err := viper.ReadInConfig()           // Find and read the config file
	if err != nil {                       // Handle errors reading the config file
		panic(fmt.Errorf("Fatal error config file: %s \n", err))
	}
}
```
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.5.0-dev+nightly-95-g01493e799
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong
-fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210421-58006-3qiss6/build/config -I/tmp/neovim-20210421-58006-3qiss6/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210421-58006-3qiss6/build/src/nvim/auto -I/tmp/neovim-20210421-58006-3qiss6/build/include
Compiled by ssoriche@Megatron.coloredblocks.net

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-01493e7_2/share/nvim"

Run :checkhealth for more info
```
- Operating system: macOS 11.2.2
- lspsaga commit: 

```
commit 333178b4e941eb19d9c97c0b0b5640c76363b0ad (HEAD -> main, origin/main, origin/HEAD)
Author: tamago324 <tamago_pad@yahoo.co.jp>
Date:   Sun Apr 18 22:29:18 2021 +0900

    fix: not overwrite NormalFloat (#180)
```
</details>

This is telescope with a proper border:
<img width="791" alt="image" src="https://user-images.githubusercontent.com/19838/115565139-1dd95880-a287-11eb-8b18-13ab78d95b41.png">

This is the result of `Lspsaga preview_definition`:

<img width="559" alt="image" src="https://user-images.githubusercontent.com/19838/115565366-4eb98d80-a287-11eb-9ac2-3c7eba2bd897.png">

**Comment by glepnir** [comment]
the latest neovim version？

**Comment by ssoriche** [comment]
I think so, before asking for help I ran `brew reinstall neovim` to make sure it was up to date, and now that you just questioned it, I uninstalled and reinstalled with `brew install --head neovim` which installed the same version:

```
VIM v0.5.0-dev+nightly-95-g01493e799
Build type: Release
```

```
brew info neovim
neovim: stable 0.4.4 (bottled), HEAD
Ambitious Vim-fork focused on extensibility and agility
https://neovim.io/
/usr/local/Cellar/neovim/HEAD-01493e7_2 (1,460 files, 20.5MB) *
  Built from source on 2021-04-21 at 10:01:36
```

The SHA there matches the SHA of the latest commit on GitHub.

**Comment by BenGH28** [comment]
I also noticed that borders were missing in my config a few days ago.  I did a test with a minimal init.lua and add plugins gradually and found that treesitter was the culprit at least for me.

**Comment by davidkariuki** [comment]
You could maybe try setting the border type manually and see if that changes anything, e.g.
```lua
require("lspsaga").init_lsp_saga
{
  border_style = "round"
}
```

**Comment by vuki656** [comment]
> ```lua
>   border_style = "round"
> ```

No luck with that.

**Comment by ssoriche** [comment]
Interestingly this solved it for me. Uninstalling treesitter, didn't help, only setting `border_style = "round"`.

<img width="481" alt="image" src="https://user-images.githubusercontent.com/19838/115973758-762d8600-a525-11eb-91ca-12373d603fbc.png">

**Comment by BenGH28** [comment]
Worked for me too

**Comment by glepnir** [comment]
@vuki656  you need update your neovim version
