### ISSUE TITLE
ActionIcon highlights in the SignColumn

### ISSUE THREAD

**Issue by pedro757** [glepnir/lspsaga.nvim#189]
### Description
There is no way to change ActionIcon highlights, i can only uptade color of virtual text icon, but i cant do anything to the Icon on the signcolumn, so i disabled that :´(

![image](https://user-images.githubusercontent.com/30637426/116024564-765c7d00-a61c-11eb-99dc-a21d96ad3724.png)

**Comment by ranebrown** [comment]
I think the sign highlight group is `LspSagaLightBulbSign`. It is missing from the readme table and isn't in the plugin/ highlight definitions. It looks like there are some other defined highlights that aren't actually used as well.
