### ISSUE TITLE
bug: Float Terminal: text very hard to read

### ISSUE THREAD

**Issue by matu3ba** [glepnir/lspsaga.nvim#19]
Consider changing background color and text color. Would it be possible to use the terminal emulator colors, where neovim was started with?

**Comment by glepnir** [comment]
which color? floate terminal just config the shadow color. it does not change builtin terminal color

**Comment by matu3ba** [comment]
![Screenshot_20210126_183127](https://user-images.githubusercontent.com/13089667/105881639-0b8fab80-6005-11eb-98be-151bb0578f2f.png)

Terminal emulator colors (Alacritty):
background: '0xfafafa'
foreground: '0x383a42'

It appears the foreground color is used for the background. How do you read the colors?

**Comment by glepnir** [comment]
This is your colorschme issue. it should config terminal color
