### ISSUE TITLE
Error executing lua, attempt to call field _trim (a nil value)

### ISSUE THREAD

**Issue by jordisantamaria** [glepnir/lspsaga.nvim#192]
### Description

When trying to use some command of lsp saga, I'm getting this error.
![スクリーンショット 2021-04-30 11 01 13](https://user-images.githubusercontent.com/6263700/116640769-40b1ee00-a9a6-11eb-8caf-7e25c3976cf6.png)

For now, as workaround I'm using enhance-window branch instead of master, which at least only give this error in LspInfo, but in master everything gives same error.

This is happening from around 1 month, after I updated lspsaga.

<details><summary>Environment</summary>

- nvim --version output:

NVIM v0.5.0-dev+1178-gf0ace6d41
Build type: Release
LuaJIT 2.1.0-beta3

- Operating system: macOS 11.2.1 20D75 x86_64

</details>

**Comment by jordisantamaria** [comment]
It's fixed updating neovim version

**Comment by AYM1607** [comment]
What version are you using? Are you using brew? I just updated lspsaga and I'm getting these errors.

**Comment by jordisantamaria** [comment]
> What version are you using? Are you using brew? I just updated lspsaga and I'm getting these errors.

I'm using NVIM v0.5.0-dev+1428-g997a9c879

**Comment by JjersaR** [comment]
I currently have this problem and the version of neovim is 0.10 on fedora workstation 40.
