### ISSUE TITLE
feat: Project-wide editing: CocSearch-like behavior

### ISSUE THREAD

**Issue by matu3ba** [glepnir/lspsaga.nvim#20]
I would like to do project-wide editing with opening all usages of a variable for potential modification.
Coc offers split windows for project-wide editing on `:CocSearch`.

Is this in scope of this project?

**Comment by glepnir** [comment]
I'm not sure this is related to lsp, you can try `far.vim``

**Comment by matu3ba** [comment]
Thanks alot. I was expecting something like getting all usages to a variable under cursor, but CocSearch simply invokes `rg` with refactor windows.
