### ISSUE TITLE
vim E417: missing argument: guibg=

### ISSUE THREAD

**Issue by qazip** [glepnir/lspsaga.nvim#200]
Whenever I do `:Lspsaga lsp_finder` I get the error below. The annoying part is that, once I do that, my selected line becomes green. As in, the color of the text changes from whiteish to green for the current line. 

![vim_lspsaga](https://user-images.githubusercontent.com/16175716/118036608-4de2bb80-b35c-11eb-8ce5-65102ea7b3a3.png)

**Comment by lkhphuc** [comment]
Same problem

**Comment by zbirenbaum** [comment]
Same issue, which is interesting because guibg is explicitly set for floating windows in my config. I think that it must be related to the default lspsaga configuration.

**Comment by barrydevp** [comment]
same on macos 11.5.2 :(, I have to return back to vim.lsp.buf.references() instead :((

**Comment by rauleite** [comment]
> same on macos 11.5.2 :(, I have to return back to vim.lsp.buf.references() instead :((

 @barrydevp , what do you mean by "back to vim.lsp.buf.references()", please? I'm new in Neovim and Lspsaga, and I'm have a same problem.
