### ISSUE TITLE
E5108 wrong number of arguments

### ISSUE THREAD

**Issue by AckslD** [glepnir/lspsaga.nvim#201]
### Description
When doing `:Lspsaga preview_definition` I get the error:
```
E5108: Error executing lua vim/shared.lua:209: wrong number of arguments (given 2, expected at least 3)
```

**Expected Behavior**
No error

**Actual Behavior**
Error above

**Neovim Built in Behavior**
Not sure what I should answer here.

### Details

<details><summary>Reproduce</summary>

1. Do: `:Lspsaga preview_definition`
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1318-g61aefaf29
- Operating system: Arch linux 5.12.2-arch1-1
- lspsaga commit: cb0e35d

</details>

**Comment by jonasstr** [comment]
I have the exact same error when using `preview_definition`

**Comment by nashio** [comment]
Same here

**Comment by AckslD** [comment]
@nashio just fyi I don't think lspsaga is maintained anymore.

**Comment by jonasstr** [comment]
> @nashio just fyi I don't think lspsaga is maintained anymore.

True, btw there is a fork by tami5 that contains some fixes regarding the LSP signature change introduced in 0.5 (nightly) / 0.5.1

**Comment by nashio** [comment]
oh, will try that, thanks. Any other alternatives? or is it not recommended to use a UI utility anymore

**Comment by AckslD** [comment]
What functionality are you looking for? :) I currently just use `lspconfig` and `lsp_signature`

**Comment by nashio** [comment]
I actually just might just stop using it, I liked the interface it gave me for code actions, previews, etc.
Will try lsp_signature seems nice
