### ISSUE TITLE
How exactly do i configure it like this:

### ISSUE THREAD

**Issue by hrqmonteiro** [glepnir/lspsaga.nvim#202]
![img](https://user-images.githubusercontent.com/41671631/110590664-0e102400-81b3-11eb-9b9d-a894537104bc.gif)

Is not clear in the readme. How i configure this EXACTLY like yours? To the lightbulb to appear when you hold the mouse?

**Comment by leisiji** [comment]
> ![img](https://user-images.githubusercontent.com/41671631/110590664-0e102400-81b3-11eb-9b9d-a894537104bc.gif)
> 
> Is not clear in the readme. How i configure this EXACTLY like yours? To the lightbulb to appear when you hold the mouse?

The lightbulb means that there are code actions in this line, and you can type `:Lspsaga code_action` to achieve this.

**Comment by hrqmonteiro** [comment]
> > ![img](https://user-images.githubusercontent.com/41671631/110590664-0e102400-81b3-11eb-9b9d-a894537104bc.gif)
> > Is not clear in the readme. How i configure this EXACTLY like yours? To the lightbulb to appear when you hold the mouse?
> 
> The lightbulb means that there are code actions in this line, and you can type `:Lspsaga code_action` to achieve this.

Yes, this i understand. I have it mapped to my `Leader ca` keys, but it doesn't appear a lightbulb at all, and it doesn't appear when i just have my cursor position on it. How do i achieve that?

**Comment by hrqmonteiro** [comment]
https://user-images.githubusercontent.com/17055027/119126665-b0e1eb80-ba09-11eb-812c-04c7aa346973.mp4

**Comment by leisiji** [comment]
You should provide a neovim version and a minimal vimrc to reproduce the problem. I think it is a bug because the lightbulb can be setup by the default config

**Comment by hrqmonteiro** [comment]
Nvim version:

```
NVIM v0.5.0-dev+1339-g5d9c56012
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/hrq/neovim/build/config -I/home/hrq/neovim/src -I/home/hrq/neovim/.deps/usr/include -I/usr/include -I/home/hrq/neovim/build/src/nvim/auto -I/home/hrq/neovim/build/include
Compilado por hrq@motherbase

Features: +acl +iconv +tui
See ":help feature-compile"

    arquivo vimrc de sistema: "$VIM/sysinit.vim"
            padrão para $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

The config:

```
vim.cmd "nnoremap <silent><leader>ca <cmd>lua require('lspsaga.codeaction').code_action()<CR>"
vim.cmd "vnoremap <silent><leader>ca :<C-U>lua require('lspsaga.codeaction').range_code_action()<CR>"
```

**Comment by CallumHoward** [comment]
Maybe you also need to install https://github.com/kosayoda/nvim-lightbulb

**Comment by glepnir** [comment]
do not need that

--------------原始邮件--------------
发件人："Callum Howard ***@***.***&gt;;
发送时间：2021年6月1日(星期二) 晚上8:52
收件人："glepnir/lspsaga.nvim" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [glepnir/lspsaga.nvim] How exactly do i configure it like this: (#202)
-----------------------------------

 

 
Maybe you also need to install https://github.com/kosayoda/nvim-lightbulb

**Comment by CallumHoward** [comment]
> do not need that
> 
> 
> 
> --------------原始邮件--------------
> 
> 发件人："Callum Howard ***@***.***&gt;;
> 
> 发送时间：2021年6月1日(星期二) 晚上8:52
> 
> 收件人："glepnir/lspsaga.nvim" ***@***.***&gt;;
> 
> 抄送："Subscribed ***@***.***&gt;;
> 
> 主题：Re: [glepnir/lspsaga.nvim] How exactly do i configure it like this: (#202)
> 
> -----------------------------------
> 
> 
> 
>  
> 
> 
> 
>  
> 
> Maybe you also need to install https://github.com/kosayoda/nvim-lightbulb
> 
>  
> 
> —
> 
> You are receiving this because you are subscribed to this thread.
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.

Awesome! That means I can simplify my plugins. Going to look up the documentation and try and set this up. Thanks for an amazing plugin!
