### ISSUE TITLE
Rename box does not have a title.

### ISSUE THREAD

**Issue by ironfish** [glepnir/lspsaga.nvim#206]
### Description<img width="511" alt="Screen Shot 2021-05-26 at 8 28 51 PM" src="https://user-images.githubusercontent.com/1911792/119747964-d3d52b00-be61-11eb-939d-b286a0fbfe7b.png">

Rename box does not have a title.

**Expected Behavior**
Should have title `New Name`

**Actual Behavior**
Rename box does not have a title.

**Comment by dhruvmanila** [comment]
This is not a bug, it was removed around 2 months ago in this commit: https://github.com/glepnir/lspsaga.nvim/commit/495e0bbb1205e99e39b7b102acffd2dd2f0f3bcd#diff-f32ec025e8dba999980cb5edba6804977ad1bf763eb83840172ec6eb3755d34aL101-L144

**Comment by ironfish** [comment]
Okay, thank you. Will close the issue.
