### ISSUE TITLE
Code action is not working with tsserver 

### ISSUE THREAD

**Issue by ahmedelgabri** [glepnir/lspsaga.nvim#21]
when using `tsserver` running `lua require 'lspsaga.codeaction'.code_action()` will show the proper actions popup but selecting any action doesn't do anything. While the native LSP code action `lua vim.lsp.buf.code_action()` works fine.

**Comment by glepnir** [comment]
reproduce.. It's wired. If run this `vim.lsp.buf.execute_command(action)` after this can work. but do it in `do_code_action` function,It does not work ..
https://github.com/glepnir/lspsaga.nvim/blob/a31d355bfdc151b29f8f6361dfecf9a797a98f4f/lua/lspsaga/codeaction.lua#L24
