### ISSUE TITLE
More convenient mapping to close floating window when using lsp_finder()

### ISSUE THREAD

**Issue by benallan** [glepnir/lspsaga.nvim#213]
When using lsp_finder(), I'd like to be able to close the floating window by pressing `Esc` or `<C-c>`, however I think I can only use `<c-w> q`.

Does lsp saga have any way to set custom maps to close this window?
Or if not, is there any way to identify the saga floating window so I can use a standard vim map or autocommand?

Thanks.

**Comment by charles-l** [comment]
I figured out that you can enable this with some config changes:

```
saga.init_lsp_saga {
  finder_action_keys = {
    open = {'<CR>', 'o'}, vsplit = 's',split = 'i',quit = {'q', '<esc>', '<C-c>'},
    scroll_down = '<C-f>',scroll_up = '<C-b>'
    },
  code_action_keys = {
    quit = {'q', '<esc>', '<C-c>'}, exec = '<CR>'
    },
  rename_action_keys = {
    quit = {'<esc>', '<C-c>'}, exec = '<CR>'
    },
  }
```

However, I think these would make good defaults as well (since most users would probably expect <kbd>Esc</kbd> and <kbd>Ctrl</kbd><kbd>C</kbd> to work). Let me know if you agree @glepnir and I can put together a CR for this.

**Comment by benallan** [comment]
Awesome, thanks @charles-l !  I see the quit option can be a table, so we can set several mappings and (maybe) keep everyone happy. 

I agree that having the extra quit mappings as defaults might be more user friendly.
