### ISSUE TITLE
Way to jump to references found by lsp_finder()

### ISSUE THREAD

**Issue by benallan** [glepnir/lspsaga.nvim#214]
When using lsp_finder() and viewing a floating window of references, I was hoping I could jump to the reference I have selected under the cursor (so this file will open in the main window).

Is there any way to do this in lsp saga currently? If not, would you consider adding it?

Thanks.

**Comment by someoneinjd** [comment]
> When using lsp_finder() and viewing a floating window of references, I was hoping I could jump to the reference I have selected under the cursor (so this file will open in the main window).
> 
> Is there any way to do this in lsp saga currently? If not, would you consider adding it?
> 
> Thanks.

select the file and type 'o'

**Comment by benallan** [comment]
Awesome, thanks a lot!

**Comment by mkujbus** [comment]
Is there a way to remap this to another key?
