### ISSUE TITLE
How do I close the floaterm with keybinds?

### ISSUE THREAD

**Issue by mTvare6** [glepnir/lspsaga.nvim#218]
### Description
How do I close the terminal with keybinds?

**Expected Behavior**
I have set leader+t+c to close terminal and want it closed when pressing these
**Actual Behavior**
when running those the keystrokes just gets typed to terminal as text

### Details

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.5.0-dev+1428-g997a9c879
- Operating system: macOS 11.4
- lspsaga commit: 

</details>

**Comment by monomadic** [comment]
I also had this question, since it's quite custom it would be worth documenting options or suggestions in the README.

**Comment by glepnir** [comment]
which keymap bind you used?

**Comment by victor-iyi** [comment]
I'm having the same issue. How does one close the floaterm once it's opened?
