### ISSUE TITLE
Having to close floating terminal twice

### ISSUE THREAD

**Issue by AckslD** [glepnir/lspsaga.nvim#219]
### Description
When opening a floating terminal I need to close it twice, with eg `:q`. The first time the actual floating terminal is closed but the slightly darker background is still there. Doing `:q` a second time brings the brightness back to normal. Anyone else having the same issue?

**Expected Behavior**
See above.

**Actual Behavior**
See above.

**Neovim Built in Behavior**
Not applicable.

### Details

<details><summary>Reproduce</summary>
I don't have a minimal reproducable code example at this point but wanted to see if anyone else have the same issue.

</details>

<details><summary>Environment</summary>

- nvim --version output: v0.5.0-dev+1425-g7da86f55a
- Operating system: 5.12.11.arch1-1
- lspsaga commit: cb0e35d

</details>

**Comment by mTvare6** [comment]
I seem to have same issue, the terminal is not closable without a keybinds(which I am having hardtime to get work) or press outside the terminal with mouse and run :q, which leaves a black vignette thing, which I again have to close

**Comment by AckslD** [comment]
@mTvare6 Closing with `:q` works fine for me, it is just that I have to to it twice.

**Comment by AckslD** [comment]
Using for example the following keymap works:
```lua
vim.api.nvim_set_keymap(
    't',
    '<A-d>',
    [[<C-\><C-n>:lua require("lspsaga.floaterm").close_float_terminal()<CR>]],
    {noremap = true, silent = true},
)
```
