### ISSUE TITLE
Can not change header area border color 

### ISSUE THREAD

**Issue by Mofiqul** [glepnir/lspsaga.nvim#222]
Unable to change the bottom border color hover doc

![Screenshot from 2021-07-11 15-41-16-](https://user-images.githubusercontent.com/23612580/125191583-d7c9da80-e260-11eb-893b-36346d2127d7.png)
 

I tried by changing `LspSagaBorderTitle` group color but didnot work

**Comment by gajzl** [comment]
Try:
```vim
highlight LspSagaDocTruncateLine guifg=#000000 " Replace the hex code with what you need
```
If you're intrested in changing the header border of other windows, you could try these:
```vim
highlight LspSagaShTruncateLine guifg=#000000
highlight LspSagaDocTruncateLine guifg=#000000
highlight LspSagaCodeActionTruncateLine guifg=#000000
```
You can explore the [colour file](https://github.com/glepnir/lspsaga.nvim/blob/main/plugin/lspsaga.vim) of the plugin to find these. I found that the highlight groups determining these line colours has "...TruncateLine" in the name.

**Comment by Mofiqul** [comment]
Thanks, it worked now.
