### ISSUE TITLE
Support copy text in hover or preview window

### ISSUE THREAD

**Issue by topelinux** [glepnir/lspsaga.nvim#223]
**Is your feature request related to a problem? Please describe.**
There are some usefull code/ text snippet in hover/preview windows, i'd like copy these information from hover/windows, for  now it just exit if the mouse is clicked in hover/preview windows area.

**Comment by soahyle** [comment]
Do you still face this problem? I mean I can click on the preview window or use `Ctrl + W + W` and yank the text block in case I only want to use keyboard.

**Comment by topelinux** [comment]
Doesn't work, in terminal when i click around the preview defination window, the preview window just disappeared.

**Comment by soahyle** [comment]
What terminal are you using? Mine are kitty, but then why don't you use the keyboard, it's way easy.
