### ISSUE TITLE
Preview is not shown on the side of main window in Lsp Finder

### ISSUE THREAD

**Issue by ronisbr** [glepnir/lspsaga.nvim#225]
### Description

Using the latest version with Neovim 0.5, the preview window of Lsp Finder is not shown on the side of the main window:

<img width="915" alt="Captura de Tela 2021-07-21 às 11 07 31" src="https://user-images.githubusercontent.com/1068295/126502718-381f3d5c-ea62-42d2-8ba9-bd8058a3c870.png">

P.S.: I cropped this figure but I had a lot of space to the right.

**Expected Behavior**
It should be placed on the right of the main window as we have in the screenshot in README.md.

**Actual Behavior**
It is shown on the bottom with a lot of space.

**Comment by jim-at-jibba** [comment]
I have the same issue. I am hoping [this](https://github.com/glepnir/lspsaga.nvim/pull/207) will fix the issue

**Comment by glepnir** [comment]
I will come back soon

--------------原始邮件--------------
发件人："James G. Best ***@***.***&gt;;
发送时间：2021年7月22日(星期四) 晚上7:03
收件人："glepnir/lspsaga.nvim" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：Re: [glepnir/lspsaga.nvim] Preview is not shown on the side of main window in Lsp Finder (#225)
-----------------------------------

 

 
I have the same issue. I am hoping this will fix the issue

**Comment by jim-at-jibba** [comment]
@glepnir No worries buddy. I hope you are starting to feel better

**Comment by ronisbr** [comment]
> I will come back soon

I wish you a very fast recovery!

**Comment by rsheasby** [comment]
If anyone stumbles upon this in the interim, there's a temporary solution:
https://github.com/glepnir/lspsaga.nvim/pull/207#issuecomment-894708443

**Comment by vinnyA3** [comment]
Feel better @glepnir !

**Comment by EpsilonKu** [comment]
@glepnir Don't die.

**Comment by rsheasby** [comment]
@EpsilonKu That's kinda a crappy phrasing, since it makes light of a situation we have no awareness of. Regardless, I'm gonna assume good faith and hope that you were actually being sincere

**Comment by EpsilonKu** [comment]
@rsheasby Sorry mate
