### ISSUE TITLE
How to change square diagnostic icon in editor

### ISSUE THREAD

**Issue by LuisxSullivaN** [glepnir/lspsaga.nvim#226]
Hi, I'm wondering if this is the right place to ask this, but I'm trying to get the diagnostic icons in the editor look like these ones:
![image](https://user-images.githubusercontent.com/29529436/126682549-9e944dda-a63c-4c06-a4d8-52baf0beff2d.png)
(look at the diagnostic text among with the circle, instead of the square that comes by default)

In [this issue](https://github.com/folke/lsp-colors.nvim/issues/4) folke says that it's handled by lspsaga.

Thanks in advanced.

**Comment by ashincoder** [comment]
Hello it is handled by lspconfig.
Here is the code snippet
```lua
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, {
	virtual_text = {
		prefix = "●",
		spacing = 0,
	},
	signs = true,
	underline = true,

	-- set this to true if you want diagnostics to show in insert mode
	update_in_insert = false,
})

```

**Comment by ashincoder** [comment]
Change the prefix to whatever you want.
Hope it works. It does work for me.

**Comment by ashincoder** [comment]
![2021-07-24-160454_1366x768_scrot](https://user-images.githubusercontent.com/83629316/126865867-b0cc046f-6af9-4d9b-825d-db54ae732785.png)

**Comment by LuisxSullivaN** [comment]
Thanks! that's the setting I was looking for
