### ISSUE TITLE
ANNOYING RANDOM LIGHT BUL‌B ICONS!

### ISSUE THREAD

**Issue by JS-junky** [glepnir/lspsaga.nvim#228]
![Screenshot_20210726_161258](https://user-images.githubusercontent.com/68812862/126984326-c35f3fa4-fbcc-48b6-b68a-4ba16c3d0f04.png)

these grey and yellow light bulbs keep showing up randomly for no reason and they serve no other purpose but to annoy u
i think it's some sort of bug or something... anybody else getting this? or is it just me??

**Comment by Joakker** [comment]
Those bulbs indicate that you can perform a code action there. `:Lspsaga code_action` should open a popup with the available actions

**Comment by JS-junky** [comment]
thank you all :D
