### ISSUE TITLE
Raise an error ('attempt to index a nil value') when trigger `preview_definition`

### ISSUE THREAD

**Issue by Yarnus** [glepnir/lspsaga.nvim#230]
### Description

When I triggered a `preview_definition` action, it raise below error:

![image](https://user-images.githubusercontent.com/18589312/127838320-e85f1be6-f3c1-4f35-9521-7d29c9d0af32.png)

**Expected Behavior**

Show the popup window as my expected.

**Actual Behavior**

Raise below error:
`E5108: Error executing lua .../pack/packer/start/lspsaga.nvim/lua/lspsaga/provider.lua:449: attempt to index a nil value`

**Neovim Built in Behavior**

It works normally when I use 'vim.lsp.buf.definition()' and jump to the definition file.

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```bash
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
```
- Operating system:  `MacOS 10.14.6`
- lspsaga commit: `cb0e35d`

</details>

**Comment by rebuilt** [comment]
We don't use lspsaga anymore.  You'll need to run :PackerSync to recompile the packer_compiled file, install any missing plugins, and update the ones already installed
