### ISSUE TITLE
 Highlights and underscore in the references

### ISSUE THREAD

**Issue by guilhermeprokisch** [glepnir/lspsaga.nvim#238]
How to have these highlights and underscore in the references, like in documentation?

![image](https://user-images.githubusercontent.com/12011070/131259083-ef08f8f4-2fed-483d-a196-8aee55a975ba.png)

Thanks

**Comment by someoneinjd** [comment]
[vim-cursorword](https://github.com/itchyny/vim-cursorword)

**Comment by ray-x** [comment]
`autocmd CursorHold <buffer> lua vim.lsp.buf.document_highlight()`

**Comment by guilhermeprokisch** [comment]
Thanks!
