### ISSUE TITLE
Use project relative paths in finder window

### ISSUE THREAD

**Issue by weilbith** [glepnir/lspsaga.nvim#24]
Hey,
so great to see your plugin becoming better and better! :rocket: 

I recognized that in the window with all the references etc using the `lsp_finder` function, all paths are relative to the users home directory. At least for me this is the case. And for me this sometimes end up with really long paths. Which make the window huge and "bad" to read. What would you think about making them relative to the projects root? I'm not sure if it is possible to get the root as detected by the LSP server. But probably it would be fine to set them relative to NeoVims current directory as well. Not that powerful, but better then relative to `$HOME`. Wouldn't it? :thinking:

**Comment by glepnir** [comment]
Now I had used the lsp root dir or home dir . but some file path still too long.
https://github.com/glepnir/lspsaga.nvim/blob/b01607b22b02c80c004bc2ba8b94263b0a453a04/lua/lspsaga/provider.lua#L58-L63

**Comment by weilbith** [comment]
Hmm. I just did an update and are locally now on b01607b which includes your references changes. But I still get the home relative path. When I open `:LspInfo`, the root of the language server is correct. For all of them (I use `efm` as general purpose language server for linting and formatting next to the "regular" servers). Any idea how I could debug this?

**Comment by glepnir** [comment]
can you post the min code and which server? now I am work with remake auto preview window.
