### ISSUE TITLE
Compability with nvim-jdtls

### ISSUE THREAD

**Issue by callebstrom** [glepnir/lspsaga.nvim#243]
Hi,

I would like to be able to use this great plugin for java. Currently `code_action` via `lspsaga.nvim` works perfectly with all languages expect Java and yields the following error:
```
java: -32601: No delegateCommandHandler for java.apply.workspaceEdit
```

Running `:lua require'nvim-jdtls'.code_action()` works standalone oddly enough, so the language server and client seems to support code actions but there is seemingly a difference in how these commands are passed to the language server (i.e. a difference between `nvim-jdtls` and `lspsaga`).

As there unfortunately is no [`jdtls.ui`](https://github.com/mfussenegger/nvim-jdtls/wiki/UI-Extensions) extension for `lspsaga` I figured I should be able to just use `:lua require('lspsaga.codeaction').code_action()` out of the box.

Any clues as to why this would not as expected? I.e. installing jdtls via for example `nvim-lspinstall` I would expect `:lua require('lspsaga.codeaction').code_action()` to work out of the box but I feel like I am missing something here. 

Thank you!

**Comment by ITHDevelopment** [comment]
Try nvim trouble code action method. It works well with jdtls. Sadly this plugin doesn't.
