### ISSUE TITLE
Code actions does not work and cause an exception

### ISSUE THREAD

**Issue by FeistyKit** [glepnir/lspsaga.nvim#246]
### Description
Whenever I try to use "code actions" it does not work and causes an error

**Expected Behavior**
That it shows suggestions for actions to auto take with the code

**Actual Behavior**
getting an error

**Neovim Built in Behavior**
I don't think it has this feature

### Details

I'm using [kyoto.nvim](https://github.com/samrath2007/kyoto.nvim) as my base config, branch "without-coq" and [here](https://pastebin.com/kg5pBU8Q) is my init.lua. [Here](https://cdn.discordapp.com/attachments/849688419227533352/888760844836540416/lsp_error.png) is an example of the error.

- nvim --version output: NVIM v0.6.0-dev+254-g413e86869
- Operating system: ArcoLinux
- lspsaga commit: cb0e35d2e594ff7a9c408d2e382945d56336c040

**Comment by samrath2007** [comment]
Hey,
I'm the author of kyoto.nvim, and basing this off a similar issue you raised in the kyoto repo that is your `lua/kyotorc/init.lua`. So for anyone wanting to reproduce, here are the steps

```
git clone https://github.com/samrath2007/kyoto.nvim ~/.config/nvim --branch without-coq
cd ~/.config/nvim/lua
mkdir kyotorc
cd kyotorc
wget https://pastebin.com/raw/kg5pBU8Q init.lua
# or using curl
# curl https://pastebin.com/raw/kg5pBU8Q -o init.lua
nvim
```
The mapping for triggering code actions is `<leader>ca`.

**Comment by mks1508** [comment]
@samrath2007 Lspsaga is out of date ... neovim 0.6.0 have some breaking changes... and codeaction handler signature is one of them.
What you can do:
- Fork lspsaga repo... and in [codeaction.lua](https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/codeaction.lua) change any callback functions look like
```lua
function Action:[some_name]()
  return function(_, _, [param_name])
     ...
  end
end
```
To:
```lua
function Action:[some_name]()
  return function(_, [param_name], _) 
     ...
  end
end
```
It's a temporal fix to make codeaction work... but I'm not sure about other part

- Use neovim 0.5.0 and lspsaga still work although it's out of date

- Get rid of Lspsaga ... follow this tutorial [UI-customization](https://github.com/neovim/nvim-lspconfig/wiki/UI-customization) to get same experience like lspsaga with builtin handler

**Comment by samrath2007** [comment]
Thanks, might move to a similar plugin

**Comment by EpsilonKu** [comment]
> Thanks, might move to a similar plugin

There is [fork](https://github.com/tami5/lspsaga.nvim). Guess u can also open issue there.

**Comment by nikensss** [comment]
For me, [this](https://github.com/rinx/lspsaga.nvim) fork worked better. I use hover doc very often and the one from tami didn't have it fixed.
