### ISSUE TITLE
code_action throw a error.

### ISSUE THREAD

**Issue by singlexyz** [glepnir/lspsaga.nvim#252]
Occurs in all filetypes.
But the built-in lsp is no problem. 
`:lua vim.lsp.buf.code_action()` works.
 
<img width="1326" alt="图片" src="https://user-images.githubusercontent.com/4456413/136652945-972564af-a589-47e9-b40c-631265360b62.png">

Config:
<img width="616" alt="图片" src="https://user-images.githubusercontent.com/4456413/136653171-9c91a694-5535-44cd-89ba-63b95c044b3a.png">

**Comment by BodeSpezial** [comment]
I looked into it a bit and found that the error occurs when trying to access `action.title` where `action` is extracted from `response`.
The lines where this issue occurs are:
[`action.title` at the end of the line](https://github.com/glepnir/lspsaga.nvim/blob/cb0e35d2e594ff7a9c408d2e382945d56336c040/lua/lspsaga/codeaction.lua#L112)
[`action` is extracted with the `pairs()` function from `response`](https://github.com/glepnir/lspsaga.nvim/blob/cb0e35d2e594ff7a9c408d2e382945d56336c040/lua/lspsaga/codeaction.lua#L110)

The same issue seems to occur a bit lower in line 132 but I'd expect a change to affect both lines.

If I find the time I'll look deeper into it in the not so far future and try to fix it.

**Comment by eddyekofo94** [comment]
@BodeSpezial getting the same error.

**Comment by hrqmonteiro** [comment]
Same error

![codeaction](https://user-images.githubusercontent.com/17055027/137602414-13bf32cc-07df-419b-8e38-8e2ece661c05.png)

Will it get fixed?
