### ISSUE TITLE
Open folds in previews

### ISSUE THREAD

**Issue by weilbith** [glepnir/lspsaga.nvim#26]
Just installed it yesterday, but I'm already enjoying this plugin so much. :blush: 
One thing I realized which is a problem while working is that previews (especially the definition preview) is not open folds. I assume this is just opening the file into a regular buffer and scroll to the specific line. So this automatically applies my usual fold settings (which I use from Treesitter). While I still like my folds and think they are useful when opening a file, for  a preview they are more obstructive. Do you think it is possible to open them? Maybe set the `foldlevel` option for the preview window to a very high value or just "run" `zR` in the window. What ever fits better the code I would say.

---

Another idea: If I remember the LSP specification correctly, the `Location` object includes a range. This would allow to trim the preview to just the range of the definition. So there is nothing shown below. Trimming the buffer seems to cumbersome, but adopting the window height to the range height should be perfectly fine. 
Maybe you are doing this already and I just don't see this as I have the folds. Just came into my mind and I haven't checked the code.

**Comment by weilbith** [comment]
Btw: I'm totally fine to contribute to the plugin myself. I'm just opening issues first to discuss them with you. All the issues must be a lot of work.

**Comment by glepnir** [comment]
Maybe you are right, because I did not test the folding situation, Pr welcome.

Regarding Location, built-in lsp use it everywhere, but I don’t like to use location , so I use a lot of floating windows. I hope our eyes only need to focus on the center of the screen or a slightly lower position instead of lowering our heads. to look at location...

**Comment by glepnir** [comment]
I'm not sure  I understand what you mean. Because my english is not so good :)

**Comment by weilbith** [comment]
> Maybe you are right, because I did not test the folding situation, Pr welcome.

Alright. I'll probably go for the window option approach. Let's see how it goes.

**Comment by weilbith** [comment]
> I'm not sure I understand what you mean. Because my english is not so good :)

I need to express myself better. :grimacing: 

> Regarding Location, built-in lsp use it everywhere, but I don’t like to use location , so I use a lot of floating windows. I hope our eyes only need to focus on the center of the screen or a slightly lower position instead of lowering our heads. to look at location...

I think there is a little misunderstanding. I like the floating window. I mean thats what this plugin is about, right?
So I looked at the code myself. And it looks like you almost do what I intended to. But why do you add this "extension" of 10 additional lines [here](https://github.com/glepnir/lspsaga.nvim/blob/5a0f459e3257e6ee04454a3ef204d0e606a7425d/lua/lspsaga/provider.lua#L365). As I understand the LSP spec, the range of the returned location object should span from the first line of the definition to the last. So just using `range.start.line` to `range.end.line + 1` should be fine or?
