### ISSUE TITLE
Getting the error when trying to acces the code actions

### ISSUE THREAD

**Issue by imSafdarAwan** [glepnir/lspsaga.nvim#260]
whenever i try to do the code action it gives me this error 
![image](https://user-images.githubusercontent.com/87114084/139411682-a47ca2bd-e663-439e-aa6f-5e8037945658.png)

this is my lsp config https://github.com/imSafdarAwan/Dnvim/blob/master/nvim/.config/nvim/lua/lsp/lsp.lua

**Comment by fragov** [comment]
Are you using neovim 0.6? I have got the same error:

`
Error executing vim.schedule lua callback: ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:112: attempt to concatenate field 'title' (a nil value)
` 
after I have updated my neovim to 0.6 version and switched from init.vim and Plug to init.lua and Packer

**Comment by imSafdarAwan** [comment]
> Are you using neovim 0.6? I have got the same error:
> 
> `Error executing vim.schedule lua callback: ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:112: attempt to concatenate field 'title' (a nil value)` after I have updated my neovim to 0.6 version and switched from init.vim and Plug to init.lua and Packer

no i am using 0.5.1

**Comment by fragov** [comment]
I found hint you can switch to tami5/lspsaga.nvim, now I have this error not any more.

**Comment by BitInByte** [comment]
Any date on fixing this?

**Comment by dinhmai74** [comment]
I got the same error when update to nvim 0.6. It also breaks the diagnostic go next and prev

**Comment by FireSK7** [comment]
Still broken function now
