### ISSUE TITLE
How do I configure lspsaga

### ISSUE THREAD

**Issue by SingularisArt** [glepnir/lspsaga.nvim#264]
I just got the plugin, and right off the bat, I had a ton of issues. Can someone please help me?
Here are the issues that I'm running into:

1. A light bulb just kept following my cursor
2. Running `Lspsaga code_action` returned **attempt to index local 'action' (a number value)**
3. Running `Lspsaga lsp_finder` gives me such a small window with no definitions or anything
4. The `hover docs` don't work. It doesn't output an error and doesn't output any information.

Also, two last questions.

1. How do I configure `LspSaga`. I read over the `README.md`, and it was extremely confusing. I spent about 30 minutes just looking over it making sure I didn't miss anything, but I cannot seem to figure it out.
2. How do I change the icons for the:
   1. Errors
   2. Warnings
   3. Information
   4. Hints

**Comment by Tus1688** [comment]
Hi there! It should be working, you can try this:
```
local saga = require 'lspsaga'
saga.init_lsp_saga {
    -- your configuration 
    error_sign = 'fill it with your preferences',
    warn_sign = 'fill it with your preferences',
    hint_sign = 'fill it with your preferences',
    infor_sign = 'fill it with your preferences',
    code_action prompt = {
        enable = false --to turn off light bulb
    },
}
```

**Comment by SingularisArt** [comment]
Thank you @Tus1688. I will try this out when I have the chance!

**Comment by SingularisArt** [comment]
## Rename

The config you gave me works! But, when I run `:Lspsaga rename`, it gives me this error:

`pylsp: -32602: jedi.api.expections.RefactoringError: There is not name under the cursor`

## Code Action, Range Code Action

When I run `:Lspsaga code_action`, it gives me this error:

`attempt to concatenate filed title (a nil alue)`

## Implementation

When I run `:Lspsaga implement`, it gives me this error:

`table index is nil`

## Lsp Finder

When I run `:Lspsaga lsp_finder`, it gives me a weird output.
The boxes are seperated. The box with the files is up top, and the box with the definitions is on the bottom, and they are both very small.
