### ISSUE TITLE
Bunch of errors happening

### ISSUE THREAD

**Issue by SingularisArt** [glepnir/lspsaga.nvim#266]
# Code Action, Range Code Action

When I run ` :Lspsaga code_action` and ` :Lspsaga range_code_action`, it gives me this error:

attempt to concatenate filed title (a nil alue)

# Implementation

When I run `:Lspsaga implement`, it gives me this error:

table index is nil

# Lsp Finder

When I run `:Lspsaga lsp_finder`, it gives me a weird output.
The boxes are separated completely. The box with the files is up top, and the box with the definitions is on the bottom, and they are both very small.

Any help with be greatly appreciated.

**Comment by BitInByte** [comment]
It is broken on the new versions of Neovim... I don't know if there is any plan of fixing this to be honest but I heard that there is a new repo forked by this one that is being maintained and it is working as far as I'm concerned...

**Comment by SingularisArt** [comment]
What's the new repo's name?

**Comment by fans3210** [comment]
This is the most active fork for now: https://github.com/tami5/lspsaga.nvim

**Comment by SingularisArt** [comment]
Thanks. It works now. I'm going to go ahead and close this issue.
Thanks for your help 😊
