### ISSUE TITLE
It's clear that LspSaga needs a Fork / Maintainer

### ISSUE THREAD

**Issue by aprowe** [glepnir/lspsaga.nvim#267]
Looking at the author's github, the last time he made any contribution on github was April 2021, and he had a comment around that time mentioning he was in the hospital. I sincerely hope he is doing alright :(. 
if we want LspSaga to continue, it seems like a fair assumption that we will need to fork it and start maintaining it. 
There's a lot of issue threads appearing and I would love for this repo to continue, it is a great tool. 
Anyone know of an active fork? Has anyone attempted some fixes of the issues that have come up?

**Comment by DavidePatria** [comment]
I saw [this fork](https://github.com/tami5/lspsaga.nvim)  mentioned elsewhere and it seems to be mantained

**Comment by yuchanns** [comment]
The author is back now

**Comment by fans3210** [comment]
Glad to see Raphael, the author back after one whole year. Hope he's good
