### ISSUE TITLE
Code actions float window open even if empty and cannot close it

### ISSUE THREAD

**Issue by phelipetls** [glepnir/lspsaga.nvim#27]
I'm having this problem where the code actions float window opens even if there aren't code actions available. If I move the cursor, or move tabs etc. the window does not go away.

![code-actions-bug](https://user-images.githubusercontent.com/39670535/105843421-74036c00-5fb6-11eb-8ae3-de3bbb01fd65.gif)

**Comment by glepnir** [comment]
maybe a bug .the quick way is `<C-w><C-w>` move to the code action window and press q

**Comment by glepnir** [comment]
should be fixed. please test.

**Comment by lynndylanhurley** [comment]
@glepnir now when I try to open the codeactions popup I get an error:

```
E5108: Error executing lua vim/shared.lua:199: Expected table, got nil
```

**Comment by lynndylanhurley** [comment]
Correction to my previous comment - it appears to be working now. Not sure if I did anything, will report if it happens again.

**Comment by glepnir** [comment]
seems like start server need time ..so if you press the keymap but server is not start It will appear

**Comment by phelipetls** [comment]
I can confirm that it happened to me too with tsserver. But it solved the issue of not being able to close the floating window.

**Comment by glepnir** [comment]
I can add a patch to render float window when we confirm get code action result.

**Comment by glepnir** [comment]
Now should be works fine.
