### ISSUE TITLE
Automatically show virtual text when cursor hover

### ISSUE THREAD

**Issue by tristone13th** [glepnir/lspsaga.nvim#274]
**Describe the solution you'd like**
When the cursor hovers on a line with diagnostics, I think it should show the diagnostics information automatically with a delay rather than just show the virtual text after the line text as the text may be limited by the screen width.

**Comment by kalkin** [comment]
```lua
vim.cmd [[autocmd! CursorHold,CursorHoldI * lua require'lspsaga.diagnostic'.show_line_diagnostics()]]
```
