### ISSUE TITLE
Support custom formatting of diagnostic messages

### ISSUE THREAD

**Issue by jsatt** [glepnir/lspsaga.nvim#276]
The built-in neovim diagnostic tooling allows customizing the diagnostic messages (using vim.diagnostic.config()) that appear in the virtual text and floating window. These options include displaying the `source` (which tool generated the message), a `prefix` which can be added to the message and a `format` function which allows users to access the diagnostic object tables for complete control over the message. It appears that the Lspsaga implementation is hard coded to only show the message (https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/diagnostic.lua#L102).

It would be very useful if Lspsaga either (ideally) respected these builtin settings as configured OR provided some similar options within it's own setup to customize the messages.

**Comment by rocket-engineer** [comment]
Same here. Apparently, the virtual text is always enabled when using Lspsaga. I'd prefer to have no virtual text for diagnostics (cause I enabled virtual text for DAP).
