### ISSUE TITLE
disable hover line when no detail is provided

### ISSUE THREAD

**Issue by elianiva** [glepnir/lspsaga.nvim#28]
Hi there! It's a bit hard to explain, I'll just show the current one vs the one that I want.

![image](https://user-images.githubusercontent.com/51877647/105865747-ce87e100-6025-11eb-8ac0-9c5844a82ad7.png)
![image](https://user-images.githubusercontent.com/51877647/105865802-dba4d000-6025-11eb-931f-c15b18d9e838.png)
![image](https://user-images.githubusercontent.com/51877647/105866807-f6c40f80-6026-11eb-83a5-91cbb926734f.png)

So, some hover result doesn't have an extra detail like this one, I think it would be better if we don't show the extra line at the bottom (like the second image) but still show it on a longer result / if it has more than 1 line (last image).
The code for the second image was taken from your old config before releasing lspsaga btw. 

The highlights seems to be broken because I have a variable filled with `"\\"` and it tries to treat that as a literal `\` unescaped.

**Comment by glepnir** [comment]
We does not show hover window when `textDocument/hover` request get empty result form lsp right?

**Comment by elianiva** [comment]
yep, it doesn't. But if the result is just 1 line, it still has that extra line at the bottom which looks kinda weird. I'd prefer not having that extra line at the bottom if the result is short/a single line like this one.

**Comment by glepnir** [comment]
Okay.If doc has one line we can remove truncate line..

**Comment by elianiva** [comment]
Yeah, that seems to be the case. If there's no docs, I'd prefer it to not show the separator line at all. Is that possible?

**Comment by glepnir** [comment]
yep. It can be support later.
