### ISSUE TITLE
Support custom formatting of diagnostic messages

### ISSUE THREAD

**Issue by jsatt** [glepnir/lspsaga.nvim#292]
The built-in neovim diagnostic tooling allows customizing the diagnostic messages (using vim.diagnostic.config()) that appear in the virtual text and floating window. These options include displaying the `source` (which tool generated the message), a `prefix` which can be added to the message and a `format` function which allows users to access the diagnostic object tables for complete control over the message. It appears that the Lspsaga implementation is hard coded to only show the message.

It would be ideal if Lspsaga respected these builtin settings as configured. Short of supporting the builtin formatting, Lspsaga should at least provided some similar options within it's own setup to customize the messages.

**Comment by glepnir** [comment]
@jsatt  currently lspsaga just support jump diagnostic. and all diagnostics form `vim.lsp.diagnostic.get` function. so use `vim.diangositc.config` should be work .

**Comment by glepnir** [comment]
Okay got it. I will test. and I am wonder why your pics1 miss color. it should be red:)

**Comment by jsatt** [comment]
Yeah I was kind of wondering the same, but I was just taking one issue at a time. Could be related to something else in my config, but I feel like I've narrowed down the stuff that I would expect to affect saga.

**Comment by glepnir** [comment]
check `hi DiagnosticError`.

**Comment by glepnir** [comment]
@jsatt  now support config diagnostic source .

**Comment by jsatt** [comment]
So I see the it includes the source now, which is the main thing I was looking for, but it still doesn't seem to respect the vim.diagnostic.config. It's now showing the source at all time regardless of if the float.source is true or false.

Also, placing it in the header brings to mind the question of multiple diagnostics on the same line, but maybe this should just be a separate ticket. Since the current jump to next/prev only displays one diagnostic at a time, but using the jump to next/prev also only seems to be jumping to the next line with a diagnostic, not the next diagnostic (ie. skipping the other diagnostics on that line).

The coloring issue is definitely related to those highlights not being set as expected. I'll look into what's up my theme, but it's not anything in the plugin.

**Comment by jsatt** [comment]
Oh, I just saw in the commit that you added a new config option. I think that's probably fine for managing it that way, really as long as it's configurable. Using that to configure works as expected.

**Comment by glepnir** [comment]
now move the source into the content not in title.

**Comment by glepnir** [comment]
and other options, they are config the sign and virtual text. it's work in builtin. saga just deal with jump or show line/buffer diagnostics in future.
```
  signs = {
    active = signs,
  },
  update_in_insert = false,
  underline = true,
  severity_sort = true,
  virtual_text = {
    source = true,
  },
```
