### ISSUE TITLE
Open lsp_finder in tab

### ISSUE THREAD

**Issue by leoatchina** [glepnir/lspsaga.nvim#293]
**Is your feature request related to a problem? Please describe.**
Open lsp_finder results in tab, like using `tabe`

**Describe the solution you'd like**
Acctually I have folked another `lspsaga.nvim` from `tami5`,  and have added this feature
https://github.com/tami5/lspsaga.nvim/commit/978b2f5845fed65953833b3c3ffd268140b90e0a

**Comment by glepnir** [comment]
if you had implemented.pr welcome
