### ISSUE TITLE
Problems with floating window

### ISSUE THREAD

**Issue by abenz1267** [glepnir/lspsaga.nvim#3]
Hi,

![Screenshot_20210125_100007](https://user-images.githubusercontent.com/7055955/105684509-56ba9900-5ef5-11eb-81b7-61629db80823.png)

This happens for me. Also when pressing to to preview the floating window doesn't expand. At least on my end there seems to be an issue with the floating windows. Latest neovim nightly.

Regards

**Comment by glepnir** [comment]
can you post your saga config here? I will test it. because I can't reproduce this issue.

**Comment by abenz1267** [comment]
Hi,

literally empty config. So just

```
local saga = require 'lspsaga'
local opts = {}
saga.init_lsp_saga(opts)
```

Btw: when using "xxx" as error sign neovim throws me an error as well. "invalid sign text: xxx"

Regards

**Comment by abenz1267** [comment]
Also: when having the floating window open and doing :q it closes the floating window....while the hover one stays up.

![Screenshot_20210125_102545](https://user-images.githubusercontent.com/7055955/105686577-b5811200-5ef7-11eb-8d14-314e166004a5.png)

**Comment by abenz1267** [comment]
tried with latest commit. same problems.

**Comment by glepnir** [comment]
How about now?

**Comment by abenz1267** [comment]
Hey,

looks like this now: 
![Screenshot_20210125_150506](https://user-images.githubusercontent.com/7055955/105716266-e32d8180-5f1e-11eb-9dc0-b5f8d36bdf90.png)

The issue doing `:q` while the floating windows are up is still present.

Also from a UX standpoint i'd personally much rather prefer the preview to be optional.

Regards

**Comment by glepnir** [comment]
you can just press `q` in `lsp_finder` window it will auto close all the lspsaga float window. seems like there has some blank line in preview window.

**Comment by abenz1267** [comment]
I know how to close the window. The point is: if it's open and you wanna actually :q out of the file it's broken and you have to :q 2 times.

**Comment by glepnir** [comment]
Now support `:q` or `Ctrl-c` to quit all the lsp_finder float window.

**Comment by glepnir** [comment]
Now looks like this . if you still have problem please create a new issue about auto preview window position.
![image](https://user-images.githubusercontent.com/41671631/105849893-f96d3780-601b-11eb-8296-cabd71c15fb3.png)
