### ISSUE TITLE
[Feature] Current line diagnostic and signature help

### ISSUE THREAD

**Issue by kristijanhusak** [glepnir/lspsaga.nvim#30]
Hi,

what do you think about adding current line diagnostic and signature help? Currently we have these in neovim:

Diagnostic:
```
vim.lsp.diagnostic.show_line_diagnostics()
```

Signature:
```
vim.lsp.buf.signature_help()
```

And I'm using it like this:
```lua
  vim.cmd [[autocmd CursorHold * lua vim.lsp.diagnostic.show_line_diagnostics()]]
  vim.cmd [[autocmd CursorHoldI * silent! lua vim.lsp.buf.signature_help()]]
```

But it would be nice to have this nice styling to it.

Thanks!

**Comment by glepnir** [comment]
signature help support now
![signature_help](https://user-images.githubusercontent.com/41671631/105969051-c7fb7700-60c2-11eb-9c79-aef3e01d88b1.gif)

**Comment by kristijanhusak** [comment]
Signature works great, thanks. Only current line diagnostics are left.

**Comment by nghialm269** [comment]
@glepnir The signature help popup currently use the current buffer's filetype to highlight, which makes some random words get highlighted:
![image](https://user-images.githubusercontent.com/13317164/106230741-c5179800-6222-11eb-8d21-a7304af695bc.png)

Is it possible to use the current buffer's filetype to highlight the label, and markdown to highlight the documentation?

**Comment by glepnir** [comment]
There are some problems with the render doc in neovim upstream.When I implement other features, I will  try to make it better

**Comment by glepnir** [comment]
@kristijanhusak Is the display line diagnosis really useful? I haven't used it much. I want to use a floating window to display all the diagnostic information of the buffer and add some previews. Of course, you can jump from this window to the location of the diagnosis, which is more useful than the line diagnostics?

**Comment by kristijanhusak** [comment]
@glepnir yeah, it's useful for me. I disable virtual text diagnostic because it creates too much noise for me. I have a CursorHold event that shows current line diagnostic (see first comment), and i know where errors are by sign column. If i want to see all, i just open up quickfix window.

**Comment by glepnir** [comment]
support

**Comment by kristijanhusak** [comment]
@glepnir I gave current line diagnostic a try, it works, but it's a bit different when you jump, and when you preview. For example, this is what I get when I use current line diagnostic:

![current-line](https://i.imgur.com/sXTQXaw.png)

And this is when i jump to it with "next":

![jump-to-next](https://i.imgur.com/LinLLVl.png)

Built in one shows the same in both situation (similar to the current line version here):

![builtin](https://i.imgur.com/JQhbpPs.png)

**Comment by glepnir** [comment]
`show_line_diagnostic` from neovim upstream I just use my window instead of.  `next` or `jump`  is my implement. it will wrap the diagnostic message. Because some times some diagnostcis message too long.

I will fixed work with both. must be only show one in same time

**Comment by glepnir** [comment]
@kristijanhusak  now should be works fine.

**Comment by kristijanhusak** [comment]
@glepnir unfortunately it still happens:

![diagnostic-error](https://user-images.githubusercontent.com/1782860/106283475-44689400-6242-11eb-8877-f002ebea631d.gif)

I also get an error when I try second time, watch cmd line.

How to reproduce:

```lua
  "mininit.lua
  vim.o.updatetime = 300
  vim.cmd [[autocmd CursorHold * lua require'lspsaga.diagnostic'.show_line_diagnostics()]]
  utils.keymap('n', '[g', ':LspSagaDiagJumpPrev<CR>')
  utils.keymap('n', ']g', ':LspSagaDiagJumpNext<CR>')
```

1. Open file with error
2. Jump to error
3. Go back up
4. Try to jump again, watch error in cmd line.

**Comment by glepnir** [comment]
Got it .check it later. seems like there need check when they both happen.

**Comment by glepnir** [comment]
I want to know that we are expect is when we press `[g` want to see the diagnostic float not show line diagnostics right?

**Comment by glepnir** [comment]
Can you test now. should be fixed.

**Comment by kristijanhusak** [comment]
Works good now, thanks!
Will you make the current line diagnostic look same as next/prev, or it will be left as it is? Just curious.

**Comment by glepnir** [comment]
if the diagnostic message is too long, I think make it look same as `next/prev` is better. we need deal the long diagnostic message text. sometimes they are not very friendly.

**Comment by kristijanhusak** [comment]
Yeah I like the next/prev design more than the current line one.

**Comment by glepnir** [comment]
I had deal them with width 50. But I didn't test it the behavior with the long message text. so if you got problem create an new issue. Thanks

**Comment by kristijanhusak** [comment]
50 is ok. How hard is it to make it configurable if someone wants ?

**Comment by glepnir** [comment]
easy to config just add a key word. support it tomorrow

**Comment by kristijanhusak** [comment]
Tried it, works great. Thanks!
