### ISSUE TITLE
Smart scroll doesn't work

### ISSUE THREAD

**Issue by sandangel** [glepnir/lspsaga.nvim#301]
### Description

I described the issue here: https://github.com/tami5/lspsaga.nvim/issues/118
Could you take a look?

**Expected Behavior**

The smart scroll key map will scroll preview definition and Lspfinder

**Actual Behavior**

It doesn't do anything. Also throw error in LspFinder

**Neovim Built in Behavior**

There is no built-in behavior AFAIK

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 0.8.0-dev
- Operating system: linux
- lspsaga commit: main

</details>

**Comment by sandangel** [comment]
Hi @glepnir . I tested, it works, but still generate error if I scroll in the last item. COuld you check again?

```lua
E5108: Error executing lua ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/action.lua:44: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/action.lua:44: in function 'scroll_in_win'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:414: in function 'scroll_in_preview'
        [string ":lua"]:1: in main chunk
```

**Comment by glepnir** [comment]
fixed
