### ISSUE TITLE
Get error when doing code action

### ISSUE THREAD

**Issue by jim-at-jibba** [glepnir/lspsaga.nvim#314]
### Description

Get the following error when doing code action:

```
E5108: Error executing lua vim/shared.lua:0: attempt to index a boolean value
stack traceback:
        vim/shared.lua: in function 'tbl_get'
        ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:224: in function 'do_code_action'
        ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:260: in function 'do_code_action'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

**Expected Behavior**

Perform code action

**Actual Behavior**

I get the error above and the action is not complete

**Neovim Built in Behavior**

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@Mac-1650023513425.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"
```
- Operating system: MacOS Intel
- lspsaga commit: latest

</details>

**Comment by glepnir** [comment]
@jim-at-jibba  can you provide some code that can reproduce and the builtin code action do it well?

**Comment by glepnir** [comment]
no update closed
