### ISSUE TITLE
Markdown rendering of pyright hover_doc is still broken

### ISSUE THREAD

**Issue by WieeRd** [glepnir/lspsaga.nvim#321]
Hi @glepnir, good to see you working on lspsaga again!  

Closed issue #121 (visible `\` and `&nbsp;` in pyright hover_doc) is still not fixed.  
Back then this was considered as upstream issue.  
But even after builtin `vim.lsp.buf.hover()` got fixed, lspsaga still renders pyright docs incorrectly.

**Comment by glepnir** [comment]
yup. I know there has something wrong in markdown render.it's time to improve

**Comment by AGou-ops** [comment]
@glepnir  still has `\` https://github.com/glepnir/lspsaga.nvim/issues/391

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/57939102/185923407-1aa1c0f6-2d72-45cd-9463-b9070f215d94.png">
