### ISSUE TITLE
Issue is CursorLine background color is not present

### ISSUE THREAD

**Issue by samtgarson** [glepnir/lspsaga.nvim#325]
### Description
When I try to interact with elements of the finder (for example, open a definition or reference from a floating window), I get an error, the command fails and from the onwards vim's highlighting acts oddly.

**Expected Behavior**
Interacting with the finder works as documented

**Actual Behavior**
The following error occurs:
```
E5108: Error executing lua /Users/sam/.vim/plugged/lspsaga.nvim/lua/lspsaga/finder.lua:478: attempt to concatenate field 'curs
or_line_bg' (a nil value)
stack traceback:
        /Users/sam/.vim/plugged/lspsaga.nvim/lua/lspsaga/finder.lua:478: in function 'clear_tmp_data'
        /Users/sam/.vim/plugged/lspsaga.nvim/lua/lspsaga/finder.lua:448: in function 'open_link'
        [string ":lua"]:1: in main chunk
```

### Details
Digging into the code, it looks like [this line](https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/finder.lua#L358) is setting the property to null as the CursorLine background color is not present:
```
:lua print(vim.inspect(vim.api.nvim_get_hl_by_name('Cursorline',true)))
{
  foreground = 3011776
}
```
I'm not sure where this comes from, presumably my theme?

In any case, maybe [this line](https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/finder.lua#L488) which produces the error should check for the presence of that property? I'm not quite sure what this line is doing so I didn't want to put in a broken PR.

<details><summary>Environment</summary>

- nvim --version output: 
```NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.0/share/nvim"

Run :checkhealth for more info
```

- Operating system: macOS 12.3
- lspsaga commit: `0ba75b7`

</details>

**Comment by glepnir** [comment]
@samtgarson  did you update lspsaga?

**Comment by glepnir** [comment]
@samtgarson  which colorscheme do you used ?  can your try this colorscheme to test ?

https://github.com/glepnir/zephyr-nvim

looks like the preview window does not disappear. can your provide the react code that can reproduce it?
