### ISSUE TITLE
[Discuss] Async render lsp finder

### ISSUE THREAD

**Issue by glepnir** [glepnir/lspsaga.nvim#33]
For some language servers with very slow performance, such as pyls, lspfinder uses buf_request_sync, which awaits the response and renders the window. This is a blocking behavior. If the language server responds very slowly, it means waiting for it, which is very bad.

1. use `vim.loop.new_async`
2. use `buf_request` need rewrite render window.

**Comment by megalithic** [comment]
elixirls should be included in this list; for certain codebases, it can take, unfortunately, 2-5 seconds to retrieve the references, for instance. telescope's implementation also fails to retrieve them in time, it has/had a fixed timeout for something like 1-2s to retrieve the results. lsp-fuzzy handles them, but with no progress indicator that the results are infact being gathered and rendered.

**Comment by glepnir** [comment]
@megalithic  Reopen issue. now the lspfinder support timeout but Because there are some escaping here, the above code snippet should work.
