### ISSUE TITLE
`symbolwinbar.lua:42: attempt to index field 'range' (a nil value)`

### ISSUE THREAD

**Issue by codepuncher** [glepnir/lspsaga.nvim#349]
### Description

For some filetypes, the winbar does not work and throws error:
 
```
Error detected while processing CursorMoved Autocommands for "<buffer=1>":
Error executing lua callback: ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:42: attempt to index field 'range' (a nil value)
stack traceback:
        ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:42: in function 'binary_search'
        ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:70: in function 'find_in_node'
        ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:115: in function 'render_symbol_winbar'
        ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:212: in function <...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:208>
```

This issue seems to happen for code languages that do not have a hierarchy.

**Expected Behavior**

To either show winbar symbols or silently exit winbar.

**Actual Behavior**

Shows error and I have to keep pressing `<CR>` to hide error. But when I press any movement key, error appears again

**Neovim Built in Behavior**

Not sure what this means?

### Details

<details><summary>Reproduce</summary>

1. Open a shell a `.sh` or `.blade.php` file (I have only had issues with these)
2. Do anything
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
VIM v0.8.0-dev+1963-gee6b21e84
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by lee-work@Lees-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-ee6b21e/share/nvim"

Run :checkhealth for more info
```
- Operating system: macOS 12.4
- lspsaga commit: `08c087adbd5820122a7cd78a3949cdd55bade638`

</details>

**Comment by nullchilly** [comment]
Hmm
Can you edit `.local/share/nvim/site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua` and add `vim.pretty_print(node) on line 42?

**Comment by nullchilly** [comment]
Hmm I don't have this bug

I opened oh-my-zsh.sh with lsp server bashls

**Comment by codepuncher** [comment]
Hi @nullchilly,

I opened `symbolwinbar.lua` and added `vim.pretty_print(tbl)` but I cannot get the output of `:message` due to it being too long and the lspsaga error is making it difficult.

Is there a way to log output to file, perhaps?

**Comment by nullchilly** [comment]
Yes, you can use lua standard file open

**Comment by nullchilly** [comment]
https://www.tutorialspoint.com/lua/lua_file_io.htm

**Comment by nullchilly** [comment]
@codepuncher For the time being you can add to line 39

```lua
if tbl[mid].range == nil then
  return nil
end
```

Still, I don't understand which server is causing it, please post a screenshot of `:Lspinfo` so I can test

**Comment by nullchilly** [comment]
I installed all the language server in your configuration and all of it says `All servers of this buffer does not support textDocument/documentSymbol` so I guess we need to remove autocmd when it happens?
![image](https://user-images.githubusercontent.com/56817415/177827705-8ac4db35-e044-4210-80f0-ffbd68e394d6.png)
Anyway, I am going to sleep, good luck with your pr

**Comment by codepuncher** [comment]
Thanks @glepnir !
