### ISSUE TITLE
[Feature] Rename popup

### ISSUE THREAD

**Issue by kristijanhusak** [glepnir/lspsaga.nvim#35]
Hi,

what do you think about introducing rename popup similar to coc.nvim?

![coc-rename](https://user-images.githubusercontent.com/1782860/105971310-a8e0f300-608a-11eb-8b5f-297a29769e06.gif)

**Comment by glepnir** [comment]
Okay support it later. but find a way to make it beautiful than coc

**Comment by glepnir** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/41671631/105995632-3ac91a00-60e4-11eb-84b4-70b180196cc3.gif)

**Comment by kristijanhusak** [comment]
Looks good. Only thing that I noticed is that it has 2 rows instead of 1. Is that on purpose or?

**Comment by glepnir** [comment]
yep.. because 1 row looks too thin ..what do you think 1 is better?

**Comment by kristijanhusak** [comment]
I guess it can be configurable. 2 is a bit too big for me because I use some additional line spacing. Passing an configuration to `rename()` function would work I guess.

**Comment by glepnir** [comment]
`opts.rename_row`  ?

**Comment by kristijanhusak** [comment]
Yeah that is fine.

**Comment by glepnir** [comment]
done.

**Comment by kristijanhusak** [comment]
Thanks. I'll give it a test in couple of hours.

**Comment by kristijanhusak** [comment]
I gave it a try, it's working ok. 1 row is perfect. I just noticed one thing. After I do rename, it triggers an autocompletion in my main window. Is there a way to prevent this from happening? It's not a big deal, but if it's a simple fix, guess it can be fixed. Here's the gif:

![rename-insert](https://user-images.githubusercontent.com/1782860/106017044-57535b00-60c0-11eb-9ce4-1cf4fca64104.gif)

**Comment by glepnir** [comment]
reproduce with nvim-compe. works fine with completion-nvim.. I will check it.

**Comment by glepnir** [comment]
Should be fixed.

**Comment by glepnir** [comment]
with new ui

![rename](https://user-images.githubusercontent.com/41671631/106115648-f6915480-618b-11eb-9818-003cfb15c8ac.gif)

**Comment by kristijanhusak** [comment]
@glepnir works great, thanks!

**Comment by nghialm269** [comment]
@glepnir is it possible to prefill the rename input with [prepareRename](https://microsoft.github.io/language-server-protocol/specification#textDocument_prepareRename) placeholder or `<cword>` just like what `vim.lsp.buf.rename()` does?

**Comment by glepnir** [comment]
I’m not sure if this is useful or it’s noise to some people, But I will add an option to control this.

**Comment by kristijanhusak** [comment]
I'd also likr that option, thanks.

**Comment by glepnir** [comment]
Hmm got some problem. can't set text into `prompt buffer`...

**Comment by kristijanhusak** [comment]
@glepnir Maybe it's because of neovim issue. See https://github.com/RishabhRD/nvim-lsputils/issues/19#issuecomment-751783291

**Comment by glepnir** [comment]
I had talk to bfredl ..need fixed in upstream.
