### ISSUE TITLE
Symbols outline: auto close if is last window

### ISSUE THREAD

**Issue by codepuncher** [glepnir/lspsaga.nvim#366]
**Is your feature request related to a problem? Please describe.**
When editing a file in one window and with symbols outline in another window, pressing `ZZ` will close main window but leave symbols outline open.

**Describe the solution you'd like**
If symbols outline is the last window open, close it/exit neovim.

**Describe alternatives you've considered**
N/A

**Additional context**
I was editing a lua file, then I hit `ZZ` to quit neovim but symbols outline stayed open.
![Screenshot 2022-07-18 at 15 17 42](https://user-images.githubusercontent.com/8135396/179531772-3d931b06-28fb-4a49-a6a2-3cf64f7ad34c.png)

**Comment by glepnir** [comment]
`autocmd WinEnter * if &filetype == 'lspsagaoutline' && winnr('$') == 1 | bdel | endif`
