### ISSUE TITLE
Hi, how can I jump to floating window when showing current line diagnostic? `<c-w><c-w>` doesn't work.

### ISSUE THREAD

**Issue by sandangel** [glepnir/lspsaga.nvim#367]
Hi, how can I jump to floating window when showing current line diagnostic? `<c-w><c-w>` doesn't work.

_Originally posted by @sandangel in https://github.com/glepnir/lspsaga.nvim/discussions/365_

**Comment by glepnir** [comment]
now you can press the shortcut twice to jump in.

**Comment by sandangel** [comment]
hi @glepnir , I think it's throwing error. BTW, can we make it work with all floating windows that lspsaga create? (hover, definition preview, etc...)

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/22189661/180586870-f59964fc-b091-4842-a9ad-0b8eb7f91f1b.png">

**Comment by glepnir** [comment]
yeah in plan .press twice jump in

**Comment by glepnir** [comment]
fix it later.

**Comment by sandangel** [comment]
thanks a lot for working on this. 🙇🏼‍♂️. It's a really useful plugin

**Comment by sandangel** [comment]
Could we reopen this issue until it's fixed?
