### ISSUE TITLE
Outline doesn't respect win_position + previews don't popup on subsequent toggles

### ISSUE THREAD

**Issue by fennelcakes** [glepnir/lspsaga.nvim#369]
(n.b.: let me know if these should be separate issues)

**Expected Behavior**
1) On default config, or when specifically setting `win_position = 'right'`, the symbols outlines should appear on the right side.
2) When toggling the outline on for the second time or more, the symbols preview should appear, like it does on the first toggle.

**Actual Behavior**
`win_position` is always on the left side, regardless of config; but, the preview window pops up on the expected side.
Also, the outline's preview popup window only appears on the initial outline toggle, but not on subsequent outline calls.

![outline-issues](https://user-images.githubusercontent.com/23170004/180074908-1a0038bf-6965-4cdb-94e2-0256dbdeef7d.gif)

### Details
<details><summary>config</summary>

```lua
-- packer config
    use {
      'wbthomason/packer.nvim',
        }
    use {
      'williamboman/nvim-lsp-installer',
      'neovim/nvim-lspconfig',
      'glepnir/lspsaga.nvim',
    }
-- packer config ^^

local saga = require 'lspsaga'
saga.init_lsp_saga({
  show_outline = {
    win_position = 'right',
    auto_enter = true,
    auto_preview = true,
    virt_text = '┃',
    jump_key = 'o',
    -- auto refresh when change buffer
    auto_refresh = true,
  },

})

-- Outline toggle
vim.keymap.set("n", "<Leader>a", ':LSoutlineToggle<CR>', { silent = true, noremap = true })


```
</details>

<details><summary>Reproduce</summary>

1. :LSoutlineToggle
2. Navigate outline to see previews
3. Repeat

<details><summary>Environment</summary>

- nvim --version output: 0.7.2 (also on nightly, 8.0)
- Operating system: MacOS 12.4
- lspsaga commit: #362 

</details>

**Comment by glepnir** [comment]
@fennelcakes  did you config the `set nosplitright` ?

**Comment by glepnir** [comment]
I add a patch that can fix this win position issue.

about preview . when you close outline. then open it again there is no preview window?

**Comment by fennelcakes** [comment]
Correct, like so:

![preview-outline](https://user-images.githubusercontent.com/23170004/180089189-9b724e16-343d-4ac7-8b98-4d199409daa6.gif)

**Comment by glepnir** [comment]
fixed.

**Comment by fennelcakes** [comment]
> fixed.

Yes, works as intended! You're incredible, thanks so much for your work on this plugin. Don't burn yourself out! I need to learn lua properly so I can contribute.

**Comment by augustocdias** [comment]
I'm having an issue where the outline window open on the right side from the currently focused window but the float window is always relative as if it were in the right of the vim window. I'm using default config. I've just configured keymaps.

![tty](https://user-images.githubusercontent.com/1080789/183064104-80eb259e-fa59-499b-91c6-c23d5c6c770c.gif)

**Comment by glepnir** [comment]
@augustocdias  create a new issue for this . fix it later. go to dinner now
