### ISSUE TITLE
Is there a method to show whether LspServer and finder are ready?

### ISSUE THREAD

**Issue by YangEfei** [glepnir/lspsaga.nvim#370]
I met the similar matter as https://github.com/glepnir/lspsaga.nvim/issues/309#issue-1285182905.

My lsp server is Clangd  and my project is so large that needs some time to load.
And if I use finder before every information is ready, there're 2 possible situations:
1. There's nothing in the finder, no definition functions and no reference functions, just with some icons and text.
![image](https://user-images.githubusercontent.com/54932475/180358228-8a350329-94b8-4b0b-b4f5-56c827073367.png)
3. Throw a error with `Error executing Lua callback: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:126: attempt to index a nil value`

But if I wait long enough, it runs fine.
So is there any method that I can know finder or lsp server has ready to work? This uncertainty is distressing to me.

Thanks a lot!

**Comment by YangEfei** [comment]
I have tried to use this plugin https://github.com/arkav/lualine-lsp-progress to check whether indexing is complete.
However, the situations which mentioned in the issue still occur...

**Comment by glepnir** [comment]
if you use the lspsaga symbolwinbar. when you see the symbol in winbat that mean the server is ready
