### ISSUE TITLE
`symbol_in_winbar` messages with `null-ls`

### ISSUE THREAD

**Issue by johnallen3d** [glepnir/lspsaga.nvim#372]
### Description
When I enable `symbol_in_winbar` I receive frequent messages when loading new buffers

**Expected Behavior**
No message

**Actual Behavior**
Frequent messages

**Neovim Built in Behavior**
N/A

### Details

<details><summary>Reproduce</summary>
1. Create minimal config file at: `~/.config/nvim/minimal.lua`

```lua
-- borrowed from: https://www.reddit.com/r/neovim/comments/tyxp8s/comment/i3w00kb/
-- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand("~/.config/nvim"))
vim.opt.packpath:remove(vim.fn.expand("~/.local/share/nvim/site"))

-- append test directory
local test_dir = "~/tmp/nvim-config"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
	vim.cmd(
		"!git clone https://github.com/wbthomason/packer.nvim " .. install_path
	)
	vim.cmd("packadd packer.nvim")
	install_plugins = true
end

local packer = require("packer")

packer.init({
	package_root = test_dir .. "/pack",
	compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

packer.startup(function(use)
	-- Packer can manage itself
	use({ "wbthomason/packer.nvim" })
	use({ "neovim/nvim-lspconfig" })
	use({ "nvim-lua/plenary.nvim" })

	use({
		"glepnir/lspsaga.nvim",
		branch = "main",
		config = function()
			local saga = require("lspsaga")

			saga.init_lsp_saga({
				symbol_in_winbar = {
					enable = true,
				},
			})
		end,
	})

	use({
		"jose-elias-alvarez/null-ls.nvim",
		config = function()
			require("null-ls").setup({
				sources = {
					require("null-ls").builtins.formatting.stylua,
				},
			})
		end,
	})

	if install_plugins then
		packer.sync()
	end
end)
```
2. Launch with only minimal config
```shell
nvim --clean -u minimal.lua minimal.lua
```
3. Packer will install itself and dependencies (ignore error at end if occurs)
4. Quit and re-launch with only minimal config
```shell
nvim --clean -u minimal.lua minimal.lua
```
<img width="734" alt="CleanShot 2022-07-22 at 14 11 48@2x" src="https://user-images.githubusercontent.com/184915/180499067-ae15ea1c-6cbf-41c4-9e99-0e12c9b54a08.png">

</details>

<details><summary>Environment</summary>

- nvim --version output: `NVIM v0.8.0-dev-nightly-2966-g946c8fd28`
- Operating system: macOS 11.6.7
- lspsaga commit: `7559a32`

</details>

**Comment by johnallen3d** [comment]
I've managed to write out the `null-ls` client configuration via:

```lua
    local file = io.open("/tmp/saga" .. conf.name .. ".log", "w")
    file:write(vim.inspect(conf))
```

... and it looks like `documentSymbolProvider` is not supported.

```
  server_capabilities = {
    codeActionProvider = {
      resolveProvider = false
    },
    completionProvider = {
      allCommitCharacters = {},
      completionItem = {
        labelDetailsSupport = true
      },
      resolveProvider = false,
      triggerCharacters = { ".", ":", "-" }
    },
    documentFormattingProvider = true,
    documentRangeFormattingProvider = true,
    executeCommandProvider = true,
    hoverProvider = true,
    textDocumentSync = {
      change = 1,
      openClose = true,
      save = {
        includeText = true
      }
    }
  },
```

 I guess the question is, is it worth calling `vim.notify` in this scenario?

**Comment by vsedov** [comment]
A quick note, i have a similar issue with DiganosticLS. 
```
dlsconfig.setup({
    ["python"] = {
        linter = require("diagnosticls-configs.linters.flake8"),
        formatter = {
            require("diagnosticls-configs.formatters.yapf"),
            require("diagnosticls-configs.formatters.isort"),
        },
    }
})
```
Id love to use lsoutline + the symbols outline with heirline, but giving that weird textdocument not found is a tad bit annoying >.<

**Comment by glepnir** [comment]
question is the there also has notify message with latest commit? I had remove notify print.

**Comment by d12bb** [comment]
> question is there also has notify message with latest commit? I had remove notify print.

Just `:PackerSync`d, still there

**Comment by glepnir** [comment]
just remove notify but I wonder this buffer has one server or more ? and all servers not support documentsymbol right?

**Comment by d12bb** [comment]
> I wonder this buffer has one server or more ? and all servers not support documentsymbol right?

For me, it is (was, thank you!) Lua and Swift, which are the only ones I'm using null-ls for and which both have a second server (sumneko/sourcekit) attached for anything but formatting.

**Comment by glepnir** [comment]
if the buffer has `lua-language-server` and `null-ls` servers. the symbol winbar should be work.

**Comment by glepnir** [comment]
I want to know the actual behavior when buffer has a language server with a null-ls or other server that doesn't support documentSymbol. does the symbol winbar works or not.

**Comment by d12bb** [comment]
yes, works fine for me with both Lua (sumneko+null-ls) and Swift (sourcekit+null-ls).

**Comment by d12bb** [comment]
Yes, works fine for me for both Lua (sumneko+null-ls) and Swift(sourcekit+null-ls)

**Comment by glepnir** [comment]
Okay. that's expect. thanks.

**Comment by johnallen3d** [comment]
Just pulled the latest and am no longer seeing the messages. Thanks @glepnir!
