### ISSUE TITLE
Weird border with Lspsaga diagnostic_jump_next() and Lspsaga diagnostic_jump_prev()

### ISSUE THREAD

**Issue by katinbox** [glepnir/lspsaga.nvim#374]
### Description

Border have underscore

**Expected Behavior**

**Actual Behavior**

**Neovim Built in Behavior**

Neovim 0.8
### Details
![2022-07-23_15-00](https://user-images.githubusercontent.com/43630437/180596510-6c09e67a-b2fd-4baf-aee6-57be27d82084.png)

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.8.0-dev+562-g606af7887
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az250-131

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

- Operating system: manjaro
- lspsaga commit: [c5b5d0b](https://github.com/glepnir/lspsaga.nvim/commit/c5b5d0b127e896f3d7a709c641a8d326e4f8f57c)

</details>

**Comment by glepnir** [comment]
kitty ? and I think this not  a bug of lspsaga.

**Comment by katinbox** [comment]
yeah, i'm using kitty, it not a bug, other float diagnotice working good!, only 2 command have weird border :(

**Comment by katinbox** [comment]
I try with alacritty
![2022-07-23_15-53](https://user-images.githubusercontent.com/43630437/180598127-9c326d21-bb2c-4794-9cb6-93e025e5df58.png)
:

**Comment by glepnir** [comment]
for me it's

![image](https://user-images.githubusercontent.com/41671631/180599841-3cc12b9c-858c-4e0a-ab96-c58ba68309b9.png)

**Comment by glepnir** [comment]
And in kitty . so I can't reproduce. 

![image](https://user-images.githubusercontent.com/41671631/180599887-1a3c917c-a820-45ab-a6bb-73cc9e6e2116.png)

**Comment by katinbox** [comment]
Hm, i will try re-config neovim to check why ? thank you!

**Comment by katinbox** [comment]
I finally found the cause, my theme grubox-material makes this weird rendering behavior :)

**Comment by glepnir** [comment]
aha congratulation

**Comment by fans3210** [comment]
Thanks for the info. I'm having similar issue and I was using everforest theme which has the same author as your gruvbox-material
