### ISSUE TITLE
(Bug) Error Finder

### ISSUE THREAD

**Issue by maxmx03** [glepnir/lspsaga.nvim#377]
### Description
Finder is not working, i get an error

**Neovim Built in Behavior**
Neovim nightly

Error:
![Captura de tela de 2022-07-25 19-09-58](https://user-images.githubusercontent.com/50273941/180882697-d01bfb59-c5f4-40ef-a841-c2a6b843350d.png)

Location:
![Captura de tela de 2022-07-25 19-09-31](https://user-images.githubusercontent.com/50273941/180882773-29ede1a3-2113-43bd-a8f0-2ca4b3a98728.png)

Possible a solution:
![Captura de tela de 2022-07-25 19-09-09](https://user-images.githubusercontent.com/50273941/180882748-184d538d-95cc-473e-a59d-01f5cc343942.png)

![Captura de tela de 2022-07-25 19-14-40](https://user-images.githubusercontent.com/50273941/180883066-22b52108-1a2a-4f74-b5ad-9db624f326f9.png)

**Comment by glepnir** [comment]
can you provide a min code that can reproduce?

**Comment by maxmx03** [comment]
my lspsaga config?

```
local saga = require 'lspsaga'

saga.init_lsp_saga()
```

**Comment by glepnir** [comment]
no…language code

**Comment by maxmx03** [comment]
```
Error executing Lua callback: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:
158: bad argument #1 to 'ipairs' (table expected, got string)
stack traceback:
        [C]: in function 'ipairs'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:158: in function 'crea
te_finder_contents'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:111: in function 'lsp_
finder_request'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:590: in function <...t
e/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:585>
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:36: in function 'load_
command'
        ...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:68: in function <...m/
site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:67>
```

**Comment by glepnir** [comment]
hmm which code that you run the `finder` .I can test with it.

**Comment by maxmx03** [comment]
```lua
if fn.empty(fn.glob(install_path)) > 0 then
  packer_bootstrap = fn.system {
    'git',
    'clone',
    '--depth',
    '1',
    'https://github.com/wbthomason/packer.nvim',
    install_path,
  }
end
```

**Comment by glepnir** [comment]
![issue](https://user-images.githubusercontent.com/41671631/180886437-a6359845-7343-40bc-a73c-67a48253bd5b.gif)

**Comment by maxmx03** [comment]
![2022-07-25 19-50-43](https://user-images.githubusercontent.com/50273941/180888239-8ee3bfa3-d4b1-4bfc-b774-15ac186fb42e.gif)

how i run the command


```lua
local opts = { noremap = true, silent = true }

vim.keymap.set('n', '<space>sf', ':Lspsaga lsp_finder<cr>', opts)
```

**Comment by glepnir** [comment]
![issue](https://user-images.githubusercontent.com/41671631/180889270-cdce9707-cd6f-4540-9138-f0ea4ebd8b6f.gif)

**Comment by glepnir** [comment]
I can't reproduce . btw i am not use latest version lua-language-server.

**Comment by maxmx03** [comment]
tsserver works fine, i guess only lua not.

**Comment by glepnir** [comment]
the latset lua language Server？

**Comment by maxmx03** [comment]
yes

**Comment by changyiyao** [comment]
I have the same issue when using dartls.
I use the clean app project created by flutter cli, which shows the following:
<img width="1212" alt="截屏2022-07-26 13 54 43" src="https://user-images.githubusercontent.com/766842/180933564-69e1b38f-929a-48d0-a1e2-1f6b80e0ab86.png">

**Comment by glepnir** [comment]
@maxmx03  I update to  `lua-language-server 3.5.0` . works fine.

**Comment by glepnir** [comment]
@changyiyao  create a new issue with reproduce step.
