### ISSUE TITLE
LspSagaFinder error lspsaga_finder nil value?

### ISSUE THREAD

**Issue by lbiaggi** [glepnir/lspsaga.nvim#38]
Hello there, finder method is not working as expected, I'm testing with default values

![sagafinder_error](https://user-images.githubusercontent.com/5401584/106135958-59143180-6147-11eb-8fbd-3abae563039d.gif)

**Comment by glepnir** [comment]
Aha. my mistake. I will fixed it later. now I am refactor finder window.

**Comment by glepnir** [comment]
Now works.
