### ISSUE TITLE
improve rename feature

### ISSUE THREAD

**Issue by niuiic** [glepnir/lspsaga.nvim#381]
1. rename with specified lsp
`rename` cannot work in vue/react/… files. Because mutiple lsps are running, and some of them will cause trouble (for example, cssls).
Can you add an argument or something like the original function. `vim.lsp.buf.rename("newName", {name = "volar"})`

2. a little problem with the name match
For example, `prefix-name` is a class name in html. If I rename it in css, `prefix` will be selected but `. -name` not. So there is a little problem about matching name with `-` or some other separator characters. It is recommended to add a command in visual mode,

Thank you for your awesome work.

**Comment by glepnir** [comment]
I can't reproduce in react project.
![issue](https://user-images.githubusercontent.com/41671631/181121727-90e78f5e-f0d4-4132-b5c1-b9faabbc2558.gif)

**Comment by niuiic** [comment]
cssmodule_ls don't have the ability to rename variables. Try cssls.

**Comment by glepnir** [comment]
vue really blows my mind, three elements in one file type. html css js/ts . I will test it later though

**Comment by glepnir** [comment]
do you use `volar/vue-language-server`?

**Comment by niuiic** [comment]
lsps
![image](https://user-images.githubusercontent.com/63799565/181864011-968bf6cb-1b8d-4d63-aa59-f5d022cf51ac.png)

disable rename feature of cssls

```lua
	on_attach = function(client, _)
		if vim.bo.filetype == "vue" then
			client.server_capabilities.renameProvider = false -- disable rename feature
		end
	end,
```

before
![image](https://user-images.githubusercontent.com/63799565/181864041-4294b8f4-7c89-4237-9899-57533d143638.png)
after
![image](https://user-images.githubusercontent.com/63799565/181864066-df5fc945-8659-42d6-80b1-b58511ad59e6.png)
![image](https://user-images.githubusercontent.com/63799565/181864093-0f02a95f-1c37-40ca-8f7f-c919d58fddd1.png)

enable rename feature of cssls
after
![image](https://user-images.githubusercontent.com/63799565/181864126-ed711cb6-4d7c-41e0-9f03-a8854e268eea.png)

You need to use the `setup` syntax sugar and rename variables in the `template` tag.

**Comment by sandangel** [comment]
regarding improving `rename`. is it possible to use `<esc>` to switch to normal mode, and in normal mode when you hit `<esc>` again it quit the rename window?

**Comment by niuiic** [comment]
You can use `<C-c>` to switch to normal mode.

**Comment by sandangel** [comment]
@niuiic that is not something I usually do when I want to switch to normal mode. I use `<esc>` all the times. But thanks for the tips though

**Comment by glepnir** [comment]
@niuiic  how do you install volar. I use npm install -g failed

**Comment by niuiic** [comment]
`npm i -g @volar/vue-language-service` failed?

You can try `mason.nvim` or `nvim-lsp-installer`.

**Comment by glepnir** [comment]
I don't use them .

**Comment by glepnir** [comment]
@niuiic  you config cssls work on vue right?

**Comment by glepnir** [comment]
@sandangel  can do this . but I prefer to provide a function that return rename win id and bufnr .then you can write a function and bind it to esc in a buffer map

**Comment by niuiic** [comment]
> @niuiic you config cssls work on vue right?

I need cssls to provide snippets in vue files. I have disabled the rename feature of cssls and there is no problem with renaming.  But use a specified lsp should be a more versatile choice.

**Comment by niuiic** [comment]
The problem about name matching.

![image](https://user-images.githubusercontent.com/63799565/181872354-d68165b9-bd85-46ef-a2ff-f568863da440.png)

`--xxx` is not selected.

Call original funtion in virtual mode.
![image](https://user-images.githubusercontent.com/63799565/181872426-38e75a1d-cfea-4137-b61b-7cbda908c475.png)

**Comment by glepnir** [comment]
because it's not a word so not select.

**Comment by glepnir** [comment]
@niuiic  works for me ..
![issue](https://user-images.githubusercontent.com/41671631/181877457-9a235407-04bd-4206-be45-b23b51762619.gif)

**Comment by niuiic** [comment]
emm..... I have no idea. Maybe different version of neovim? (mine is `NVIM v0.8.0-dev-739-ge59bc078d-dirty`, this also occurs on previous 0.8 version). I will check my configuration again. If it is my problem, please ignore this issue.

**Comment by glepnir** [comment]
my version is `NVIM v0.8.0-dev-739-ge59bc078d` and if you can reproduce with a min config reopen
