### ISSUE TITLE
Outline only works well for left side when using with_left

### ISSUE THREAD

**Issue by gutyina70** [glepnir/lspsaga.nvim#384]
## Description
For example, when using NvimTree on the **right side**, you still need to set **`show_outline.win_position = 'left'`** and `show_outline.left_with = 'NvimTree'` in order to open the **Outline window next to NvimTree**. This configuration feels weird to me, and it also causes a bug:

![lspsaga-bug](https://user-images.githubusercontent.com/29818440/181762258-c94fc643-7f9d-46a6-ae4c-290e68bc7226.png)

On a side note, the comment for `left_with` in the readme could be improved as well:
[-- set the special filetype in there which in left like nvimtree neotree defx](https://github.com/glepnir/lspsaga.nvim/blob/main/README.md?plain=1#L143)

## The current implementation of opening the outline window is (in pseudocode):
```
if (win_position is right) then open outline to the right
if (win_position is not right and couldn't find window with filetype win_at) then open outline to the left
if (win_position is not right and found window with filetype win_at) then open outline next to the found window
```
And displaying the outline preview window depends on `win_position`.

## Ideal solution
Implementing this would be a bad idea at this point, since most people's config would break.

Merge `win_position` and `left_with` to `win_at`. So `win_at` could have values like `left`, `right`, `NvimTree`, etc.

Creating the outline window would be simpler:
```
if (found window with filetype win_at) then open outline next to the found window
else if (win_at is right) open outline to the right
else open outline to the left
```

But opening the outline preview window depends on `win_pos` which is gone, so we'd need to get whether the opened outline window is on the left or right and use that.

## Realistic solution

Leave the configuration as it is.

Change the outline window opening implementation so it prioritizes `left_with` over `win_position`:
```
if (found window with filetype left_with) then open outline next to the found window
else if (win_position is right) open outline to the right
else open outline to the left
```

And again when we try to open the outline preview window, we need to get where is the outline window, since a valid `left_with` could've put the window on the right or the left as expected.

I'd be happy to submit a PR for this issue, but I may need some help checking if the outline window is on the left or on the right.

**Comment by glepnir** [comment]
hmm works for me set the nvimtree to right and outline in left . left_with is empty

![image](https://user-images.githubusercontent.com/41671631/181773807-9e7ddf90-5cfd-451b-bff0-1e6dc12c8fb9.png)

**Comment by glepnir** [comment]
oh.  okay.   we can change `left_with` to `win_with` .
