### ISSUE TITLE
Scroling docs not working in lsp finder preview and preview definition

### ISSUE THREAD

**Issue by Akianonymus** [glepnir/lspsaga.nvim#385]
Scrolling works in hover doc

### Details

Reproduce

1. `:Lspsaga lsp_finder`
2. `<c-f>`
3. It doesn't scroll

##### Environment

nvim --version output: 

```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

**Comment by glepnir** [comment]
please read doc you need map c-f to lspsaga scroll function

**Comment by Akianonymus** [comment]
I have these two functions 

```lua
-- scroll down
vim.keymap.set("n", "<C-f>", function()
    require("lspsaga.action").smart_scroll_with_saga(1)
end)
  -- scroll up
vim.keymap.set("n", "<C-b>", function()
    require("lspsaga.action").smart_scroll_with_saga(-1)
end)
```

**Comment by glepnir** [comment]
verbose map <C-f>/ <C-b>

**Comment by Akianonymus** [comment]
Aah, i didn't notice the `max_preview_lines` option, increasing it solved it. Thank you

**Comment by glepnir** [comment]
most welcome
