### ISSUE TITLE
is it possible to use `<esc>` to quit rename window only in normal mode?

### ISSUE THREAD

**Issue by sandangel** [glepnir/lspsaga.nvim#386]
Hi, I would like create new issue here to track this feature request.

Regarding improving `rename`. is it possible to use `<esc>` to switch to normal mode in rename window, and in normal mode when you hit `<esc>` again it quit the rename window? 

I want to use `<esc>` to quit the rename window, but currently it is in visual mode when I enter the window, and sometimes I just want to switch to normal mode to edit a part of the text only, but it will quit the entire window if I hit `<esc>`

> can do this . but I prefer to provide a function that return rename win id and bufnr .then you can write a function and bind it to esc in a buffer map

_Originally posted by @sandangel in https://github.com/glepnir/lspsaga.nvim/issues/381#issuecomment-1200059184_

**Comment by sandangel** [comment]
Another way for doing it is allowing setting the initial mode when enter the rename window.

**Comment by glepnir** [comment]
> it is allowing setting the initial mode

I don't think this is make sense.  current behavior most like other ide in visual mode select the current name.  provide an public function it's easy
