### ISSUE TITLE
Change popup background color

### ISSUE THREAD

**Issue by serhez** [glepnir/lspsaga.nvim#387]
**Is your feature request related to a problem? Please describe.**
Not a problem, simply that it would be nice to be able to change the background color of the popup windows.

**Describe the solution you'd like**
A new highlight group used by LSPSaga for defining the background color of the popup windows which could be overriden by the user, just as [these](https://github.com/glepnir/lspsaga.nvim/blob/main/plugin/lspsaga.lua).

**Describe alternatives you've considered**
N/A.

**Additional context**
N/A.

**Comment by glepnir** [comment]
just `hi LspsagaGroupName guibg=yourcolor code`

**Comment by serhez** [comment]
@glepnir I'm sorry, I don't see what you mean? I don't see LSPSaga currently picking up any highlight group to set the background of the popups (including the one you mention), am I wrong? Hence, I don't see a way of configuring what I described unless the plugin starts doing this; if there is a way, PLMK!

**Comment by serhez** [comment]
I think you could take a similar approach to this to implement it, [a one-liner](https://github.com/tversteeg/registers.nvim/blob/dfcf0962ce88b52e00dd96dfaabc9997a18f4efe/lua/registers.lua#L169).

**Comment by glepnir** [comment]
It's `LspFloatWinNormal`

**Comment by serhez** [comment]
That works, thank you 😃
