### ISSUE TITLE
Initial mode for rename

### ISSUE THREAD

**Issue by ofirgall** [glepnir/lspsaga.nvim#390]
Configure the initial mode for rename, right now its `SELECT` I personally prefer `NORMAL`, can we add a config option for that?

**Comment by glepnir** [comment]
yup can support .but why you don't like select mode  @sandangel  same #386

**Comment by ofirgall** [comment]
Most of the time I edit the name rather then create a new name, normal mode binds are just better for that.

E.g: insert a prefix to the variable

**Comment by ofirgall** [comment]
Thanks for the quick reply! @glepnir

**Comment by sandangel** [comment]
same for me, I found that when I use select mode I have to rewrite the entire name. thanks. I think this would close my issue too.
