### ISSUE TITLE
`hover_doc` escape character `\`.

### ISSUE THREAD

**Issue by AGou-ops** [glepnir/lspsaga.nvim#391]
### Description

![image](https://user-images.githubusercontent.com/57939102/182028642-646e6e22-17bd-4911-88b9-e09b92f662bd.png)

**Expected Behavior**

no `\`.

<details><summary>Environment</summary>

- nvim --version output:
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
编译者 brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/opt/homebrew/Cellar/neovim/0.7.2/share/nvim"

Run :checkhealth for more info
```
- Operating system: MacOS 12.5
- lspsaga commit: [014aeb8](https://github.com/glepnir/lspsaga.nvim/commit/014aeb8be75d927960914d442bf81ada4e24295b)

</details>

**Comment by glepnir** [comment]
duplicate #321
