### ISSUE TITLE
LSP finder spawns multiple servers

### ISSUE THREAD

**Issue by rawhat** [glepnir/lspsaga.nvim#392]
### Description
Running `:Lspsaga lsp_finder<cr>` seems to start servers in dependencies.  I have attached a GIF to demonstrate this behavior.

**Expected Behavior**
It should not start other language servers.

**Actual Behavior**
It seems to start the server in each dependency directory?  I first noticed this when I saw like 6 `rust-analyzer` instances for each crate in the references list.

**Neovim Built in Behavior**
Running `:lua vim.lsp.buf.references()` displays them in the quickfix window, but `:LspInfo` still only shows the one server running.

### Details

<details><summary>Reproduce</summary>
See below.
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
alex@c14f7b0bfd46:~/test-project$ nvim --version
NVIM v0.8.0-dev-750-g68ec497d5
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/alex/neovim/build/cmake.config -I/home/alex/neovim/src -I/home/alex/neovim/.deps/usr/include -I/usr/include -I/home/alex/neovim/build/src/nvim/auto -I/home/alex/neovim/build/include
Compiled by alex@c14f7b0bfd46

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
- Operating system:  WSL/Docker+Ubuntu
- lspsaga commit: `main` branch

</details>

![wezterm-gui_01P73j811P](https://user-images.githubusercontent.com/2095509/182034271-4b3951a8-ff56-4110-a4d3-372626e209b7.gif)

Let me know if you need any more info.  Thank you!

**Comment by glepnir** [comment]
@rawhat  lsp_finder doesn't start lsp server . just send request to server. so I think you need test with a min config

**Comment by rawhat** [comment]
I was able to reproduce this behavior with the following `init.lua`.  Does this consititute a minimal configuration?  The README notes, at least for plug, to install `lspconfig`.  And this is the recommended method for registering LSP servers with that plugin.

Do you mind clarifying if there is something smaller I should be testing with?

```lua
vim.cmd([[packadd packer.nvim]])

return require("packer").startup(function(use)
    use("wbthomason/packer.nvim")

    use({
        "neovim/nvim-lspconfig",
        config = function()
            require('lspconfig').tsserver.setup({})
        end,
    })

    use({
        "glepnir/lspsaga.nvim",
        branch = "main",
        config = function()
            local saga = require("lspsaga")

            saga.init_lsp_saga()
        end,
    })
end)
```

**Comment by glepnir** [comment]
like I said . lspsaga doesn't use `vim.lsp.start` .so it not start a new server. Please check your lspconfig config

```lua
vim.opt.runtimepath:append('~/Workspace/lspsaga.nvim/')
vim.opt.runtimepath:append('~/Workspace/nvim-lspconfig//')
vim.opt.number = true

local lspconfig = require('lspconfig')
lspconfig.tsserver.setup{}
```
![issue](https://user-images.githubusercontent.com/41671631/182048735-428d1a6b-cee8-4bc6-b167-f50b7531f0d6.gif)

**Comment by rawhat** [comment]
Got it, thanks for the info.  It seems like even the built-in LSP behaves effectively the same way (it locates the `cargo` deps in the local registry folder.  When loading that up, it finds the root directory as that of the crate (similar for things within `node_modules`)).  So I guess I will need to figure out how to work around that starting up another server.

Apologies for the misdirected issue.

**Comment by glepnir** [comment]
if builtin lspconfig issue you can also report to me i will fix it in neovim as neovim member
