### ISSUE TITLE
Diagnostics incompatibility while tracking `.` mark with marks.nvim

### ISSUE THREAD

**Issue by fennelcakes** [glepnir/lspsaga.nvim#394]
**Description**: tracking the `.` mark (last change in current buffer mark) with @chentoast 's `marks.nvim`  makes both the jump diagnostic UI and the show-line-diagnostics UI display empty messages.

This is a very particular issue that I don't expect you to devote time to, but I thought it might be useful for you to know in case something else comes up! And also in case someone else comes looking for this issue.

As of the recent UI update, https://github.com/glepnir/lspsaga.nvim/commit/c7f83ca81afc8cf59a4fc974bf63683e632725b2, with the nice arrows for jump diagnostics, the following [marks.nvim](https://github.com/chentoast/marks.nvim) setting makes lspsaga's jump diagnostics and line diagnostics slightly break.

Here are videos with examples of the behavior. You can see that in this first video, my `marks.nvim` config contains the following:
```lua
  builtin_marks = { ".", "<", ">", "^" },
```
With this config, tracking `.` makes lspsaga behave strangely.

https://user-images.githubusercontent.com/23170004/182054443-9500fa84-59b1-4565-909b-dd8e20fd506c.mov

In this second video, I remove `.` from the table, and lspsaga behaves as expected.

https://user-images.githubusercontent.com/23170004/182054440-62e957c1-a265-4d50-a1ad-eb0949155531.mov

Here is the relevant setting from the `marks.nvim` docs:
```
                                                               *marks-builtin*
  builtin_marks: table
    (default {})

    Which builtin marks to track and show. If set, these marks will also show
    up in the signcolumn and will update on |CursorMoved|

    Supported values:
      "'"
      "^"
      "."
      "<"
      ">"
```

**How To Resolve**
Don't track the `.`  mark in the `builtin_marks` key in `marks.nvim`. Remove it from the table.
Rolling back `marks.nvim` to its first commit does not resolve the issue, so it's baked in from the beginning.

@glepnir , feel free to close this issue as you see fit.

EDIT: 
```
:version
NVIM v0.8.0-dev+491-gf3ce06cfa
```

**Comment by glepnir** [comment]
Looks like there are some issues. But this is not a problem with lspsaga I think. I don't use mark.nvim, so I can't investigate what's going on with it that causes lspasga to behave strangely. terribly sorry if anyone can fix it pr welcome
