### ISSUE TITLE
Lsp finder file title (Find: xxx) not automatically closing on close/file open

### ISSUE THREAD

**Issue by jonasnilsberg** [glepnir/lspsaga.nvim#397]
Hi! 
Really love the plugin, but I have a small issue with the lsp_finder.
When i try to either close it with 'q' or open a file the small title window with "Find: xxx" never closes. See pictures below.

1. Use `Lspsaga  lsp_finder` on "authorizedFetch"

![image](https://user-images.githubusercontent.com/11648233/182242876-8c8e376a-2cf2-4a2d-862d-986c32a9c586.png)

2. Lsp finder window opens and i select the definition with for example 's'
 
![image](https://user-images.githubusercontent.com/11648233/182242945-713f7c1a-fc5d-4d31-8324-fdf36fd24259.png)

3. The file opens i a split, but the small title window with 'Find: authorizedFetch' does not close automatically. Leaving me to having to close it manually.

![image](https://user-images.githubusercontent.com/11648233/182243285-58ff06f3-f211-441f-9d52-f0f12c2bab0a.png)

Hope anyone can help me with this.

Neovim version: 0.7.0

**Comment by glepnir** [comment]
I can't reproduce your problem. Please test with a min config
![issue](https://user-images.githubusercontent.com/41671631/182251244-7228a83a-48d1-4baa-8866-8a5b6801dfc5.gif)

**Comment by jonasnilsberg** [comment]
Works like a charm now! Awesome job :-)
