### ISSUE TITLE
lsp_finder error when file is not saved

### ISSUE THREAD

**Issue by edward-s** [glepnir/lspsaga.nvim#400]
Just started using the awesome `Lspsaga lsp_finder`

It's working great so far, one issue that is bothering me.
If I were to edit the file without saving, and execute lsp_finder, I'm getting the following error

```
E5108: Error executing lua: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:608: Vim(edit):E37: No write since last change (add ! to override)
stack traceback:
        [C]: in function 'nvim_command'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:608: in function 'open_link'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:377: in function <...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:376>
```

Is this a bug? or it's by design that we have to save the file first before executing lsp_finder?

**Comment by glepnir** [comment]
@edward-s  which open type `edit`?

**Comment by edward-s** [comment]
this is the issue im facing, lsp_finder errors if i do not save after editing the buffer, "asdf" in the example

![lspfinder](https://user-images.githubusercontent.com/237278/182380534-306cadff-8662-414f-9d42-a3183a3e22ed.gif)

**Comment by edward-s** [comment]
works now, i uninstalled and re-installed neovim 0.8 nightly.
the title now disappears correctly, and no more error in lsp_finder in unsaved buffer
