### ISSUE TITLE
remove underline in show_line_diagnostics

### ISSUE THREAD

**Issue by edward-s** [glepnir/lspsaga.nvim#401]
hi, how do you remove the text underlines in show_line_diagnostics window? is it possible?

<img width="851" alt="Screenshot 2022-08-02 at 10 53 46 PM" src="https://user-images.githubusercontent.com/237278/182405244-37d2b227-fa8a-4615-8f1a-8e2b89798b9f.png">

**Comment by edward-s** [comment]
just found out the underline is from `gruvbox-material` colorscheme
anyone knows how to fix?

**Comment by glepnir** [comment]
rewrite the lsp highlight group in your config
