### ISSUE TITLE
Error when use finder

### ISSUE THREAD

**Issue by dinhmai74** [glepnir/lspsaga.nvim#404]
### Description
Happens when I update lspsaga, change back commit to 1 August is fine.
**Expected Behavior**

Work like normal
**Actual Behavior**

Got error when use it.
<img width="827" alt="image" src="https://user-images.githubusercontent.com/40544043/182596907-acd796a7-4c46-4050-a3a5-ddb5ff8fa721.png">
**Neovim Built in Behavior**

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/40544043/182597242-19058a12-d335-4072-b08e-dae085a2a133.png">

<details><summary>Environment</summary>

- nvim --version output:  VIM v0.8.0-dev+597-g5c3bbb67e
- Operating system: macOS 12.4 (21F79)
- lspsaga commit: db9b4adcc14ed42ba8c912bf91e57a1af89cd866
</details>

**Comment by glepnir** [comment]
@dinhmai74  I can't reproduce

**Comment by glepnir** [comment]
check #408
