### ISSUE TITLE
error while using lsp finder

### ISSUE THREAD

**Issue by bryant-the-coder** [glepnir/lspsaga.nvim#405]
![image](https://user-images.githubusercontent.com/92417638/182622742-7e1987c6-cdfb-47bd-b2e0-98b9ca13b161.png)

**Comment by glepnir** [comment]
I can not reproduce …

**Comment by glepnir** [comment]
please try latest and packercompile if you used packer. if not please provide a min config that can reproduce this problem

**Comment by bryant-the-coder** [comment]
its still proceeding with min config

**Comment by glepnir** [comment]
![images](https://user-images.githubusercontent.com/41671631/182721844-e64f9b88-9863-415c-b713-111d6c371693.gif)

**Comment by glepnir** [comment]
check #408
