### ISSUE TITLE
Changes to finder break mappings directly to the lsp_finder function

### ISSUE THREAD

**Issue by jsatt** [glepnir/lspsaga.nvim#409]
I've had the following mapping as outlined in the README:

```lua
vim.keymap.set('n', 'gh', require('lspsaga.finder').lsp_finder, {noremap = true, silent = true})
```

but after the recent updates to the finder code, this resulted in the following error.

```
E5108: Error executing lua: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:30: attempt to index local 'self' (a nil value)
stack traceback:
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:30: in function <...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:25>
```

After a bit of digging, wrapping in a function and using `:` instead of `.` now seems to work as expected.

```lua
vim.keymap.set('n', 'gh', function() require('lspsaga.finder'):lsp_finder() end, {noremap = true, silent = true})
```

**Comment by glepnir** [comment]
please use command in vim.keymap.set ，not use some builtin function

**Comment by jsatt** [comment]
If this is the official way of mapping them, then the docs should probably be updated to indicate that. The current README includes the mapping to the function directly, even including it before the mapping to the command, which could imply that it is the preferred way to do the mapping.
