### ISSUE TITLE
Use custom highlight group for selection in finder

### ISSUE THREAD

**Issue by weilbith** [glepnir/lspsaga.nvim#41]
You recently added the ability to change colors to highlight the current active entry in the finder. This is configured by two color values. I think it would be cool if you would add a new custom highlight group and then link the cursor line to this group. This still allows the user to easily change the highlight. But instead of defining raw color values you could also create a highlight link. So for example would I link it to the `Search` highlight group of my theme. But now I need to copy paste the colors. And I can't even apply "effects" like bold text. And now if I change my theme, I must also change the colors here again...
Would be a cool addition.

---

Btw: your recent improvements on the finder window are great! :muscle:

**Comment by weilbith** [comment]
Or just say you agree with the solution and I quickly do it so you can focus on what you intended to do else.

**Comment by glepnir** [comment]
pr，welcome
