### ISSUE TITLE
Error detected while processing CursorHold Autocommands for "*": method textDocument/codeAction is not supported by any of the servers registered for the current buffer

### ISSUE THREAD

**Issue by pogopaule** [glepnir/lspsaga.nvim#411]
### Description
In JSON files the following error appears if a lua file is opened.

**Expected Behavior**
No error message

**Actual Behavior**

```
Error detected while processing CursorHold Autocommands for "*":
method textDocument/codeAction is not supported by any of the servers registered for the current buffer
```
![image](https://user-images.githubusercontent.com/576949/183020210-d616392f-62d6-40d3-9005-f8a6931261d6.png)

**Neovim Built in Behavior**
Don't know

### Details

<details><summary>Reproduce</summary>

1. open nvim
2. open a json file where jsonls attaches
3. open a lua file where sumneko_lua attaches
4. go back to the json file
5. move the cursor
6. the error message above appears
7. hit enter -> error disappears
8. move the the cursor
9. the error message above appears
10. and so on...
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by pogopaule@pogopaule-xxxxxxxx

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/pogopaule/.linuxbrew/Cellar/neovim/0.7.2_1/share/nvim
"

Run :checkhealth for more info
```
- Operating system: Ubuntu 22.04.1
- lspsaga commit: always the latest

</details>

This issue and PR seem related: 
https://github.com/glepnir/lspsaga.nvim/pull/339
https://github.com/glepnir/lspsaga.nvim/issues/268

**Comment by glepnir** [comment]
@pogopaule  can you try the nightly ?

**Comment by pogopaule** [comment]
That was a quick! Thank you! :1st_place_medal:

**Comment by pogopaule** [comment]
@glepnir I guess this issue needs to be reopened. Either I didn't check the fix correctly yesterday or the bug was reintroduced.

**Comment by arminveres** [comment]
@pogopaule @glepnir I am having this issue as well and this only appeared after setting up this plugin.
I used the default configuration and removed my existing autocommands for `CursorHold`.
Dumping all the aucmds results in only two cursorholds:
```
Lspsaga  CursorHold
    *         <lua: 106>
Lspsaga  CursorHoldI
    *         <lua: 107>
```
leading me to your init.lua, at line 97,
```lua
  if conf.code_action_lightbulb.enable then
    api.nvim_create_autocmd({ 'CursorHold', 'CursorHoldI' }, {
      group = saga.saga_augroup,
      pattern = '*',
      callback = require('lspsaga.lightbulb').action_lightbulb,
    })
  end
```
Commenting this out, seems to resolve this.
I did not want to create a pull request, since I don't know what your final goal is, but you may want to look into it.
Cheers!

**Comment by noomly** [comment]
I've also been experiencing this issue since a few days and yesterday's fix also didn't solve it. I've noticed the error also shows up in the symbol rename floating input.

**Comment by glepnir** [comment]
@arminveres  no need comment just set disable for quick fix. I can't reproduce this problem always
```lua
saga.init_setup{
code_action_lightbulb.enable = false
}
```

**Comment by glepnir** [comment]
lspsaga doesn't print this message .it from neovim? but in nightly there also no print message. looks like only in 0.7 but I can't use 0.7 to reproduce ..

**Comment by arminveres** [comment]
Yeah I deactivated it for now. 
Seems that this issue is related to https://github.com/neovim/neovim/issues/12587. I also tried
https://github.com/antoinemadec/FixCursorHold.nvim but that did not solve it for me either.

**Comment by glepnir** [comment]
…i had fixed ，now can work in 0.7

**Comment by gmr458** [comment]
I get the error when I open an HTML file, when I open a Lua or JavaScript file nothing happens
![Captura desde 2022-08-07 19-29-43](https://user-images.githubusercontent.com/53343401/183318204-2c0828dd-29ea-47a3-9d53-c2b9c7ae3350.png)

**Comment by glepnir** [comment]
do you have nullls on this buffer

**Comment by glepnir** [comment]
now should be work with null-ls on 0.7 version

**Comment by johnallen3d** [comment]
I was running into this with `set ft=sh` (I also use `null-ls`). Just wanted to confirm that the latest has resolved the issue for me, thanks @glepnir!
