### ISSUE TITLE
LSoutlineToggle throw error 

### ISSUE THREAD

**Issue by katinbox** [glepnir/lspsaga.nvim#414]
### Description

LSoutlineToggle command error when call in react basic

**Expected Behavior**

Open with not show error

**Actual Behavior**

Before open, error showing -> open panel with null node.
**Neovim Built in Behavior**

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.8.0-dev+562-g606af7887
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az250-131

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

- Operating system: Linux kat-pc 5.15.57-2-MANJARO #1 SMP PREEMPT Mon Jul 25 01:32:51 UTC 2022 x86_64 GNU/Linux

- lspsaga commit: https://github.com/glepnir/lspsaga.nvim/commit/584e4da514cc2f9b5d98815a1ff77f9897ca7c

</details>

![lspsaga-outline](https://user-images.githubusercontent.com/43630437/183327062-ba1d0ef4-d7db-4297-9afa-f1b78718a462.png)

Press enter:
![outline2](https://user-images.githubusercontent.com/43630437/183327486-886aa131-f26d-46ce-bf22-570f9145089e.png)

**Comment by katinbox** [comment]
if have function, no error 
![outline3](https://user-images.githubusercontent.com/43630437/183328034-37606e09-438f-473d-a6cf-5eece68ac9a1.png)

**Comment by katinbox** [comment]
![outline](https://user-images.githubusercontent.com/43630437/183424900-dad3fb6d-a0f3-4cc2-a2d7-8c11a99e7fb0.png)

It throw new error

**Comment by glepnir** [comment]
fixed.

**Comment by katinbox** [comment]
Now it working perfect !!!
