### ISSUE TITLE
Blame error when move cursor file bash

### ISSUE THREAD

**Issue by katinbox** [glepnir/lspsaga.nvim#415]
### Description

**Expected Behavior**

**Actual Behavior**

**Neovim Built in Behavior**

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.8.0-dev+562-g606af7887
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az250-131

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

- Operating system:  Linux kat-pc 5.15.57-2-MANJARO #1 SMP PREEMPT Mon Jul 25 01:32:51 UTC 2022 x86_64 GNU/Linux

- lspsaga commit: https://github.com/glepnir/lspsaga.nvim/commit/584e4da514cc2f9b5d98815a1ff77f9897ca7c23

</details>

![blamcodeaction](https://user-images.githubusercontent.com/43630437/183334666-7a18544d-fe0d-4766-8a60-f36853419ae4.png)

**Comment by glepnir** [comment]
buffer only have one server？

**Comment by katinbox** [comment]
null-ls not attached and bash-language-server not load :
![lspinfo](https://user-images.githubusercontent.com/43630437/183353577-1ec3135b-3979-47c2-be64-95f5f54bd83a.png)
![mason-bash](https://user-images.githubusercontent.com/43630437/183353590-c7b28d99-386a-4f9d-9c60-dc922d2ffc58.png)
(

**Comment by katinbox** [comment]
I wanna stop blame when i move cursor if not server attached :)

**Comment by glepnir** [comment]
if no server. it doesn't appear

**Comment by katinbox** [comment]
Oh, null-ls made error show, when i type LspStop, no error appear, i will config null-ls server, thank you.

**Comment by glepnir** [comment]
if disable nullls works fine？

**Comment by katinbox** [comment]
Yeah, I was comment plugin in packer and error not appear. But i don't know hot to config null-ls not attached bash file :cry:

**Comment by katinbox** [comment]
![nullls](https://user-images.githubusercontent.com/43630437/183358598-25474bf0-c55c-4d7d-889b-47ff44033c6a.png)

Yeah, I add some line to config and null-ls not attached :smile:

**Comment by glepnir** [comment]
you don't need add this check. there need improve in saga i think

**Comment by glepnir** [comment]
@katinbox  can you remove your code and update for check?

**Comment by katinbox** [comment]
I remove it and updated, blame not appear. It working fine :smile:

**Comment by glepnir** [comment]
glad to hear that.
