### ISSUE TITLE
Key show_diagnostic_source not exist in config values

### ISSUE THREAD

**Issue by Azzpg7** [glepnir/lspsaga.nvim#417]
I didn't see the diagnostic source in the popup window. Tried to set the `show_diagnostic_source = true` option (as in the docs), but got an error when starting neovim.

Did you change the name of the option?

Thanks!

**Comment by glepnir** [comment]
No it's true by default. which error? i think you should post the error here

**Comment by Azzpg7** [comment]
Example of popup with no diagnostic source
<img width="1120" alt="image" src="https://user-images.githubusercontent.com/63911407/183600641-7929a40d-00b1-44e4-9332-8efd0a7b9f05.png">

I load plugin using Packer
<img width="944" alt="image" src="https://user-images.githubusercontent.com/63911407/183600918-9d892cf1-3e4e-46f8-9273-7d09eb603db7.png">

This is my lspsaga config file
<img width="454" alt="image" src="https://user-images.githubusercontent.com/63911407/183601309-0e9e883f-33d1-4f61-b56c-e987a7546a3d.png">

But when I start NeoVim I get this error
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/63911407/183601535-beff3950-7947-410d-99a2-de54f528ea7b.png">

**Comment by glepnir** [comment]
you use a wrong repo my github is glepnir

**Comment by Azzpg7** [comment]
Thanks a lot! I should less config my neovim at nights 😁

**Comment by chananababa** [comment]
I have the same problem with "glepnir/lspsaga.nvim".
<img width="1205" alt="스크린샷 2022-08-10 오전 11 31 49" src="https://user-images.githubusercontent.com/62169778/183797384-8c404b1d-c900-4873-a458-e898f3559487.png">

Here is my config
<img width="462" alt="스크린샷 2022-08-10 오전 11 32 41" src="https://user-images.githubusercontent.com/62169778/183797485-0e389573-8813-4b94-9186-a86b3d439a06.png">

<img width="370" alt="스크린샷 2022-08-10 오전 11 32 20" src="https://user-images.githubusercontent.com/62169778/183797449-029effe9-2443-4c20-a3f4-04611b15c21e.png">

**Comment by glepnir** [comment]
oh diagnostic source just work on jump window. you used show line diagnostic.maybe I can add it support in next version.

**Comment by chananababa** [comment]
Thanks!!

**Comment by ooloth** [comment]
> oh diagnostic source just work on jump window. you used show line diagnostic.maybe I can add it support in next version.

@glepnir Please do!

**Comment by glepnir** [comment]
doing.
