### ISSUE TITLE
Error with lsp_finder in Javascript

### ISSUE THREAD

**Issue by imsumoregn** [glepnir/lspsaga.nvim#422]
### Description

Using lsp_finder in Javascript files causing error.

**Actual Behavior**

It shows an error.
`Error executing Lua callback: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:143: attempt to index field 'client' (a nil value)
stack traceback:
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:143: in function 'do_request'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:39: in function 'lsp_finder'
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:13: in function <...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:12>
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:39: in function 'load_command'
        ...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:69: in function <...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:68>`

### Details

<details><summary>Reproduce</summary>

1. Running finder on anything in a Javascript file. It works normally in Typescript.
</details>

<details><summary>Environment</summary>

- nvim --version output:  `NVIM v0.7.2 Build type: Release LuaJIT 2.1.0-beta3`
- Operating system: WSL2 Ubuntu 20.04
- lspsaga commit: `3215fccc6c890701fa8e03de1e8f2db695c75089`

</details>

**Comment by glepnir** [comment]
maybe a test js code is useful

**Comment by imsumoregn** [comment]
@charlie39 Please take a look. [output.txt](https://github.com/glepnir/lspsaga.nvim/files/9310663/output.txt)
@glepnir In my nvim, importing anything from another file and running lsp_finder on it will produce the error.

**Comment by charlie39** [comment]
you are using null-ls right?

null-ls doesn't have support for referencesProvider or definationProvider, hence
you can't lsp_finders() on it

**Comment by imsumoregn** [comment]
@charlie39 Oh I see. I'm using `tsserver`, and it's working fine. What do you recommend if not null-ls?

**Comment by charlie39** [comment]
It seems you can actually make do with tsserver, have a look here https://www.reddit.com/r/neovim/comments/pxcxku/comment/hemy7a2/?utm_source=share&utm_medium=web2x&context=3


Or just choose anyone from here with javascript support, there tonnes of them
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#java_language_server

**Comment by charlie39** [comment]
Of course make sure the language server have the required capabilities you are
looking for.

**Comment by imsumoregn** [comment]
I got it working with `denols`, but now refs and defs are only being looked for in one file only. Could you help me with this, how can I make it project-wide? @charlie39

**Comment by imsumoregn** [comment]
@glepnir

```javascript
// test.js
export const test = () => {}
export const a = 1
```

```javascript
// index.js
import { test, a } from './test.js'
const r = test()
console.log(r)
console.log(a)
```

Running lsp_finder() on both `test` and `a` gives the following error (using `denols`)
`Error executing vim.schedule lua callback: ...site/pack/packer/start/lspsaga.nvim/lua/lspsaga/libs.lua:94: bad argument #1 to 'pairs' (table expected, got string)
stack traceback:
        [C]: in function 'pairs'
        ...site/pack/packer/start/lspsaga.nvim/lua/lspsaga/libs.lua:94: in function 'get_lsp_root_dir'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:165: in function 'render_finder'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:133: in function 'cb'
        vim/_editor.lua:256: in function <vim/_editor.lua:256>`

**Comment by glepnir** [comment]
@imsumoregn  I am wonder that the denols better than tsserver?

**Comment by glepnir** [comment]
now i am in `version_2` branch works fine. so it will fix on verison2
![images](https://user-images.githubusercontent.com/41671631/184479237-f560d68c-26b0-4418-b304-f7f6fe93167a.gif)

**Comment by charlie39** [comment]
paste your
open a js file from your project,
and run
```:lua =vim.lsp.get_active_clients()[1].config```

and paste the output.
Don't upload in file ratther use pastebin or ix.io and than share the link

**Comment by imsumoregn** [comment]
Oh thank you so much @glepnir, looking forward to it.

Just one more thing, I'm experiencing [this](https://www.loom.com/share/2431cd05863c4f228e653b8a9ce58952) behaviour. The finder's window doesn't automatically quit when I press `<C-w>h` and the similars. Do you think this is a bug? If so, I'll create another issue.

**Comment by glepnir** [comment]
I want to know why you do not use `<C-c>` or you custom exit key to quit the finder window.  I can fix this but want to the reason

**Comment by imsumoregn** [comment]
I'm reporting this just bc there's one time I accidentally pressed mis-pressed a keybinding and the finder's window stayed there floating, forcing me to close and reopen the whole editor. So from my POV, there's should be a fix to prevent such innocuous but frustrating situation.

**Comment by charlie39** [comment]
> I'm reporting this just bc there's one time I accidentally pressed mis-pressed a keybinding and the finder's window stayed there floating, forcing me to close and reopen the whole editor. So from my POV, there should be a fix to prevent such innocuous but frustrating situation.

When that happens, press ```shift+zz```

**Comment by charlie39** [comment]
or ```shift+zq```

**Comment by glepnir** [comment]
right.will add a patch for it in version2

**Comment by imsumoregn** [comment]
Thank you for your support, I really appreciate it! Will close the issue now.
