### ISSUE TITLE
sign column diagnostic symbols

### ISSUE THREAD

**Issue by fans3210** [glepnir/lspsaga.nvim#428]
Thanks glepnir for the amazing work. I have one small issue which I'm not sure whether a feature from old version of lspsaga was removed. In the old version of lspsaga, there are settings of "error_sign", "warning_sign" settings from which we can set symbols for sign columns.  But those settings were not there anymore. A letter of "E" or "W" was displayed in the sign column instead of the symbols. It would be good if we still can display symbols in sign column. Thanks

**Comment by glepnir** [comment]
@fans3210  it's config by upstream.now the upstream has a better config function .so you can use it like this.

```lua
local signs = {
  Error = ' ',
  Warn = ' ',
  Info = ' ',
  Hint = 'ﴞ ',
}
for type, icon in pairs(signs) do
  local hl = 'DiagnosticSign' .. type
  vim.fn.sign_define(hl, { text = icon, texthl = hl, numhl = hl })
end

vim.diagnostic.config({
  signs = true,
  update_in_insert = false,
  underline = true,
  severity_sort = true,
  virtual_text = {
    source = true,
  },
})

```

**Comment by rodhash** [comment]
Is it supposed to be enabled by default? I just installed this plugin and it was not .. I had to add it manually.

Thanks.

**Comment by glepnir** [comment]
this is not provide by lspsaga. it's neovim `vim.diagnostic` module. so this mean neovim provide this way to config it.
