### ISSUE TITLE
Using add-import code action in haskell performs wrong action

### ISSUE THREAD

**Issue by mizlan** [glepnir/lspsaga.nvim#432]
### Description
I am in a Haskell file, and if there is a symbol I want to import, and I try using LspSaga code action, it always picks this different option that is not very helpful (will explain in more detail below).

**Expected Behavior**
The "add import" action is executed (e.g., `import Data.Maybe` is added to top of file)

**Actual Behavior**
For Haskell, I have `{-# OPTIONS_GHC -Wno-deferred-out-of-scope-variables #-}` added to the top of my file (which is another codeaction option)

**Neovim Built in Behavior**
`vim.lsp.buf.code_action` works fine

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
```lua
P = require('neopm')

P 'https://github.com/neovim/nvim-lspconfig'
P 'https://github.com/glepnir/lspsaga.nvim'
P.autoinstall(true)
P.load()

local on_attach = function(client, bufnr)
  local bufopts = { noremap = true, silent = true, buffer = bufnr }
  vim.keymap.set('n', '<leader>ca', "<cmd>Lspsaga code_action<CR>", bufopts)
end
require('lspconfig')['hls'].setup {
  on_attach = on_attach,
}
```
2. post your program language min code snippet that can reproduce your issue

1 line:
```haskell
c = catMaybes
```
There is error on catMaybes, variable not in scope, but if you use codeAction add import it doesnt work, instead the long GHC option is added.

3. instead of that, `import Data.Maybe` should be added.
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.8.0-dev+608-g778541067
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by ml@Michaels-MacBook-Pro.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-7785410/share/nvim"
```
- Operating system: macOS monterey
- lspsaga commit: f4041254c242dee33cd14a047471b2abc1fe2fa2

</details>

**Comment by glepnir** [comment]
`{-# OPTIONS_GHC -Wno-deferred-out-of-scope-variables #-}`  put this line at the head of file?

**Comment by mizlan** [comment]
Lspsaga puts that line there even though thats not the option I want.

**Comment by glepnir** [comment]
Hmm I don't know how to reproduce your question .I don't write haskell .so a complete reproduce step will be useful.

**Comment by mizlan** [comment]
It is a bit annoying to setup because long build time is required. As an alternative, I will try locating the issue of the bug myself.

**Comment by mizlan** [comment]
Found the issue, will see if is already implemented upstream and if not push PR soon

**Comment by glepnir** [comment]
check  the pr just make function receive an uncertain parameter ?

**Comment by mizlan** [comment]
yes. problem is if I do something like `:lua require('lspsaga.codeaction').do_code_action('2')`, the `'2'` is not actually passed to inside function. This is wrong, all the functions should pass on the arguments they receive.

**Comment by glepnir** [comment]
where is the 2 used? make function receive but you never used it in function

**Comment by mizlan** [comment]
It has been fixed in v2. PR is very stale now
