### ISSUE TITLE
which colorgroup for goto_prev/next line pointer?

### ISSUE THREAD

**Issue by rowsephx** [glepnir/lspsaga.nvim#433]
I have a transparent background and would like to clear the background of the unknown highlight group. `LspFloatWinNormal` worked only for the floating windows.

![2022-08-14_14-51-lspsaga](https://user-images.githubusercontent.com/110653023/184526295-fbda30bb-fdf0-4440-b385-556b7514a1d3.png)

**Comment by glepnir** [comment]
this line background use `winlend=100` to transparent.

**Comment by rowsephx** [comment]
I'm sorry, how do I set that with `vim.api.nvim_set_hl`?

**Comment by glepnir** [comment]
you can't set it's window config. by defualt it also use `LspFloatWinNormal`

**Comment by rowsephx** [comment]
Can you further explain what "window config" means? 

> by defualt it also use `LspFloatWinNormal`

That's weird I've already cleared the bg of that group

**Comment by glepnir** [comment]
it's window an option to make window background transparent. I will take a look at this behavior. fix it in version2 maybe

**Comment by rowsephx** [comment]
I guess changing the value of [this](https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/diagnostic.lua#L79) to 0 worked for me.

And also, I'm getting this weird behavior from the pointer. (This was already present before changing winblend to 0)

![2022-08-14_15-34-lspsaga-2](https://user-images.githubusercontent.com/110653023/184527192-176b90c9-0d46-4afb-a0f2-cfa0f79b86df.png)

**Comment by glepnir** [comment]
yup this behavior is known bug. work for this currently

**Comment by rowsephx** [comment]
I guess maybe for the winblend add something that checks if `LspFloatWinNormal` is cleared, if so make the value 0. Idk really.

**Comment by glepnir** [comment]
remove this setting in version 2 will make sense for you.
