### ISSUE TITLE
希望可以给 floaterm 加一个切换的显示和隐藏的功能

### ISSUE THREAD

**Issue by liaohui5** [glepnir/lspsaga.nvim#434]
现在的 floaterm 的功能是这样的:
Lspsaga open_floaterm 命令是打开终端
Lspsaga close_floaterm 命令是关闭终端,
希望可以增加一个 Lspsaga toggle_floaterm 命令, 功能就是用来切换终端显示和隐藏(不关闭)
因为有的时候, 我想敲一个比较长的命令,  我命令敲一半了, 我想看文件内容然后继续敲
现在是没有办法切换, 只能退出终端, 然后打开重新开始敲一遍, 我知道有个[toggleterm](https://github.com/akinsho/toggleterm.nvim)
插件可以实现这个功能, 但是我觉得, lspsaga都实现这个功能了, 就不需要另外再安装插件了

**Comment by glepnir** [comment]
hmm lspsaga的浮动终端只是个简单的exmaple ，使用我封住的window api 可以很简单的实现一个浮动终端。所以我就弄了一个。这是个lsp插件。这个浮动窗口其实是不应该存在的。只是简单实现了就放里面了。 close_floaterm 可以实现。加上下文保存虽然很多人提过想要。但是实现有点麻烦。目前没什么想法弄这个
