### ISSUE TITLE
LSoutlineToggle Error

### ISSUE THREAD

**Issue by NEX-S** [glepnir/lspsaga.nvim#435]
```
Error executing vim.schedule lua callback: ...ite/pack/packer/opt/lspsaga.nvim/lua/lspsaga/outline.lua:257: attempt to index a nil value
stack traceback:
        ...ite/pack/packer/opt/lspsaga.nvim/lua/lspsaga/outline.lua:257: in function 'callback'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1782: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1230: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

nvim version: nvim-nightly

**Comment by NEX-S** [comment]
In version 2 `LSoutlineToggle` has no reaction. Once I execute `LSoutlineToggle` and press `<CR>`, there's no error or any messages, but outline windows doesn't appear.

**Comment by NEX-S** [comment]
So is Lspsaga's outline in development? Seems there doesn't any way to customize it :D

**Comment by glepnir** [comment]
customize for what. just fixed this issue in version2 .

**Comment by NEX-S** [comment]
Customize like icons, highlights etc. BTW, is there any way to make LSoutline show GPS in lualine? Just like Aerial or NVIM-GPS, that's a great fuction :)

**Comment by NEX-S** [comment]
And functions called chains. Does any LanguageSever support showing functions call chain?

**Comment by glepnir** [comment]
please read doc you can `require('lspsaga.kind')`. symbols in statusline is same in winbar check doc. function called chain. maybe you want find references implement check lspsaga finder

**Comment by NEX-S** [comment]
Sorry, I didn't notice the README.md has been updated, I'll try to recustomize my Lspsaga's config.
