### ISSUE TITLE
Auto close outline when last buffer is closed

### ISSUE THREAD

**Issue by ayamir** [glepnir/lspsaga.nvim#436]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The outline should be closed when last buffer is closed.

**Describe alternatives you've considered**
No

**Additional context**

**Comment by glepnir** [comment]
`autocmd WinEnter * if &filetype == 'lspsagaoutline' && winnr('$') == 1 | bdel | endif`
