### ISSUE TITLE
UI 问题

### ISSUE THREAD

**Issue by zjp-CN** [glepnir/lspsaga.nvim#437]
### 描述

![截图_20220814231224](https://user-images.githubusercontent.com/25300418/184543488-da328a30-fee0-4a75-82c4-86b1075aecaa.gif)

1. 这个转弯的箭头
![image](https://user-images.githubusercontent.com/25300418/184543661-8aa0ad12-73ad-410f-a420-8c4b11e81187.png)
有时候方向不对，有时候又是对的 
![image](https://user-images.githubusercontent.com/25300418/184543703-99639ebe-499e-476b-b521-70db85faa0fa.png)
2. 悬浮窗口似乎没提供自定义 width 和 height，而默认的计算方式总是导致
  - 要么窗口宽度太窄 
![image](https://user-images.githubusercontent.com/25300418/184543895-145aa125-6b9d-4ab9-b5a3-63583c9b0478.png)

  - 要么窗口高度太窄
![image](https://user-images.githubusercontent.com/25300418/184543771-e7aad22d-bbe2-44b5-ab1e-74f9499b6e88.png)
![image](https://user-images.githubusercontent.com/25300418/184543785-4410ebc1-89a9-4f15-894a-a79095d7fbb9.png)

缩放也改变不了这种显示。

### 配置

```lua
local saga = require 'lspsaga'

saga.init_lsp_saga {
  show_diagnostic_source = false,
  diagnostic_header = { 'E', 'W', 'I', 'H' },
  code_action_icon = '',
  max_preview_lines = 30, -- preview lines of lsp_finder and definition preview
  finder_action_keys = {
    open = '<CR>', vsplit = 's', split = 'i', quit = '<Esc>', scroll_down = '<C-f>', scroll_up = '<C-b>'
  },
  code_action_keys = { quit = "<Esc>", exec = "<CR>" },
  rename_action_quit = '<Esc>',
  definition_preview_icon = ''
}
```

**Comment by glepnir** [comment]
version_2 branch had fixed this bug. when all task complete will merge to main

**Comment by zjp-CN** [comment]
![截图_20220814233657](https://user-images.githubusercontent.com/25300418/184544445-2d7e4394-d54d-49a6-bdb2-a68050e0a9b8.gif)

问题 1 解决了~

问题二依然存在。我粗略看了历史的 issue 和一些代码，似乎是按照主窗口大小的比例计算悬浮窗口大小的。

**Comment by glepnir** [comment]
yup a known bug there has some thing wrong in wrap function. need rewrite it. provide some example code that can reproduce this bug it's useful.

**Comment by zjp-CN** [comment]
The code in GIF is [here](https://github.com/zjp-CN/mini-redis/tree/lspsaga).

It's Rust code and Rust-Analyzer is required.

Complete nvim config is [here](https://github.com/zjp-CN/nvim-config).

**Comment by zjp-CN** [comment]
The error from rustc (compiler) and diagnostic from Rust-Analyzer are (and should be) the same. So the error msg is this

```rust
$ cargo c
    Checking mini-redis v0.4.1 (/rust/github/mini-redis)
error[E0308]: mismatched types
   --> src/frame.rs:269:22
    |
269 |         Error::Other(src)
    |         ------------ ^^^ expected struct `Box`, found struct `String`
    |         |
    |         arguments to this enum variant are incorrect
    |
    = note: expected struct `Box<(dyn std::error::Error + Send + Sync + 'static)>`
               found struct `String`
note: tuple variant defined here
   --> src/frame.rs:28:5
    |
28  |     Other(crate::Error),
    |     ^^^^^
```

Hope it's useful.

**Comment by glepnir** [comment]
Okay take a look at later.

**Comment by rowsephx** [comment]
> ![截图_20220814233657](https://user-images.githubusercontent.com/25300418/184544445-2d7e4394-d54d-49a6-bdb2-a68050e0a9b8.gif)

@zjp-CN, I'm sorry that this is unrelated to your issue, but how were you able to jump inside the diagnostic popup window?

**Comment by zjp-CN** [comment]
@rowsephx 
> jump inside the diagnostic popup window

`Ctrl-w w`. 
You can refer to `:h CTRL-W_w`.

**Comment by rowsephx** [comment]
> `Ctrl-w w`.

Oh wow! I didn't know that. 

I just use the inline diagnostic, and press its keybinding twice to get inside the diagnostic window. 

This is good to know!

**Comment by zjp-CN** [comment]
How to get inside the diagnostic window? I always want to to that. @rowsephx 

I recently find [lsp_lines](https://git.sr.ht/~whynothugo/lsp_lines.nvim) might be a solution too.

**Comment by rowsephx** [comment]
@zjp-CN, you can either use `vim.diagnostic.open_float` or `Lspsaga show_line_diagnostics`, and put mapping.

For example:
 `
vim.keymap.set("n", "gl", require("lspsaga.diagnostic").show_line_diagnostics, { silent = true })`

Pressing `gl` will show all the diagnostics for the current line, and if `gl` is pressed again, it will put your cursor inside the diagnostic window.

> I recently find [lsp_lines](https://git.sr.ht/~whynothugo/lsp_lines.nvim) might be a solution too.

I'm aware of this, but I find it cluttered.

**Comment by zjp-CN** [comment]
@rowsephx Thank you for reminding me of that!
![image](https://user-images.githubusercontent.com/25300418/184571942-b8adc619-4559-4ecd-b416-5d964a41cfb0.png)
