### ISSUE TITLE
set keymaps overwrites mapping of :help

### ISSUE THREAD

**Issue by rowsephx** [glepnir/lspsaga.nvim#439]
I have the lspsaga hover set to `K`, and it only attaches during lsp:

```
M.on_attach = function(client, bufnr)
    local map = vim.keymap.set
    local bufopts = { noremap = true, silent = true, buffer = bufnr }

    map("n", "K", require("lspsaga.hover").render_hover_doc, { desc = "lsp hover" }, bufopts)

```
The problem is if the keymap gets attached, the `K` inside help no longer works. If you don't know what I'm referring to, check `:h K`

This only happens when I use lspsaga's hover, and not with `vim.lsp.buf.hover`. I can technically just use this, but it takes up the whole width of my window if the content is lengthy, which bothers me. I can also just bind the hover with a different key, but I'm already used to using `K`.

Related: 
lewis6991/hover.nvim#1
neovim/neovim#18997

**Comment by glepnir** [comment]
so you can use that function in hover#1  just check the current filetype is help or not

**Comment by rowsephx** [comment]
> use that function in hover#1 just check the current filetype is help or not

Oh my, I'm blind...

```
map('n', 'K', function()
    if vim.bo.filetype == 'help' then
        vim.api.nvim_feedkeys('K', 'ni', true)
    end
    require("lspsaga.hover").render_hover_doc()
end, { desc = "lsp hover" }, bufopts)
```
Dunno if this is the best way of doing it, what do you think?

**Comment by glepnir** [comment]
right. which `keyowordprg` you set or default?

**Comment by rowsephx** [comment]
> which `keyowordprg` you set or default?

I haven't touch that, so I would assume default

**Comment by glepnir** [comment]
aha. okay. maybe we can add this function into default hover function . then no need this hack.

**Comment by rowsephx** [comment]
> aha. okay. maybe we can add this function into default hover function . then no need this hack.

That would be great actually, makes the config file cleaner hehe
