### ISSUE TITLE
lsp_finder error: `Invalid buffer`

### ISSUE THREAD

**Issue by keaising** [glepnir/lspsaga.nvim#442]
### Description

When I use `gr` to find references, I find this error in message lines

```
Error executing vim.schedule lua callback: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:109: Invalid buffer id: 7
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:109: in function ''  
✔ gopls
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/8179012/184794039-1cfe0b21-4048-4e2e-b3ae-bd2a2774dff2.png">

If I press Enter to ignore the error message, the reference UI display as I expect.

**Expected Behavior**

Don't show error message

**What I try to fix**

I forked this repo and comment the lines which make error, and the error disappear and the plugin works charmly.

You can find the update I make in  [link to my fork](https://github.com/keaising/lspsaga.nvim/commit/57062ac19869caa78cf91440257f4c4f30d3accb)

**Neovim Built in Behavior**

If I use `:lua vim.lsp.buf.references()`, I can get the correct content as I expect, be like:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/8179012/184794396-0416a683-5e3e-4707-8ba6-3e6e381a74a3.png">

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga

```lua
local fn = vim.fn

-- Automatically install packer
local install_path = fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"
if fn.empty(fn.glob(install_path)) > 0 then
	PACKER_BOOTSTRAP = fn.system({
		"git",
		"clone",
		"--depth",
		"1",
		"https://github.com/wbthomason/packer.nvim",
		install_path,
	})
	print("Installing packer close and reopen Neovim...")
	vim.cmd([[packadd packer.nvim]])
end

-- Autocommand that reloads neovim whenever you save the plugins.lua file
-- vim.cmd [[
--   augroup packer_user_config
--     autocmd!
--     autocmd BufWritePost plugins.lua source <afile> | PackerSync
--   augroup end
-- ]]

-- Use a protected call so we don't error out on first use
local status_ok, packer = pcall(require, "packer")
if not status_ok then
	return
end

-- Have packer use a popup window
packer.init({
	display = {
		open_fn = function()
			return require("packer.util").float({ border = "rounded" })
		end,
	},
})

return packer.startup(function(use)
	use({
		"glepnir/lspsaga.nvim",
		branch = "version_2",
		config = function()
			local saga = require("lspsaga")
			saga.init_lsp_saga({
				-- your configuration
				saga_winblend = 0,
				max_preview_lines = 20,
				finder_action_keys = {
					open = { "<CR>", "o" },
					vsplit = "v",
					split = "s",
					tabe = "t",
					quit = { "<ESC>", "q" },
					scroll_down = "<C-n>",
					scroll_up = "<C-p>", -- quit can be a table
				},
				code_action_keys = {
					quit = { "<ESC>", "q" },
					exec = "<CR>",
				},
				rename_action_quit = "<ESC>",
				show_outline = {
					win_position = "down",
					-- set the special filetype in there which in left like nvimtree neotree defx
					left_with = "",
					win_width = 60,
					auto_enter = true,
					auto_preview = true,
					virt_text = "┃",
					jump_key = "o",
					-- auto refresh when change buffer
					auto_refresh = true,
				},
			})

			vim.keymap.set("n", "gr", "<cmd>Lspsaga lsp_finder<CR>", { silent = true, noremap = true })
		end,
	})
	-- Automatically set up your configuration after cloning packer.nvim
	-- Put this at the end after all plugins
	if PACKER_BOOTSTRAP then
		require("packer").sync()
	end
end)
```

3. post your program language min code snippet that can reproduce your issue

Just a simple go hello world program

</details>

<details><summary>Environment</summary>

- nvim --version output: 

```
NVIM v0.8.0-dev-852-g6264aa521
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/cmake.config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include
Compiled by runner@Mac-1660540799386.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

- Operating system: macOS 12.5 on M1 Pro
- lspsaga commit: The latest `a340275428f097b9fb1db9465745f974c48e4693`

</details>

**Comment by keaising** [comment]
I have read this issue [issue 408](https://github.com/glepnir/lspsaga.nvim/issues/408) and have a try with `version_2`, the same error.

**Comment by glepnir** [comment]
cannot reproduce

**Comment by keaising** [comment]
After a bisect search, I find the conflict comes from https://github.com/folke/trouble.nvim.

If I use trouble.nvim with lspsaga, lspsaga will make error messages above, here is my troubele.nvim's config:

```
local status_ok, trouble = pcall(require, "trouble")
if not status_ok then
  return
end
trouble.setup()

vim.api.nvim_set_keymap("n", "<leader>xx", ":TroubleToggle<cr>", {silent = true, noremap = true})
vim.api.nvim_set_keymap("n", "<leader>xw", "<cmd>Trouble workspace_diagnostics<cr>", {silent = true, noremap = true})
vim.api.nvim_set_keymap("n", "<leader>xd", "<cmd>Trouble document_diagnostics<cr>", {silent = true, noremap = true})
vim.api.nvim_set_keymap("n", "<leader>xl", "<cmd>Trouble loclist<cr>", {silent = true, noremap = true})
vim.api.nvim_set_keymap("n", "<leader>xq", "<cmd>Trouble quickfix<cr>", {silent = true, noremap = true})
vim.api.nvim_set_keymap("n", "gR", "<cmd>Trouble lsp_references<cr>", {silent = true, noremap = true})
```
I use latest commit of trouble.nvim's master branch, both main and version_2 branch of lspsaga can reproduce.

Could you pls take a look? @glepnir

**Comment by glepnir** [comment]
so it's not lspsaga problem? i don't work for other plugin. if you can reproduce with a min config.that only have lspsaga. I will fix it. sry

**Comment by keaising** [comment]
I'm not sure which plugin create this issue, I just know there is a conflict: both plugins try to add highlight to a buf.

Whatever, I disabled the trouble.nvim :)

**Comment by glepnir** [comment]
you can try the mini config that only have lspsaga.
> both plugins try to add highlight to a buf.

I don't know about trouble.nvim. for lspsaga there has a loadingbar when you use finder.

**Comment by keaising** [comment]
> you can try the mini config that only have lspsaga.

Yeah, I have tried this minimal config you said, it's ok. 

But what I find is a conflict caused by lspsaga and trouble.nvim, and the error message comes from lspsaga.

If I raise a issue in trouble.nvim, the author of trouble.nvim can say: "It's a problem of lspsaga"  _ (:з」∠)_

Anyway, I disabled trouble.nvim and I think my issue solved. 

For anyone else find this issue in the futrue, you can try to disable trouble.nvim or replace it with other plugin in active development.

**Comment by glepnir** [comment]
yup the error message is from lspsaga ,but need a reproduce step that can reproduce it 100%. maybe I can add a patch to avoid error. I will test it in version2 if you still get this error. ping me is. okay
