### ISSUE TITLE
[Feature Request] implement ctags stack when using Go to Definition/Reference

### ISSUE THREAD

**Issue by hronro** [glepnir/lspsaga.nvim#443]
**Is your feature request related to a problem? Please describe.**
The Neovim's built-in LSP has implemented ctags stack when using Go to Definition/Reference, which means I use `<C-t>` to jump back after using go to definitions/references. However with lspsaga, when jumping to definitions/references using LSP finder, I'm not able to use `<C-t>` to jump back.

**Comment by glepnir** [comment]
I think it.is ctrl o

**Comment by hronro** [comment]
`<Ctrl-o>` is a different thing. Even cursor moves will add new histories when using `<Ctrl-o>`, but only goto definitions/references will add new histories when using `<Ctrl-o>`.

**Comment by glepnir** [comment]
yup when you edit something it will change `<C-o>` .
