### ISSUE TITLE
neovim 0.7.2 don't have LspAttach event

### ISSUE THREAD

**Issue by 45degree** [glepnir/lspsaga.nvim#446]
### Description
`lspsaga` cause an error: 

> packer.nvim: Error running config for lspsaga.nvim: ...e/pack/packer/opt/lspsaga.nvim/lua/lspsaga/lightbulb.lua:164: unexpected event

**Expected Behavior**
no error

### Details

I use neovim 0.7.2,  and it  only have `LspProgressUpdate` and `LspRequest` events, but you used `LspAttach` event in `lua/lspsaga/lightbulb.lua` 

<details><summary>Environment</summary>

- nvim --version output:

``` shell
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info 
```

- Operating system: Archlinux

- lspsaga commit: [c2bc87d](https://github.com/glepnir/lspsaga.nvim/commit/c2bc87d40a6d02032853f29b4ad97ea57bf4bfe2)

</details>

**Comment by kohane27** [comment]
[Bug Report] lightbulb.lua:164: unexpected event

Hello there. Hope you're doing well.

I got the error when running lspsaga:

```code
packer.nvim: Error running config for lspsaga.nvim: ...pack/packer/start/lspsaga.nvim/lua/lspsaga/lightbulb.lua:164: unexpected event
```

```
  use({
    "glepnir/lspsaga.nvim",
    branch = "main",
    config = function()
      local saga = require("lspsaga")

      saga.init_lsp_saga({
        -- your configuration
      })
    end,
  })
```


<details><summary>Environment</summary>

```
❯ nvim --version
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser
```

- Operating system: Linux
- lspsaga commit: Version 0.2 (#421)

</details>

**Comment by kohane27** [comment]
@glepnir Confirmed the error is gone and lspsaga is working again. Thank you!

**Comment by timoleistner** [comment]
Not gone for me on 0.8:
```
NVIM v0.8.0-dev+26-gdb851cb10
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by root@manjo

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
With latest version of saga on manjaro.

**Comment by glepnir** [comment]
it should works fine in 0.8 if not please update your version
