### ISSUE TITLE
[Feature Request] command trigger the second time jump into float window.

### ISSUE THREAD

**Issue by 66RING** [glepnir/lspsaga.nvim#450]
It may be more convenient that cursor jump into float window when command trigger the second time. just like the origin lsp api do.

So that I need not to mapping additional key for smart scroll.

Such as:

![Peek 2022-08-19 17-07](https://user-images.githubusercontent.com/49358576/185585729-3120e32b-425e-4838-b8bb-b0fb6b8d17c7.gif)

**Comment by glepnir** [comment]
already support

**Comment by 66RING** [comment]
Hello @glepnir 

I found it work well on `hovc_doc` and some other, but looks not good on `preview_definition`. And `preview_definition` just hang when I call it twice.

![Peek 2022-08-19 17-21](https://user-images.githubusercontent.com/49358576/185588256-69f4432b-2d63-4eea-b297-cb876cefa069.gif)

**Comment by younger-1** [comment]
preview_definition still have this problem

**Comment by 66RING** [comment]
fixed. 0635ed55f03e0300fadf0dce94eb123c5ced02bd
