### ISSUE TITLE
Code action nil self error on the latest update

### ISSUE THREAD

**Issue by zsmatrix62** [glepnir/lspsaga.nvim#453]
I just updated the plugin today and it reports a Lua error at [codeaction.lua#144](https://github.com/glepnir/lspsaga.nvim/blob/9233600fbb40d2a3d0b7358cfa67caa281f9a3ba/lua/lspsaga/codeaction.lua#L144) saying that the `self` is nil

I reverted to commit [330a8a9a404a3173cea8af3ad33f59900d579302](https://github.com/glepnir/lspsaga.nvim/commit/330a8a9a404a3173cea8af3ad33f59900d579302) and everything is okay.

**Comment by glepnir** [comment]
please read changelog and example configure.usecommand in rhs not call builtin function

**Comment by colossatr0n** [comment]
Just for reference, the previous format 
`<cmd>lua require("lspsaga.codeaction").code_action()<CR>` 
has been changed to 
`<cmd>Lspsaga code_action<CR>`
which can be found in the example config under [README#configuration](https://github.com/glepnir/lspsaga.nvim#configuration).
