### ISSUE TITLE
Jump and show diagnostic shows weird border and color for some colorschemes

### ISSUE THREAD

**Issue by fans3210** [glepnir/lspsaga.nvim#459]
<img width="543" alt="Screenshot 2022-08-25 at 10 14 07 PM" src="https://user-images.githubusercontent.com/6023208/186688830-723258fa-2c91-4bd5-8621-de2749ab5b20.png">
As we see, the diagnostic shows white color border, it should be red. The border also not smooth.

Tested on "everforest" colorscheme and other schemes from this author also have similar issue eg: gruvbox-material.

Lastest popular colorschemes like tokyonight doesn't have such issue

**Comment by glepnir** [comment]
color scheme problem not lspsaga.
