### ISSUE TITLE
Rust warning messages cause issues

### ISSUE THREAD

**Issue by TimUntersberger** [glepnir/lspsaga.nvim#46]
The following line fails with `String cannot contain newlines` when trying to cycle through rust warnings.

https://github.com/glepnir/lspsaga.nvim/blob/1a09da7878fb4ebc46b10e0dc594242ab7c64269/lua/lspsaga/window.lua#L172

**Warning**

![image](https://user-images.githubusercontent.com/32014449/106353943-6f102680-62ee-11eb-9aa5-c4cc03850e09.png)

It also seems like the coloring is wrong when displaying the error:

![image](https://user-images.githubusercontent.com/32014449/106353982-ca421900-62ee-11eb-993e-435817af3742.png)

**Comment by glepnir** [comment]
`rust-analyzer` ?

**Comment by glepnir** [comment]
can you post a min code that reproduce this ?

**Comment by glepnir** [comment]
@TimUntersberger  fixed.

**Comment by al3xfischer** [comment]
Currently, having a similar error.

```rust
fn main() {
    let _ = File::open("hello.txt").expect("Nop nop");
}
```
Cursor is on `File`

`:Laspsaga code_action`


Fails with: 
Error executing vim.schedule lua callback: ...te\pack\packer\start\lspsaga.nvim\lua\lspsaga\window.lua:155: String cannot contain newlines
