### ISSUE TITLE
jibberish on popup

### ISSUE THREAD

**Issue by k1ng440** [glepnir/lspsaga.nvim#460]
### Description

I am seeing jibberish on the popup window. https://puu.sh/JhYKj/40bca6f7af.png

**Expected Behavior**

should be clean

**Actual Behavior**

**Neovim Built in Behavior**

works fine. just issue with popup window

### Details

<details><summary>Reproduce</summary>
I am using following and I don't know how to reproduce this but I can give you dotfiles
 
1. tmux
2. neovim 0.7

</details>

<details><summary>Environment</summary>
tmux
neovim 0.7
wazterm
WSL

- nvim --version output: 
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az316-460

- Operating system: Ubuntu on Windows
- lspsaga commit: 40d6f5c

</details>

**Comment by glepnir** [comment]
I can' reproduce this with wezterm. try to update your wezterm version

![image](https://user-images.githubusercontent.com/41671631/186780451-f56ec0bf-2be3-4c81-80b8-dca8d992b856.png)
