### ISSUE TITLE
Part of the pop-up window remains after exiting

### ISSUE THREAD

**Issue by guilhermedeandrade** [glepnir/lspsaga.nvim#461]
### Description
Part of the pop-up window remains after trying to jump to definition using space (maybe this isn't the correct mapping, but I couldn't find how to do it and I guess it looks like a bug anyway)

Using :q to exit the pop-up doesn't works fine.

PS.: a bit off-topic but I'm not being able to realize how can I jump to a definition. Is there a default keymap or I should define one? If the latter, which command I should map?

**Expected Behavior**
I expected nothing would be left after exiting from lsp-finder.

**Actual Behavior**
![image](https://user-images.githubusercontent.com/8797405/186726547-039d9c97-65d7-4a78-918a-d04733207e86.png)

**Neovim Built in Behavior**

I don't know which should be the default behavior, sorry.

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga

2. post your program language min code snippet that can reproduce your issue:
```ts
type User = {
  age: number,
  name: string
}

function getUserName(user: User): string {
  return user.name
}

getUserName({ age: 26, name: 'guilherme' })
```

(posted a simple snippet but this happens in big projects as well)
</details>

<details><summary>Environment</summary>

- nvim --version output: NVIM v0.7.2
- Operating system: macOS 12.14
- lspsaga commit: 40d6f5c3cc8b6984e6b244fb2245762b51c05747 (was already happening before this commit though)

</details>

**Comment by glepnir** [comment]
can' reproduce .just add a patch to make sure it close.

**Comment by guilhermedeandrade** [comment]
Thanks for letting me know about the `finder_action_key`! However, the problem remains on the latest commit. When I press `Space` within the pop-up it will exit and leave this artifact on the screen.

**Comment by glepnir** [comment]
`space` ? there is no keymap in finder window with space. I can't reproduce
![images](https://user-images.githubusercontent.com/41671631/186869665-9b141e29-b125-4421-ad5a-63d0f1e1f99f.gif)

**Comment by guilhermedeandrade** [comment]
> there is no keymap in finder window with space

I know, after you talked about `finder_action_key` I realized that. However, before knowing it I tried to open using `space` and it would always leave an artifact on the screen. It still does as I said.

![Kapture 2022-08-26 at 11 00 37](https://user-images.githubusercontent.com/8797405/186880038-e65c6068-0d93-454e-99bd-2ad70ad4c177.gif)

**Comment by glepnir** [comment]
what are you doing? just open lspsaga lsp_finder then use j/k to move  , use `q` to close

**Comment by guilhermedeandrade** [comment]
> what are you doing? just open lspsaga lsp_finder then use j/k to move , use `q` to close

Basically, using `space` instead of `o`, which is the correct thing to do, since I'm using the default config. I'd ask you to read the rest of the comment though.

As I said, after you told me about the `finder_action_key` I realized that `space` isn't the key to be used to open a file. However, when I use `space` this weird thing happens: it leaves an artifact on the screen.

Now I'm using the default mapping which is `o` to open a file. But in this clip I used `space` on purpose to show you what happens and why I opened the issue in the first place.

Sorry if I wasn't clear.

**Comment by glepnir** [comment]
when you in finder window . `:verbose <space>` to check your space map.

**Comment by guilhermedeandrade** [comment]
> when you in finder window . `:verbose <space>` to check your space map.

`E21: Cannot make changes, 'modifiable' is off`

**Comment by glepnir** [comment]
input this in cmdline to check your space map

**Comment by guilhermedeandrade** [comment]
Didn't understand what you mean, sorry.

**Comment by glepnir** [comment]
start  lspsaga lsp_finder. then cursor in finder window. press`:` the cursor in cmdline then input `verbose <space>` press <CR>

**Comment by guilhermedeandrade** [comment]
That's what I did and this is returned `E21: Cannot make changes, 'modifiable' is off`

**Comment by glepnir** [comment]
![images](https://user-images.githubusercontent.com/41671631/186908315-60301dbe-428f-48ed-b656-e9a28b1b0820.gif)

**Comment by guilhermedeandrade** [comment]
<img width="1840" alt="image" src="https://user-images.githubusercontent.com/8797405/186913760-40dcd242-f7f9-4056-ae7f-db43febeeb08.png">

**Comment by glepnir** [comment]
so your space is bind to <c-w> w
