### ISSUE TITLE
Highlight result in LspSaga Floating windows

### ISSUE THREAD

**Issue by NEX-S** [glepnir/lspsaga.nvim#465]
Can we set the options that can let lspsaga's floating highlight the result?
For example, if I want to know where the variable `my_variable` defined, when I use lspsaga's preview definition, I wish to see the highlighted `my_variable` in a floating window (or add the underline to make it more clear)

![image](https://user-images.githubusercontent.com/97107165/187089132-e9102a1b-ed96-4f43-9be5-d4eb51d82381.png)

**Comment by glepnir** [comment]
I think this is relate your colorscheme .it make lots of highlight not stickout .  if you in 0.8 set another colorscheme namespace in `finder_preview_hl_ns` .highlight `TSVariable underline = true` maybe can work .

**Comment by NEX-S** [comment]
Sorry, I dont know what is the colorscheme namespace is ... I have read the saga's source code for `finder_preview_hl_ns` and try to use `finder_preview_hl_ns = { bg = "#000000", fg = "#ffffff", bold = false, italic = false }` in config, but nvim got error for can't compare number with table :(

**Comment by glepnir** [comment]
```lua

local my_ns = api.nvim_create_namespace('another_colorscheme')

api.nvim_set_hl(my_ns,'TSvariable', {fg = 'color',underline = true})

finder_preview_hl_ns = my_ns
```

**Comment by NEX-S** [comment]
thanks :D

**Comment by NEX-S** [comment]
Ohhhh, it's work!!! but seems in definition preview window it's not work lol, I am thinking if we can use regex to search the var only in floating window to avoid the set another highlight group, is that possible?

**Comment by glepnir** [comment]
no need use symatch in preview buffer and parse everyline . very trouble some. 

I don't set this option work in preview window.
