### ISSUE TITLE
CMD ':bp' will cause lspsaga's lsp_finder bug

### ISSUE THREAD

**Issue by NEX-S** [glepnir/lspsaga.nvim#466]
If I use lspsaga's finder and use cmd `bp/bn` in finder window, then :
![image](https://user-images.githubusercontent.com/97107165/187089315-4d968e60-f1cf-4c62-994b-01ade5fb239e.png)

If I use :q to quite the window, the preview window will not disappear and cursor will leave in that window.

![image](https://user-images.githubusercontent.com/97107165/187089358-2992b8da-3180-439b-96b6-7aa261c1f098.png)

**Comment by NEX-S** [comment]
这个issue触发有点刁钻，我也是不小心按到了切换buffer的快捷键然后触发了这个问题

**Comment by NEX-S** [comment]
![image](https://user-images.githubusercontent.com/97107165/187089472-dd45a648-abb4-4f26-8203-83c1fff1da9e.png)
this floating will not disappear too.

**Comment by NEX-S** [comment]
Seems still there...

https://user-images.githubusercontent.com/97107165/187169836-8ea77bb1-f075-4a92-8b96-79239bf0cec0.mp4

**Comment by glepnir** [comment]
> If I use :q to quite the window, the preview window will not disappear and cursor will leave in that window.

It just fix this behavior.
