### ISSUE TITLE
how to change LSOutLine highlight and icons

### ISSUE THREAD

**Issue by NEX-S** [glepnir/lspsaga.nvim#467]
my config
![image](https://user-images.githubusercontent.com/97107165/187090077-a14db082-6252-41c3-92cb-865c407798e3.png)

my highlight
![image](https://user-images.githubusercontent.com/97107165/187090138-411b6eef-5aec-4506-bb96-46d155390bcc.png)

seems in LSOutLine it dont take any effect :(
![image](https://user-images.githubusercontent.com/97107165/187090148-00ad85e4-5fac-4dcf-830e-a54b164d11dd.png)

btw, i wish my LSOutline can be like this
![image](https://user-images.githubusercontent.com/97107165/187090175-a8593112-2d85-4d61-b09a-55cb1712e8a3.png)

how to config can make these field... dont show up? Thanks! :D

**Comment by glepnir** [comment]
can't reproduce it works for me .you don't need config the winbar highlight . `custom_lind` also effect it 
![image](https://user-images.githubusercontent.com/41671631/187096275-182f9f0e-cc0f-4613-940b-5486736497fb.png)

**Comment by NEX-S** [comment]
I dont know why it's working now, but how to config LSOutLine can make these `field string = ...` stuff hide, I think it's little annoying for me lol

**Comment by NEX-S** [comment]
and :q will leave LSOutLine in the buffer, maybe can add a config that autoclose with buffer exit?
