### ISSUE TITLE
Lsp_finder throws error in svelte files

### ISSUE THREAD

**Issue by mpiorowski** [glepnir/lspsaga.nvim#468]
### Description
lsp_finder throws error when trying to go to selected files

Should move me to the file

I am using the "o" key to go to the definition and then i get this error.

![image](https://user-images.githubusercontent.com/26543876/187092928-d0c75fd8-c9f8-4d95-b4df-04bfaa2935ee.png)

@glepnir i see You fixed my previous issue, amazing work :) Thaks for this plugin btw.

But i cannot download the new version of Your fix.

**Comment by glepnir** [comment]
> But i cannot download the new version of Your fix.

Hmm Why you can't download.

can you show me some svelte code  that can reproduce this.

**Comment by longlhh90** [comment]
I got the same issue in lua, typescript/javascript, and python (I think all of the lsp servers but I just tried these 3. 
I'm using lspconfig and nvim-lsp-installer to install and setup server, null-ls for diagnostics and formatting
![Recording 2022-08-28 at 17 12 38](https://user-images.githubusercontent.com/58371075/187098614-e262a529-661a-4087-953c-035426bfa6df.gif)
)
