### ISSUE TITLE
`max_preview_lines` affect finder's columns not the lines

### ISSUE THREAD

**Issue by NEX-S** [glepnir/lspsaga.nvim#472]
https://user-images.githubusercontent.com/97107165/187172590-374d826b-a891-4d7a-aadf-717234f369d0.mp4

maybe we need an options that can control definition_preview window and finder window's size? like
```
preview_window_size = {
    column = 40,
    lines = 20
}
```

**Comment by glepnir** [comment]
It will adapt to the height and width of the current window according to the length and width of the content. Customization is not supported.
