### ISSUE TITLE
Large floating windows are not truncated vertically

### ISSUE THREAD

**Issue by akinsho** [glepnir/lspsaga.nvim#48]
Thanks for the great work on this plugin 🚀 

Ive noticed whilst trying it out that when I hover over something with a lot of information the windows don't seem to have safe default limits and in the case of the vertical size, the height isnt truncated if there is too much content like in the example below, it overlaps with my tabline and statusline in this case

![image](https://user-images.githubusercontent.com/22454918/106366633-17e17480-6335-11eb-80de-285a95d29fdc.png)

**Comment by glepnir** [comment]
yep we can runcated vertically but need a smart height value to do that.

**Comment by akinsho** [comment]
@glepnir I think
```lua
-- As an example I think 80% of the "safe area" is a good default
local max_size = (vim.o.rows - vim.o.cmd_height - (statusline_size_is_one) - (tabline_height_is_one)) * 0.8
```

**Comment by akinsho** [comment]
The 80% is arbitrary but you get the idea aka it should not eat into other vim UI like tabline and statusline and tbh even then I dont think it's useful for it to take up *all* of the "safe" vertical height I think it should still only be a proportion of the vertical axis with the that space

**Comment by glepnir** [comment]
and then we need support scroll in doc float window.

**Comment by akinsho** [comment]
Tbh I think this is needed anyway since even with the current behaviour as you can see with my screenshot it still isn't guaranteed you will be able to fit all the content into the window

**Comment by glepnir** [comment]
yep . now I had rewrite the width in my local .

**Comment by glepnir** [comment]
how about this
![image](https://user-images.githubusercontent.com/41671631/106383446-f9e14600-6400-11eb-8e2d-3aca696fb32e.png)
