### ISSUE TITLE
Hover docs using old key mapping to scroll

### ISSUE THREAD

**Issue by Avimitin** [glepnir/lspsaga.nvim#481]
### Description

I have set the new key mapping for scrolling in the setup function, however the lspsaga is still using old default value.

```lua
saga.init_lsp_saga({
    scroll_in_preview = {
      scroll_down = "<C-d>",
      scroll_up = "<C-u>",
    },
  })
```

- result for command: `lua =require("lspsaga").config_values`

![image](https://user-images.githubusercontent.com/30021675/187651020-85fec915-ad02-4c03-b1d0-83a0751453e2.png)

- mappings

![image](https://user-images.githubusercontent.com/30021675/187651316-9952438f-7553-4183-9944-64ef534cb2ca.png)

**Expected Behavior**

**Actual Behavior**

**Neovim Built in Behavior**

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 

```text
NVIM v0.8.0-dev-984-g568737d5b3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -flto=auto -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-git/src/build/cmake.config -I/build/neovim-git/src/neovim-git/src -I/usr/include -I/build/neovim-git/src/build/src/nvim/auto -I/build/neovim-git/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

- Operating system: 
- lspsaga commit: master HEAD 

</details>

**Comment by glepnir** [comment]
looks like your plugin neoscroll rewrite it .

**Comment by Avimitin** [comment]
However there is no <C-u> key mapping presenting. What I want is lspsaga map the ctrl-u key.

**Comment by Avimitin** [comment]
`:map <C-u>`

![image](https://user-images.githubusercontent.com/30021675/187659468-879fe85d-488e-4703-8a68-86501a21a0f6.png)
