### ISSUE TITLE
maybe float term should add `resume / open new` options?

### ISSUE THREAD

**Issue by NEX-S** [glepnir/lspsaga.nvim#484]
1. Resume last float term
2. Open new float term

reason:
If we can only open one float term and compile a big program in it, that mean we're have to wait until that job is done and can not exit nvim, so maybe we need a new cmd to resume last float term or open a new float term.

If there are more than 2 floating term in the background, saga should ask user to resume which float term.

:D

**Comment by glepnir** [comment]
this is not floaterm plugin . it's lsp plugin
