### ISSUE TITLE
Definition preview window hl problem

### ISSUE THREAD

**Issue by NEX-S** [glepnir/lspsaga.nvim#485]
### Description
![image](https://user-images.githubusercontent.com/97107165/187742069-dbc90662-ce88-4f34-b6d6-6a8dbe198f62.png)
![image](https://user-images.githubusercontent.com/97107165/187742772-60aa7f7d-5662-4f3d-af03-029e139d10d1.png)

**Expected Behavior**
File: meta -----------> m should in hl

**Actual Behavior**
File: meta -----------> m is not in hl

**Comment by glepnir** [comment]
because treesitter work on this buffer
