### ISSUE TITLE
LSOutLine highlight is not work

### ISSUE THREAD

**Issue by NEX-S** [glepnir/lspsaga.nvim#494]
### Description
LSOutLine highlight is not work with this config, only work in we manual hl it in cmdline
```lua
...
vim.api.nvim_set_hl(0, "LSOutLineProperty",      { bg = "NONE", fg = "#6a5a9d" })
vim.api.nvim_set_hl(0, "LSOutLineField",         { bg = "NONE", fg = "#666666" })
vim.api.nvim_set_hl(0, "LSOutLineConstructor",   { bg = "NONE", fg = "#666666" })
vim.api.nvim_set_hl(0, "LSOutLineEnum",          { bg = "NONE", fg = "#666666" })
vim.api.nvim_set_hl(0, "LSOutLineInterface",     { bg = "NONE", fg = "#666666" })
vim.api.nvim_set_hl(0, "LSOutLineFunction",      { bg = "NONE", fg = "#ffffff", italic = true })
...
```

**Expected Behavior**
hl work normal

**Actual Behavior**
LSOutline hl will only work when we manual exec `lua vim.api.nvim_set_hl(0, "LSOutLineFunction" ...` in cmd line

https://user-images.githubusercontent.com/97107165/188243671-9e1defee-cd9a-423d-87a8-fa5b3e41eada.mp4

**Comment by glepnir** [comment]
you must make these function run after you open outline
