### ISSUE TITLE
{ LSOutline } server not support [ textDocument/documentSymbol ]

### ISSUE THREAD

**Issue by RAprogramm** [glepnir/lspsaga.nvim#498]
LspInfo said "`O clients attached to this buffer`" and "`2 active client not attached to this buffer`".
this i get when i ma in outline, but is is working (every time cursor moved in outline i had this message).
i am understand that in outline buffer there are no lsp clients, but how i cat fix that or remove notify message?

**Comment by glepnir** [comment]
can you provide a step that reproduce it?

**Comment by RAprogramm** [comment]
i just make a command `:LSOutlineToggle`. then winbar is hide and open the outlinebar in left side, cursor is in outline bar and notify make about 'server not support...'

**Comment by glepnir** [comment]
oh .which filetype ?

**Comment by RAprogramm** [comment]
**.lua**, but i just tested **.py** - same situation

**Comment by RAprogramm** [comment]
i think it because outline buffer not linked to lsp server of opened main file. it is possible?

**Comment by glepnir** [comment]
a simple patch to disable it in lspsagaoutline filetype. I will improve outline in 0.2.2 version. will publish after three day.

**Comment by RAprogramm** [comment]
thank you, i admire your work.
in future i will be a good developer like you

**Comment by glepnir** [comment]
you  always a good programer :)
