### ISSUE TITLE
Range Code Action key map doesn't work.

### ISSUE THREAD

**Issue by LimbicSys** [glepnir/lspsaga.nvim#499]
### Description

The keymap `keymap("v", "<leader>ca", "<cmd><C-U>Lspsaga range_code_action<CR>", { silent = true })` in readme file doesn't work and get `E492: Not an editor command: ^ULspsaga range_code_action `

Change the `<CMD>` to `:` can make it work.
**Expected Behavior**

**Actual Behavior**

**Neovim Built in Behavior**

### Details
Neovim version: 0.7.2

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: 
- lspsaga commit: 

</details>

**Comment by glepnir** [comment]
make sure you had load lspsaga plugin.

**Comment by LimbicSys** [comment]
The same keymap in normal mode is ok. So the plugin should be loaded.

**Comment by glepnir** [comment]
`<C-u><Cmd>` should be work I think

**Comment by glepnir** [comment]
@LimbicSys  should be `keymap("v", "<leader>ca", "<cmd>Lspsaga range_code_action<CR>", { silent = true })` readme is wrong .I will update it.

**Comment by LimbicSys** [comment]
> @LimbicSys should be `keymap("v", "<leader>ca", "<cmd>Lspsaga range_code_action<CR>", { silent = true })` readme is wrong .I will update it.

Using `<cmd>` only will not change the mode to normal.
<img width="384" alt="图片" src="https://user-images.githubusercontent.com/30319215/188300786-7099d79a-8b91-48b4-bb14-4251234e9022.png">

**Comment by LimbicSys** [comment]
It seems that `<CMD>` is not a simple pseudokey of `:`.

**Comment by glepnir** [comment]
![images](https://user-images.githubusercontent.com/41671631/188300854-d5d790c5-1705-4ad8-812d-1980452e5869.gif)

**Comment by glepnir** [comment]
```
:verbose vmap ga

x  ga          * <Cmd>Lspsaga range_code_action<CR>                                                                                                                                          
        Last set from Lua   
```

**Comment by glepnir** [comment]
hmm test with `:<C-u>Lspsaga range_code_action` this works fine.
