### ISSUE TITLE
feat: enhance hover doc format

### ISSUE THREAD

**Issue by elianiva** [glepnir/lspsaga.nvim#50]
Hi there! Is it possible to make the first row on the hover doc to be multiple lines? eg.

![image](https://user-images.githubusercontent.com/51877647/106376188-5757a180-63c5-11eb-8ece-d7de891d0e94.png)

I expect the first separator line to get placed at the line where that is marked with a red line. This is causing some issue when it doesn't have enough space until the `{` symbol so the highlight got messed up. Here's an example

![image](https://user-images.githubusercontent.com/51877647/106376287-6be86980-63c6-11eb-83bc-e60c172ef879.png)

Thanks in advance!

**Comment by glepnir** [comment]
May be is a bug, it should not be insert  the truncated line  to index 2. fixed it later.

**Comment by elianiva** [comment]
I have this config for lspsaga. 

```lua
require"lspsaga".init_lsp_saga({
  max_hover_width = 80,
  border_style = 1,
  use_saga_diagnostic_handler = false,
  use_saga_diagnostic_sign = false
})
```

Then hover to any javascript function that has a long documentation like `filter`, `map`, etc.

**Comment by glepnir** [comment]
can provide a min js code? like your bug pic function `readdirSync`

**Comment by glepnir** [comment]
Aha I know what happen. because you set the max_hover_width so the length of first line will be wraped..

**Comment by elianiva** [comment]
Is it possible to make it work even if I set the `max_hover_width`? I don't really like when the hover popup being so wide when the content inside it is really long.

**Comment by glepnir** [comment]
I am thinking about it.  I want we can have a smart height and width. not a fix number that this way can't works fine with any window size.

**Comment by glepnir** [comment]
@elianiva  Now works like this in my local 

![image](https://user-images.githubusercontent.com/41671631/106383016-35c6dc00-63fe-11eb-9ad2-9947990458b0.png)

**Comment by elianiva** [comment]
That looks great!

**Comment by glepnir** [comment]
yep. now I want to make a smart width and height value not depend max_hover_width or smomething

**Comment by elianiva** [comment]
agree, that would be ideal
