### ISSUE TITLE
Jump and show diagnostics does not work.

### ISSUE THREAD

**Issue by Fausto-Korpsvart** [glepnir/lspsaga.nvim#506]
### Description
Jump and show diagnostics does not work.
![saga](https://user-images.githubusercontent.com/47998118/189455717-3244a623-d34b-4488-898b-dfa54151e519.png)

**Expected Behavior**
Jump between different LSP diagnoses

**Actual Behavior**
Pressing the key combination throws the error shown in the screenshot.

### Details

- nvim --version output: v0.8.0-dev+1027-g4bf005e9f
- Operating system: Fedora
- lspsaga commit: Latest commit, after the update to version 2.2

**Comment by glepnir** [comment]
looks like get saga code_action keymap failed. you don't use lspsga codeaction right?

**Comment by Fausto-Korpsvart** [comment]
> 

Actually I had the default configuration of LSP Saga and the only thing I had changed was the Saga keymaps, but with the new update it's already fixed, thanks.
