### ISSUE TITLE
attempt index local 'client'  (a nil value)

### ISSUE THREAD

**Issue by cathaysia** [glepnir/lspsaga.nvim#507]
When a code action be availabile, then the first call code action will has a error message: attempt index local 'client'  (a nil value)

But when I call it once, it works.

https://user-images.githubusercontent.com/42114817/189460999-2f05f80e-afa7-4cd1-a436-7fd7523178e6.mp4

**Comment by glepnir** [comment]
this is only happened in 0.2.2 version ? it works fine fore me

**Comment by glepnir** [comment]
may be fixed now.

**Comment by cathaysia** [comment]
This morning I switched from the fork branch to this repository, and this bug already exists. It was still there when we tested it today. But when I just changed the load order of the plug-in and re-executed PackerSync, the bug disappeared. But I don't know why.

**Comment by glepnir** [comment]
oh It's wired .if you still get this error I will reopen and add a debug print for you. then we will know what happened maybe .
