### ISSUE TITLE
Error showing after update plugin

### ISSUE THREAD

**Issue by katinbox** [glepnir/lspsaga.nvim#511]
### Description

![Screenshots_2](https://user-images.githubusercontent.com/43630437/189510473-3c59a912-54f0-4b70-9ae3-ca2fa4cd6789.png)

Commit: https://github.com/glepnir/lspsaga.nvim/commit/43b80d7a4515a25aa3a485acb60a517ec27820d2
**Expected Behavior**

**Actual Behavior**

**Neovim Built in Behavior**
neovim 0.8

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: 
- lspsaga commit: 

</details>

**Comment by glepnir** [comment]
@katinbox  `defintion_preview_icon` had removed. so you should remove it.

**Comment by katinbox** [comment]
I just removed and error gone! Tks
