### ISSUE TITLE
attempt to call a nil value in command.lua

### ISSUE THREAD

**Issue by toomuat** [glepnir/lspsaga.nvim#513]
### Description
I got an error of lspsaga when I press CTRL+K in live grep in telescope.nvim.
CTRL+K doesn't make any sense and doesn't affect the operation of telescope, but I'm reporting it just in case.

**Expected Behavior**

**Actual Behavior**
![lspsaga_error](https://user-images.githubusercontent.com/32962031/189527929-67012801-a963-4c43-b9cc-8f7a4119ab9d.png)

### Details

- nvim --version output: 
NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
- Operating system: WSL2 Ubuntu 20.04
- lspsaga commit: 1cffa99684db5a149baa6cc3fabe555bfd889635

**Comment by glepnir** [comment]
I think you need check your config with keymap. lspsaga only work with lsp server .it not affect telescope

**Comment by toomuat** [comment]
I don't know what caused the error, but the error is gone by checking nil.

```diff
diff --git a/lua/lspsaga/command.lua b/lua/lspsaga/command.lua
index a9c80aa..0fd474f 100644
--- a/lua/lspsaga/command.lua
+++ b/lua/lspsaga/command.lua
@@ -53,7 +53,9 @@ function command.load_command(cmd, ...)
   if next(args) ~= nil then
     subcommands[cmd](args[1])
   else
-    subcommands[cmd]()
+    if subcommands[cmd] ~= nil then
+      subcommands[cmd]()
+    end
   end
 end
```

**Comment by glepnir** [comment]
you set an already removed command in your config ?

**Comment by toomuat** [comment]
I don't know what the removed command refers to.
My Neovim setup was just created yesterday using the following famous ? config and settings are same, so I don't think I'm doing anything weird
https://github.com/craftzdog/dotfiles-public/tree/master/.config/nvim

**Comment by glepnir** [comment]
`vim.keymap.set('i', '<C-k>', '<Cmd>Lspsaga signature_help<CR>', opts)`

**Comment by glepnir** [comment]
so I think you need check your config

**Comment by toomuat** [comment]
Uh, okay. You were right.
Looks like I was using the deleted command you mentioned.
Thank you very much.
