### ISSUE TITLE
`preview_definition` and `preview_definition` doesn't work when in a Elixir project

### ISSUE THREAD

**Issue by scottming** [glepnir/lspsaga.nvim#516]
### Description
When in the Elixir project, `preview_definition` and `preview_definition` doesn't work. Sometimes we found the References, sometimes not, but always can not find the Definition.

**old versoin**: 37bb464d55ba068ad14befd048c82cef007cea4d
<img width="635" alt="image" src="https://user-images.githubusercontent.com/12830256/189555055-8a9fa145-4802-47e4-91c2-c183999b5312.png">

**last version**: 2ee8b5b
<img width="912" alt="image" src="https://user-images.githubusercontent.com/12830256/189558402-6987ac0f-003c-4600-acf0-da267fb8a075.png">

**Expected Behavior**

can find the definition and preview the definition.

**Actual Behavior**

 `preview_definition` and `preview_definition` doesn't work

**Neovim Built in Behavior**

https://github.com/elixir-lsp/elixir-ls

and the `lua vim.lsp.buf.definition()` worked very well

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
  ```
  call plug#begin()
    Plug 'neovim/nvim-lspconfig'
    Plug 'glepnir/lspsaga.nvim', { 'branch': 'main' }
  call plug#end()
  
  lua << EOF
  local on_attach = function(client, bufnr)
    local bufopts = { noremap=true, silent=true, buffer=bufnr }
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, bufopts)
    vim.keymap.set("n", "gp", "<cmd>Lspsaga peek_definition<CR>", bufopts) 
    vim.keymap.set("n", "gh", "<cmd>Lspsaga lsp_finder<CR>", bufopts)
  end
  
  require('lspconfig').elixirls.setup {
    cmd = { "/Users/scottming/.local/share/nvim/lsp_servers/elixir/elixir-ls/language_server.sh" },
    on_attach = on_attach,
  }
  EOF
  ```
modify the cmd folder `/Users/scottming/` with your $HOME folder.

2. post your program language min code snippet that can reproduce your issue
  * install elixir
  * run `mix new demo` create a elixir project
  * compile the project with `mix compile`
  * Open the `test/demo_test.exs` file, install elixirlsp with `:LspInstall elixirls`, and find the function `Demo.hello()` cursor then type `gh` or `gp`
</details>

<details><summary>Environment</summary>

- nvim --version output: 
  ```
  NVIM v0.8.0-dev-896-g1a57cd383-dirty
  Build type: RelWithDebInfo
  LuaJIT 2.1.0-beta3
  ```
- Operating system: macos 12.5.1
- lspsaga commit: 2ee8b5b

</details>

**Comment by glepnir** [comment]
please check changelog. use `peek_definition` instead

**Comment by scottming** [comment]
Hello, @Raphael. Thank you for your quick reply, but I've already used the `peek_definition`, and it doesn't work.

**Comment by glepnir** [comment]
I think your at is wrong . should be my github id.  I had a patch for peek_defintion try it now.

**Comment by scottming** [comment]
Hi, @glepnir , I've tried your patch

currently, `peek_definition` will show nothing, and `lsp_finder` still raise error:

<img width="801" alt="image" src="https://user-images.githubusercontent.com/12830256/189563416-aa5d4352-bfb7-499e-a943-29ebc292b15d.png">

**Comment by glepnir** [comment]
the server not return uri ?

**Comment by scottming** [comment]
> the server not return uri ?

**Comment by scottming** [comment]
> the server not return uri ?

**Comment by glepnir** [comment]
```lua
init_lsp_saga({ degbug_print = true})
```
then use peek_definition it will output the results post it to there

**Comment by scottming** [comment]
```lua
Error executing vim.schedule lua callback: vim/_editor.lua:0: Chunk is not an array with one or two strings
stack traceback:
        [C]: in function 'nvim_echo'
        vim/_editor.lua: in function 'notify'
        ...ack/packer/start/lspsaga.nvim/lua/lspsaga/definition.lua:65: in function 'callback'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1939: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1371: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue
```

**Comment by glepnir** [comment]
my mistake should be work now.

**Comment by scottming** [comment]
it give me this:

```lua
{ {
    result = {
      range = {
        end = {
          character = 6,
          line = 14
        },
        start = {
          character = 6,
          line = 14
        }
      },
      uri = "file:///Users/scottming/Code/demo/lib/demo.ex"
    }
  } }
```

**Comment by glepnir** [comment]
not a normal response like other servers response . please test it with last commit.

**Comment by scottming** [comment]
@glepnir 

It raises error now

<img width="966" alt="image" src="https://user-images.githubusercontent.com/12830256/189567634-6b4693f5-9bc2-48ba-88cd-7a91d735daff.png">

**Comment by glepnir** [comment]
hmm if you post the response is correct now should work ..

**Comment by scottming** [comment]
@glepnir It works now, thank you so much.
<img width="765" alt="image" src="https://user-images.githubusercontent.com/12830256/189569492-d6a31732-4cd6-4eaa-8c6e-ec22f154bd1d.png">

**Comment by glepnir** [comment]
okay then I will fix it in finder later.

**Comment by glepnir** [comment]
the correct response like other server should
{
  { 
         result = {{
             uri = xx
      } }
  }
}

**Comment by scottming** [comment]
> .so this server is special.

Yes, I agree with you, but [this](https://github.com/elixir-lsp/elixir-ls) is the only lsp in our Elixir community
