### ISSUE TITLE
Code action improvements

### ISSUE THREAD

**Issue by smjonas** [glepnir/lspsaga.nvim#518]
There are a few things that I think can be improved for `:Lspsaga code_action`:
1. the lightbulb will always be shown, regardless of where the cursor position is within a line:
**Current behavior:**

![image](https://user-images.githubusercontent.com/40792180/189886852-60fee32f-8e39-4ac7-b6f9-b4d4d0d4c965.png)

**Expected behavior:** 

The code action for `[1] Add import:: "io"` should only be shown when above  the `io` identifier. This is how VSCode behaves.

---

2. add option to filter code action items based on their kind
- **Current behavior:**

All code actions are shown when using `:Lspsaga code_action` regardless of the `kind` (both `quickfix` and `source.organizeImports`).

- **Expected behavior:** It would be nice to be able to filter them, e.g. only show `quickfix` and not global code actions such as `organizeImports`.

---

3. E.g. the Golang LSP server can send additional diagnostics for an error. It would be nice to show them in Lspsaga's window.
Example response:
```
 diagnostics = {
  {
    code = "UndeclaredName",
    codeDescription = {
      href = "https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source=gopls#UndeclaredName",
    },
    message = "undeclared name: io",
    range = {
      ["end"] = {
        character = 14,
        line = 92,
      },
      start = {
        character = 12,
        line = 92,
      },
    },
    severity = 1,
    source = "compiler",
  },
}                 
```
This is how VSCode shows this info:
![image](https://user-images.githubusercontent.com/40792180/189888255-0163641e-845d-4948-b067-cfd8365b506c.png)

---

Do you think these are improvements that you want to include in your plugin?

**Comment by glepnir** [comment]
I will accept any suggestion for improvement. My aim is to make lspsaga have a great ui. Have you used lspsaga's diagnostic yet. I also looked at vscode for this behavior. I think he is showing the behavior of the diagnosis and not the codeaction right? I implement it in jump diagnostic.
![image](https://user-images.githubusercontent.com/41671631/189889578-c4061d83-5320-4a42-b3cc-a3bb8148f665.png)

about lightbulb .seems like jump to floatwindow it's disappear. if not it always in.  I will fix it later.

> add option to filter code action items based on their kind

why not !! good catch.

**Comment by glepnir** [comment]
there will have a new ui because I am implement title in border in upstream now .   It's done right away. Need to write some test code.
![image](https://user-images.githubusercontent.com/41671631/189890368-e45d2e05-3df9-45e0-9932-14a8759435e9.png)

**Comment by smjonas** [comment]
> Have you used lspsaga's diagnostic yet

I haven't, thank you - that looks really nice! 

>  I think it is showing the behavior of the diagnosis and not the codeaction right? I implement it in jump diagnostic.

Yes, I think it would be nice to show the code action and diagnostic information combined so users can fix it immediately. (for me ` the `QuickFixKey: ga` text is not shown so I can't run the code action directly)

**Comment by glepnir** [comment]
right if there has diagnostic when jump it  we can show diagnostic and codeaction. then quick fix not press another shortcut.
