### ISSUE TITLE
lsp_finder loading animation stuck

### ISSUE THREAD

**Issue by YuCao16** [glepnir/lspsaga.nvim#519]
### Description
When I using clangd with big package such as libtorch, if I move cursor to type alias such as int64_tor size_t, loading bar will stuck at ('█▁▁▁▁▁▁▁▁▁',) and took several seconds to load. I have set finder_request_timeout = 2000 but doesn't help. 
In my case, It takes around 5 seconds to load (longer than `finder_request_timeout`), then `lsp_finder` window will appear. But if I switch window (`<c-w>`*2) during it processing, the preview window will stay (won't disappear unless move cursor to it and quit).
### Details

<details><summary>Reproduce</summary>

1. nvim test.cpp
2. You need a big package to reproduce such as libtorch
3. Move cursor to a variable typed `int64_t` and run `Lspsaga lsp_finder`
</details>

<details><summary>Environment</summary>

- nvim --version output: 
NVIM v0.8.0-dev-1071-gf98cff957
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
- Operating system: 
Ubuntu 22.04
- Terminal
kitty 0.26.2 created by Kovid Goyal

</details>

**Comment by glepnir** [comment]
okay . I will take a look at it. thanks for report.

**Comment by YuCao16** [comment]
> okay . I will take a look at it. thanks for report.

Thanks, If you need any debugging files or logs, please feel free to contact me.
