### ISSUE TITLE
show_line_diagnostics truncates aggressively?

### ISSUE THREAD

**Issue by mikatpt** [glepnir/lspsaga.nvim#527]
### Description

hi glepnir! Glad you are back and feeling better. I just migrated over from tami5's fork, noticed that `show_line_diagnostics` now truncates to one line per diagnostic. Is there any way we could make this configurable? Would be nice to see more than one line per error - most rust errors are multiline by design.

thank you!

Example:
```rs
fn main() {
    println!("hey world.");

    let a = 5;
    let b: String = 5.into(); // run Lspsaga here.
}
```

Output of `Lspsaga show_line_diagnostics`:
![image](https://user-images.githubusercontent.com/67210789/190922269-cf27cdef-ae8b-4a8e-9267-adeca64d3551.png)

Output of `Lspsaga diagnostic_jump_next`
![image](https://user-images.githubusercontent.com/67210789/190922285-727848c6-9dfc-48a9-a595-659caeb56746.png)

**Expected Behavior**

**Actual Behavior**

**Neovim Built in Behavior**

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

- Operating system: 
windows 10 wsl2 ubuntu 20.04
- lspsaga commit: 
c2ef011
</details>

**Comment by glepnir** [comment]
I will take a look at this behavior later.

**Comment by tobealive** [comment]
experiencing the same behavior in rust

`Lspsaga show_line_diagnostics` :
![Screenshot_20220927_204127](https://user-images.githubusercontent.com/34311583/192609878-4895fb65-ef00-4a50-91c4-3611c07f6603.png)

vs 

`Lspsaga diagnostic_jump_next`
![Screenshot_20220927_204143](https://user-images.githubusercontent.com/34311583/192609921-fe5b84b7-36cb-407a-8cac-1ee065a024c9.png)

**Comment by glepnir** [comment]
okay .when the 0.8 release I will do some update on lspsaga.
