### ISSUE TITLE
Cursor moving to the top of the buffer after saving/formatting 

### ISSUE THREAD

**Issue by patrykwegrzyn** [glepnir/lspsaga.nvim#528]
### Description
When i edit the same buffer in `peek_definition` prompt and save , cursor move to the top of the screen.
I'm not sure if this is ` lspsaga` related but i do not seems to have this behaviour elsewhere.

**Expected Behavior**
Cursor to stay in the same position :

**Actual Behavior**
Cursor move to top of the buffer

**Neovim Built in Behavior**
none

### Details

Steps to reproduce
Use Code `Test.tsx`
```javascript
import {StyleSheet, View} from 'react-native';

const Test = () => {
  const arr = Array.from(Array(5));
  return (
    <View style={styles.colors}>
      {arr.map(el => {
        // return <View key={el} style={{...styles.color}} />;
        return <View key={el} style={styles.color} />;
      })}
    </View>
  );
};

const styles = StyleSheet.create({
  colors: {
    //
    alignItems: 'center',
    justifyContent: 'space-around',
    flexDirection: 'row',
  },
  color: {
    borderRadius: 50,
    height: 30,
    width: 30,
  },
});

```

Replace return statement with 
```javascript
return <View key={el} style={{...styles.color}} />;
```
the issue seems to be with `style={{...styles.color}}` once replaced with `style={styles.color}` cursor stay in the correct position

 Environment Information 

```nvim --version
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
```

```
uname -a
Linux dev 5.19.7-arch1-1 #1 SMP PREEMPT_DYNAMIC
```

```
git log
commit c2ef0115fb917460daf5c76fe3ad3a9357213b54 (grafted, HEAD -> main, origin/main, origin/HEAD)
Author: Adelar da Silva Queiróz 
Date:   Fri Sep 16 20:41:25 2022 -0300

    Spelling corrections and changes (#526)
```
![lsps](https://user-images.githubusercontent.com/7962796/191069558-78f4cb6b-c74f-4525-a2c2-6c0168b29715.gif)

**Comment by glepnir** [comment]
typescript-language-server right?

**Comment by patrykwegrzyn** [comment]
> typescript-language-server right?
yes , im also using `null-ls` with `prettierd` for formatting if that helps

**Comment by patrykwegrzyn** [comment]
@NikolaM-Dev  thanks for the hint, i just tested it with prettier and i'm experiencing the same issue , would you mind to share your dot files or something that will point me to the right direction?

**Comment by patrykwegrzyn** [comment]
I have re done my config and everything works :D
