### ISSUE TITLE
Diagnostics border rendering is inappropriate

### ISSUE THREAD

**Issue by lisiur** [glepnir/lspsaga.nvim#529]
### Description

The diagnostics border rendering is inappropriate when I jump and show diagnostics:
![image](https://user-images.githubusercontent.com/15188817/191161798-481891bd-761c-46e5-ab9b-4326679a5148.png)

**Expected Behavior**

border should not be italic
**Actual Behavior**

border is italic
### Details

<details><summary>Reproduce</summary>

1. set highlight Diagnostic(Error|Warn|Info|Hint) with italic = true
</details>

<details><summary>Environment</summary>

- nvim --version output: v0.7.2
- Operating system: windows11
- lspsaga commit: c2ef0115fb917460daf5c76fe3ad3a9357213b54

</details>

**Comment by lisiur** [comment]
I found that border's hl are using LspSagaDiagnostic* definition which link to Diagnostic*.
Maybe we should use a separate highlight that extends Diagnostic* but with italic = false.

**Comment by glepnir** [comment]
you can rewrite the highlight `hi LspSagaDiagnosticError fg= red`
