### ISSUE TITLE
Default file icon for winbar files with no devicon

### ISSUE THREAD

**Issue by tobealive** [glepnir/lspsaga.nvim#530]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a default file icon in the winbar for files with unknown devicons. 

This would allow for better visual separation of filename and path for such files.

**Describe the solution you'd like**
If you like, I can submit a draft PR with a solution that allows specifying a default file icon in the config and would leave the current behavior as default.

**Describe alternatives you've considered**
I tried to implement a default file icon as a condition based on the return of `require('lspsaga.symbolwinbar').get_file_name()` which is not as easy and straightforward to me as a user.

**Comment by glepnir** [comment]
devicon provide an unknow icon that not work for you ?

**Comment by tobealive** [comment]
E.g., `.txt` files or files without an extension currently don't load an icon. This results in:
![no-icon](https://user-images.githubusercontent.com/34311583/191444827-0a8c4dd6-d16a-4520-b9bc-12c0261bb8ed.png)

Currently, I have hardcoded the fallback icon (``) that's also used in e.g., bufferline in the lspsaga repo on my local machine. Which results in:
![with-icon](https://user-images.githubusercontent.com/34311583/191446338-287804c2-b8eb-41a7-8bbc-0858b4da8a53.png)

The idea to make something like a `fallback_icon` configurable comes from [fgheng/winbar.nvim#configuration](https://github.com/fgheng/winbar.nvim#configuration)

**Comment by glepnir** [comment]
there has a default icon . looks like this not work.

https://github.com/kyazdani42/nvim-web-devicons/blob/master/lua/nvim-web-devicons.lua#L1542

**Comment by glepnir** [comment]
can you provide  your winbar config?

**Comment by tobealive** [comment]
> there has a default icon . looks like this not work.
https://github.com/kyazdani42/nvim-web-devicons/blob/master/lua/nvim-web-devicons.lua#L1542

Oh, I see. This shows that there actually really should be a default icon. Thanks for shedding light.

My config is based of the function you provide in the README. I tested it just now with explicitly the winbar config from the README with the same result. So it should be a good 'minimal' reproducible example.

```lua
-- Example:
local function get_file_name(include_path)
    local file_name = require('lspsaga.symbolwinbar').get_file_name()
    if vim.fn.bufname '%' == '' then return '' end
    if include_path == false then return file_name end
    -- Else if include path: ./lsp/saga.lua -> lsp > saga.lua
    local sep = vim.loop.os_uname().sysname == 'Windows' and '\\' or '/'
    local path_list = vim.split(string.gsub(vim.fn.expand '%:~:.:h', '%%', ''), sep)
    local file_path = ''
    for _, cur in ipairs(path_list) do
        file_path = (cur == '.' or cur == '~') and '' or
                    file_path .. cur .. ' ' .. '%#LspSagaWinbarSep#>%*' .. ' %*'
    end
    return file_path .. file_name
end

local function config_winbar_or_statusline()
    local exclude = {
        ['teminal'] = true,
        ['toggleterm'] = true,
        ['prompt'] = true,
        ['NvimTree'] = true,
        ['help'] = true,
    } -- Ignore float windows and exclude filetype
    if vim.api.nvim_win_get_config(0).zindex or exclude[vim.bo.filetype] then
        vim.wo.winbar = ''
    else
        local ok, lspsaga = pcall(require, 'lspsaga.symbolwinbar')
        local sym
        if ok then sym = lspsaga.get_symbol_node() end
        local win_val = ''
        win_val = get_file_name(true) -- set to true to include path
        if sym ~= nil then win_val = win_val .. sym end
        vim.wo.winbar = win_val
        -- if work in statusline
        vim.wo.stl = win_val
    end
end

local events = { 'BufEnter', 'BufWinEnter', 'CursorMoved' }

vim.api.nvim_create_autocmd(events, {
    pattern = '*',
    callback = function() config_winbar_or_statusline() end,
})

vim.api.nvim_create_autocmd('User', {
    pattern = 'LspsagaUpdateSymbol',
    callback = function() config_winbar_or_statusline() end,
})
```

copied from: https://github.com/glepnir/lspsaga.nvim#show-symbols-in-winbarnvim-08-or-in-statusline

**Comment by tobealive** [comment]
Found the crock in here. Until now, I didn't need an explicit setup in my config for devicons.
```lua
require 'nvim-web-devicons'.setup {
	default = true;
}
```
enables the default icon
