### ISSUE TITLE
There is no symbols in winbar(pyright, python)

### ISSUE THREAD

**Issue by RAprogramm** [glepnir/lspsaga.nvim#532]
### Description
No rendering winbar symbols for python filetypes.
But in outline is all good.

![winbar](https://user-images.githubusercontent.com/70325462/191488509-ba04cb0e-bc41-44ef-a4e7-d1fc7165cf66.png)
![outline](https://user-images.githubusercontent.com/70325462/191488532-a4fa44f5-9fed-48e9-81e6-d11e47f511c7.png)

NVIM v0.8.0-dev-1117-g7bd4c8e8e

in .lua files all good
![winbar_in_lua](https://user-images.githubusercontent.com/70325462/191489228-549375b8-d391-4495-8d7d-9a87c48b8b81.png)

**Comment by glepnir** [comment]
sorry I can't reproduce this with min config

![image](https://user-images.githubusercontent.com/41671631/191719573-1b5c64df-daa8-4f0c-9baa-8cefbb071ffe.png)

**Comment by RAprogramm** [comment]
does it possible because i have config like that?
in ~/.config/nvim/lua/plugins.lua
```
    use({
      'glepnir/lspsaga.nvim',
      branch = 'main',
      config = function() require('lsp.saga') end,
    })
``` 
and this file is in ~/.config/nvim/lua/lsp/saga.lua

previously it can not apply config on start and  i add this to my init.lua
```
do
  local install_path = vim.fn.stdpath('data')
    .. '/site/pack/packer/start/packer.nvim'
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({
      'git',
      'clone',
      'https://github.com/wbthomason/packer.nvim',
      install_path,
    })
    vim.cmd('packadd packer.nvim')
    require('plugins')
    require('packer').sync()
    vim.cmd('autocmd User PackerComplete ++once lua load_config()')
    vim.api.nvim_command('PackerCompile')
  else
    require('plugins')
    load_config()
    vim.api.nvim_command('PackerCompile')
  end
end
```
so after file PackerCompile config is apply.
here is config
```
local function outline_width() return vim.api.nvim_win_get_width(0) / 3 end

require('lspsaga').init_lsp_saga({
  border_style = 'rounded',
  saga_winblend = 20,
  move_in_saga = { prev = '<C-p>', next = '<C-n>' },
  diagnostic_header = {
    icon('x-circle'),
    icon('alert'),
    icon('info'),
    icon('light-bulb'),
  },
  max_preview_lines = 10,
  code_action_icon = '🪄 ',
  code_action_num_shortcut = true,
  code_action_lightbulb = {
    enable = false,
    sign = false,
    enable_in_insert = false,
    sign_priority = 20,
    virtual_text = false,
  },
  finder_icons = {
    def = '  ',
    ref = icon('cross-reference') .. ' ',
    link = icon('link') .. ' ',
  },
  finder_request_timeout = 1500,
  finder_action_keys = {
    open = 'o',
    vsplit = 'v',
    split = 's',
    tabe = 't',
    quit = 'q',
    scroll_down = '<C-j>',
    scroll_up = '<C-k>',
  },
  code_action_keys = {
    quit = 'q',
    exec = '<CR>',
  },
  rename_action_quit = '<C-c>',
  rename_in_select = true,
  symbol_in_winbar = {
    in_custom = true,
    enable = true,
    separator = ' ' .. icon('triangle-right'),
    show_file = true,
    click_support = false,
  },
  show_outline = {
    win_position = 'right',
    win_with = '',
    win_width = outline_width(),
    auto_enter = true,
    auto_preview = true,
    virt_text = '┃',
    jump_key = 'o',
    auto_refresh = true,
  },
  server_filetype_map = {},
})
```

**Comment by glepnir** [comment]
you don't need copy all options to your config. just put the modified options into init function argument table.

**Comment by glepnir** [comment]
if you want use the default the winbar of lspsaga just `symbol_in_winbar.enable = true` if you want use in custom winbar just
`symbol_in_winbar.in_custom = true` no need config other things.

**Comment by RAprogramm** [comment]
sorry, but still not working... Can you show your config? part about winbar

**Comment by glepnir** [comment]
I just use default winbar provide by saga . just 
```lua
  local saga = require('lspsaga')
  saga.init_lsp_saga({
    symbol_in_winbar = {
      enable = true,
    },
  })

```
`in_custom` that mean you used the function that provide by saga to get the symbols. so if you config this option other options of winbar will not work .  lspsaga provide a simple winbar

**Comment by DinkyTrady** [comment]
@glepnir me too, i don't know why the winbar just work in lua.
my lspsaga setup :
``` lua
local status, saga = pcall(require, 'lspsaga')
if (not status) then return end

saga.init_lsp_saga({ symbol_in_winbar = { enable = true } })
```

**Comment by puppyapple** [comment]
+1

**Comment by glepnir** [comment]
can provide a python file ?

**Comment by puppyapple** [comment]
> can provide a python file ?
[pipeline.py.zip](https://github.com/glepnir/lspsaga.nvim/files/10318711/pipeline.py.zip)
Sure. And I found that it is not a "no symbols" problem. In my case, the symbols flash out when I moved my cursor and disappear when I stopped. (file provide is not the one in the video but the performances are the same)
I use pyright as LSP and null-ls with Lunarvim.
https://user-images.githubusercontent.com/33118185/209933534-b7dccb06-a9c3-4f9c-82a8-a0734b511a99.mov

**Comment by glepnir** [comment]
I will try reproduce with it .

**Comment by puppyapple** [comment]
> 



> I will try reproduce with it .

That will be kind. And for me, lua file  also works like a charm.

**Comment by puppyapple** [comment]
Morning @glepnir , I think I found out the cause for my case. In Lunarvim they use https://github.com/SmiteshP/nvim-navic for winbar display and it seems that it conflicts with lspsaga. After I disable naive, lspsaga's winbar works just fine. (Though I'm not sure it is the case for others above). Anyway, thanks for your amazing work!
<img width="887" alt="image" src="https://user-images.githubusercontent.com/33118185/210025923-02edc59a-ea52-4eda-977d-2851ad390eb4.png">

**Comment by puppyapple** [comment]
> Morning @glepnir , I think I found out the cause for my case. In Lunarvim they use https://github.com/SmiteshP/nvim-navic for winbar display and it seems that it conflicts with lspsaga. After I disable navic, lspsaga's winbar works just fine. (Though I'm not sure it is the case for others above). Anyway, thanks for your amazing work!
> <img alt="image" width="887" src="https://user-images.githubusercontent.com/33118185/210025923-02edc59a-ea52-4eda-977d-2851ad390eb4.png">

But I'm still confused why the conflict only happens for python file 😂

**Comment by glepnir** [comment]
nvim-navic is a winbar plugin it set the winbar string . lspsaga also set the winbar string there has conflict . you just the one of them.
