### ISSUE TITLE
lightbulb not showing

### ISSUE THREAD

**Issue by jason-shen** [glepnir/lspsaga.nvim#539]
great plugin !

here is my issue
all settings are default, everything is working, except when on the code lightbulbs don't show

i do have antoinemadec/FixCursorHold.nvim installed

my setup file
local status, saga = pcall(require, "lspsaga")
if not status then
  return
end

saga.init_lsp_saga({})

local opts = { noremap = true, silent = true }
vim.keymap.set("n", "<C-j>", "<Cmd>Lspsaga diagnostic_jump_next<CR>", opts)
vim.keymap.set("n", "K", "<Cmd>Lspsaga hover_doc<CR>", opts)
vim.keymap.set("n", "gd", "<Cmd>Lspsaga lsp_finder<CR>", opts)
vim.keymap.set("i", "<C-h>", "<Cmd>Lspsaga signature_help<CR>", opts)
vim.keymap.set("n", "gp", "<cmd>Lspsaga peek_definition<CR>", opts)
vim.keymap.set("n", "gr", "<Cmd>Lspsaga rename<CR>", opts)
vim.keymap.set("n", "ca", "<Cmd>Lspsaga code_action<CR>", opts)

❯ nvim --version
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-005.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.2_1/share/nvim"

Run :checkhealth for more info

check screen capture below

https://user-images.githubusercontent.com/1794291/192430736-3babbce3-31b9-49ea-bbb3-408512c2ce0c.mp4

any help would be awesome

thank you

**Comment by jason-shen** [comment]
> what is output of `au CurosrMoved`. it should have lspsagalightbulb
here is the output
<img width="592" alt="CleanShot 2022-09-28 at 05 25 17@2x" src="https://user-images.githubusercontent.com/1794291/192581953-f08179c5-4c97-42ee-9f11-3ce22fe064d4.png">

**Comment by jason-shen** [comment]
sorry maybe i missed understand you, a bit here, how do i check the au CurosrMove

**Comment by glepnir** [comment]
sorry there has a typo it's `CursorMoved`

**Comment by jason-shen** [comment]
so we have to set au cursorMoved for the lightbulbs to work?

**Comment by jason-shen** [comment]
<img width="1572" alt="CleanShot 2022-09-28 at 19 10 45@2x" src="https://user-images.githubusercontent.com/1794291/192701235-806ba351-d5d5-4cf1-8e99-f3175c300007.png">
looks like its not set, how can i do this? sorry i am pretty new to nvim 

thanks

**Comment by glepnir** [comment]
yup there no lspsaga `CursorMoved` callback so it not work.  please try this if you confirm that the lspsaga had loaded.

```lua
saga.init_lsp_saga({
  code_action_lightbulb = {
    enable = true,
   },
})

```

**Comment by jason-shen** [comment]
i have this loaded 
```saga.init_lsp_saga({
  code_action_lightbulb = {
    enable = true,
   },
})```

**Comment by glepnir** [comment]
so still not work ? i think that mean the lspsaga not loaded

**Comment by jason-shen** [comment]
nope

**Comment by glepnir** [comment]
how do you load the lspsaga ?

**Comment by jason-shen** [comment]
after added that in 
the screen shot still; the same 
<img width="1606" alt="CleanShot 2022-09-28 at 19 29 27@2x" src="https://user-images.githubusercontent.com/1794291/192704486-75467acc-3797-4062-8000-43b66bfd17e0.png">

**Comment by jason-shen** [comment]
here is the config https://github.com/jason-shen/dotfile/blob/main/lua/user/lspsaga.lua

**Comment by jason-shen** [comment]
but i have added `saga.init_lsp_saga({
  code_action_lightbulb = {
    enable = true,
   },
})`

**Comment by jason-shen** [comment]
also server_filetype_map is been taken out too

**Comment by glepnir** [comment]
there missed all the lspsaga `CursorMoved` event..the correct is  this.  maybe you need  try to use the min config to test it works for you or not.

![image](https://user-images.githubusercontent.com/41671631/192705735-cbe1ee10-e829-4777-9784-c27792117bc3.png)

**Comment by jason-shen** [comment]
ok maybe i overwrite it withlsp_document_hightlight maybe

**Comment by jason-shen** [comment]
ok i have figured out why, the lightbulb does show up on rust but not typescript very strange

**Comment by glepnir** [comment]
my test on a ts file with the `sign_priority = 9999`

![image](https://user-images.githubusercontent.com/41671631/192722722-03651f42-c00c-4176-8bc4-e747620330ab.png)

**Comment by jason-shen** [comment]
ok i added more sign_priority = 9999
<img width="1046" alt="CleanShot 2022-09-28 at 21 02 17@2x" src="https://user-images.githubusercontent.com/1794291/192723488-33b46a56-83ce-4427-a912-ce9822c2480a.png">
 then this shows, but still no lightbulbs

**Comment by jason-shen** [comment]
ok finally got it working by adding this in

`server_filetype_map = {
  typescript = 'typescript',
  javascript = 'javascript',
}`

very strange must be my configs lol

**Comment by jason-shen** [comment]
yeah but it seems to made it worked, so strange...
