### ISSUE TITLE
Outline does not show symbols by default and live update does not work

### ISSUE THREAD

**Issue by patrykwegrzyn** [glepnir/lspsaga.nvim#543]
Hi there thanks for awesome work on `lspsaga` i love it more and more everyday .
I may have found a bug? or possible doing something stupid?

I need to use space to get symbols to show , also when i update buffer outline is not auto updating.

im using bare stock config from the readme
```lua
local keymap = vim.keymap.set
local saga = require('lspsaga')

saga.init_lsp_saga()
keymap("n", "gh", "<cmd>Lspsaga lsp_finder<CR>", { silent = true })
....
```
**Expected Behavior**
1 See symbols by default without need yo expand.
2 Auto update when buffer is modified

Could be js / typescriptreact related?
see code below

```javascript
import {StyleSheet, View} from 'react-native';

export default function Test(): JSX.Element {
  const arr = Array.from(Array(5));
  return (
    <View style={styles.container}>
      {arr.map(item => {
        return <View key={item} style={styles.item} />;
      })}
    </View>
  );
}

const foo = () => {};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  item: {
    height: 60,
    width: '100%',
  },
});
```

![outline](https://user-images.githubusercontent.com/7962796/192888283-0cd0b30a-0d9e-4bdf-bd8f-01a2a96440df.gif)

Thanks for looking

**Comment by glepnir** [comment]
there has a new implement of lspsaga outline .maybe it can fix this
