### ISSUE TITLE
gitsigns's code action does not work

### ISSUE THREAD

**Issue by jinzhongjia** [glepnir/lspsaga.nvim#544]
### Description

I use gitsigns.nvim ,and Null-ls can provide code actions from Gitsigns.My config is correct ,but in lspsaga's code action ,it does not work.
When i disable lspsaga's code action keymap to use lsp-config's keymap, gitsigns's code action works well

It looks like lspsaga is not sending the json information to gitsigns correctly

**Behavior**

Graphical display is normal， but it actually does not work!
![image](https://user-images.githubusercontent.com/41784264/193222105-5b376d55-a315-4e5b-a1cb-4aa633999b6a.png)

if it works well ,when i activate it, it will show me the preview of hunk,such as 
![image](https://user-images.githubusercontent.com/41784264/193222323-4bd1af33-2619-49fd-ab09-4898c513d58a.png)

### Details

<details><summary>Reproduce</summary>

this is just a git plugin,i hope it can preview the git hunk or reset git hunk

</details>

<details><summary>Environment</summary>

```bash
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/8svf52rgypxxjcwq5l1sjcykmibb7a61-neovim-unwrapped-0.7.2/share/nvim
"

```

</details>

**Comment by glepnir** [comment]
> It looks like lspsaga is not sending the json information to gitsigns correctly

gisigns is another plugin .I don't use it .don' know what happen .

> I use gitsigns.nvim ,and Null-ls can provide code actions from Gitsigns.

also I don't use `null-ls` .

what do you want ? see the git hunk from code action?

**Comment by jinzhongjia** [comment]
> > 看起来 lspsaga 没有正确地将 json 信息发送到 gitsigns
> 
> gisigns 是另一个插件。我不使用它。不知道会发生什么。
> 
> > 我使用 gitsigns.nvim ，并且 Null-ls 可以提供来自 Gitsigns 的代码操作。
> 
> 我也不用`null-ls`。
> 
> 你想要什么 ？从代码操作中看到 git hunk？

i just want to preview or reset hunk through code action
