### ISSUE TITLE
outline toggling error after enable symbol_in_winbar

### ISSUE THREAD

**Issue by Meow-2** [glepnir/lspsaga.nvim#545]
### Description

After I enable symbol_in_winbar, the following errors were reported when toggling the outline for the second time

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/67471300/193425112-6e3c61cc-f9ac-4a0b-9b07-99443ef7ec00.png">

### Details
![Peek 2022-10-02 03-37](https://user-images.githubusercontent.com/67471300/193425536-706cccf5-b80a-4eab-8df6-9c8c56e37bbe.gif)

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
- Operating system: 
ArchLinux
- lspsaga commit:
04e8167740c66193686ea3d14b511c7b160ea755
 

</details>

**Comment by Meow-2** [comment]
And this this occurs when using clangd. When using sumneko_lua/gopls/pyright, outline toggles normally. I tried to update clangd to the latest version(15.0.1), but still couldn't solve the problem

**Comment by CharlesChiuGit** [comment]
Is this bug still under investigation? `:LSoutlineToggle` still report the same error when using `pyright`.

**Comment by glepnir** [comment]
outline will refactor in 0.2.3 see #586  please wait.
