### ISSUE TITLE
Font used for diagnostic

### ISSUE THREAD

**Issue by h3xOo** [glepnir/lspsaga.nvim#548]
What font is used for displaying this nice arrow in diagnostic (or is it an option)?

This is screenshot taken from README
![image](https://user-images.githubusercontent.com/82811246/193447563-d1e46798-8bf2-4076-a87c-ef39e07b810c.png)

and this is how mine looks
![image](https://user-images.githubusercontent.com/82811246/193447611-95eca22c-13f1-4977-be66-6ff63b723a35.png)

**Comment by glepnir** [comment]
this arrow I had delete .so there is no arrow now.
