### ISSUE TITLE
Hovering line with an error shows floating window with error message

### ISSUE THREAD

**Issue by Jezda1337** [glepnir/lspsaga.nvim#549]
Hello, I would like to suggest one feature we have on vanilla LSP but not in LSP-saga.

It would be nice if we implement something like this but with LSP-saga :arrow_down: :arrow_down: 

https://github.com/neovim/nvim-lspconfig/wiki/UI-Customization#show-line-diagnostics-automatically-in-hover-window

For example, if I have an error on line 32:20, just hovering line 32 will open a floating window with an error message no need to hover 32:20 to see an error message.

Is this possible for LSP-saga? :smile:

**Comment by glepnir** [comment]
`Lspsaga show_line_diagnostic`
