### ISSUE TITLE
No way to cancel rename

### ISSUE THREAD

**Issue by DanCardin** [glepnir/lspsaga.nvim#55]
Once the rename popup showing, it seems like there's no way to cancel it unless you actually choose a name and hit enter.

Ideally <esc> (or <esc><esc> if you want to keep normal mode as an option for editing the rename's text) and/or <C-c> would cancel the rename and hide the floating window.

**Comment by glepnir** [comment]
you can use `q` in normal mode or `:q`

**Comment by glepnir** [comment]
Now you can use `C-c` in insert mode on rename window
