### ISSUE TITLE
Rename: Wrong variable name with hyphens

### ISSUE THREAD

**Issue by pleshevskiy** [glepnir/lspsaga.nvim#553]
### Description

When I try renaming a variable that contains hyphens (nix lang for example), lsp saga shows a popup with part of the variable name. 

**Expected Behavior**

Lsp saga shows popup with full variable name including hyphens.

Ex: `is-hello-world`

**Actual Behavior**

Lsp saga shows popup with part of variable name

Ex: `is`

**Neovim Built in Behavior**

Default lsp behavior shows full variable name correctly. 

### Details

<details><summary>Reproduce</summary>

1. Install nil (nixos lsp server)
2. Install neovim with lspconfig and lspsaga plugins.
3. Run neovim with the following configuration
  
  ```lua
  -- Leaders
  vim.g.mapleader = ","
  vim.g.maplocalleader = "-"
  
  local lsp_config = require("lspconfig")
  local saga = require("lspsaga")
  
  -- See: https://github.com/glepnir/lspsaga.nvim#configuration
  saga.init_lsp_saga({
	  code_action_lightbulb = { enable = false },
	  symbol_in_winbar = { enable = false },
  })
  
  -- always show signcolumns
  vim.opt.signcolumn = "yes"
  
  -- Use an on_attach function to only map the following keys
  -- after the language server attaches to the current buffer
  local on_attach = function(client, bufnr)
	  local bufopts = { noremap = true, silent = true, buffer = bufnr }
	  vim.keymap.set("n", "<localleader>n", "<Cmd>Lspsaga rename<CR>", bufopts)
  end
  
  -------------------------------------------------------------------------------
  -- See: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md
  --
  
  -- Override the default configuration to be applied to all servers
  lsp_config.util.default_config = vim.tbl_extend("force", lsp_config.util.default_config, {
	  on_attach = on_attach,
  })
  
  -- nix
  lsp_config.nil_ls.setup({})
  
  ```
4. create `example.nix` with the following content
  ```nix
  let is-hello-world = true; in { }
  ```
5. move cursor to `hello` and do `Lspsaga rename` command. You can use `<localleader>n` (`-n`) binding.

Alternatively, for nix-users you can configure neovim from my minimal flake for this bug:
```sh
nix run 'git+https://git.pleshevski.ru/mynix/neovim?branch=lspsaga-rename-bug'
```

</details>

<details><summary>Environment</summary>

- nvim --version                                                                                                                                                                  
```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/jnfqzl7lzqshbqfm9mkl27024nsbcgvz-neovim-unwrapped-0.7.2/share/nvim
"
```

- Operating system: 
OS: NixOS 22.11.20220918.f677051 (Raccoon) x86_64

- lspsaga commit: 
tested on `c2ef0115fb917460daf5c76fe3ad3a9357213b54` and `381900d932db058aa3236ba66cc9f45747c0df71`

</details>

**Comment by pleshevskiy** [comment]
Thank you! Now it is shown correctly, but initially only the first part is selected.

![image](https://user-images.githubusercontent.com/7839004/193513809-ea28b9dd-4268-48d3-bf31-91a375bc1482.png)

**Comment by glepnir** [comment]
fixed.

**Comment by rhcher** [comment]
Here we use `cword` to get symbol text, it has same result as you execute `viw` in vim. Because different programming languages have different lexical rules， so vim uses `iskeyword` to manage which characters are legal in a symbol. See `:h iskeyword` for details.

**Comment by pleshevskiy** [comment]
hm) I see...

![image](https://user-images.githubusercontent.com/7839004/193530389-a5767125-2abd-4358-81a7-fc4ed25f816b.png)

Maybe nix has a wrong "keyword"

**Comment by pleshevskiy** [comment]
@rhcher but why default lsp-behavior works fine?

![image](https://user-images.githubusercontent.com/7839004/193532541-f79951b8-435a-4ffd-9773-dcbf76745dfe.png)

**Comment by rhcher** [comment]
maybe some plugin change iskeyword, execute `:set iskeyword?` ensure it

**Comment by glepnir** [comment]
update then test.

**Comment by glepnir** [comment]
btw what is output of this command `set iskeyword?`

**Comment by pleshevskiy** [comment]
Preface: neovim with lspconfig and lspsaga plugins. Full configuration in the issue description.

`iskeyword=@,48-57,_,192-255`

`Lspsaga rename` output:
![image](https://user-images.githubusercontent.com/7839004/193542342-e4790d28-4e60-468d-ad8a-8d006c9615bb.png)

`vim.lsp.buf.rename` output:
![image](https://user-images.githubusercontent.com/7839004/193542684-f2432028-5615-479a-8d10-fa590757997b.png)

**Comment by glepnir** [comment]
hmm I don't find nothing special in built in .`set iskeyword+=-` will be easy to fix.

**Comment by glepnir** [comment]
how about now?
