### ISSUE TITLE
Error occuring in init_lsp_saga

### ISSUE THREAD

**Issue by joshuajeschek** [glepnir/lspsaga.nvim#555]
### Description

When using the plugin with Neovim 0.7.2, an error occurs when calling the function `init_lsp_saga`.
On my personal machine I was able to stop the error by updating to Neovim 0.8, however, on my work server I cannot do that.
The error occurs on every commit after 04e8167
If I can provide you with any more info lmk :)

**Expected Behavior**

No errors

**Actual Behavior**

This error occurs:
```console
Error detected while processing /home/joshua/.config/nvim/after/plugin/lsp.lua:
E5113: Error while calling lua chunk: ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:289: unexpected event
stack traceback:
        [C]: in function 'nvim_create_autocmd'
        ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:289: in function 'config_symbol_autocmd'
        ...site/pack/packer/start/lspsaga.nvim/lua/lspsaga/init.lua:118: in function 'init_lsp_saga'
        /home/joshua/.config/nvim/after/plugin/lsp.lua:5: in main chunk
```
### Details

<details><summary>Reproduce</summary>

1. use Neovim 0.7.2 with the newest commits (after 04e8167)
2. call `require(lspsaga').init_lsp_saga()`
</details>

<details><summary>Environment</summary>

- nvim --version output: 0.7.2
- Operating system: Observed on Ubuntu 22.04 and Debian 10
- lspsaga commit: every commit after 04e8167

</details>

**Comment by olastor** [comment]
Same problem. It happened after updating. I fixed it by pinning an older commit

`Plug 'glepnir/lspsaga.nvim', { 'branch': 'main', 'commit': 'c8bbcb598e5d63ce927d0f93d2f243532dd602c5' }`

where the error does not happen. I think it'd be great if the maintainers could introduce tagging of new versions to avoid pulling buggy code from the main branch.

**Comment by gildvp** [comment]
I just commented out these lines in the ../packer/start/lspsaga.nvim/lua/lspsaga/init.lua code and it worked:

┃ 116   -- if conf.symbol_in_winbar.enable or conf.symbol_in_win
┃ 117     -- kind.gen_symbol_winbar_hi()
┃ 118     -- require('lspsaga.symbolwinbar').config_symbol_autoc
┃ 119   -- end

**Comment by glepnir** [comment]
hmm no need this. I will disable winbar at default because there has a bug with winbar in upsteam

**Comment by joshuajeschek** [comment]
Alright, thanks! Any way to re-enable this in the meantime? I liked it on my personal machine :)

**Comment by joshuajeschek** [comment]
> Same problem. It happened after updating. I fixed it by pinning an older commit
> 
> `Plug 'glepnir/lspsaga.nvim', { 'branch': 'main', 'commit': 'c8bbcb598e5d63ce927d0f93d2f243532dd602c5' }`
> 
> where the error does not happen. I think it'd be great if the maintainers could introduce tagging of new versions to avoid pulling buggy code from the main branch.

Totally agree with you on the tagging thing!

**Comment by glepnir** [comment]
hello currently I disable the winbar feature by default. so don't need use commit .

**Comment by joshuajeschek** [comment]
Hey, do you have any idea on whether the upstream bug to this is fixed?

**Comment by glepnir** [comment]
works fine for me .

**Comment by joshuajeschek** [comment]
Alright thanks :)

**Comment by joshuajeschek** [comment]
I'm just a tiny bit confused to be honest, because when neovim 8 was fresh and I updated, there was a nice winbar, filled with lsp information without me having to do anything. However now, it doesn't show.

**Comment by joshuajeschek** [comment]
Another Update from me, it works again, but I had to enable it manually in the config. I thought it was activated by default, since the README mentions it.
reference: https://github.com/glepnir/lspsaga.nvim/blob/main/README.md?plain=1#L190
