### ISSUE TITLE
Is there a way to show line number in split mode

### ISSUE THREAD

**Issue by bryantchan** [glepnir/lspsaga.nvim#557]
**Is your feature request related to a problem? Please describe.**
When I use the `peek_definition` to open a file in a split window, the line number column will be gone.
<img width="320" alt="CleanShot 2022-10-06 at 12 21 31@2x" src="https://user-images.githubusercontent.com/1303409/194181283-5c40f27d-bb23-449f-9d94-0c7cc1873a6c.png">

**Describe the solution you'd like**
Is this a bug or we can pass in any arguments that prevent the behaviour?

**Comment by glepnir** [comment]
how do you set the line number `vim.wo.number`?

**Comment by bryantchan** [comment]
<img width="220" alt="CleanShot 2022-10-06 at 22 18 56@2x" src="https://user-images.githubusercontent.com/1303409/194275725-1a63fc97-071c-43b5-84c1-8e6dda060963.png">

**Comment by glepnir** [comment]
which option you used `vim.opt` ? and the file is current buffer file

**Comment by bryantchan** [comment]
I recorded a video to explain it a bit better: 

https://user-images.githubusercontent.com/1303409/194279522-0003e69b-4ff8-483a-95ee-a731c4470658.mp4

Could you try `Lspsaga peek_definition`?

**Comment by bryantchan** [comment]
Sorry, it's not `lsp_finder`, but `peek_definition`

**Comment by glepnir** [comment]
it's same file so you missed the number there is a bug of upsteam the win opts.

**Comment by bryantchan** [comment]
Thanks for the fix.
