### ISSUE TITLE
Errors on definition-related commands (lsp_finder and preview_definition)

### ISSUE THREAD

**Issue by DanCardin** [glepnir/lspsaga.nvim#56]
I'm on literally the latest master commits of neovim/lspsaga at the time of writing. In rust source files, if that matters.

`<cmd>lua require"lspsaga.provider".lsp_finder()<CR>`

Yields: `lspsaga/libs.lua:21: bad argument #1 to 'pairs' (table expected, got nil)`

`<cmd>lua require'lspsaga.provider'.preview_definition()<CR>`

Yields: `Error executing lua vim/shared.lua:199: Expected table, got nil`

**Comment by glepnir** [comment]
does `Lspsaga lsp_finder ` work?

**Comment by glepnir** [comment]
can you post a gif here ? you lsp server start? I can't reproduce your issue.

**Comment by glepnir** [comment]
![image](https://user-images.githubusercontent.com/41671631/106611833-6300bf00-65a3-11eb-94bd-b1a38b29f61c.png)

**Comment by DanCardin** [comment]
![Kapture 2021-02-02 at 09 12 09](https://user-images.githubusercontent.com/701548/106612374-0d8ec880-6537-11eb-9fe3-de83ca0dfb88.gif)

Me swapping between `<leader>gd` (preview def) and `gd` (goto def) ^.

For sure, my lsp is starting. I'm able to use the vanilla `<Cmd>lua vim.lsp.buf.*()` commands.

Of note, I **do** have  https://github.com/RishabhRD/nvim-lsputils installed, although I did test with all of its handlers disabled.

On a kind of semi-unrelated note, this plugin seems like a more polished version of lsputils (and more). I wonder it would make sense to use the same interface for this plugin, i.e. to set `vim.lsp.handlers['textDocument/*']`, so that all the mappings can just be directly off the `<Cmd>lua vim.lsp.buf.*()` api?

**Comment by glepnir** [comment]
lspsaga has nothing to do with lsputil, I created it in June but only recently made it public, lspsaga will not overewrite any default handler requests

**Comment by glepnir** [comment]
`lspsaga/libs.lua:21: bad argument #1 to 'pairs' (table expected, got nil)` this is used to get root_dir

https://github.com/glepnir/lspsaga.nvim/blob/8ea260427671cb1da8be453d920592bca68a6ce9/lua/lspsaga/libs.lua#L90-L102
I had check rust-analyzer and rls setting in nvim-lspconfig. they are both table type. so don't know why you got nil , I used 
rust-analyzer. and lsp_finder works.

**Comment by DanCardin** [comment]
I actually just tried it and i get the same error while routing the `vim.lsp.handlers['textDocument/definition'] = require"lspsaga.provider".lsp_finder` call like so. So it might just be a matter of documentation of, what i assume is, the intended API nvim wants one to apply custom handlers for builtin lsp functionality?

**Comment by glepnir** [comment]
hmm `vim.lsp.handlers['textDocument/definition'] = require"lspsaga.provider".lsp_finder` ????????????


lspsaga is not a callback of the built-in lsp, it will request the lsp server. Nothing to do with built-in lsp

**Comment by glepnir** [comment]
https://user-images.githubusercontent.com/41671631/106615238-32228900-65a7-11eb-8c21-a9ecbe7046ab.mov

**Comment by DanCardin** [comment]
re handlers:
> A light-weight lsp plugin based on neovim built-in lsp with highly performance UI.

So I had assumed this plugin was primarily to produce a more ergonomic experience using the builtin lsp. And given that, my impression of how people (slash i assume plugins) are supposed to interact with it are through those handlers. At least to keep a consistent API for mappings. And it appears to at least work similarly to `lsputils` in that regard, where I can invoke lspsaga through the above handler, using the strategy of mappings that the `lspconfig` plugin suggests:
`vim.api.nvim_buf_set_keymap(bufnr, 'n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)`

fwiw, my rust-analyzer setup looks like so:
```
lsp.rust_analyzer.setup({
  on_attach = on_attach,
  settings = {
    ["rust-analyzer"] = {
      checkOnSave = {
        extraArgs = "--target-dir /tmp/rust-analyzer-check"
      }
    }
  }
})
```
Adding `filetypes = {'rust'},` into there, oddly, changes the value going into `has_value` (which is where the error is happening) into `vim.empty_dict()` when printed.

**Comment by glepnir** [comment]
> A light-weight lsp plugin based on neovim built-in lsp with highly performance UI.

Because you need to use the built-in lsp to start the server. lspsaga will not start any language servers

> So I had assumed this plugin was primarily to produce a more ergonomic experience using the builtin lsp. And given that, my impression of how people (slash i assume plugins) are supposed to interact with it are through those handlers. At least to keep a consistent API for mappings.


What is consistent api mapping? I am a neovim lsp code developer. The built-in lsp has its own callback. Any third-party plug-in should not rewrite it, it will easily cause confusion. lspsaga will send the lsp request protocol.

**Comment by glepnir** [comment]
I can't reproduce your problem first, usage refer to the video .if you still has problem  I need you provide a min config that can reproduce .
