### ISSUE TITLE
[Feat] Provide a command to goto definition directly

### ISSUE THREAD

**Issue by mslalith** [glepnir/lspsaga.nvim#564]
**Is your feature request related to a problem? Please describe.**
As of now if we want to goto definition, we have to open `lsp_finder` and navigate to definition from there

**Describe the solution you'd like**
Instead of that, provide another command (like `goto_definition`) to navigate directly. In this way we can reduce one step

**Describe alternatives you've considered**
I'm using Telescope for now to navigate to definitions

**Comment by glepnir** [comment]
did you tried the `Lspsaga peek_definition` ?

**Comment by mslalith** [comment]
Did that. `peek_definition` shows it in a floating window and again had a press a key to navigate

**Comment by glepnir** [comment]
float window also a normal buffer. you can do edit in it.

**Comment by mslalith** [comment]
that is how I can use it now if not for Telescope. I `peek_definition` and edit, which will take me to it's definition. But if there were to be a single command which does this, then this 2 step interaction can be eliminated.

**Comment by glepnir** [comment]
lspsaga support it very easy . but there has default `vim.lsp.buf.definiton`. does this not you expect ?

**Comment by mslalith** [comment]
I used to use that but that comes with not so good looking quickfix list at times. So I moved to `Telescope lsp_definitions`. Now I'm moving to Lspsaga (great plugin BTW 👏 ) and this is the only one which is dependent on Telescope.

**Comment by glepnir** [comment]
okay will add the `goto_definition` command.

**Comment by mslalith** [comment]
thanks for your efforts man!!! I'm planning to lazy load this plugin by adding `cmd = Lspsaga`. Do you have any better approach?

**Comment by glepnir** [comment]
or `after = 'nvim-lspconfig'`

**Comment by windrivder** [comment]
+1 ❤️
