### ISSUE TITLE
Separate terminal and lazygit buffer 

### ISSUE THREAD

**Issue by RakerZh** [glepnir/lspsaga.nvim#566]
**Is your feature request related to a problem? Please describe.**
After opening float terminal, use ` Lspsaga open_floaterm lazygit' ` command still stay in float terminal buffer.

**Describe the solution you'd like**
separate simple float terminal and lazygit(or another terminal process) 

**Describe alternatives you've considered**
Maybe add customized list for some process like lazygit

**Additional context**

https://user-images.githubusercontent.com/76530956/194991015-b5b5e360-4390-4c3f-a527-e867c7feed56.mov

**Comment by glepnir** [comment]
because it's use the before buffer .  it's a bug.
