### ISSUE TITLE
[feat] Hide symbols in winbar

### ISSUE THREAD

**Issue by maxmahlke** [glepnir/lspsaga.nvim#567]
**Is your feature request related to a problem? Please describe.**
I like have the symbols in the winbar but I prefer a more minimal look of the winbar. Using `custom_kind` and the `LspSagaWinbar` highlight groups, I can edit the appearance of the symbols and make the text darker. However, I cannot remove the icons.

**Describe the solution you'd like**
Something like

```lua
symbols_in_winbar = {
  enable = true,
  show_icons = false,
}
```

**Describe alternatives you've considered**
I set all icons to `""` using `custom_kind`. This works except for the filename, where the `devicon` is always used.
And it is an overkill: I would like to keep the icons overall, just hide them in the winbar.

**Additional context**
Current look of my winbar:

![Screenshot from 2022-10-13 17-59-07](https://user-images.githubusercontent.com/19716714/195646794-72c83e89-c694-4ecc-989f-87e1c1a0a85b.png)

**Comment by glepnir** [comment]
maybe you can write a custom winbar .the README have a example to write own winbar.

**Comment by maxmahlke** [comment]
A custom winbar requires a decent amount of code in the config. The icons need to be removed from the `get_symbol_node()` output with pattern matching, which feels wrong since they were initially added to the output. I understand if you don't want to add this level of customization to the config, I will just stick with what I have :+1:

**Comment by glepnir** [comment]
maybe we can adda clean_mode no any icon
