### ISSUE TITLE
[Question] How do I select the text inside `show_line_diagnostics`?

### ISSUE THREAD

**Issue by KritPaoIn** [glepnir/lspsaga.nvim#568]
<img width="475" alt="Screen Shot 2022-10-17 at 4 24 54 AM" src="https://user-images.githubusercontent.com/92923965/196059059-d2df34d7-24f4-43ab-9188-7aa1db0bfa07.png">

I want to select and copy `1. Cannot find name 'asdjkls'. [2304]`

**Comment by glepnir** [comment]
<C-w>w to float window

**Comment by KritPaoIn** [comment]
> usee wincmd map `<C-w>w` into float window

for me, that works for `hover_doc`, but it doesn't for `show_line_diagnostics`

**Comment by glepnir** [comment]
create a new issue for it.
