### ISSUE TITLE
Error using `lsp_finder()` for someone not using `nvim-lspconfig` but still has a valid LSP connection.

### ISSUE THREAD

**Issue by ckipp01** [glepnir/lspsaga.nvim#57]
Give the following init file:

```
local cmd = vim.cmd

cmd [[packadd packer.nvim]]
require('packer').startup(function(use)
  use {'wbthomason/packer.nvim', opt = true}

  use {'glepnir/lspsaga.nvim'}
  use 'scalameta/nvim-metals'

end)

local saga = require 'lspsaga'
saga.init_lsp_saga()

vim.o.shortmess = string.gsub(vim.o.shortmess, 'F', '') .. 'c'

local function map(mode, lhs, rhs, opts)
  local options = {noremap = true, silent = true}
  if opts then
    options = vim.tbl_extend('force', options, opts)
  end
  vim.api.nvim_set_keymap(mode, lhs, rhs, options)
end

map('n', 'gr', '<cmd>lua require"lspsaga.provider".lsp_finder()<CR>')
cmd [[augroup lsp]]
cmd [[autocmd!]]
cmd [[autocmd FileType scala,sbt lua require("metals").initialize_or_attach({})]]
cmd [[augroup end]]
```
When I attempt to use `lsp_finder()` I get the following error message:

```
Error executing vim.schedule lua callback: ...site/pack/packer/start/lspsaga.nvim/lua/lspsaga/libs.lua:21: bad argument #1 to 'pairs' (table
expected, got nil)
```

I'm still digging into finding out what the issue is, and I can give you detailed instructions on how to use `nvim-metals` if you want, but I'm curious if it has to do with the fact that I don't use `nvim-lspconfig` at all to manage the connect with metals, but rather my own plugin handles that all. Could that potentially be the issue here?

**Comment by glepnir** [comment]
OK  I will test it tomorrow

**Comment by ckipp01** [comment]
Alright, so I figured out the issue. `nvim-lspconfig` requires the user to have set `config.filetypes` and then that is passed into `start_client` when there is a initialization. However, from what I can tell `filetypes` is never actually used in that `config` table. For example it's not checked at all here when the table is validated: https://github.com/neovim/neovim/blob/cc1851c9fdd6d777338bea2272d2a02c8baa0fb1/runtime/lua/vim/lsp.lua#L217-L236

I'm probably totally an outlier here because `nvim-metals` doesn't rely on `nvim-lspconfig`, but an argument could be made that it shouldn't rely on this being there, since core doesn't require it. I can simply add `filetypes` to my config object that I'm passing in, but this may be confusing for someone in the future if they stumble onto it. What do you think?

**Comment by glepnir** [comment]
Yes, this is a problem. For plug-ins that do not use nvim-lspconfig to start the server, but no matter any plug-in starts the server, the filetypes need to be displayed and passed, right? We can determine whether the filetypes are table or string, and then compare it with the current vim. bo.filetype for comparison

**Comment by glepnir** [comment]
check 7b49d2e

**Comment by xfyuan** [comment]
> Now we check the type of client filetypes
> https://github.com/glepnir/lspsaga.nvim/blob/5b1a7858458299c3d98dea7afd24fd0a5eb3df78/lua/lspsaga/libs.lua#L95-L108

But now it give me this error (I've tried go/ruby files):

```
[LspSaga] get root dir failed
```

If I revert your last two commits with filetype checking, check out the `1fd7a1d8ab68df6b5ad3ef479e2df8f7145588e8`, then `lsp_finder` works very fine.

**Comment by glepnir** [comment]
which server?

**Comment by glepnir** [comment]
I tested it works fine in go project.

**Comment by glepnir** [comment]
@xfyuan  fixed .

**Comment by ckipp01** [comment]
> Yes, this is a problem. For plug-ins that do not use nvim-lspconfig to start the server, but no matter any plug-in starts the server, the filetypes need to be displayed and passed, right?

No, they actually  don't. If you take a look at the table that is required to be passed into `lsp.start_client(config)`, there is no `filetypes`. `filetypes` is a `nvim-lspconfig` convention since they use it to know when to start a certain server based on the filetype. However, there are other plugins like [nvim-metals](https://github.com/scalameta/nvim-metals) or [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls) that instead rely on an autocmd to first start the server.

> We can determine whether the filetypes are table or string, and then compare it with the current vim. bo.filetype for comparison

Sure, that would work, but not for clients that don't have `config.filetypes` set.

I'm definitely in the minority here, so I just went ahead and added `filetypes` into my config table when I pass it in in case users are using lspsaga.  So if you want to close this, feel free, but as more plugins pop up that don't rely on `nvim-lspconfig` you might hit on this more.

**Comment by glepnir** [comment]
Yes, this is a problem. The `rootdir` is used to truncate the length of the definition and reference object files to reduce the window width . Use autocmd to specify the file type to start the server, the plugin will not display the filetype.In this way, config.filetype is incorrect to find a server that matches the current buffer file type.

Another way is to match through cmd. But this way I need to maintain a table of filetype and server cmd .

**Comment by ckipp01** [comment]
> Another way is to match through cmd. But this way I need to maintain a table of filetype and server cmd .

That would be a lot of work, and I probably wouldn't recommend that. 🤔 I'm not sure what a good solution is for this, since I totally understand how having `filetypes` set is useful. You could also expose maybe a mapping table so that if someone is using something that doesn't have `filetypes`, you double check to see if there isn't like a `server_mappings = {'scala', 'metals'}`. Although if that was required, I'm assuming most plugin authors would just add in `filetypes` to their config object since it's not that hard. Again, I'm not sure. Maybe it's just fine to put a note somewhere that if you are using nvim lsp without nvim-lspconfig, make sure to have `filetypes` set.

**Comment by glepnir** [comment]
filetype is an optional option for them. So I should not let them add filetypes in order to cooperate with lspsaga. I can provide a table for users to register filetype and cmd, so I don’t need to maintain this table.

**Comment by ckipp01** [comment]
> I can provide a table for users to register filetype and cmd, so I don’t need to maintain this table.

That sounds reasonable to me. 🙏🏼 thanks a lot for all your work on lspsaga.

**Comment by glepnir** [comment]
Now work like this 
```
saga.init_lsp_saga {
      server_filetype_map = { scala = 'metals'}
}
```

**Comment by ckipp01** [comment]
Just tested it and am getting `[LspSaga] get root dir failed`. I can try to take a closer look later today to see if I can see what is happening in my case.

**Comment by ckipp01** [comment]
Also, I just looked at the last commit. I wouldn't fully default to one or the other. Because I also use other servers for example that do utilize nvim-lspconfig, and the logic now checks if there is a `server_filetype_map` and if so, only check there. However, if a user has that table for one server, but uses nvim-lspconfig for the rest, shouldn't the both work? Maybe check to see if `filetypes` is there, and if not, _then_ check to see if there is an entry in `server_filetype_map` that matches the filtype from the buffer?

**Comment by glepnir** [comment]
yep I found this patch is incorrect. wait.

**Comment by glepnir** [comment]
How about now?

**Comment by EpsilonKu** [comment]
I'm getting `get root dir failed` on nvim-jdtls when I run `show usage`.
