### ISSUE TITLE
功能失效

### ISSUE THREAD

**Issue by 1084350607** [glepnir/lspsaga.nvim#570]
## Description
在项目中lspsaga重命名等功能正常工作，新建的文件里失效

我的nvim-lspconfig配置

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/58846658/196673374-bba0e3ad-65ea-40c6-b3be-36c9f94b5374.png">

lsp-sage只初始化

<img width="489" alt="image" src="https://user-images.githubusercontent.com/58846658/196673438-ee2fd994-26d0-4726-b938-39c7204a7ea6.png">

## Error

功能在新的文件夹中失效，但是项目中可以正常工作（项目中有eslint和prettier，不知道是不是因为这个）
### 新建的文件夹：
<img width="997" alt="image" src="https://user-images.githubusercontent.com/58846658/196673857-d61d2a91-4c4c-47d4-9130-f7c9ccb0b428.png">

### 项目中正常工作
<img width="939" alt="image" src="https://user-images.githubusercontent.com/58846658/196674366-c3b439cc-4bcd-4609-a817-e967e6152ea2.png">

**Comment by glepnir** [comment]
your new project `refactor` no root file of typescript server . so the buffer of `index.js` no server then the lspsaga can't work. the project must have one of `package.json , .git , jsconfig.json`.

**Comment by 1084350607** [comment]
Has been solved, thanks a lot.
