### ISSUE TITLE
Support Call Hierarchy

### ISSUE THREAD

**Issue by lazywei** [glepnir/lspsaga.nvim#574]
**Is your feature request related to a problem? Please describe.**
Is there a way to support to call hierarchy feature like in https://github.com/ldelossa/litee-calltree.nvim?

**Describe the solution you'd like**
A floating UI to display the call hierarchy provided by LSP server
Something like this
![image](https://user-images.githubusercontent.com/2840571/198105305-c4a78591-8d97-44fb-af6c-e1009bc75ad3.png)

**Comment by glepnir** [comment]
nice feature. I like this. will implement one with a nice ui.
