### ISSUE TITLE
LSPsaga lsp_finder bad argument #1 to 'pairs' (table expected, got string)

### ISSUE THREAD

**Issue by kseikyo** [glepnir/lspsaga.nvim#575]
### Description

When I try going to the definition of some variable,  specifically on typescript react projects (don't know for sure for every other type), I get a request timeout or an error. 
But, for my own config, e.g., lspsaga config, I first get a request timeout, and on the second time it works.

**Expected Behavior**

It should show the popup for definitions and references.

**Actual Behavior**

 I get the following error
```
Error executing vim.schedule lua callback: ...site/pack/packer/start/lspsaga.nvim/lua/lspsaga/libs.lua:91: bad argument #1 to 'pairs' (table expected, got string)
stack traceback:
        [C]: in function 'pairs'
        ...site/pack/packer/start/lspsaga.nvim/lua/lspsaga/libs.lua:91: in function 'get_lsp_root_dir'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:203: in function 'render_finder'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:150: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Neovim Built in Behavior**

Not sure, I have just started using Neovim.

### Details

My config
```lua
local status, saga = pcall(require, "lspsaga")
if (not status) then return end

saga.init_lsp_saga {
  server_filetype_map = {
    typescript = 'typescript'
  }
}

local opts = { noremap = true, silent = true }
vim.keymap.set('n', '<C-j>', '<Cmd>Lspsaga diagnostic_jump_next<CR>', opts)
vim.keymap.set('n', 'K', '<Cmd>Lspsaga hover_doc<CR>', opts)
vim.keymap.set('n', 'gd', '<cmd>Lspsaga lsp_finder<CR>', opts)
vim.keymap.set('i', '<C-k>', '<Cmd>Lspsaga signature_help<CR>', opts)
vim.keymap.set('n', 'gp', '<Cmd>Lspsaga peek_definition<CR>', opts)
vim.keymap.set('n', 'gr', '<Cmd>Lspsaga rename<CR>', opts)
```

<details><summary>Reproduce</summary>

1. Clone this [repo](https://github.com/t3-oss/create-t3-app) (or any other react project should do from my experience)
2. nvim into any .tsx file
3. try to view the definition of some variable
4. Get timed-out or the error.
</details>

<details><summary>Environment</summary>

- nvim --version output: 
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
- Operating system: macOS Monterey version 12.6
- lspsaga commit: 391cf74

</details>

**Comment by glepnir** [comment]
you use a folk version.

**Comment by kseikyo** [comment]
> you use a folk version.

I don't think that's the issue, since I'm referencing this repo when installing the plugin on my packer config

```lua
local status, packer = pcall(require, "packer")
if (not status) then
  print("Packer is not installed")
  return
end

vim.cmd [[packadd packer.nvim]]

packer.startup(function(use)
  -- [...]
  use 'neovim/nvim-lspconfig'
  use 'glepnir/lspsaga.nvim' -- LSP UIs
  -- [...]
end)
```

**Comment by glepnir** [comment]
`  typescript = {'typescript' }` a table type.
