### ISSUE TITLE
Error upon `:Lspsaga show_line_diagnostics`

### ISSUE THREAD

**Issue by KritPaoIn** [glepnir/lspsaga.nvim#578]
Virtual Text from lsp:
<img width="1012" alt="Screenshot 2022-11-01 at 12 42 57 AM" src="https://user-images.githubusercontent.com/92923965/199073935-1098e465-df0d-4e4a-a568-35628beb5d72.png">

Error:
<img width="1296" alt="Screenshot 2022-11-01 at 12 51 42 AM" src="https://user-images.githubusercontent.com/92923965/199075561-f6bb1143-082e-4a12-af77-a65b7a0ccfaf.png">
```
E5108: Error executing lua .../pack/packer/opt/lspsaga.nvim/lua/lspsaga/diagnostic.
lua:30: bad argument #3 to 'gsub' (string/function/table expected)
stack traceback:
        [C]: in function 'gsub'
        .../pack/packer/opt/lspsaga.nvim/lua/lspsaga/diagnostic.lua:30: in function
 'format_message'
        .../pack/packer/opt/lspsaga.nvim/lua/lspsaga/diagnostic.lua:118: in functio
n <.../pack/packer/opt/lspsaga.nvim/lua/lspsaga/diagnostic.lua:61>
        ...ite/pack/packer/opt/lspsaga.nvim/lua/lspsaga/command.lua:40: in function
 'load_command'
        [string ":lua"]:1: in main chunk
```

Lsp: 
https://www.npmjs.com/package/@tailwindcss/language-server
<img width="1033" alt="Screenshot 2022-11-01 at 12 44 36 AM" src="https://user-images.githubusercontent.com/92923965/199074253-f189766d-01cb-496d-b94e-6b1dbc18a801.png">

Code:
```tsx
function Bug() {
  return <div className="flex hidden" />
}
```

**Comment by glepnir** [comment]
which lspsaga do you used ? I don't have the `format_message` function.

**Comment by KritPaoIn** [comment]
Oops, I forgot I was using a forked version. Thanks for reminding me.
