### ISSUE TITLE
add support for cmp kinds

### ISSUE THREAD

**Issue by yao-weijie** [glepnir/lspsaga.nvim#579]
**Is your feature request related to a problem? Please describe.**
1. I tried to use lspkind icons in lspsaga to shown in cmp plugin, but I found some kinds are not in saga yet, so I have to add the kinds manully.
![图片](https://user-images.githubusercontent.com/36393630/199565286-a72bfa02-7a7f-4d20-b18f-ef51596be164.png)

**Describe the solution you'd like**
1. enrich the kinds and icons in saga, such as Text and Snippet
2. if it is possible to add a function to format cmp items like [lspkind.nvim](https://github.com/onsails/lspkind.nvim)?

**Comment by glepnir** [comment]
because the text and snippet is for completion. there has no defined in lsp.  maybe we can support.
