### ISSUE TITLE
Disable sidescrolloff in rename window

### ISSUE THREAD

**Issue by kristijanhusak** [glepnir/lspsaga.nvim#58]
Hi,

today I was renaming some longer method name, and noticed that cursor stays at middle of screen while i type. I noticed that my default `scrolloff` and `sidescrolloff` is being used.

Here's the gif:
![long-rename](https://user-images.githubusercontent.com/1782860/106654605-a0ac1a80-6598-11eb-872b-85e81660f3cd.gif)

Steps to reproduce:

```lua
-- init.lua
vim.o.scrolloff = 8
vim.o.sidescrolloff = 15
vim.o.sidescroll = 5
```

1. do `:Lspsaga rename` on something
2. Try typing long name

**Comment by glepnir** [comment]
change them value to -1 in rename window.

**Comment by kristijanhusak** [comment]
I pulled latest changes and gave it a try, but looks like issue still exist:
![rename-window](https://user-images.githubusercontent.com/1782860/106729499-d3dcc100-660d-11eb-973d-436529760710.gif)

I tried to change values by myself, and noticed that setting it to `0` instead of `-1` make it work fine.
Here's the patch if it's easier for you to change:

```diff
diff --git a/lua/lspsaga/rename.lua b/lua/lspsaga/rename.lua
index f36601f..fa0b55b 100644
--- a/lua/lspsaga/rename.lua
+++ b/lua/lspsaga/rename.lua
@@ -48,8 +48,8 @@ local rename = function()
 
   local cb,cw,_,bw = window.create_float_window(content_opts,border_opts,opts)
   local saga_rename_prompt_prefix = api.nvim_create_namespace('lspsaga_rename_prompt_prefix')
-  api.nvim_win_set_option(cw,'scrolloff',-1)
-  api.nvim_win_set_option(cw,'sidescrolloff',-1)
+  api.nvim_win_set_option(cw,'scrolloff',0)
+  api.nvim_win_set_option(cw,'sidescrolloff',0)
   api.nvim_buf_set_option(cb,'modifiable',true)
   local prompt_prefix = get_prompt_prefix()
   api.nvim_buf_set_option(cb,'buftype','prompt')
```

**Comment by glepnir** [comment]
Thanks for report .got it.

**Comment by glepnir** [comment]
now fixed.

**Comment by kristijanhusak** [comment]
Awesome, thanks!
