### ISSUE TITLE
Error when rename variable

### ISSUE THREAD

**Issue by coffebar** [glepnir/lspsaga.nvim#584]
When i try to rename variable under cursor in lua code, i get error:

`Error executing Lua callback: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 1141 for language lua stack traceback: [C]: in function '_ts_parse_query' /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: in function 'get_query' ...cker/start/nvim-treesitter/lua/nvim-treesitter/query.lua:104: in function 'get_query' ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/rename.lua:115: in function 'support_change' ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/rename.lua:193: in function 'lsp_rename' ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:21: in function <...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:20 > ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:56: in function 'load_command' ...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:83: in function <...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:82 >`

**Comment by glepnir** [comment]
Please fill the issue template , if you want your issue get fix. you don't provide any useful information, basiclly you need provide the reproduce step.

**Comment by coffebar** [comment]
You are right. sorry! Can't reproduce today. So far it works.
