### ISSUE TITLE
Overlapping between popup

### ISSUE THREAD

**Issue by vanhtuan0409** [glepnir/lspsaga.nvim#59]
Hi, I'm trying to test lspsaga with nvim. When 2 function is activated at the same time, popups are overlapped with each other. Can we have a workaround or able to set the priority of each popup?

Config:
```
nnoremap <silent> K         :Lspsaga hover_doc<CR>
autocmd CursorHold  * :Lspsaga show_line_diagnostics
```

Demo

![image](https://user-images.githubusercontent.com/8175932/106725909-70b65300-663c-11eb-9b4f-af4d14747ca1.png)

**Comment by glepnir** [comment]
fix it later.

**Comment by vanhtuan0409** [comment]
Currently pressing K doesnt close the diagnosis
