### ISSUE TITLE
`hover_doc` returns "No information available" on JSX/TSX files

### ISSUE THREAD

**Issue by eduardomcv** [glepnir/lspsaga.nvim#593]
### Description

Calling `:Lspsaga hover_doc` returns a "No information available" message, even though calling `vim.lsp.buf.hover()` is working correctly. This seems to be happening on JSX and TSX files.

**Expected Behavior**

Should open the `hover_doc` window with information.

**Actual Behavior**

Shows a "No information available" print at the bottom.

**Neovim Built in Behavior**

The `vim.lsp.buf.hover()` function is working correctly and shows a floating window with information.

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
```tsx
﻿﻿function Test() {
  return (
    <div>test</div>
  )
}
```
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
```
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info
```
- Operating system: MacOS
- lspsaga commit: `201dbbd13d6bafe1144475bbcae9efde224e07ec`

</details>

**Comment by glepnir** [comment]
a known issue on neovim

**Comment by emi2k01** [comment]
This happens to me because I have multiple LSPs running for typescript (`tsserver`, `eslintls` and `graphql`).

Is this really a neovim issue? AFAIK, the OP is saying the neovim issue is that hover calls all the LSPs while lspsaga.nvim only calls one.

**Comment by emi2k01** [comment]
@eduardomcv, try adding

```
on_attach = function(client, bufnr)
    client.server_capabilities.hoverProvider = false
    on_attach(client, bufnr)
end
```

to the server configurations that run on your JSX/TSX files. Looking at your dotfiles, I think you only need it on the graphql one, but you can make sure what LSPs are running with `LspInfo`

**Comment by eduardomcv** [comment]
@emi2k01 Thanks 👍  this fixed the issue. Seems like the problem was indeed with the graphql LSP config.
