### ISSUE TITLE
Diagnostics windows height is highly truncated.

### ISSUE THREAD

**Issue by fjchen7** [glepnir/lspsaga.nvim#594]
![image](https://user-images.githubusercontent.com/10106636/202861142-f6308366-8350-4ce2-bcb2-9a259c908e35.png)

![image](https://user-images.githubusercontent.com/10106636/202861178-846baa37-63df-4217-ac40-0bf0a7d02c6e.png)

The height of diagnostics popup window is too small. How to set them to a big number or make them adaptive?

**Comment by SeitaHigashi** [comment]
I have the same bug, but it is caused by SmoothCursor.nvim. Did you use the plugin like same?

**Comment by glepnir** [comment]
look at #586  some gif show new diagnostic
