### ISSUE TITLE
Lspsaga hover_doc reports width key error

### ISSUE THREAD

**Issue by CharaD7** [glepnir/lspsaga.nvim#595]
### Description
`Lspsaga hover_doc()` does not work in TypeScript react project. It rather throws a popup error referring to lspsaga/window.lua:191 saying `'width' key must be a positive Integer`. This happened after I updated the plugin today.

**Expected Behavior**
Hover doc should show on cursor position after call is made

**Actual Behavior**
Hitting an error message
![Screenshot from 2022-11-19 18-36-19](https://user-images.githubusercontent.com/9804780/202868416-34f76e09-94eb-485e-8408-9ba65317f346.png)

**Neovim Built in Behavior**
Using vim.lsp.buf.the handlers works fine

### Details

- Update neovim  lspsaga plugin
- Launch a TypeScript react project
- Move cursor position to any delcaration or reference and hit the hover keymap
![Screenshot from 2022-11-19 19-41-07](https://user-images.githubusercontent.com/9804780/202868669-f540caf5-d59e-402a-a917-f42a1d471961.png)

Ubuntu 22.04
Nvidia graphics
Linux charapyge-Katana-GF66-11UE 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```
NVIM v0.9.0-dev-176+g1fe31651b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/__w/neovim/neovim/build/cmake.config -I/__w/neovim/neovim/src -I/__w/neovim/neovim/.deps/usr/include -I/usr/include -I/__w/neovim/neovim/build/src/nvim/auto -I/__w/neovim/neovim/build/include
Compiled by root@fa97477525b5

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```

**Comment by glepnir** [comment]
hmm I can't reproduce . did you install it with `glepnir/lspsaga.nvim` not fork version ?

**Comment by CharaD7** [comment]
I did install `glepnir/lspsaga.nvim`, let me check to be sure it's not the fork version. Thank you

**Comment by glepnir** [comment]
still have this problem ?
