### ISSUE TITLE
Cannot see multiple diagnostics for a single position

### ISSUE THREAD

**Issue by rensftw** [glepnir/lspsaga.nvim#596]
### Description
Lspsaga does not show **all** diagnostic messages for a position (line:column, eg 1:29). 
When there are multiple diagnostics it only shows one diagnostic (it appears to be non-deterministic which one gets shown)

**Expected Behavior**
All three diagnostic messages are shown for position 1:29 are shown in the popup:
<img width="573" alt="image" src="https://user-images.githubusercontent.com/22574186/202913943-f790115a-3ad8-4356-aac5-bed17cf727d6.png">

**Actual Behavior**
The Lspsaga popup shows only one out of three diagnostics for 1:29:
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/22574186/202916094-c30369fc-1c0f-4e05-ba55-a4eb873a1b53.png">

### Details

I initially found this issue with [`null-ls`](https://github.com/jose-elias-alvarez/null-ls.nvim) and [Vale](https://github.com/errata-ai/vale), but I suspect it will be reproducible with other LSPs as well.

<details>
    <summary>Steps to reproduce</summary>
    <ol>
    <li>
Copy Vale config
Copy the contents of <a href="https://github.com/rensftw/.dotfiles/tree/main/vale">this folder</a> to your home directory.
These are the sources (only <code>yml</code> and <code>json</code> files) that Vale uses to lint prose.
</li>

<li>
Use this minimal Neovim config 👇
<pre><code>
require('packer').startup(function(use)
    use({ 'glepnir/lspsaga.nvim', branch = 'main' })
    use 'jose-elias-alvarez/null-ls.nvim'
end)
require('null-ls').setup({
    sources = {
        require('null-ls').builtins.diagnostics.vale,
    },
})
require 'lspsaga'.init_lsp_saga {
    border_style = 'rounded',
    diagnostic_header = { ' ', ' ', ' ', ' ' },
    code_action_icon = '↯ ',
}
</code></pre>
</li>

<li>
Create a Markdown file and paste the following line:
<code>
_Note: This setup is built for and tested on macOS._
</code>
</li>

<li>
Open that Markdown file in Neovim and <code>:Lspsaga diagnostic_jump_next</code>
</li>

<li>
Observe that the Lspsaga popup shows only one diagnostic message for position <b><code>1:19</code></b>, while in reality there should be 3.

For reference these are the CLI results of running vale
<img width="614" alt="image" src="https://user-images.githubusercontent.com/22574186/202914712-e7554db3-061d-4428-8c16-944fb3a0b260.png">
</li>
</ol>
</details>

<details><summary>Environment</summary>

- nvim --version output: 
<pre><code>
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local
</code></pre>
- Operating system: <code>macOS v13.0.1 (Ventura)</code>
- lspsaga commit: <code>85e1c00f5a6645b0571d475b4b43803377a82bf0</code>

</details>

**Comment by glepnir** [comment]
`Lspsaga show_line_diagnostic` and `Lspsaga show_cursor_diagnostic`
