### ISSUE TITLE
How can i theme the lspoutline colors in my theme?

### ISSUE THREAD

**Issue by uloco** [glepnir/lspsaga.nvim#600]
**Is your feature request related to a problem? Please describe.**
I cannot manage to theme the lspoutline colors.

I tried using the ones here 

``` 
LSOutLineProperty { Property },
    LSOutLineConstructor {},
    LSOutLineInterface { Type },
    LSOutLineFunction { Function },
```
but they always get reset to default values whenever I toggle it.

**Describe the solution you'd like**
Make it possible for theme authors to theme the lspoutline colors 

**Describe alternatives you've considered**
At least you could also link to the default highlight groups reserved for such things as property, interface, method, etc.

**Comment by uloco** [comment]
@glepnir Thanks for your help. Altough I don't want to change the colors for me only. I want people to be able to install my theme and make it work. Can I do this in my theme and **not** in my lua config?

**Comment by glepnir** [comment]
I had add it support in next version.  then you config it in your colorscheme.
