### ISSUE TITLE
An error happened when i use outline

### ISSUE THREAD

**Issue by zengshenggit** [glepnir/lspsaga.nvim#601]
My neovim veriosn is 0.8.1 on archlinux system.
The following error often happened when i use outline:
![微信截图_20221123152127](https://user-images.githubusercontent.com/21997717/203492163-d833f529-efdd-4f40-b197-17c81c295b49.png)

**Comment by glepnir** [comment]
outline had refactor in version 0.2.3  see #586 . please wait for this pr merge.
