### ISSUE TITLE
auto_refresh failed

### ISSUE THREAD

**Issue by LauGaHo** [glepnir/lspsaga.nvim#602]
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/52206004/203567269-2dea34bb-28fd-4d3f-8bef-2b3d9ed66057.png">

### Description
I use the bufferline plugin, when I open a new tab, Lspoutline auto_refresh failed.
When I change to keymaps.lua, but still show lspsaga.lua's outline

**Expected Behavior**
when I focus other tab, the outline will auto refresh

**Actual Behavior**
the outline still no change

**Neovim Built in Behavior**

### Details

<details><summary>Environment</summary>

- nvim --version output: v0.8.0
- Operating system: MacOS

</details>

**Comment by glepnir** [comment]
#586 had fixed.
