### ISSUE TITLE
Rename fails when minimap.vim is open: `Cursor position outside buffer`

### ISSUE THREAD

**Issue by harmolipi** [glepnir/lspsaga.nvim#603]
### Description
Rename fails when using [minimap.vim](https://github.com/wfxr/minimap.vim). If I have the minimap open and hit my shortcut "gr" on a variable to rename it, I get the below error. If I close the minimap buffer, it works fine. If I open anything else in a split view, it still works fine. It's only when that minimap is open. Not sure if this is therefore something I should report to lspsaga or to the minimap plugin, but posting here for now.

```
E5108: Error executing lua: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/rename.lua:21: Cursor position
outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/rename.lua:21: in function 'close_rename_win'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/rename.lua:258: in function 'do_rename'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/rename.lua:43: in function <...te/pack/packer/start
/lspsaga.nvim/lua/lspsaga/rename.lua:42>
```

**Expected Behavior**
Should be able to rename all instances of variable, whether the minimap is open or not.

**Actual Behavior**
Above error is thrown if I try renaming with the minimap open.

### Details

<details><summary>Reproduce</summary>

1. Add [minimap.vim](https://github.com/wfxr/minimap.vim) plugin
2. Open a file with a variable to rename
3. Open the minimap with `:Minimap`
4. Try to rename a variable with lspsaga
</details>

<details><summary>Environment</summary>

- nvim --version output:
```
NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.1/share/nvim"

Run :checkhealth for more info
```
- Operating system: Mac OS 13.0.1
- lspsaga commit: 85e1c00f5a6645b0571d475b4b43803377a82bf0

</details>

**Comment by glepnir** [comment]
hmmm it's wired..
