### ISSUE TITLE
About :LSoutlineToggle

### ISSUE THREAD

**Issue by LauGaHo** [glepnir/lspsaga.nvim#604]
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/52206004/203616959-aa069cbb-1f2b-4c6d-86c6-180d00116b15.png">

### Description
When I run the command `:LSoutlineToggle`.

**Expected Behavior**
open the outline

**Actual Behavior**
It reports the error as the pic shows

**Neovim Built in Behavior**

### Details

<details><summary>Reproduce</summary>

1. open the nvim
2. select a `.ts` file or other file
3. run the command `LSoutlineToggle`
</details>

<details><summary>Environment</summary>

- nvim --version output: v0.8.0
- Operating system: 
- lspsaga commit: 

</details>

**Comment by glepnir** [comment]
outline had been refactor in #586 . please wait for #586
