### ISSUE TITLE
How to make winbar show symbol context of first line in the screen

### ISSUE THREAD

**Issue by fjchen7** [glepnir/lspsaga.nvim#607]
### Description

I configure winbar by the [README.md](https://github.com/glepnir/lspsaga.nvim#show-symbols-in-winbarnvim-08-or-in-statusline) and find that winbar always shows the symbol context under my cursor. Winbar is on the top screen and it is a far distance to scan for my eye if my cursor in the middle screen (in most time). 

I think a better way is to show symbol context of the first line in the screen. This is what VSCode does.

**Expected Behavior**

Winbar shows the symbol of the first line in screen. No mater where my cursor move, as long as the first line in the screen is unchanged, the winbar keep unchanged.

**Actual Behavior**

Currently the winbar shows symbol context of cursor line. It changes with the moving of my cursor.

**Neovim Built in Behavior**

N/A

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: 
- lspsaga commit: 

</details>

**Comment by glepnir** [comment]
can you post a image that what does vscode do it ?

**Comment by fjchen7** [comment]
<img width="783" alt="image" src="https://user-images.githubusercontent.com/10106636/203793694-bb750a25-6e68-4509-8543-6c5d5477d6f7.png">

I may mistake. The red rectangle (this is not winbar) in the screenshot is the method signature where the code of the top half screen belongs to. I want to let it show in the neovim winbar.

BYW, currently neovim winbar (configure as README) shows the very inner block but not method name. In the below screenshot, the tail of winbar is `else->ok` but not method name `config_winbar_or_statusline`. I think this is not a good information as I can easily know where inner block the cursor is.

<img width="608" alt="image" src="https://user-images.githubusercontent.com/10106636/203795332-33693045-3b1e-4b41-a7fa-259b868d57dc.png">

**Comment by glepnir** [comment]
should be like a context bar.

**Comment by glepnir** [comment]
vscode also show `for` `if` etc in my test

![image](https://user-images.githubusercontent.com/41671631/204073410-158d892f-c9b5-4fa8-8b47-490f573e9b2f.png)

**Comment by fjchen7** [comment]
Mine is different fro yours. Seems it can be configured. Could `lspsaga.nvim` configure level of the context shown in winbar?

**Comment by glepnir** [comment]
in my opinion that the symbols like `if for while` etc no need to show in winbar. these symbols does not make sense..
