### ISSUE TITLE
May be a little problem about lsp finder ?

### ISSUE THREAD

**Issue by zengshenggit** [glepnir/lspsaga.nvim#609]
When i use lsp finder in vue file, part of the colorsheme lost , as below picture:
![微信截图_20221126181621](https://user-images.githubusercontent.com/21997717/204084256-73dda633-5792-42ea-8364-31233cd2f892.png)
But in other files (i tested in typescript and rust), it worked well:
![微信截图_20221126181707](https://user-images.githubusercontent.com/21997717/204085008-03a7e84d-06c2-46eb-8e4b-96d3280352ba.png)

**Comment by glepnir** [comment]
maybe missing the tag ? so the treesitter not parse it as well in preview buffer.  i will test it later .

**Comment by zengshenggit** [comment]
Does "missing the tag" mean that my original file has syntax errors? If this is the meaning, I am sure there are no syntax errors.

**Comment by glepnir** [comment]
No I mean that get preview content by using the line start number which will might lost some content like a tag `<script>` . so the treesitter can not parse it as well. then as you can see the code in script tag missing the highlight.

**Comment by zengshenggit** [comment]
Oh, i see.

**Comment by glepnir** [comment]
yup. so there may need do some work on preview buffer with treesiter.

**Comment by zengshenggit** [comment]
okay.
