### ISSUE TITLE
there are some typos in Readme file which must be considered

### ISSUE THREAD

**Issue by rustiever** [glepnir/lspsaga.nvim#61]
- _nnoremap <silent> [e :Lspsaga lsp_jump_diagnostic_next<CR>
nnoremap <silent> ]e :Lspsaga lsp_jump_diagnostic_prev<CR>_
 instead of 
**nnoremap <silent> [e :Lspsaga diagnostic_jump_next<CR>
nnoremap <silent> ]e :Lspsaga diagnostic_jump_prev<CR>**

- nnoremap <silent> <A-d> :Lspsaga open_float_terminal<CR>
tnoremap <silent> <A-d> <C-\><C-n>:Lspsaga close_float_terminal<CR>
 instead of 
**nnoremap <silent> <A-d> :Lspsaga open_floaterm<CR>
tnoremap <silent> <A-d> <C-\><C-n>:Lspsaga close_floaterm<CR>**

**Comment by glepnir** [comment]
fixed
