### ISSUE TITLE
Recursive Hover Docs 

### ISSUE THREAD

**Issue by fraso-dev** [glepnir/lspsaga.nvim#615]
**Is your feature request related to a problem? Please describe.**
As I'm currently learning Rust, I found myself jumping alot between docs online and hover_docs windows (because of examples provided in the LSP that I'm using)..
It would be extremely useful to have recursive calls to hover_docs to "dig deeper" when hovering docs. 
So, for example if I'm inside a hover_doc window (pressing H twice in my case), I'd move inside that window searching for another keyword to "hover". Another H would open another window hovering last hovered keyword (this time inside hover window)

**Describe the solution you'd like**
I't would be really nice to have a kind of a stack to open a reference to the last hover_doc call (with stacking windows), that keeps focus on last call and when user closes that window (in my  case mapped on q), the focus would be back on the first available window untill all of those are closed. It'd be considerable (adopting the stack solution) to map a "Q" command to close all opened windows at once.

**Comment by glepnir** [comment]
behavior a little same as lspsaga peekd_definition .  just use a double linkedlist.
