### ISSUE TITLE
Lsp finder can be slow and throw errors in larger projects

### ISSUE THREAD

**Issue by KingEdwardI** [glepnir/lspsaga.nvim#616]
### Description

I'm running into an issue where the Lsp finder will either time out, or throw errors, when working in a project with >100k files (when you include node_modules) -- More specifically it seems to have to do with how many references are found. With some debugging I found that it would usually throw when trying to open anywhere between ~180 - ~220 references. I tried updating the `finder_request_timeout`, and it only started to work once setting that to 20s. However that just brought me to a new problem, where an error was thrown about too many files open. I also noticed that it spawned a new tsc instance, seems to be one for each file that gets opened. After it has been opened once, successfully or with errors, it continues to work as expected, though it's still slow.

I tried making an attempt to fix it by adding a `pcall` to loading the buffer in [`finder.lua`](https://github.com/glepnir/lspsaga.nvim/blob/2eb8d023790099b182ac0c43d13dede80f42153e/lua/lspsaga/finder.lua#L266), but would still run into issues about "lots of files open".

<details>
<summary>Error screenshots</summary>

This is after updating the timeout

![Screen Shot 2022-12-05 at 10 15 32 AM](https://user-images.githubusercontent.com/20171781/205700356-c53cdea3-d18c-47b8-8ea8-d0cd25bd27a6.png)

![Screen Shot 2022-12-05 at 10 17 29 AM](https://user-images.githubusercontent.com/20171781/205700795-432d517a-b6c4-4f7b-a5f6-bbacfc7a0efc.png)

lots of tsc processes, bogging down my whole pc.

<img width="1769" alt="Screen Shot 2022-12-05 at 10 20 16 AM" src="https://user-images.githubusercontent.com/20171781/205701495-a6b76c5a-2506-409c-be93-e7759aa988e8.png">

</details>

**Expected Behavior**

Lsp finder doesn't time out, or at least doesn't throw errors.

**Actual Behavior**

Errors are thrown.

**Neovim Built in Behavior**

Running `lua vim.lsp.buf.references()` sometimes takes a few seconds the first time it is run, but no errors are thrown.

### Details

<details><summary>Reproduce</summary>

1. [minimal config](https://gitlab.com/KingEdwardI/neovim-config/-/tree/lspsaga-mvp). Just lspsaga and the lsp helpers I have.
2. Clone a large TS project, I used [material ui](https://github.com/mui/material-ui)
3. Open a file that has a `React.forwardRef` in it (I went to `packages/mui-lab/DesktopTimePicker/DesktopTimePicker.tsx`).
4. With the cursor on `forwardRef` run `Lspsaga lsp_finder`
5. See errors thrown in messages output

</details>

<details><summary>Environment</summary>

- nvim --version output: 0.8.0
- Operating system: macOS (Monterey)
- lspsaga commit: 2eb8d023790099b182ac0c43d13dede80f42153e

</details>

**Comment by glepnir** [comment]
look at your pic ..there is no lspsaga error throw out.. but  I will try your reproduce step.

**Comment by glepnir** [comment]
look at your pic ..there is no lspsaga error throw out.. but  I will try your reproduce step.

**Comment by KingEdwardI** [comment]
The error I'm referring to is the

```
...site/pack/packer/opt/lspsaga.nim/lua/lspsaga/finder.lua:266 in function 'create_finder_contents'
```

<details>
<summary>Here's another screenshot with a more direct error message:</summary>

![Screen Shot 2022-12-06 at 11 38 33 AM](https://user-images.githubusercontent.com/20171781/205994368-4c2afdb4-e27a-477a-8d67-c8fc0f7a3200.png)
</details>

From what I can tell, the root of the issue is that as the finder window is being opened and collecting the files to show, it's also loading them into different buffers. So if there are hundreds of files to open, they are opened in rapid succession. This spawns separate tsc, eslint, etc processes for each of those files and that takes up a lot of memory. (I would imagine that with 32 gigs of ram that I could have a few hundred files open without issue.) Once the buffers have been loaded it can calm down to using a single process and all of the spawned processes are closed, freeing up the memory so that the files can be viewed.

One possible solution I can think of is to simply collect the references, but not load the buffer until it is hovered over in the finder menu - essentially lazy load the files. I'm not very well versed in writing plugins though, so I'm not sure if that's a viable way to go about it.

I'm more than happy to help out, this is a great plugin, I just want to make sure the solution is solid, viable, and aligns with the plugin's focus.

**Comment by TheFox666** [comment]
Can confirm have timeout problems in big projects as well.

**Comment by glepnir** [comment]
please wait the pr #586
