### ISSUE TITLE
Lightblub duplicated

### ISSUE THREAD

**Issue by XXiaoA** [glepnir/lspsaga.nvim#617]
### Description
If we have a light bulb sign in current window, then enter another window. There Are duplicated signs like this:

https://user-images.githubusercontent.com/62557596/206843880-37e82c58-3f5d-4232-8b6c-ebf54d2bc7c4.mp4

**Expected Behavior**
Only one sigh in all windows

**Actual Behavior**
Duplicated sighs

### Details

</details>

<details><summary>Environment</summary>

- nvim --version output:  nightly
- Operating system:  arch linux
- lspsaga commit: last

</details>

**Comment by glepnir** [comment]
looks like you test in a same file?

**Comment by XXiaoA** [comment]
Yeah
