### ISSUE TITLE
Using outline feature crashes neovim

### ISSUE THREAD

**Issue by TheFox666** [glepnir/lspsaga.nvim#619]
### Description
When i try to use the outline feature (using in_custom or default setting doesn't matter) it crashes my neovim. I am working in a big php project, if that matters.

- It works in Lua Config files with lua
- Doesn't work in php with LSP intelephense

After crash it looks like this on terminal:
![image](https://user-images.githubusercontent.com/38280689/207016558-8ab58a2c-9692-4a86-89cc-e539c479a346.png)

**Expected Behavior**
<leader>o shows working outlines

**Actual Behavior**
opening outlines just crashes neovim completly, it freezes for a while then exits.

### Details
</details>

<details><summary>Environment</summary>

- nvim --version output: 
![image](https://user-images.githubusercontent.com/38280689/207004046-b14dd11b-a2c5-4392-b859-89b9492d9cc5.png)

- Operating system: 
![image](https://user-images.githubusercontent.com/38280689/207005650-a5111011-057f-4c39-a35c-d801de868ae7.png)

- lspsaga commit: 
latest

</details>

**Comment by glepnir** [comment]
see #586

**Comment by nerdo** [comment]
I am having the same issue, so I wonder if it is fully resolved.

It seems to work fine in other file types (I've only tried a few, namely js, ts, lua), but specifically php intelephense just hangs.

I scanned #586 but can't really make sense of what there was meant to fix it.
