### ISSUE TITLE
Add support of close_on_exit into outline

### ISSUE THREAD

**Issue by zhang-stephen** [glepnir/lspsaga.nvim#626]
**Is your feature request related to a problem? Please describe.**
If there is a buffer related to file, with outline window, now I want to exit nvim with `:q`, then the buffer will be closed but the outline window still is here...

**Describe the solution you'd like**
I want the outline window closes automatically when nvim exits.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by glepnir** [comment]
already support in #586  wait for merge.
