### ISSUE TITLE
Allow to overwrite all highlight groups in a colorscheme

### ISSUE THREAD

**Issue by socamacb** [glepnir/lspsaga.nvim#63]
Currently it is not possible to customize the colors of all highlight groups in a colorscheme. 

The problem is that `lspsaga.nvim` defines and overwrites all groups after calling `init_lsp_saga(opts)` with a call to https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/syntax.lua.

My current workaround is to copy the function found in `syntax.lua` and call my custom function after the call to `init_lsp_saga(opts)`

```lua
require("lspsaga").init_lsp_saga({
    use_saga_diagnostic_sign = false,
    rename_prompt_prefix = '>',
    max_diag_msg_width = 80,
})

-- color scheme can not be used as the lspsaga plugin would overwrite the colors again
-- this function gets called after the lspsaga plugin was loaded and defines the final colors
require("settings.lspsaga").overwrite_highlight()
```

It would be nice if all the highlight groups used by the plugin can be overwritten in a colorscheme instead of calling a custom function after the plugin was loaded.

This relates to:
- #41
- #42

**Comment by glepnir** [comment]
you can use `hi LspSagaxxxx your color here` after `init_lsp_saga`

**Comment by socamacb** [comment]
That is exactly what I do with the `overwrite_highlight()` function to change all colors in Lua. But it would be nice to set these colors directly in my colorscheme which is possible with `LspSagaFinderSelection`.

**Comment by glepnir** [comment]
It's easy todo just move the all the syntax highlight to `plugin/lspsaga.vim`

**Comment by socamacb** [comment]
I am currently busy with work but I can create a pull request on the weekend if the ticket is still not done.

**Comment by glepnir** [comment]
It's okay  I will do it later.

**Comment by levouh** [comment]
Will moving things to `plugin/lspsaga.vim` still work in the case that the plugin isn't loaded on start? Say I have `lspsaga` in a `pack/*/opt/lspsaga.nvim/` folder. It won't get loaded until I explicitly load it, say on my `on_attach` for some `lsp-config` setup.

If you move the definitions to `plugin/lspsaga.vim`, my colorscheme will get loaded first, and then _when_ `lspsaga` gets loaded it will overwrite what my colorscheme setup, right?

Have you looked at something like `:h hlexists`? You could also consider setting them all up as links, as in the `:h hi-link`:

```
- If there are already highlight settings for the {from-group}, the link is
  not made, unless the '!' is given.  For a ":highlight link" command in a
  sourced file, you don't get an error message.  This can be used to skip
  links for groups that already have settings.
```

What do you think @glepnir?

**Comment by sblumentritt** [comment]
@levouh moving the groups to the vimscript file still works even when the plugin is not loaded on start. The current implementation has the problem that the colors are overwritten when the plugin is loaded.

The new approach uses the `default` argument. See `:highlight-default`:
```vimhelp
The [default] argument is used for setting the default highlighting for a
group.	If highlighting has already been specified for the group the command
will be ignored.  Also when there is an existing link.

Using [default] is especially useful to overrule the highlighting of a
specific syntax file.  For example, the C syntax file contains: >
	:highlight default link cComment Comment
If you like Question highlighting for C comments, put this in your vimrc file: >
	:highlight link cComment Question
Without the "default" in the C syntax file, the highlighting would be
overruled when the syntax file is loaded.
```
