### ISSUE TITLE
Is there a way I can detect if lspsagafinder is opening?

### ISSUE THREAD

**Issue by YuCao16** [glepnir/lspsaga.nvim#630]
**Is your feature request related to a problem? Please describe.**
No

I tried `echo bufwinnr('lspsagafinder')`, but it keeps return `-1`.

**Comment by glepnir** [comment]
that's buffer filetype so it that function not work.  you can use `getbufinfo` then traverse the bufnr  check the bufnr filetype equals to 'lspsagafinder'

**Comment by YuCao16** [comment]
> that's buffer filetype so it that function not work. you can use `getbufinfo` then traverse the bufnr check the bufnr filetype equals to 'lspsagafinder'

Would you mind give me more hints? I have no clue how to do it.

**Comment by glepnir** [comment]
```lua
local buffers = vim.fn.getbufinfo()
for _, data in pairs(buffers) do
   if vim.bo[data.bufnr].filetype == 'lspsagafinder' then
         do your stuff
   end
end

```

**Comment by YuCao16** [comment]
> ```lua
> local buffers = vim.fn.getbufinfo()
> for _, data in pairs(buffers) do
>    if vim.bo[data.bufnr].filetype == 'lspsagafinder' then
>          do your stuff
>    end
> end
> ```

Thanks for your help!
