### ISSUE TITLE
Codeaction function errors if there are no available on given line

### ISSUE THREAD

**Issue by akinsho** [glepnir/lspsaga.nvim#64]
I've noticed when trying to use the code action commands in a `lua` file with `sumneko_lua` lsp if there aren't any available at the current postion.
```lua
require('lspsaga.codeaction').code_action()
require('lspsaga.codeaction').range_code_action()
```
I get `Error executing lua ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:27: bad argument #1 to 'pairs' (table expected, got nil)`, it works fine if I happen to use the mapping in a position where there is a valid code action.

I think it would be better if this function did not error and was able to gracefully handle being called where there aren't any code actions

**Comment by glepnir** [comment]
Got it .fixe it now.

**Comment by glepnir** [comment]
question is which code snippet that you got this error. I tried it with a no error line .nothing happened.

**Comment by akinsho** [comment]
@glepnir it happens *a lot* for me, I'll try and find some examples

**Comment by glepnir** [comment]
can you test now..a easy patch.

**Comment by akinsho** [comment]
Here's a random example
```lua
  local sumneko<cursor_here>_binary = sumneko_path .. "/bin/" .. vim.g.system_name .. "/lua-language-server"
```

**Comment by akinsho** [comment]
When I press code action at that point I see the error, you can just fake those other variables if you want

**Comment by glepnir** [comment]
![finder](https://user-images.githubusercontent.com/41671631/106868853-416e1780-670a-11eb-8a0b-570c7eb09fba.gif)

**Comment by akinsho** [comment]
I just tried the same and got the error so must be something about my setup. My config is
```lua
  local function get_lua_runtime()
    local result = {
      -- This loads the `lua` files from nvim into the runtime.
      [fn.expand("$VIMRUNTIME/lua")] = true,
      [fn.expand("$VIMRUNTIME/lua/vim/lsp")] = true
    }
    for _, path in pairs(api.nvim_list_runtime_paths()) do
      local lua_path = path .. "/lua"
      if fn.isdirectory(lua_path) > 0 then
        result[lua_path] = true
      end
    end
    return result
  end

local servers = {
	sumneko_lua = {
      cmd = {sumneko_binary, "-E", sumneko_path .. "/main.lua"},
      settings = {
        Lua = {
          diagnostics = {globals = {"vim"}},
          completion = {keywordSnippet = "Both"},
          runtime = {
            version = "LuaJIT",
            path = vim.split(package.path, ";")
          },
          awakened = {cat = true},
          workspace = {
            maxPreload = 1000,
            preloadFileSize = 1000,
            library = get_lua_runtime()
          }
        }
      }
    }
}
```

**Comment by akinsho** [comment]
![lsp_saga_ca](https://user-images.githubusercontent.com/22454918/106869594-077c2180-66c8-11eb-8129-99ad0fda6edb.gif)

**Comment by glepnir** [comment]
Ok i test your config now. btw did you update lua langserver?

**Comment by akinsho** [comment]
Yeah I updated it just yesterday since something was fixed I wanted to try out but I was having this error before that, as a side note I also tried commenting out most of my settings apart from the diagnostic key and it made no difference so it might be related to the version of `sumneko_lua`

**Comment by glepnir** [comment]
Now I will add a debug option to see what response you got.

**Comment by glepnir** [comment]
Now you can set `debug = true` in init_lsp_saga. and it will print the response. post here.

**Comment by akinsho** [comment]
@glepnir this is the error I get, not I'm using `efm-language-server` as well as `sumneko_lua` so maybe that is causing this as well?
![image](https://user-images.githubusercontent.com/22454918/106883537-05ba5a00-66d8-11eb-99b5-983ea6738797.png)

**Comment by akinsho** [comment]
Ahhhh, off the back of that I just tried commenting out `efm-language-server` and the errors stop

**Comment by glepnir** [comment]
Okay we need match this response.

**Comment by glepnir** [comment]
Now should be work.

**Comment by akinsho** [comment]
@glepnir that didn't work unfortunately 😢

**Comment by glepnir** [comment]
How about now?

**Comment by akinsho** [comment]
Yep that works now 🚀 thanks 👍🏿

**Comment by zelphir** [comment]
still getting a similar error using tsserver and efm:
```
[Lspsaga] Server return wrong response
E5108: Error executing lua ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:27: bad argument #1 to 'pairs' (table expected, got nil)
```

**Comment by glepnir** [comment]
I don't use efm. test tsserver with lspsaga code action works fine.

**Comment by akinsho** [comment]
@zelphir try adding the `debug = true` to your `lspsaga` options and posting the result that might give some indication of whats going on. Also this is a bit of a given but I'm assuming your running the latest version of the plugin after @glepnir added the fix right.

**Comment by zelphir** [comment]
yes I'm on latest `main` (985bcf3), added debug, but it just prints `nil`

```
nil
[Lspsaga] Server return wrong response
E5108: Error executing lua ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:27: bad argument #1 to 'pairs' (table expected, got nil)
Press ENTER or type command to continue
```

**Comment by zelphir** [comment]
not sure can help but this plugin https://github.com/RishabhRD/nvim-lsputils is working fine

**Comment by zelphir** [comment]
I tried playing around and I can get the result using the async function, the sync function always returns `nil`, this line here: https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/codeaction.lua#L81 is using `buf_request_sync`, why not using the async version `buf_request`? @glepnir

**Comment by glepnir** [comment]
I had test it with tsserver. works fine. so shoudle be there has some problem with efm. `buf_request_sync` is based on `buf_request` only await all the response .

**Comment by iduuck** [comment]
I still have this issue sometimes with `typescript-language-server`.

**Comment by glepnir** [comment]
@iduuck I think you use lspsaga fork version ? I don't have this indicator file

**Comment by iduuck** [comment]
Right! I was using the @tami5 fork, because this was maintained. Will check back again, and report.
