### ISSUE TITLE
outline and winbar symbol error 

### ISSUE THREAD

**Issue by JuanZoran** [glepnir/lspsaga.nvim#643]
### Describe the bug

- I just update this plugin, and I use lspsaga outline to get these messages:
Do you know how I can fix that?
```Lua
Error executing vim.schedule lua callback: vim/_meta.lua:0: unknown option 'stc'
stack traceback:
	[C]: in function 'nvim_get_option_value'
	vim/_meta.lua: in function '__index'
	...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/outline.lua:60: in function 'set_local'
	...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/outline.lua:153: in function 'create_outline_window'
	...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/outline.lua:413: in function 'render_outline'
	...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/outline.lua:208: in function 'handler'
	/usr/share/nvim/runtime/lua/vim/lsp.lua:1391: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```
- I use lualine for winbar processer and I add these code in lualine config, I get these:
```lua
        lualine_c = {
            {
                -- require('lspsaga.symbolwinbar'):get_winbar(),
                -- on_click = handler,
            },
        },

Error in packer_compiled: ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:2: attempt to index field 'config' (a nil value)
```
thanks for your reply

### Steps to reproduce

- add `        lualine_c = {
            {
                -- require('lspsaga.symbolwinbar'):get_winbar(),
                -- on_click = handler,
            },
        },
` into lualine config
- use `lspsaga outline` in some lua file 

### Expected behavior

just like the screenshot in the readme

### Neovim version (nvim -v)

NVIM v0.9.0-dev-635+gc19bd47c0

### Operating system/version

Ubuntu 22.04

### Terminal name/version

kitty release

### $TERM environment variable

xterm-256color

**Comment by glepnir** [comment]
update your neovim version stc merged recently
