### ISSUE TITLE
Support  Project Level Rename

### ISSUE THREAD

**Issue by glepnir** [glepnir/lspsaga.nvim#645]
Currently I had write the project level rename code except the ui .  it's use rg to search the target word in whole project  it's async and fast so you don't need worry about the speed.  before i write ui , I want ask here. do we need this? sometimes Lsp rename not works fine with me and slow  .. any suggestions?

**Comment by johnmathews** [comment]
project level rename would be very helpful, for sure. Thank you for a great plugin.

**Comment by glepnir** [comment]
then need think about ui and how to works with lsp. because both async some file data need sync

**Comment by HendrikPetertje** [comment]
greplace has a nice-ish flow I think.... 

what it does:

1. You start greplace by either searching for something or replacing it straight away
2. You rename something and it opens up a buffer showing all lines in all files that will be replaced. you can make some edits in it too to get out inconsistencies or filter missmatches
3. You perform the :Greplace command
4. Greplace opens all the files in the background, makes the edit and leaves them unsaved. 
5. Greplace outputs a message (print) telling you to either go through your open buffers or to assert the ":wall" command.


What I like about that flow is that it kind of gets the job done (I don't care too much for, but it is not saving; but rather allowing someone to execute :wall is a nice touch)

COC also implements a global rename, it saves all the files on edit; but it is mostly just based on the implementation of VScode i think.

**Comment by glepnir** [comment]
all logic code had wrote. currently in my case it run after lsp rename . then pop up a window show all other matches then you can choice the file which you don't want rename then just `dd` to delete then press enter .

**Comment by glepnir** [comment]
80 % complete .
