### ISSUE TITLE
Lspsaga stopped working after latest update

### ISSUE THREAD

**Issue by bwilytsch** [glepnir/lspsaga.nvim#646]
### Describe the bug

I am seeing the following error after upgrading to the latest version. For any action, I've tried. Still pretty new to nvim, so my apology if this is an easy fix.

```
Error executing vim.schedule lua callback: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/window.lua:152: invalid key: title
stack traceback:
        [C]: in function 'nvim_open_win'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/window.lua:152: in function 'create_win_with_border'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:377: in function 'render_finder_result'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:244: in function 'render_finder'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:169: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>the 
```

### Steps to reproduce

via `Packer`

```
use({
    "glepnir/lspsaga.nvim",
    branch = "main",
    config = function()
        require('lspsaga').setup({})
    end,
})
```

### Expected behavior

Open the buffer in a modal.

### Neovim version (nvim -v)

v0.9.0-dev-16-g56998feeb-dirt

### Operating system/version

mac0S 12.6.2

### Terminal name/version

Kitty

### $TERM environment variable

xterm-256color

**Comment by glepnir** [comment]
your neovim 0.9 is old update

**Comment by bwilytsch** [comment]
I am using the latest version from yesterday. Would you be able to point me to the one I should use?

https://github.com/neovim/neovim/releases

**Comment by glepnir** [comment]
your neovim version is `v0.9.0-dev-16-g56998feeb-dirt` the latest is `NVIM v0.9.0-dev-672+g4876654d4-dirty `

the head version will release every day.  your version is old.

**Comment by bwilytsch** [comment]
Thank you!
