### ISSUE TITLE
lspsaga braking changes

### ISSUE THREAD

**Issue by RiteshChepuri** [glepnir/lspsaga.nvim#647]
### Describe the bug

![Screenshot 2023-01-13 191948](https://user-images.githubusercontent.com/81766942/212336167-e8bdfdf1-7ff7-433a-8d5e-fdc5ff3d5e93.png)

### Steps to reproduce

local saga_status, saga = pcall(require, "lspsaga")
if not saga_status then
  return
end

saga.init_lsp_saga({
  move_in_saga = { prev = "<C-k>", next = "<C-j>" },
  finder_action_keys = {
    open = "<CR>",
  },
  definition_action_keys = {
    edit = "<CR>",
  },
})

### Expected behavior

lsp saga 

### Neovim version (nvim -v)

0.8.2

### Operating system/version

wsl ubuntu 22.04

### Terminal name/version

Windows terminal 1.15.3466.0

### $TERM environment variable

xterm

**Comment by glepnir** [comment]
you don't need copy all config . just set the modified options into setup function it will extend into default config

**Comment by RiteshChepuri** [comment]
Got it, Thank you.

**Comment by CharlesEkkel** [comment]
Just as an addendum, I had this issue and went looking in the readme (I assume it functions as the docs for lspsaga) but couldn't find a mention of this change. Is there a changelog for releases somewhere with migration advice? If not, is that something worth looking into? Either way, thanks for the example @MrMineDe :smile: 

And I do really like the more organised config style.

**Comment by glepnir** [comment]
`:h lspsaga`
