### ISSUE TITLE
[outline] there already have a request for outline please wait

### ISSUE THREAD

**Issue by max107** [glepnir/lspsaga.nvim#648]
### Describe the bug

```
Error executing Lua callback: ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/outline.lua:449: Invalid buffer id: 11
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/outline.lua:449: in function 'render_outline'
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/outline.lua:511: in function 'outline'
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:38: in function <...e/pack/packer/start/lspsaga.nvim/lua/lspsa
ga/command.lua:37>
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:60: in function 'load_command'
        ...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:8: in function <...m/site/pack/packer/start/lspsaga.nvim/plugi
n/lspsaga.lua:7>
```

![Jan-13-2023 21-15-07](https://user-images.githubusercontent.com/862272/212340556-51237d96-bf79-4a1f-9eb5-5aef72b62d1e.gif)

### Steps to reproduce

open nvim, run `:Lspsaga outline`, open another file. Boom.

### Expected behavior

outline refreshed without error )

### Neovim version (nvim -v)

NVIM v0.8.2

### Operating system/version

macOS 13.1

### Terminal name/version

alacritty 0.11.0 (8dbaa0b), iterm

### $TERM environment variable

screen-256color, xterm-256color

**Comment by eXvimmer** [comment]
The last update is completely buggy. After running lspsaga hover_doc and seeing info, I cannot use ctrl-f and ctrl-b to scroll through buffers.

**Comment by glepnir** [comment]
looks like it will appear when you jump into a tree window.

**Comment by max107** [comment]
> looks like it will appear when you jump into a tree window.

Need just to open another file / buffer to reproduce this bug. With / without tree behavior is identical.

**Comment by max107** [comment]
If we close outline before open new file - no error. For reproduce outline should be opened.

**Comment by max107** [comment]
perfect 🙏

**Comment by glepnir** [comment]
@eXvimmer  open hover then press <C-f> <C-b> can't work ? in my test it works . if you still get this scroll bug please open a new issue.

![diagnostic](https://user-images.githubusercontent.com/41671631/212348624-b209bcb2-f6f9-4439-ba07-2e5935e3acd7.gif)

**Comment by eXvimmer** [comment]
@glepnir Hi, sorry for late response.
The scrolling stops **after** running hover_doc.
[Screencast from 01-13-2023 10:23:43 PM.webm](https://user-images.githubusercontent.com/30720669/212397436-cbc6990e-5f2f-483e-814f-c0cf475e8e28.webm)

**Comment by glepnir** [comment]
@eXvimmer  fixed

**Comment by eXvimmer** [comment]
@glepnir thanks, it works
