### ISSUE TITLE
Code actions action keys

### ISSUE THREAD

**Issue by sharksforarms** [glepnir/lspsaga.nvim#65]
I would be nice to have a configuration similar to `finder_action_keys` for the code actions menu. I use `<ESC>` to close instead of `q` and would like to keep it consistent

For example here's what I have in my config:
```
    finder_action_keys = {
     open = '<CR>', vsplit = 'v', split = 's', quit = '<ESC>'
    },

```

**Comment by glepnir** [comment]
now you can use `quit = '<ESC> or quit = {'<ESC>','q'}`

**Comment by sharksforarms** [comment]
Hey @glepnir , that's a nice feature, thanks! What I mean with this issue is that currently the "Code Actions" menu can only be closed with "q" and not is not configurable:
https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/codeaction.lua#L62

**Comment by glepnir** [comment]
hmm like this option? `  code_action_quit_key = 'q',`

**Comment by sharksforarms** [comment]
What about `code_action_keys = { quit = 'q' or {'<ESC>', 'q', ..}, execute = '<CR>', }` that way you can add more later if needed

**Comment by glepnir** [comment]
I don't want to make the configuration too complicated

**Comment by glepnir** [comment]
I am think about why we need two keys to quit window?

**Comment by sharksforarms** [comment]
> I don't want to make the configuration too complicated

Fair enough!

> I am think about why we need two keys to quit window?

I don't, but I thought you implemented it: https://github.com/glepnir/lspsaga.nvim/issues/65#issuecomment-773744754

I'm ok with a single way to quit.

**Comment by glepnir** [comment]
Now support it with `code_action_keys = { quit = 'q',exec = '<CR>' }`. update.

**Comment by sharksforarms** [comment]
Hitting this:
https://github.com/glepnir/lspsaga.nvim/blob/df33f45872f3d3fb16be7aceccf5f564991891d1/lua/lspsaga/init.lua#L36

Also the apply function doesn't seem to be called, should it be called here? 
https://github.com/glepnir/lspsaga.nvim/blob/df33f45872f3d3fb16be7aceccf5f564991891d1/lua/lspsaga/codeaction.lua#L60

Typo `appely` -> `apply`

**Comment by glepnir** [comment]
..my fault.

**Comment by glepnir** [comment]
fixed.
