### ISSUE TITLE
Any solution to disable "new style" of popups?

### ISSUE THREAD

**Issue by max107** [glepnir/lspsaga.nvim#650]
<img width="144" alt="image" src="https://user-images.githubusercontent.com/862272/212352651-0c014c07-5702-4938-9ad8-7a18f97056f6.png">

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/862272/212352551-63a33314-76ea-4467-b374-c7a90d9bff23.png">

**Comment by glepnir** [comment]
did you configed  DiagnosticError DiagnosticWarn DiagnsoticInfo DiagnosticHint highlight ?

**Comment by glepnir** [comment]
it's highlight group should be configed by colorscheme not plug

output is what `:hi DiagnsoticError`

**Comment by max107** [comment]
> output is what :hi DiagnsoticError

```
:hi DiagnosticError
DiagnosticError xxx ctermfg=1 guifg=Red
                   links to ErrorText
```

**Comment by max107** [comment]
Here is the same "new style" of popups https://github.com/glepnir/lspsaga.nvim/issues/653
