### ISSUE TITLE
Misconfigured keymaps in Example conf

### ISSUE THREAD

**Issue by mannjaro** [glepnir/lspsaga.nvim#651]
In example configuration, Float terminal keymaps is described as follows
```lua
-- Float terminal
keymap({"n", "t"} "<A-d>", "<cmd>Lspsaga term_toggle<CR>")
```

But this doesn't work, so it should be changed as follows
```lua
keymap({"n", "t"}, "<A-d>", "<cmd>Lspsaga term_toggle<CR>")
```

**Comment by glepnir** [comment]
hmm which different ?

**Comment by mannjaro** [comment]
I added a comma between {"n", "t"} and "<A-d>"

**Comment by glepnir** [comment]
oh I saw it . good catch.
