### ISSUE TITLE
[outline] another bug

### ISSUE THREAD

**Issue by max107** [glepnir/lspsaga.nvim#652]
### Describe the bug

```Error executing vim.schedule lua callback: ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/outline.lua:305: Invalid buffer id: 6
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/outline.lua:305: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
Press ENTER or type command to continue```

![output](https://user-images.githubusercontent.com/862272/212354886-d518f2c0-b360-463b-985d-b9df26270a93.gif)



### Steps to reproduce

Open buffer, open outline, close buffer without closing outline, open another buffer

### Expected behavior

idk, no error?

### Neovim version (nvim -v)

NVIM v0.8.2

### Operating system/version

macOS 13.1

### Terminal name/version

iterm / alacritty

### $TERM environment variable

screen-256color, xterm-256color

**Comment by max107** [comment]
https://user-images.githubusercontent.com/862272/212355001-b1dbf6fe-305a-4015-8d67-33da03242ca7.mov

**Comment by max107** [comment]
@glepnir Nope, reopen it or i need create another issue? Current behavior is so strange.

If i current buffer tree is also closed.

https://user-images.githubusercontent.com/862272/212363919-fda57aa8-c105-457b-8c0e-f99234cbe2ec.mov

**Comment by glepnir** [comment]
because I don't use file tree plugin. so just fix in my mind.  fix when i wake-up. sleep time

**Comment by max107** [comment]
ok, thanks

**Comment by max107** [comment]
https://user-images.githubusercontent.com/862272/212367394-2804dae6-642e-44bf-bb31-0871baba345d.mov

+1 bug

**Comment by max107** [comment]
another bug without any tree plugins (and without my ugly MR above), only netrw


https://user-images.githubusercontent.com/862272/212370100-cae53db5-bfd3-416a-ae0a-d6543b9ddcc1.mov

**Comment by max107** [comment]
https://user-images.githubusercontent.com/862272/212465774-373fddf8-abae-45d8-86c0-aca73eef4a7d.mov

Nope, bug is still here.

**Comment by glepnir** [comment]
which commit ?

**Comment by max107** [comment]
949234a450f6dd14fc3f9e482d69a049cf1d27c2

https://user-images.githubusercontent.com/862272/213158011-11e915c8-060a-4e8b-a7ed-4d54e3d64431.mov

**Comment by max107** [comment]
if we wait lsp started and call `:Lspsaga outline` then outline buffer is closed correctly. If we try to run outline before lsp is started, after close buffer and open outline in another file we see 2 outlines.

Sorry for my bad english

**Comment by glepnir** [comment]
I think all of user will run this command after lsp initialzed..

**Comment by max107** [comment]
nope, is not working 
<img width="761" alt="image" src="https://user-images.githubusercontent.com/862272/213536969-87c2fe5e-d647-41c1-b18d-2d04b4db8a23.png">

same use case. `Lspsaga outline`, then lsp started and nothing...

**Comment by glepnir** [comment]
cant reproduce
