### ISSUE TITLE
Quick move to "code action' section in the lates diagnostic style

### ISSUE THREAD

**Issue by zsmatrix62** [glepnir/lspsaga.nvim#653]
Hey,

If it's possible to move quickly to the code action section in the new style of diagnostic? currently I have to type several "j" keys to move to execute the fix: 

Thanks!

<img width="638" alt="image" src="https://user-images.githubusercontent.com/2951879/212355088-7ea2c294-52bd-44b2-b2ce-8af8f8dfc218.png">

**Comment by glepnir** [comment]
can support a new keymap in this buffer that quickly jump to action.
