### ISSUE TITLE
Lspsaga show_line_diagnostics not working

### ISSUE THREAD

**Issue by yeseongmoon** [glepnir/lspsaga.nvim#655]
### Describe the bug

when I try to do "show line diagnostics", it gives me the error.
My config
require("lspsaga").setup({
	ui = {
		theme = "round",
		border = "double",
		winblend = 1,
	},
	-- keybinds for navigation in lspsaga window
	scroll_preview = {
		scroll_down = "<C-j>",
		scroll_up = "<C-k>",
	},
})
<img width="1210" alt="Screenshot 2023-01-14 at 12 58 47 AM" src="https://user-images.githubusercontent.com/20822372/212364398-45b8ffb4-0ed0-4f11-84dc-ebde0b32f3d1.png">

### Steps to reproduce

.

### Expected behavior

see the diagnostic message of a line

### Neovim version (nvim -v)

0.8.2

### Operating system/version

macOS 13.1 Ventura

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-256color

**Comment by glepnir** [comment]
example codes? I can't reproduce

**Comment by glepnir** [comment]
not working like what

**Comment by yeseongmoon** [comment]
> example codes? I can't reproduce

oops.  sorry
I just open a file, find an error, do Lspsaga show_line_diagnostics
and I get the error message above

**Comment by yeseongmoon** [comment]
> not working like what

when I source the lspsaga file, it shows the double border, but once I quit and restart the neovim, the border is not showing. probably because of the colorscheme? not sure, I'm new to neovim ..

**Comment by dane-harnett** [comment]
I'm also experiencing this problem, I think the trick to reproducing it is to cause a diagnostic that spans multiple lines and where its starting column on the first line is greater than the ending column on the last line.

I checked the line mentioned in the screenshot: https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/diagnostic.lua#L455

and printed out `entry` and found the `end_col` was indeed greater than the `start_col` but it was a different line.

**Comment by dane-harnett** [comment]
```
{
  bufnr = 1,
  code = "redundant-parameter",
  col = 18,
  end_col = 5,
  end_lnum = 50,
  lnum = 9,
  message = "This function expects a maximum of 0 argument(s) but instead it is receiving 1.",
  namespace = 37,
  severity = 2,
  source = "Lua Diagnostics.",
  user_data = {
    lsp = {
      code = "redundant-parameter"
    }
  }
}
```

an example `entry`

**Comment by glepnir** [comment]
so that's problem the `col > end_col`.. which column is wrong ?

**Comment by dane-harnett** [comment]
I've simplified my code to this:
```
local M = {}

function M.setup()
    local utils = require("daneharnett.utils")
    local status_ok, lspsaga = pcall(require, "lspsaga")
    if not status_ok then
        return
    end

    lspsaga.setup({
        --
    })
end
```

The error occurs when I show line diag on `lspsaga.setup({` and it doesn't matter which column my cursor is on
`echo col(".")` echos the current cursor position right?

the `entry` is... when my cursor is on column 1

```
{
  bufnr = 1,
  code = "redundant-parameter",
  col = 18,
  end_col = 5,
  end_lnum = 11,
  lnum = 9,
  message = "This function expects a maximum of 0 argument(s) but instead it is receiving 1.",
  namespace = 37,
  severity = 2,
  source = "Lua Diagnostics.",
  user_data = {
    lsp = {
      code = "redundant-parameter"
    }
  }
}
```

**Comment by glepnir** [comment]
this entry come from vim.diagnostic .so I think something wrong in neovim core..

**Comment by dane-harnett** [comment]
Yeah I think my lua language server is getting confused and thinks that `lspsaga.setup` is actually `M.setup`

**Comment by dane-harnett** [comment]
FYI
```
nvim --version
NVIM v0.9.0-dev-4818+gfd3d30a22-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by <redacted>

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-fd3d30a/share/nvim"

Run :checkhealth for more info
```

**Comment by glepnir** [comment]
just add a patch ......but still don't know why end_col will bigger than col  .

**Comment by glepnir** [comment]
> > not working like what
> 
> when I source the lspsaga file, it shows the double border, but once I quit and restart the neovim, the border is not showing. probably because of the colorscheme? not sure, I'm new to neovim ..

nope.  not relate colorscheme and i test with a min config. borde works fine when i change it in setup function. so there may something wrong in your config.

**Comment by dane-harnett** [comment]
@glepnir The latest patch has fixed my issue. It's worth noting that all three lines:
```
lspsaga.setup({
        --
    })
```
have underlines indicating that there is a diagnostic for the whole range, but `Lspsaga show_line_diagnostics` will only show something on the first line

**Comment by glepnir** [comment]
can paste the whole `entrys` and your lua language config .these line is correct looks like.

**Comment by dane-harnett** [comment]
Whole `entrys`:
```
{ {
    bufnr = 1,
    code = "redundant-parameter",
    col = 18,
    end_col = 5,
    end_lnum = 11,
    lnum = 9,
    message = "This function expects a maximum of 0 argument(s) but instead it is receiving 1.",
    namespace = 37,
    severity = 2,
    source = "Lua Diagnostics.",
    user_data = {
      lsp = {
        code = "redundant-parameter"
      }
    }
  } }
```

lua lsp config
```
    local runtime_path = vim.split(package.path, ";")
    table.insert(runtime_path, "lua/?.lua")
    table.insert(runtime_path, "lua/?/init.lua")

    lspconfig.sumneko_lua.setup({
        capabilities = capabilities,
        on_attach = on_attach,
        settings = {
            Lua = {
                runtime = {
                    version = "LuaJIT",
                    path = runtime_path,
                },
                diagnostics = {
                    globals = { "vim" },
                },
                workspace = {
                    library = vim.api.nvim_get_runtime_file("", true),
                },
                telemetry = {
                    enable = false,
                },
            },
        },
    })
```

**Comment by glepnir** [comment]
whole entrys only have one item ..so we can just show that one.  no problem with your lua langserver config. wired .

**Comment by dane-harnett** [comment]
All good, thanks for the quick fix for the error :)

**Comment by glepnir** [comment]
no problem :) close then.
