### ISSUE TITLE
outline unlock mode

### ISSUE THREAD

**Issue by BYT0723** [glepnir/lspsaga.nvim#658]
### Describe the bug

enter insert mode in outline buffer
![图片](https://user-images.githubusercontent.com/59989961/212371434-fbf0c7fb-883f-4055-92a2-7c76a4c81a9a.png)

### Steps to reproduce

- Lspsaga outline
- press o
- enter the insert mode

### Expected behavior

lock outline buffer mode

### Neovim version (nvim -v)

0.8.2

### Operating system/version

linux 5.15.86-1-lts

### Terminal name/version

alacritty 0.11.0

### $TERM environment variable

st-256color

**Comment by glepnir** [comment]
fixed
