### ISSUE TITLE
lsp_jump_diagnostic_next gets stuck

### ISSUE THREAD

**Issue by sharksforarms** [glepnir/lspsaga.nvim#66]
I'm trying to goto `err2` but the next function seems to stick to `err1` maybe because there's multiple errors on the line and it's looping back and forth on the same line? May be the same for prev.

![Peek 2021-02-04 13-51](https://user-images.githubusercontent.com/10912917/106941012-41f9b480-66f0-11eb-8026-151c5f54ce64.gif)

**Comment by glepnir** [comment]
@sharksforarms  are you config multiple syntax check?

**Comment by glepnir** [comment]
Did you config another syntax check tool? seems like not only rust-analyzer.

**Comment by sharksforarms** [comment]
It's only rust-analyzer, it's giving hints and error for the same line

**Comment by glepnir** [comment]
why I only get one error
![image](https://user-images.githubusercontent.com/41671631/107303266-b7330400-6ab9-11eb-9c14-f6b5963e4cf1.png)

**Comment by glepnir** [comment]
Update rust-analyazer got hint and error

**Comment by matu3ba** [comment]
> Update rust-analyazer got hint and error

Is there a table or something to check, what usability features which lsp supports? I have the same problem with clangd.

**Comment by glepnir** [comment]
@sharksforarms  can you confirm now works fine for you?

**Comment by sharksforarms** [comment]
Yes it's great!
