### ISSUE TITLE
:Lspsaga code_action not working under omnisharp lsp

### ISSUE THREAD

**Issue by mezdelex** [glepnir/lspsaga.nvim#660]
### Describe the bug

![image](https://user-images.githubusercontent.com/59997405/212414708-a77dece6-8d2b-415d-8527-c5e3fc88a7f4.png)

As shown in the image

EXTRA INFO:

![image](https://user-images.githubusercontent.com/59997405/212415281-ea611a6d-e5af-44c7-ac15-1e5e16540a83.png)

After pressing any key, the code_action window shows up like this

### Steps to reproduce

1. Go to random class method
2. Use code_action keymap vim.keymap.set('n', '<leader>.', ':Lspsaga code_action<CR>', opts)
3. Error appears

### Expected behavior

To open the code_actions window like before (it does actually after pressing any key)

NOTE: With Lua lsp server works properly and with typescript-language-server as well. Only happens with omnisharp-ls

### Neovim version (nvim -v)

NVIM v0.8.2

### Operating system/version

Windows 11 Pro

### Terminal name/version

Windows Terminal 1.15.221212005

### $TERM environment variable

-

**Comment by glepnir** [comment]
I just add a simple patch to avoid this error. but then you may not see the code action preview in some action line. I don't write .net  so if you can help with me that would be great. I just need the action result . so add. a debug print in there and 
do the step like reproduce `:message` to see the result. and paste here

```diff
diff --git a/lua/lspsaga/codeaction.lua b/lua/lspsaga/codeaction.lua
index e8d7f72..c26a315 100644
--- a/lua/lspsaga/codeaction.lua
+++ b/lua/lspsaga/codeaction.lua
@@ -314,6 +314,7 @@ function act:get_action_diff(num, main_buf)
   elseif action.edit.changes then
     text_edits = action.edit.changes[vim.uri_from_bufnr(main_buf)]
   end
+  print(vim.inspect(action))

   if not text_edits then
     return
```

**Comment by mezdelex** [comment]
![image](https://user-images.githubusercontent.com/59997405/212437758-096afbe9-f601-428a-a28a-25acca24a36e.png)

Don't know if this is what you need, hope it is. Thanks :)

**Comment by glepnir** [comment]
right then it's a command action so it can no preview .then nothing to do . thanks
