### ISSUE TITLE
:Lspsaga lsp_finder not working with omnisharp-ls

### ISSUE THREAD

**Issue by mezdelex** [glepnir/lspsaga.nvim#661]
### Describe the bug

![image](https://user-images.githubusercontent.com/59997405/212416510-40855c66-c2b9-46ae-8a9d-320d32203ed7.png)

As shown in the image

### Steps to reproduce

1. Go to random class in a .NET project
2. Use lsp_finder action vim.keymap.set('n', 'gh', ':Lspsaga lsp_finder<CR>', opts)
3. Error appears

### Expected behavior

To show definition/implementation/references window as before

### Neovim version (nvim -v)

NVIM v0.8.2

### Operating system/version

Windows 11 Pro

### Terminal name/version

Windows Terminal 1.15.221212005

### $TERM environment variable

-

**Comment by mezdelex** [comment]
![image](https://user-images.githubusercontent.com/59997405/212442119-f6b6590e-11a6-4f76-82dc-78ad2d743973.png)

screenshot of a working lsp_finder call in branch version_2.3 in a TS + Vue project

![image](https://user-images.githubusercontent.com/59997405/212442188-5f5f5efb-e46f-46b8-bfac-63ce393b1bf1.png)

screenshot of a working lsp_finder call in branch version_2.3 in a .NET/C# project

Notice the weird behaviour of omnisharp that even tho, the class obviously has a declaration, it returns that it doesn't fill the object with info (so lspsaga returns No Definition Found/No Implementation Found). Ask you could imagine, I can navigate anyways to declaration and implementation (both jump to the class) but the lsp_find() won't return them apparently with omnisharp. 

This is what, I guess, is breaking the lsp_find() call in main branch. The issue is still happening for me because as I said, the problem is that lspsaga assumes (with good criteria) that it should have declaration/implementation but it doesn't so it breaks in that point.

![image](https://user-images.githubusercontent.com/59997405/212442595-6dc66816-f57d-4fe0-b7e9-856c1318cf26.png)

![image](https://user-images.githubusercontent.com/59997405/212442611-8c88c0e3-550e-4a2b-8b15-7b62250051d8.png)

And this is the same action in main branch, even after the patch. As you can see there's no declaration/implementation.

Could it handle that strange behaviour like it did before? like just taking care of the references when for some reason there's no implementation/declaration return.

**Comment by glepnir** [comment]
definition not declaration . I think the vim.lsp.buf.definition also return nothing .finder just chang the ui relate

**Comment by mezdelex** [comment]
Yeah definition sorry. To go to definition/implementation I actually use the Telescope builtin picker so if there's more than 1 I prefer to handle them with Telescope interface. But lsp_find() of lspsaga was pretty handy for those references.

**Comment by glepnir** [comment]
hmmm if i can reproduce it on my local. i don't write .net

**Comment by glepnir** [comment]
currently all my project works fine ..so can you add some debug print then paste message for me would be better 
and I just add some patch hope can help you .

![image](https://user-images.githubusercontent.com/41671631/212462167-f3e40be1-8e89-4cd3-bbbe-f0cec0c55adc.png)

**Comment by mezdelex** [comment]
Yeah as much as you need. Where do you want me to debug, right before the ipairs? res, result? or before that.

**Comment by glepnir** [comment]
```lua
diff --git a/lua/lspsaga/finder.lua b/lua/lspsaga/finder.lua
index 9680576..a3b8dbd 100644
--- a/lua/lspsaga/finder.lua
+++ b/lua/lspsaga/finder.lua
@@ -259,6 +259,7 @@ local function get_msg(method)
 end

 function finder:create_finder_contents(result, method)
+  print(vim.inspect(result), method)
   self:get_file_icon()

   local contents = {}
```

**Comment by mezdelex** [comment]
![image](https://user-images.githubusercontent.com/59997405/212464119-f245622e-db9a-48fb-a70f-72be93460993.png)

Ohhhh I see, for some reason Omnisharp doesn't return the object format like 
`{
   {
    range = [
   ... ]
   },
  uri = "..."
}, {
  ...
}`

when they are only definition and implementation but just like a string literal before the location range lol...

**Comment by glepnir** [comment]
to be honest this result no respect the lsp spec. https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#location
