### ISSUE TITLE
After update of lspsaga, nothing don't work

### ISSUE THREAD

**Issue by honyani** [glepnir/lspsaga.nvim#662]
### Describe the bug

Hello! Today after update of lspsaga I started to have error on nvim launch and errors on lspsaga's actions.

### Steps to reproduce

:PackerSync (for installing latest lspsaga version)
:q
Launch nvim (first error on 1 screen) and after this try to use lsp saga (second screen)

### Expected behavior

Expect that all will work. Because I finished my nvim configuration few days ago and want to use it)

### Neovim version (nvim -v)

0.8.2

### Operating system/version

macOS 13.1

### Terminal name/version

kitty

### $TERM environment variable

xterm-256color

<img width="1254" alt="Снимок экрана 2023-01-14 в 03 17 45" src="https://user-images.githubusercontent.com/118450997/212441208-2720ef66-11a6-47a0-bc9d-47766e9a0f5f.png">

<img width="1594" alt="Снимок экрана 2023-01-14 в 03 18 35" src="https://user-images.githubusercontent.com/118450997/212441215-9841a019-2163-4e84-aa0b-3afed6a83e38.png">

**Comment by Feel-ix-343** [comment]
I think they changed the settings config. This is a pain

**Comment by glepnir** [comment]
did you change the lspsaga config follow 0.2.3 version?

**Comment by Feel-ix-343** [comment]
@glepnir I am working on it, but I can't find some specific settings. code_action_icon, custom_kind for example

**Comment by honyani** [comment]
@glepnir no. I wrote my config few days ago and all this time didn't open nvim. This is my config
<img width="1728" alt="Снимок экрана 2023-01-14 в 03 46 35" src="https://user-images.githubusercontent.com/118450997/212442237-2c089df7-06b3-4913-a882-e72ba9cb8cc1.png">
<img width="677" alt="Снимок экрана 2023-01-14 в 03 47 17" src="https://user-images.githubusercontent.com/118450997/212442278-7729a156-d139-43f1-a974-c017a6d9d987.png">

**Comment by glepnir** [comment]
please read doc new version is breakchange

**Comment by honyani** [comment]
@glepnir can you show me please what I did wrong or send me the section of documentation where is breakchange. I will be very grateful to you

**Comment by honyani** [comment]
@glepnir im newcomer in nvim world and its hard for me to understand this problem. please help
