### ISSUE TITLE
Support dynamic fold_level based on working directory

### ISSUE THREAD

**Issue by leaxoy** [glepnir/lspsaga.nvim#663]
Current symbol_in_winbar only support fixed folder_level, which is not enough, use dynamic fold_level when set fold_level to 0 or -1 or nil is a suitable alternative.

**Comment by glepnir** [comment]
nope lspsaga does not use fold . it's use treesitter based on ast level

**Comment by leaxoy** [comment]
What i describe is winbar file path, not the buffer code fold level
<img width="940" alt="image" src="https://user-images.githubusercontent.com/8556349/212458528-19826596-2fd9-4e13-91c7-069b12925c2f.png">
I'm open nvim in config dir, winbar show filepath with a fixed level(I config it to 5). 

But I think show file path start from cwd (should be lua/leaxoy/plugins/lspsaga.lua) is more reasonable.

**Comment by fent** [comment]
I'd like to do something similar as the above comment. I see that the `respect_root` option was added, but how can I set the project root in the config? is that up to the lsp or can I define it somewhere? I'd like to default it to cwd

**Comment by glepnir** [comment]
currently it will search the root from lsp client of this buffer .if not find the root it will use the cwd.

**Comment by fent** [comment]
is there a way to force the root to be cwd?
