### ISSUE TITLE
The window of outgoing_calls has the same color with buffer

### ISSUE THREAD

**Issue by YangEfei** [glepnir/lspsaga.nvim#665]
### Describe the bug

![image](https://user-images.githubusercontent.com/54932475/212448837-6d53bc8d-a8c3-42ae-ae3a-82b1fc86e28f.png)
I tried to use the new feature `Lspsaga outgoing_calls` just now.

I found that the float window of it is hard to find due to the color of it has the same color with the main buffer.
And there's not a border of it.

The color scheme which I use is tokoynight.
Maybe I can change the color of it by myself?

### Steps to reproduce

Have mentioned above.

### Expected behavior

Looks like here: https://github.com/glepnir/lspsaga.nvim#lspsaga-outgoing_calls
The float window of it has a different color. Or there's a border which I can identify it easily.

### Neovim version (nvim -v)

0.8.2

### Operating system/version

macOS 13.0

### Terminal name/version

iTerm2/3.5.0beta9

### $TERM environment variable

xterm-256color

**Comment by glepnir** [comment]
because it is same file bug of neovim
