### ISSUE TITLE
Get back old ui colors

### ISSUE THREAD

**Issue by ragu-manjegowda** [glepnir/lspsaga.nvim#667]
### Describe the bug

After the introduction of recent breaking changes we are forced to configure ui colors, it is additional overhead for those who use multiple themes (ex: I use solarized light during the day and solarized dark otherwise).

Looking for an option for fallback to (n)vim's color theme instead of using/configuring ui color via saga's config. 

Refer to this issue for screenshots - https://github.com/glepnir/lspsaga.nvim/issues/598

### Steps to reproduce

Default config should do.

### Expected behavior

Refer to this issue for screenshots - https://github.com/glepnir/lspsaga.nvim/issues/598

### Neovim version (nvim -v)

v0.8.2

### Operating system/version

Arch

### Terminal name/version

Alacritty

### $TERM environment variable

alacritty

**Comment by glepnir** [comment]
that's not relate ui. old ui still have this problem if you  open a same file in float window all colors and options will not take effect. and there has two ways to config the highlight one of is config ui.colors.  second way is same as before use highlight group find all highlight group in highlight.lua file I had introduce this in doc.
