### ISSUE TITLE
drop the hard dependency of treesitter for `hover_doc`

### ISSUE THREAD

**Issue by milanglacier** [glepnir/lspsaga.nvim#668]
### Describe the bug

Currently the `markdown` parser for treesitter is unmature. And there are many cases where treesitter markdown parser performs much worse than the traditional one.

For example for the python package documentation:

- `geopy.RateLimiter`, see the screenshot, the first one is `lspsage hover_doc`, the second one is `vim.lsp.buf.hover()`:

<img width="860" alt="Screen Shot 2023-01-14 at 03 00 18" src="https://user-images.githubusercontent.com/45728125/212462476-58f0429d-8dc2-465a-8335-ba30f554b596.png">

<img width="1439" alt="Screen Shot 2023-01-14 at 03 00 31" src="https://user-images.githubusercontent.com/45728125/212462473-0680bca6-242d-4269-8087-d6859108899d.png">

where treesitter markdown parser cannot even highlight the non-breaking space `%nbsp;` correctly.

### Steps to reproduce

That's it.

### Expected behavior

That's it.

### Neovim version (nvim -v)

0.8.2

### Operating system/version

macOS 12.6

### Terminal name/version

wezterm

### $TERM environment variable

xterm-256color

**Comment by glepnir** [comment]
why this is not a treesitter problem ?

**Comment by glepnir** [comment]
Oh I think we can handle the nbsp on lspsaga.
