### ISSUE TITLE
Odd floats when in narrow screen.

### ISSUE THREAD

**Issue by ckipp01** [glepnir/lspsaga.nvim#67]
I'm not sure what's the most helpful information to give you to chase this down, but please let me know what I can provide to help. My workflow involves often splitting my terminal with tmux so that nvim is only on half my screen. When this is done often any bigger floats get slammed up against the side. The border actually looks fine, but it's like the text shifts over a bit too far. Here is an example of what I mean while in Lua.

<img width="1680" alt="Screenshot 2021-02-04 at 20 38 43" src="https://user-images.githubusercontent.com/13974112/106946551-89506700-6729-11eb-95a4-5fbbf3d395e5.png">

Here is another example in Scala using Metals when I have full screen:

<img width="1680" alt="Screenshot 2021-02-04 at 20 40 32" src="https://user-images.githubusercontent.com/13974112/106946588-95d4bf80-6729-11eb-8710-c30a38b9b9c6.png">

However, if I then split my screen and do the hover on the same symbol it looks like this:

<img width="1680" alt="Screenshot 2021-02-04 at 20 41 01" src="https://user-images.githubusercontent.com/13974112/106946648-a71dcc00-6729-11eb-8e72-6cb2c8ed1def.png">

**Comment by glepnir** [comment]
I had notice this.. but I don't find a way to solve this ..

**Comment by glepnir** [comment]
a min code , increase the col value . the window does not move right .. not sure problem of upstream.
```lua
function move_right()
  local test_opts = {
    anchor = "NE",
    col = 10,
    height = 10,
    relative = "cursor",
    row = 2,
    style = "minimal",
    width = 31
  }
  local contents_bufnr = api.nvim_create_buf(false, true)
  api.nvim_buf_set_lines(contents_bufnr,0,-1,true,{'sssssssssssssssssssssssss','bbbbbbbbbbbbbbbbbbbbbbb'})
  local contents_winid = api.nvim_open_win(contents_bufnr, false, test_opts)
  return contents_bufnr, contents_winid
end
```

**Comment by glepnir** [comment]
@ckipp01 can you provide a min scala code that ca reproduce it. I think I found a way to solve this

**Comment by ckipp01** [comment]
For sure. Here is a minimal init file to use:

```lua
local cmd = vim.cmd
----------------------------------
-- PLUGINS -----------------------
----------------------------------
cmd [[packadd packer.nvim]]
require('packer').startup(function(use)
  use {'wbthomason/packer.nvim', opt = true}

  use {'glepnir/lspsaga.nvim'}
  use 'scalameta/nvim-metals'

end)

local saga = require 'lspsaga'
saga.init_lsp_saga()
----------------------------------
-- OPTIONS -----------------------
----------------------------------
vim.o.shortmess = string.gsub(vim.o.shortmess, 'F', '') .. 'c'

local function map(mode, lhs, rhs, opts)
  local options = {noremap = true, silent = true}
  if opts then
    options = vim.tbl_extend('force', options, opts)
  end
  vim.api.nvim_set_keymap(mode, lhs, rhs, options)
end

map('n', 'K', '<cmd>lua require"lspsaga.hover".render_hover_doc()<CR>')
----------------------------------
-- COMMANDS ----------------------
----------------------------------
-- LSP
cmd [[augroup lsp]]
cmd [[autocmd!]]
cmd [[autocmd FileType scala setlocal omnifunc=v:lua.vim.lsp.omnifunc]]
cmd [[autocmd FileType scala,sbt lua require("metals").initialize_or_attach({})]]
cmd [[augroup end]]
```

### Instruction to use with nvim-metals and Scala
1. Make sure to have [coursier](https://get-coursier.io/docs/cli-installation) installed as `nvim-metals` needs this to install Metals.
2. Clone https://github.com/ckipp01/metals-minimal-sbt
3. Open this while using the init file. You'll see the warning about Metals not being installed, so just do a `:MetalsInstall` which will install the latest Metals.
4. Restart Nvim
5. Open this file: https://github.com/ckipp01/metals-minimal-sbt/blob/master/src/main/scala/example/Hello.scala
6. You'll  see a popup to import you build. Do this and wait for indexing to complete.
7. Make sure your screen is split (not vim split, but like your terminal split or something to make it narrow) and do a hover on this line https://github.com/ckipp01/metals-minimal-sbt/blob/3fbf5bd99419086209adf839544937c44c446d9b/src/main/scala/example/Hello.scala#L33

At this point you should see this:

<img width="864" alt="Screenshot 2021-02-08 at 09 02 06" src="https://user-images.githubusercontent.com/13974112/107191821-0d864100-69ed-11eb-9edb-a8bd20011373.png">

Let me know if you need anything else.

**Comment by glepnir** [comment]
Thanks for your kind reply. no need lua code . I need this scala code.

**Comment by glepnir** [comment]
hmm seems like I can't get melas work..

**Comment by ckipp01** [comment]
> hmm seems like I can't get metals work..

What sort of issues are you having?

**Comment by glepnir** [comment]
`:MetalsInfo` I got it . but can't completion and get doc ..
![image](https://user-images.githubusercontent.com/41671631/107848752-f69e7f00-6e30-11eb-90d0-31442d882029.png)

**Comment by ckipp01** [comment]
Ahh, you need to make sure you have java installed as well. Do you have java installed?

**Comment by glepnir** [comment]
I had install openjdk. but `java -version` gave me this

```log
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

```

**Comment by ckipp01** [comment]
🤔 since you'll have coursier installed, you can also try this I guess:

This should install Java
```
cs java --jvm adopt:11.0.9
```

This should tell you if your Java home is set
```
cs java-home
```

If the above command doesn't return anything, you can do a 

```
cs java-home --jvm adopt:11.0.9
```

which should then set your java home to that jdk.


Sorry that Java is being a pain. Are you on a Mac and did you install Java with Brew by chance?

**Comment by glepnir** [comment]
on Mac and brew install openjdk 15.0.1

**Comment by ckipp01** [comment]
ah, the jdk will need to be 8 or 11, not 15. I don't want you to have to install a bunch of stuff locally. Let me try to think of another easier way to get you an environment that you can test this with, or I will spend some time myself trying to find the issue.

**Comment by glepnir** [comment]
OK  lspconfig works.. so I will try the jdk11 for nvim-metals

**Comment by ckipp01** [comment]
> OK lspconfig works.. so I will try the jdk11 for nvim-metals

👍🏼 just make sure to not have Metals registered with both nvim-metals and lspconfig at the same time or you'll start 2 servers at the same time.

**Comment by glepnir** [comment]
Yep I know that.

**Comment by glepnir** [comment]
seems like `brew install coursier` will auto install jdk15

**Comment by glepnir** [comment]
How about now?

**Comment by ckipp01** [comment]
> Please update and give a test.

So yes, this does seem to fix it!

<img width="899" alt="Screenshot 2021-02-13 at 15 14 13" src="https://user-images.githubusercontent.com/13974112/107852001-2a1be200-6e0e-11eb-9413-af331ba76cc0.png">


Thanks a lot for all of your effort in trying to chase this down. Some part of me feels like part of the issue is just that so many of the signatures in Scala will be long, so they wrap odd and don't always look the best. However, that's because of Scala, not because of saga.

Do you know why in your first image the second line `String`s are not colored the same as the first?

**Comment by glepnir** [comment]
It seems that manual line wrapping will destroy some highlights

**Comment by ckipp01** [comment]
👍🏼 sounds good thanks a lot. 🚀

**Comment by glepnir** [comment]
I will fix highlight later. I found the reason.

**Comment by glepnir** [comment]
fixed.
