### ISSUE TITLE
Hover doc bug

### ISSUE THREAD

**Issue by Jezda1337** [glepnir/lspsaga.nvim#673]
### Describe the bug

When I do capital"K" to get popup documentation, the popup window freezes in place and when I try to close it won't work, when I do :q nothing get happened or any other key, but I can move around and I can do "K" again on other function for example and that new popup window still stays in the place and won't go away after I move or anything.

https://user-images.githubusercontent.com/42359294/212472597-50248438-7a39-4030-91f8-c5a41e021004.mov

### Steps to reproduce

/

### Expected behavior

/

### Neovim version (nvim -v)

NVIM v0.9.0-dev-647+g1df2db0bc

### Operating system/version

macOS 13.0.1 (22A400)

### Terminal name/version

Iterm Build 3.5.0beta7 ,   kitty 0.26.5

### $TERM environment variable

Iterm: xterm-256color, kitty: screen-256color

**Comment by glepnir** [comment]
I can't reproduce. provide reproduce step.

**Comment by Jezda1337** [comment]
You have to init the React, Vue, or Qwik project and basically, any file from the project will show you the problem. Or if it is easier for you, you can pick up for example this repo from me [link](https://github.com/Jezda1337/website)
If you pick up the project from the repo just clone it and `cd` into it and run `npm i`, then `npm run dev` and just go into any .tsx file to check.

**Comment by glepnir** [comment]
I had check it in vue and it works fine. https://github.com/glepnir/lspsaga.nvim/issues/666

**Comment by Jezda1337** [comment]
Strange, I did Lazy Sync again just min ago and try again on the .jsx file and get this error:
![Screenshot 2023-01-14 at 14 30 15](https://user-images.githubusercontent.com/42359294/212474298-64e7520e-4da7-4de4-9d49-621fc2fbb557.png)

and when I try the same think in Qwik project the problem with freezing popup window is still there.

**Comment by glepnir** [comment]
let me try to reproduce it ..

**Comment by glepnir** [comment]
it works fine .. so if you can use a min config reproduce  I will reopen this issue thanks

![diagnostic](https://user-images.githubusercontent.com/41671631/212475458-375faca4-7099-4c09-9615-a2beb81ec9fa.gif)

**Comment by glepnir** [comment]
I had said it works fine with minconfig i had tried many times. please test with min config.

![hover](https://user-images.githubusercontent.com/41671631/215301503-d382f366-ab9a-461b-97cc-d1ce5519ad2c.gif)
