### ISSUE TITLE
Transparency working weird

### ISSUE THREAD

**Issue by yeseongmoon** [glepnir/lspsaga.nvim#678]
### Describe the bug

Before the breaking changes, my transparency worked just fine with a setting "floats" to "transparent" in my tokyonight theme setup. After the changes, the transparency is not working anymore. I tried to set normal_bg to none or transparent(but unfortunately couldn't find transparent hex code that is working) and it seems like it works only with "Lspsaga peek_definition" when I set normal_bg to "". I'm attaching the video for an example.

https://user-images.githubusercontent.com/20822372/212482867-582c01fc-07f5-4631-aded-cbf29f9447dd.mov

### Steps to reproduce

do Lspsaga peek_definition, Lspsaga hover_doc, Lspsaga lsp_finder

### Expected behavior

every floating windows should be transparent.

### Neovim version (nvim -v)

0.8.2

### Operating system/version

macOS 13.1 Ventura

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-256color

**Comment by yeseongmoon** [comment]
the thing is that I didn't change any of my colorscheme settings. It worked before, and now it is not. Am I missing something in my config?

**Comment by yeseongmoon** [comment]
In addition, it only works fine when I do Lspsaga peek_definition, anything else not being transparent including hover_doc, lsp_finder, show_line_diagnostics, show_buf_diagnostics, and diagnostic jumps

**Comment by glepnir** [comment]
known bug of neovim

**Comment by yeseongmoon** [comment]
> known bug of neovim . if you open same file in floatwindow. it will appear. peek support you can edit this file in this floatwindow. if only get some text and show in flaotwindow then this proble will disappear but it only can preview you can't
> do nothing.

Ah then I'll close this and report this to the neovim repo. Thanks for your amazing work!
