### ISSUE TITLE
goto_next and goto_prev send error message: " 'width' key must be a positive integer."

### ISSUE THREAD

**Issue by yeseongmoon** [glepnir/lspsaga.nvim#680]
### Describe the bug

`keymap("n", "[E", function()
  require("lspsaga.diagnostic").goto_prev({ severity = vim.diagnostic.severity.ERROR })
end)`
`keymap("n", "]E", function()
  require("lspsaga.diagnostic").goto_next({ severity = vim.diagnostic.severity.ERROR })
end)`

whenever I tried to goto_next in the last error or goto_prev in the first error, it gives me an error meesage, and makes a new buffer every time I get the error message.

https://user-images.githubusercontent.com/20822372/212485291-be8ef63c-83f0-42bc-a94c-87e707cef08a.mov

### Steps to reproduce

shown in the video

### Expected behavior

it should go to the next diagnostic without an error even if it is the first or the last one to go to.

### Neovim version (nvim -v)

0.8.2

### Operating system/version

macOS 13.1 Ventura

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-256color

**Comment by 0x-buidl** [comment]
I'm having this same error on macOS 13.1 Ventura 

M1 Pro Chip
