### ISSUE TITLE
TitleFileIcon doesn't work for peek definition preview window title 

### ISSUE THREAD

**Issue by TheSafdarAwan** [glepnir/lspsaga.nvim#682]
### Describe the bug

The color group for the `TitleFileIcon` doesn't work for the the `peek definition` window title.

And this is the line in source code which is causing issue 
https://github.com/glepnir/lspsaga.nvim/blob/599e6e1ed72f0e97089e3438c6731c897fa7aa99/lua/lspsaga/definition.lua#L103

### Steps to reproduce

`

### Expected behavior

![image](https://user-images.githubusercontent.com/87114084/212491528-885a6e51-a011-4436-9196-0d8bdec087a7.png)

### Neovim version (nvim -v)

NVIM v0.9.0-dev-676+gfd3d30a22

### Operating system/version

5.15.85-1-MANJARO x86_64 GNU/Linux

### Terminal name/version

wezterm 20221119-145034-49b9839f

### $TERM environment variable

tmux-256color

**Comment by glepnir** [comment]
`ui.colors.title_bg = your color` or `hi TitleFileIcon guibg= your color`

**Comment by TheSafdarAwan** [comment]
> `hi TitleFileIcon`

hey bro don't know why you completed closed this issue but tried this also didn't work out event after doing the highlight using 
`hi TitleFileIcon guibg=#f00000` to test it

**Comment by glepnir** [comment]
this command not work? does change in colors field can work?

**Comment by glepnir** [comment]
oh. I know why… miss default field fixed later in gym
