### ISSUE TITLE
Outline Fails to Open

### ISSUE THREAD

**Issue by uvb1** [glepnir/lspsaga.nvim#683]
### Describe the bug

Executing `:Lspsaga outline` results in:

> Error executing Lua callback: .../pack/packer/start/lspsaga.nvim/lua/lspsaga/outline.lua:457: attempt to concatenate a nil value
> stack traceback:
>     .../pack/packer/start/lspsaga.nvim/lua/lspsaga/outline.lua:457: in function 'render_outline'
>     .../pack/packer/start/lspsaga.nvim/lua/lspsaga/outline.lua:544: in function 'outline'
>     .../pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:38 in function <.../pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:37>
>     .../pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:60 in function 'load_command' 

### Steps to reproduce

Using Packer to load the lspsaga plugin and then attempting to view the outline for a Rust code file.

Here is the relevant portion of a minimal config:

```lua
use "neovim/nvim-lspconfig"
use {"glepnir/lspsaga.nvim", branch = "main"}
...
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true;
require('lspconfig')["rust_analyzer"].setup({
        capabilities = capabilities;
        on_attach    = on_attach;
})

require("lspsaga").setup({})
```

Open a Rust file, allow Rust-Analyzer to load, wait for LSPSaga to load (shows position in winbar, lightbulb, etc as expected).

Issue `:Lspsaga outline`.  The error occurs and the outline window is empty.

### Expected behavior

The outline window should show as it previously did before this bug.

### Neovim version (nvim -v)

0.8.2

### Operating system/version

macOS

### Terminal name/version

iTerm

### $TERM environment variable

xterm-256color

**Comment by glepnir** [comment]
did you install nvim-devicons?

**Comment by glepnir** [comment]
just add a patch but I think you need install nvim-webdevicons
