### ISSUE TITLE
Hover doc error

### ISSUE THREAD

**Issue by schizophrenical** [glepnir/lspsaga.nvim#686]
### Describe the bug

This is related to [#673](https://github.com/glepnir/lspsaga.nvim/issues/673)

With the same use-case/scenario from #673, I get the following error:

```
Error executing vim.schedule lua callback: vim/shared.lua:0: s: expected string, got table
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'gsplit'
        vim/shared.lua: in function 'split'
        ...local/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/hover.lua:21: in function 'open_floating_preview'
        ...local/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/hover.lua:139: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1391: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps to reproduce

- Open a `Java` file.
- Wait for the `LSP server` to finish loading.
- Go to a method with `JavaDoc`
- Execute `Lspsaga hover_doc`

### Example scenario
Interestingly, executing `Lspsaga hover_doc` on method or class reference works.
Java file:
```
import baz.Baz;

public class Foo {

    /**
    * Get Foo.
    *
    * @param fooParam params.
    * @return String foo.
    */
    public String getFoo(final String fooParam) { // hover_doc fails here. vim.lsp.buf.hover works
        // Do foo stuff.
    }

    /**
    * Get Baz
    *
    * @param bazParam params.
    * @return String baz.
    */
    public String getBaz(final String bazParam) { // hover_doc fails here. vim.lsp.buf.hover works
        return baz.getBazStuff() + getFoo(bazParam); // hover_doc works here, shows the docs for getFoo and getBazStuff.
    }

}
```

### Expected behavior

Lspsaga hover_doc shows docs.

### Neovim version (nvim -v)

v0.9.0-dev-fd3d30a

### Operating system/version

Windows Subsystem for Linux (WSL) - Ubuntu 20.04

### Terminal name/version

Windows Terminal

### $TERM environment variable

N/A

**Comment by uga-rosa** [comment]
This issue should have been fixed in #685
