### ISSUE TITLE
Weird color for lsp_finder

### ISSUE THREAD

**Issue by shaunwen** [glepnir/lspsaga.nvim#689]
### Describe the bug

When I trigger the lsp_finder action, it has a blue color in background when I am using gruvbox.
![image](https://user-images.githubusercontent.com/4570313/212529351-07123eec-0b9a-423a-aa5a-0c96cacf0841.png)
It needs to manually run :colorscheme gruvbox to be able to get the following:
![image](https://user-images.githubusercontent.com/4570313/212529472-4fff50ec-1f3d-4273-9753-805f18f3b163.png)

### Steps to reproduce

set the colorscheme gruvbox in config, then trigger Lspsaga lsp_finder.

### Expected behavior

![image](https://user-images.githubusercontent.com/4570313/212529468-9d3cc640-4f75-48a6-8c55-d30023e07d62.png)

### Neovim version (nvim -v)

NVIM v0.8.2

### Operating system/version

macOS 13.1

### Terminal name/version

Alacritty

### $TERM environment variable

xterm-256color

**Comment by glepnir** [comment]
there has default float window background in lspsaga. if you want change it please config the `ui.color.normal_bg` field.

```lua
ui = {
   colors = {
            normal_bg = your color
}
```

other way us ` hi SagaBorder guibg = your color code ` or `hi default link SagaBorder NormalFloat`

**Comment by shaunwen** [comment]
Thanks for the help @glepnir, it worked after I set the normal_bg. In addition, I would suggest not to make SagaBorder use the same color of normal_bg, instead, allow configuring a different color for SagaBorder to normal_bg in setup method will enable users to have a nice border(e.g. white boxed popup) for lsp_finder results popup.

**Comment by hangwonghk01** [comment]
> there has default float window background in lspsaga. if you want change it please config the `ui.color.normal_bg` field.
> 
> 
> 
> ```lua
> 
> ui = {
> 
>    colors = {
> 
>             normal_bg = your color
> 
> }
> 
> ```
> 
> 
> 
> other way us ` hi SagaBorder guibg = your color code ` or `hi default link SagaBorder NormalFloat`

for those who don't get it working with `hi default link SagaBorder NormalFloat`, can try `hi! default link SagaBorder NormalFloat`

**Comment by tkhg** [comment]
> there has default float window background in lspsaga. if you want change it please config the `ui.color.normal_bg` field.
> 
> 
> 
> ```lua
> 
> ui = {
> 
>    colors = {
> 
>             normal_bg = your color
> 
> }
> 
> ```
> 
> 
> 
> other way us ` hi SagaBorder guibg = your color code ` or `hi default link SagaBorder NormalFloat`

for those who don't get `hi default link SagaBorder NormalFloat` working can try `hi! default link SagaBorder NormalFloat`

**Comment by shaunwen** [comment]
Thanks @glepnir and @tkhg , not sure how it is possible to have different colours for the background of the popup and the border as the border is using the same colour of the normal_bg defined in https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/highlight.lua? 
```
SagaBorder = { bg = colors.normal_bg, fg = colors.blue },
SagaNormal = { bg = colors.normal_bg },
```

**Comment by shaunwen** [comment]
Sorry for the confusion, found out the issue is actually not the colour highlight, it was caused by the border = 'rounded' was placed outside of the ui table, which is supposed to be within the ui table. With the correct border config, now I can see the border displayed. Thanks for the help!
