### ISSUE TITLE
Hover error: Cursor position outside buffer

### ISSUE THREAD

**Issue by sharksforarms** [glepnir/lspsaga.nvim#69]
To reproduce:
- open hover window: `lua require('lspsaga.hover').render_hover_doc()`
- scroll "up": `require('lua lspsaga.hover').smart_scroll_hover(-1)`
- `E5108: Error executing lua .../.config/nvim/plugged/lspsaga.nvim/lua/lspsaga/hover.lua:55: Cursor position outside buffer`

**Comment by sharksforarms** [comment]
Here's an example with:

```rust
use std::str::self; // get hover doc on `std`

fn main() {
    println!("Hello, world!");
}

 // require('lspsaga.hover').render_hover_doc()
 // require('lspsaga.hover').smart_scroll_hover(1) // down
 // require('lspsaga.hover').smart_scroll_hover(1) // down
 // require('lspsaga.hover').smart_scroll_hover(-1) // up
 // require('lspsaga.hover').smart_scroll_hover(-1) // up
 // error
```

![Peek 2021-02-04 13-51](https://user-images.githubusercontent.com/10912917/107036410-9bf98900-6787-11eb-9dfa-eddfdf1e2770.gif)

**Comment by glepnir** [comment]
Please update lspsaga. can't reproduce.

**Comment by sharksforarms** [comment]
Confirmed fixed, thanks!
