### ISSUE TITLE
Colors dont follow highlights from colorscheme

### ISSUE THREAD

**Issue by paulhersch** [glepnir/lspsaga.nvim#690]
Hi,

currently all the Lspsaga functions don't use my colorscheme but their own. I did not declare the colors in the setup function, but in the colorscheme itself. After Lspsaga init, the colors are being overwritten. Is it possible to change that behaviour, so that for every highlight lspsaga tries to first get a highlight from an existing highlight group and then sets it if the group was not provided?

Also some previously existing highlight groups seem to be ignored (for example in code_action and hover_doc, the highlights were already set and now its not themed properly any more). I would love for lspsaga to also follow colorscheme highlights here instead.

regards,
Paul

Edit: if you would not want to implement that yourself, would you accept PR's that change this behaviour?

**Comment by glepnir** [comment]
because the highlight group had changed so exist in  colorscheme not works currently except them follow the new version lspsaga.  you can defined them in your config. all highlight group in the `highlight.lua` file.   some highlight defined in code or use your colorscheme first like diagnostic relate.

**Comment by paulhersch** [comment]
In my case i tested the LspSagaWinbarSep. The colorscheme only applied after running the setup function again.
thanks for the pointer to the highlights.lua file, most highlights there are not shown in vim itself.

**Comment by glepnir** [comment]
yea. because I don't write `default =true` in some highlight which write in source code . now should be works fine.

**Comment by paulhersch** [comment]
yes this works now. Thanks for the quick fix!

**Comment by glepnir** [comment]
no problem :)
