### ISSUE TITLE
Custom color for winbar: symbol <text>

### ISSUE THREAD

**Issue by etherrorcode404** [glepnir/lspsaga.nvim#691]
Can we make it possible to change the text color beisde the symbol (like vscode). Unlike, lspsaga vscodes winbar actually is not colorful lspsaga uses the symobol color as the text color, adding an option to customise that would be wise. Thanks!

**Comment by glepnir** [comment]
because it's easy to use color in full text . i am lazy  so I not do write some col check code.

**Comment by glepnir** [comment]
update
