### ISSUE TITLE
Breaking change in lspsaga.nvim

### ISSUE THREAD

**Issue by stoddart** [glepnir/lspsaga.nvim#692]
### Describe the bug

When opening Neovim, I get the following error and lspsaga breaks:

> Error detected while processing /Users/daniel/.config/nvim/init.lua:
lspsaga.nvim v0.2.3+ has braking changes. Please read the docs and migrate your configuration to the new "setup" function!

### Steps to reproduce

Open Neovim from the command line with lspsaga installed.

### Expected behavior

Expect the plugin to load without breaking. 

### Neovim version (nvim -v)

v0.8.2

### Operating system/version

macOS 13.1 (ARM 64)

### Terminal name/version

iTerm2 3.4.19

### $TERM environment variable

xterm-256-color

**Comment by glepnir** [comment]
did you see the message . version 0.2.3 is breakchange please read doc thanks
```
lspsaga.nvim v0.2.3+ has braking changes. Please read the docs and migrate your configuration to the new "setup"
```

**Comment by stoddart** [comment]
I did see the message, but it's still breaking.

**Comment by stoddart** [comment]
> 

Where is the new "setup" information? I went to read the changelog but I didn't see anything about this.

**Comment by glepnir** [comment]
really ? I think I write them 

![image](https://user-images.githubusercontent.com/41671631/212573586-c7dabfc0-72e8-4487-92f5-206c9f4fd67d.png)


more options see usage tutorial also there can see them in neovim by `:h lspsaga`

**Comment by stoddart** [comment]
What file does that snippet live in the Packer config?

**Comment by glepnir** [comment]
hmmm this is lspsaga not packer ..https://github.com/glepnir/lspsaga.nvim#install ...

**Comment by stoddart** [comment]
I did read that, but I'm afraid you're not understanding me. I'm asking where that bit of code lives. What file do I need to add that snippet to?

**Comment by stoddart** [comment]
OK, so if anyone is trying to fix this, here's what you need to do if you have a `lspsaga.lua` file:

Replace `saga.init_lsp_saga` with `saga.setup`, save the changes, quit and restart.

**Comment by preist** [comment]
This was useful, thanks @stoddart

**Comment by tdelam** [comment]
@stoddart thanks, that was useful. The changelog or doc's don't mention this at all.

**Comment by DeloneCode** [comment]
@stoddart thank you !
