### ISSUE TITLE
symbol in winbar not working properly

### ISSUE THREAD

**Issue by yeseongmoon** [glepnir/lspsaga.nvim#694]
### Describe the bug

https://user-images.githubusercontent.com/20822372/212534083-f8e7ee35-5801-4335-97a7-6be3dd411db7.mov

symbol_in_bar is not working on a file that I open with. It only triggered when there is a modification on it.
However, when I go to another file, symbol_in_bar is working as it should be.
Idk if it's because of the neovim version that is not >= 0.9.0

### Steps to reproduce

nvim "filename" or 
nvim -> open a file in neovim

symbol_in_bar not working until there is a modification.

### Expected behavior

when opening a file, symbol_in_bar starts working right away.

### Neovim version (nvim -v)

0.8.2

### Operating system/version

macOS 13.1 Ventura

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-256color

**Comment by yeseongmoon** [comment]
btw, the transparency is working just fine now! with winblend = 0, it gives me a perfect transparency with all the features except for this. I don't want to bother you to open another issue, so I'm adding this here.
<img width="419" alt="Screenshot 2023-01-15 at 6 55 55 PM" src="https://user-images.githubusercontent.com/20822372/212534434-325fae1a-e263-4269-be39-524ffe1aee49.png">

**Comment by glepnir** [comment]
because the lua serve need time to initialize.  just move for a while it also can work.  about highlight i will add a patch for that.

**Comment by yeseongmoon** [comment]
Thank you so much!

**Comment by yeseongmoon** [comment]
> because the lua serve need time to initialize. just move for a while it also can work. about highlight i will add a patch for that.

thank you so much!

**Comment by glepnir** [comment]
if you want it show quickly reduce your lua language server workspace libriary

**Comment by yeseongmoon** [comment]
> if you want it show quickly reduce your lua language server workspace libriary

I mean it shows right away, once I modify the file or move to another file, so I don't know if it's because of the loading time

**Comment by glepnir** [comment]
there has some plugin can show server loading time maybe you need.

**Comment by yeseongmoon** [comment]
> there has some plugin can show server loading time maybe you need.

like fidget you mean?

**Comment by glepnir** [comment]
I don't remember maybe you can search on some where.

**Comment by yeseongmoon** [comment]
> I don't remember maybe you can search on some where.

I've waited good amount of time, moving around, but it still doesn't work until I take an action to a code.

**Comment by glepnir** [comment]
can 't reproduce after server init it will appear.

**Comment by yeseongmoon** [comment]
> can 't reproduce after server init it will appear.

Alright let me find a plugin to see if the server is initialized!

**Comment by glepnir** [comment]
color should be fixed. add highlight group for that window. then it trans by winblend not highlight.

**Comment by glepnir** [comment]
![diagnostic](https://user-images.githubusercontent.com/41671631/212535701-1ac0c992-521a-4f58-968c-7404231405aa.gif)

**Comment by yeseongmoon** [comment]
> color should be fixed. add highlight group for that window. then it trans by winblend not highlight.

thank you!!

**Comment by yeseongmoon** [comment]
> color should be fixed. add highlight group for that window. then it trans by winblend not highlight.

I'm so sorry to keep bothering you, but what highlight group should I add for the window? is it SagaBorder?

**Comment by glepnir** [comment]
why you want to change that win ?

**Comment by yeseongmoon** [comment]
> why you want to change that win ?
<img width="419" alt="Screenshot 2023-01-15 at 6 55 55 PM" src="https://user-images.githubusercontent.com/20822372/212539979-abd64ebb-6a32-481b-8d9e-e67ffdb96907.png">

to make the red indicator line cleaner without bg color..!

**Comment by glepnir** [comment]
this is bug of neovim . the highlight is `SagaVirtNormal` 
```lua
vim.api.nvim_set_hl(0, 'SagaVirtNormal', { background = 'NONE'})
vim.keymap.set('n', '[e', function()
vim.cmd('Lspsaga diagnostic_goto_next<CR>')
local bufs = vim.api.nvim_list_bufs()
for _, buf in pairs(bufs) do
  if vim.bo[buf].filetype == 'diagvirt' then
      local winid = vim.fn.bufwinid(buf)
       vim.wo[winid].winblend = 0
       break
  end
end
)

```

**Comment by yeseongmoon** [comment]
> 

ah I see thank you so much!

**Comment by HATTER-LONG** [comment]
I have a similar problem. But I checked lsp-server has been started, which doesn't seem to be caused by it.

As shown in the pic below, the function of clangd has been started normally.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/31438141/213906298-9d7616d5-89c4-4396-8cbe-265d9229b5fe.png">

**Comment by glepnir** [comment]
works fine on my local 

![image](https://user-images.githubusercontent.com/41671631/213906383-0a4cd09e-3017-456c-ba39-aafea0738b8a.png)

**Comment by HATTER-LONG** [comment]
I'm not very familiar with Lua, so I simply added some print info to debug.

I found the lspsaga refresh symbol for winbar when first open the file, the lsp is probably not initialized. But cache flag already set, and eventually the buf winbar needs to be reloaded to display properly.

I tried to modify it to make the winbar display normally.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/31438141/213907835-c11c67c9-f917-4faf-97db-f030d5d30336.png">

**Comment by glepnir** [comment]
right good catch . start client is async . so when we do cap check maybe the client not initialized.

**Comment by glepnir** [comment]
should remove before pending request status. can you try it now

**Comment by glepnir** [comment]
@yeseongmoon  about the highlight of the line window .I had add a patch . you don't need that hack.

**Comment by HATTER-LONG** [comment]
I updated it and works normally. 👍

**Comment by glepnir** [comment]
thanks for confirm.

**Comment by yeseongmoon** [comment]
@HATTER-LONG @glepnir  Thank you guys for tackling this problem again. I will have a habit to look through the code to figure out what the problem might be. Great work for both of you!
