### ISSUE TITLE
How to turn off top code context line?

### ISSUE THREAD

**Issue by coder3101** [glepnir/lspsaga.nvim#695]
### Describe the bug

When LSP is attached the context line is shown in top, since I already use `nvim-context`. I would like to turn off that context feature.
![Screenshot 2023-01-15 at 5 13 11 PM](https://user-images.githubusercontent.com/22212259/212538614-701848d4-5fff-4017-a167-28beb011b134.png)

### Steps to reproduce

N/A

### Expected behavior

N/A

### Neovim version (nvim -v)

v0.8.2

### Operating system/version

macOS Ventura

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256

**Comment by coder3101** [comment]
I missed discussion, please move this issue as discussion Q&A

**Comment by glepnir** [comment]
read doc

**Comment by coder3101** [comment]
> read doc

What is that feature called?

**Comment by coder3101** [comment]
It worked!
```lua
symbol_in_winbar = {
 enable = false,
},
```

**Comment by glepnir** [comment]
so ? you should compare which is best.
