### ISSUE TITLE
LSP rename does not works

### ISSUE THREAD

**Issue by coder3101** [glepnir/lspsaga.nvim#696]
### Describe the bug

```lua
local bufopts = { noremap = true, silent = true, buffer = bufnr }
vim.keymap.set('n', '<leader>gr', "<cmd>Lspsaga rename<CR>", bufopts)
```

https://user-images.githubusercontent.com/22212259/212540765-a4b534a7-8843-4da4-8bf9-ea397a1b7205.mov

After enter key is pressed rename is not performed. I tried with rust and python (pyright) it fails to rename in both of these language. However, rename using native neovim functionality `vim.lsp.buf.rename()` is able to rename in all cases.

```lua
    use({
        "glepnir/lspsaga.nvim",
        branch = "main",
        config = function()
            require('lspsaga').setup({
                symbol_in_winbar = {
                    enable = false,
                },
            })
        end,
    })

``` 

### Steps to reproduce

N/A

### Expected behavior

Rename should be performed for the symbol under the cursor after "Enter" key is pressed.

### Neovim version (nvim -v)

v0.9.0-dev-696+g909abfbd8

### Operating system/version

macOS Ventura

### Terminal name/version

iTerm2

### $TERM environment variable

xterm-256

**Comment by elkowar** [comment]
@glepnir I think the commit that fixes this bug introduced other breakages, right now I'm getting 
```
Error executing vim.schedule lua callback: ...ocal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/rename.lua:207: attempt to index local 'change' (a nil value)
stack traceback:
	...ocal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/rename.lua:207: in function 'handler'
	/usr/share/nvim/runtime/lua/vim/lsp/buf.lua:480: in function 'handler'
	/usr/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```
whenever I try to use rename

**Comment by glepnir** [comment]
quickly fix is `rename.whole_project = false`. and create a new issue I need more information
