### ISSUE TITLE
Peek to definition window background bug 

### ISSUE THREAD

**Issue by TheSafdarAwan** [glepnir/lspsaga.nvim#699]
### Describe the bug

if we peek to definition to a definition and its in the same buffer then the background of the window doesn't respect the `DefinitionNormal` config.

https://user-images.githubusercontent.com/87114084/212548824-05005046-14f1-42e4-8010-9dd52f7a2a15.mp4

### Steps to reproduce

`

### Expected behavior

`

### Neovim version (nvim -v)

`

### Operating system/version

`

### Terminal name/version

`

### $TERM environment variable

`

**Comment by glepnir** [comment]
known bug of neovim

**Comment by glepnir** [comment]
but I had add a patch for this . it should have background color miss border color . anyway it's a bug of neovim .I have notice for a while but no time to fix it in neovim core . maybe recently.
