### ISSUE TITLE
Range code action

### ISSUE THREAD

**Issue by onsails** [glepnir/lspsaga.nvim#7]
In visual mode when some range is selected `vnoremap <silent><leader>ca <cmd>'<,'>lua require('lspsaga.codeaction').code_action()<CR>` fails with the following error:

```
E5108: Error executing lua ...hare/vim-plugins/lspsaga-nvim/lua/lspsaga/codeaction.lua:20: attempt to index local 'response' (a nil value)
```

Is `code_action()` supposed to work with range?

**Comment by glepnir** [comment]
support it later.

**Comment by onsails** [comment]
for some reason it's different from `vim.lsp.buf.range_code_action()`.

`vim.lsp.buf.range_code_action()`:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/107261/105855775-805ce880-5ff9-11eb-860c-786c14ed4d3e.png">

`require('lspsaga.codeaction').code_action()`:

<img width="294" alt="image" src="https://user-images.githubusercontent.com/107261/105855849-98346c80-5ff9-11eb-9405-4bff4ac91d37.png">
