### ISSUE TITLE
Diagnostics multiline not highlighted

### ISSUE THREAD

**Issue by sharksforarms** [glepnir/lspsaga.nvim#70]
It seems like diagnostics that wrap don't get highlighted

![image](https://user-images.githubusercontent.com/10912917/106950302-3318ff00-66fc-11eb-9163-cbf601afe78e.png)

**Comment by sharksforarms** [comment]
Thanks for the update!
I still seem to get getting some highlight issues:
![image](https://user-images.githubusercontent.com/10912917/107034676-0b21ae00-6785-11eb-8852-6391c6d34435.png)

**Comment by glepnir** [comment]
Can you post a min rust code that reproduce this?

**Comment by sharksforarms** [comment]
```rust
use std::str::self; // error here

fn main() {
    println!("Hello, world!");
}
```

**Comment by glepnir** [comment]
now should be work.

**Comment by philipGaudreau** [comment]
This problem still seems to arise.
![Screen Shot 2021-07-06 at 22 19 53](https://user-images.githubusercontent.com/22773951/124690533-5b25ad80-dea8-11eb-9a25-3b680455c07b.png)
I am using python.
