### ISSUE TITLE
diagnostic_jump into code_action throws an Error

### ISSUE THREAD

**Issue by el-og** [glepnir/lspsaga.nvim#700]
### Describe the bug

```
Error executing vim.schedule lua callback: ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:55: attempt to concatenate field 'bufnr' (a nil value)
stack traceback:
        ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:55: in function 'action_callback'
        ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:227: in function 'cb'
        ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:189: in function 'callback'
        ...r/neovim/HEAD-7b158e7/share/nvim/runtime/lua/vim/lsp.lua:1956: in function 'handler'
        ...r/neovim/HEAD-7b158e7/share/nvim/runtime/lua/vim/lsp.lua:1388: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

```

### Steps to reproduce

1. Jump to error/warning `Lspsaga diagnostic_jump_next` (or prev)
2. Once floater appears `Lspsaga code_action`
3. Error appears and `code_action` floater would not disappear, can't select action and when clicking `q`, have to type `:q` instead

https://user-images.githubusercontent.com/19407604/212559444-a2184be1-92fa-49bf-a45f-b594afe31cb5.mov

### Expected behavior

No Error. Can select action after `diagnostic_jump`. Can quit with `q`

### Neovim version (nvim -v)

NVIM v0.9.0-dev-337+g7b158e766-dirty

### Operating system/version

.

### Terminal name/version

iTerm2

### $TERM environment variable

.

**Comment by el-og** [comment]
@glepnir I see you have pushed a fix, but the issue still exists after updating my plugin to the latest commit
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/19407604/212619891-2d56f0fa-04a1-45a5-9f6e-14f895b9adfe.png">

**Comment by glepnir** [comment]
can't reproduce.

**Comment by glepnir** [comment]
update

**Comment by glepnir** [comment]
can you put your project here ?

**Comment by el-og** [comment]
> can you put your project here ?

The one I am working on? I really cannot, but I have tested with 3 different projects and all of them throws the same error except, only difference is number in `<buffer=7>`

**Comment by glepnir** [comment]
it works fine for me and i also called some people test both works. create a min project that can reproduce would be useful

**Comment by el-og** [comment]
> it works fine for me and i also called some people test both works. create a min project that can reproduce would be useful

https://github.com/el-og/test-lspsaga created this repo. Problem still exists in `app.tsx` when trying to use `code_actions` for eslint warning... (any error/warning same)

**Comment by glepnir** [comment]
does only tsserver can reproduce ?

**Comment by el-og** [comment]
> does only tsserver can reproduce ?

I believe so, I couldn't reproduce it on any other LSP

**Comment by glepnir** [comment]
![diagnostic](https://user-images.githubusercontent.com/41671631/212656597-622dbeba-f43b-4113-908d-37cf506203e3.gif)

**Comment by glepnir** [comment]
need your eslint config. tsserver works fine.

**Comment by el-og** [comment]
you are trying to reproduce it a bit differently. When my cursor is at the problem and I call `code_actions` everything works OK (as in your example). However, the problem appears when you use `Lspsaga diagnostic_jump_next`, then floater appears and while that floater is still visible, you call `Lspsaga code_action`, then it breaks and throws an Error.

> ![diagnostic](https://user-images.githubusercontent.com/41671631/212656597-622dbeba-f43b-4113-908d-37cf506203e3.gif)

**Comment by glepnir** [comment]
reproduce I will fix but your work flow is wrong. `diagnostic_jump_next` will also show code action in that window then you can only press the code action number it will execute. no need jump into the diagnostic floatwindow also don't need call code action. lspsaga is smart.

**Comment by el-og** [comment]
> reproduce I will fix but your work flow is wrong. `diagnostic_jump_next` will also show code action in that window then you can only press the code action number it will execute. no need jump into the diagnostic floatwindow also don't need call code action. lspsaga is smart.

Yes, I mentioned that [here](https://github.com/glepnir/lspsaga.nvim/issues/700#issuecomment-1383744639), however it was not possible yesterday, since for some reason I wasn't able to select fix options on a floatwindowd. Now, flow you described works nicely. 

Thanks for all the help and thanks for a plugin <3

**Comment by glepnir** [comment]
fixed. but you don't need this workflow. just jump press number.
