### ISSUE TITLE
LspSaga Code Action delete code

### ISSUE THREAD

**Issue by Johan-Palacios** [glepnir/lspsaga.nvim#702]
### Describe the bug

LspSaga Code action not working properly, because delete some parts of code, doing an action

https://user-images.githubusercontent.com/77251405/212588090-64e36b11-097c-4e92-8988-609980b9bc20.mp4

### Steps to reproduce

```lua
local status_saga, lspsaga = pcall(require, "lspsaga")
if not status_saga then
  return
end

lspsaga.setup {
  lightbulb = {
    enable = false,
  },
  symbol_in_winbar = {
    enable = false,
  },
lspsaga.setup {
  lightbulb = {
    enable = false,
  },
  symbol_in_winbar = {
    enable = false,
  },
  code_action = {
    num_shortcut = true,
    keys = {
      quit = "q",
      exec = "<CR>",
    },
  },
}

```

### Expected behavior

The code action should not remove the code, like vim.lsp.buf.code_action()

### Neovim version (nvim -v)

NVIM v0.9.0-dev

### Operating system/version

Ubuntu 20.04.5 LTS

### Terminal name/version

zsh 5.8

### $TERM environment variable

xterm-256color

**Comment by glepnir** [comment]
I don't write java . it works fine for langauges which i write that i can test it on  my local , c cpp rust lua go ts py

**Comment by glepnir** [comment]
no update close.
