### ISSUE TITLE
Rename triggered an error

### ISSUE THREAD

**Issue by zengshenggit** [glepnir/lspsaga.nvim#703]
### Describe the bug

After i try to rename the function name from `test_vec` to `test`, an error happened as below:
![深度截图_选择区域_20230116101230](https://user-images.githubusercontent.com/21997717/212591038-ac53928a-6ee3-4531-9d3d-8ce8a4717ab0.png)

### Steps to reproduce

The initial code:
![深度截图_选择区域_20230116100711](https://user-images.githubusercontent.com/21997717/212591248-4897f4e7-1608-4b23-a5c6-65378fd54d24.png)

Try to rename:
![深度截图_选择区域_20230116101051](https://user-images.githubusercontent.com/21997717/212591276-d445a99f-da78-4290-9e06-03a0cc12a2f4.png)

The error:
![深度截图_选择区域_20230116101230](https://user-images.githubusercontent.com/21997717/212591328-cc06e72a-e71b-46fe-9db0-ec3f47b725ea.png)

### Expected behavior

No error happends and renamed successfully.

### Neovim version (nvim -v)

0.8.2

### Operating system/version

Archlinux

### Terminal name/version

Alacritty

### $TERM environment variable

256color

**Comment by glepnir** [comment]
quickly fix change the rename.whole_project to false

**Comment by zengshenggit** [comment]
I do that,  but still not works
