### ISSUE TITLE
code action breaks when there is more than 9 possible choices

### ISSUE THREAD

**Issue by lucario387** [glepnir/lspsaga.nvim#709]
### Describe the bug

Code action breaks when there is more than 9 entries

### Steps to reproduce

Use nvim-jdtls and gitsigns in a git repo
change some lines
Open LspSaga code_action
Code action will have entries like below
![image](https://user-images.githubusercontent.com/29790821/212703214-ae791344-276c-4175-b7b9-1acc16fa9539.png)

### Expected behavior

It can correctly show entries after the 9th one

### Neovim version (nvim -v)

NVIM v0.9.0-dev-709+g9e1d2e2ca Build type: Release LuaJIT 2.1.0-beta3 Compiled by root@spacegliders  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/share/nvim"  Run :checkhealth for more info

### Operating system/version

Linux 6.1.6

### Terminal name/version

kitty

### $TERM environment variable

xterm-kitty

**Comment by glepnir** [comment]
because that unicode only 0 -9 is bigger ... I am thinking another show right now..
