### ISSUE TITLE
'Expected table, got nil' doing anything

### ISSUE THREAD

**Issue by lucax88x** [glepnir/lspsaga.nvim#71]
Ehy man,

so, I use this plugin for some features, like hover, finder, references, etc, couple of days ago was working perfectly.

Now, since yesterday afternoon, all of these actions are giving me this error.

```
E5108: Error executing lua vim/shared.lua:199: Expected table, got nil 
```

You can use [this](https://github.com/lucax88x/repro-neovim) as repro repo

**Comment by lucax88x** [comment]
After some investigation, hover works, finder and actions give this error.

**Comment by glepnir** [comment]
test now,.

**Comment by glepnir** [comment]
finder and actions does not work on where ?  I had clone your repo and yarn install .

**Comment by glepnir** [comment]
![image](https://user-images.githubusercontent.com/41671631/107032001-0c3af580-67ee-11eb-8156-527bd42510f4.png)

**Comment by glepnir** [comment]
> E5108: Error executing lua vim/shared.lua:199: Expected table, got nil 

About this error

https://github.com/glepnir/lspsaga.nvim/blob/8eb261aaf01fdeb7beb2c059ee8249a0d1f3e054/lua/lspsaga/libs.lua#L58-L62

there check the server response. normal circumstances, we should get a table type response.error response, we get nil

**Comment by lucax88x** [comment]
Sorry, I am on "forced" day shopping with family..

I will be able to check later.

**Comment by glepnir** [comment]
I think it should be issue of typescript-language-server？

**Comment by lucax88x** [comment]
Well, two days it was working, then it suddently stopped working, not works again, dunno.

**Comment by glepnir** [comment]
same code ?

**Comment by glepnir** [comment]
https://user-images.githubusercontent.com/41671631/107197086-6aeeb200-6a2e-11eb-97bc-0d3834f574eb.mov

and check this comment https://github.com/neovim/neovim/issues/13817#issuecomment-773994430.
It print the typescript-language-server response. see response it does not return the information about Test2

**Comment by lucax88x** [comment]
> check the built-in lsp default handler.If it can work. should be bug of lspsaga.

Sorry, i wanted to say, now IT works again.

So bug is gone. You probably fixed in the meantime. I just updated packages.

**Comment by lucax88x** [comment]
>  Screen.Recording.2021-02-08.at.4.53.52.PM.mov 
> and check this comment [neovim/neovim#13817 (comment)](https://github.com/neovim/neovim/issues/13817#issuecomment-773994430).
> It print the typescript-language-server response. see response it does not return the information about Test2

About this one, yeah, I remember this one, I've also debugged LSP log myself. I was wondering if it could be a problem of "REQUEST" than "response" ? I hadn't the necessary knowledge but I would like to debug the differences in REQUEST about Test1 and Test2, maybe in one case it's asking for <Test2/> and in the other Test1 and stuffs like that.. Dunno really.

**Comment by glepnir** [comment]
Aha right. I forget to check the request .good point.
