### ISSUE TITLE
Jumpping and collapsing in outline are broken

### ISSUE THREAD

**Issue by twandylue** [glepnir/lspsaga.nvim#710]
### Describe the bug

I can't jump and collapse the outline.

- Jumpping in outline would show the error message.
```plain
E5108: Error executing lua: ...cal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/outline.lua:178: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
        [C]: in function 'pairs'
        ...cal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/outline.lua:178: in function <...cal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/outline.lua:175>
```
- Collapse in outline would not work normally.

Video:

https://user-images.githubusercontent.com/70478084/212714683-dc00cbf3-a9aa-41d1-a380-6bd497f68239.mp4

### Steps to reproduce

My lspsage config

```lua
require("lspsaga").setup({
  outline = {
    keys = {
      jump = "<Enter>",
      expand_collapse = "-",
      quit = "q",
    },
  }
})
```

### Expected behavior

Jump to the region in outline and collapse the fold in outline.

### Neovim version (nvim -v)

0.8.2

### Operating system/version

macOS 12.4

### Terminal name/version

iterm 3.4.19

### $TERM environment variable

xterm-256 colors

**Comment by glepnir** [comment]
did you confirm you used latest commit? works fine for me

**Comment by twandylue** [comment]
I am on this commit. Is this the latest commit?
` "lspsaga.nvim": { "branch": "main", "commit": "963ede052055c371d1968252c040fe19f2ad16ad" }`

**Comment by glepnir** [comment]
can't reproduce.
