### ISSUE TITLE
Ui bug of `diagnostic_jump_next`

### ISSUE THREAD

**Issue by zengshenggit** [glepnir/lspsaga.nvim#715]
### Describe the bug

Unwanted black block at left and  the `fix` ui brokened
![深度截图_选择区域_20230117100331](https://user-images.githubusercontent.com/21997717/212798686-0b974b9f-b4f3-48f0-aa29-22a8caa6c487.png)

### Steps to reproduce

Just use commnad `lspsaga diagnostic_jump_next` work with a function which does not exists on it's type.

### Expected behavior

there are no unwanted black block at left, the `fix` ui has no problem.

### Neovim version (nvim -v)

0.8.2

### Operating system/version

Archlinux

### Terminal name/version

Alacritty

### $TERM environment variable

256color

**Comment by glepnir** [comment]
commit old
