### ISSUE TITLE
 I just want a box

### ISSUE THREAD

**Issue by xaotag** [glepnir/lspsaga.nvim#717]
![image](https://user-images.githubusercontent.com/40427877/212863583-3661a4b5-4ca9-496f-9251-7577a2800e5c.png)

**Comment by glepnir** [comment]
please add description , IDK what do you want to do ?

**Comment by xaotag** [comment]
![image](https://user-images.githubusercontent.com/40427877/212866020-9ac651ad-c4df-4ba8-a968-b8e5940a96bb.png)
/|\ /|\ /|\
就像这样，没有标题，没有背景色

**Comment by glepnir** [comment]
`ui.colors.nomal_bg = 'NONE' ` .

**Comment by xaotag** [comment]
![image](https://user-images.githubusercontent.com/40427877/212871071-493da083-f699-45bb-a7e4-f71d4875c302.png)
能否给这个函数加个判断，ui.title=xxxx

**Comment by glepnir** [comment]
用0.8.2就没有title

**Comment by xaotag** [comment]
![image](https://user-images.githubusercontent.com/40427877/212881066-7f409df2-dc3a-4721-a740-5150b55f5bba.png)
希望大佬可以添加
