### ISSUE TITLE
hover_doc shows raw markdown

### ISSUE THREAD

**Issue by naps62** [glepnir/lspsaga.nvim#718]
### Describe the bug

Using the latest commit (from 5 minutes ago) in a Rust codebase:

![image](https://user-images.githubusercontent.com/283819/212868665-a86699ae-2af7-4712-90c1-f0c2b4627528.png)

### Steps to reproduce

 ```lua
  use { 'glepnir/lspsaga.nvim', config = function() require('lspsaga').setup({})
```

### Expected behavior

Documentation gets rendered in a more readable way, and with syntax highlighting for code blocks

### Neovim version (nvim -v)

0.8.2

### lspsaga commit

886648f

### Terminal name/version

neovide

**Comment by glepnir** [comment]
enable treesitter markdown

![image](https://user-images.githubusercontent.com/41671631/212871026-aff97e9c-ede7-4e0c-b42e-131719c6bbc2.png)

**Comment by naps62** [comment]
@glepnir sorry, but this is still not clear.
I have treesitter and markdown installed:

```lua
  -- syntax highlight
  use { 'nvim-treesitter/nvim-treesitter',
    run = ':TSUpdate',
    config = function()
      require('nvim-treesitter.configs').setup({
        ensure_installed = {
          "rust",
          "lua",
          "javascript",
          "typescript",
          "tsx",
          "solidity",
          "graphql",
          "toml",
          "ruby",
          "bash",
          "python",
          "css",
          "markdown",
          "json",
          "elixir",
          "proto"
        },
        highlight = {
          enabled = true
        },
        indentation = { enabled = true }
      })

    end }
```

What exactly am I missing?

**Comment by glepnir** [comment]
enable highlight in markdown file

**Comment by naps62** [comment]
I'm sorry, but as far as I know I have it enabled. do you have more clear instructions that I could see?

**Comment by glepnir** [comment]
add event = "BufRead"  before ts update line

**Comment by naps62** [comment]
Do you mean on the treesitter installation I showed above?
I tried that, but didn't change anything. I'm a bit lost here trying to figure out a minimum reproducible version. currently commenting out all other plugins to see if anything is affecting this, but so far nothing

**Comment by jonathannerat** [comment]
@naps62 try adding `markdown_inline` instead / in addition to `markdown`. I was using just `markdown` but it couldn't parse / conceal some parts of the PHP documentation, but with `markdown_inline` it works better (still misses some parts that have html tags but it's good enough for me)

**Comment by glepnir** [comment]
> but it couldn't parse / conceal some parts of the PHP documentation

maybe we can handle these symbols ?  now I just handle some `<pre>` etc markdown symbols.

**Comment by jonathannerat** [comment]
Not sure how are you handling the rendering of the documentation, but *if* you're displaying markdown in a floating window, wouldn't it be better to make another plugin for that? Like a `markdown-conceal` or something, that handles those cases. If that's possible it would benefit other people as well since it's pretty common to find `README.md`'s with lot's of HTML tags that could be hidden.

**Comment by alextrastero** [comment]
Sorry to jump on this one but it's kinda similar, my `hover_doc` has no syntax highlighting, any idea why?
![image](https://user-images.githubusercontent.com/4152819/216812516-2a84fac5-6893-4496-83e9-16b0f0290c49.png)

**Comment by davidk55** [comment]
Had this problem for some weeks too and finally figured out the cause
I just had to add `hightlight = { enable = true }` to the treesitter setup
