### ISSUE TITLE
Could you add version tags?

### ISSUE THREAD

**Issue by craftzdog** [glepnir/lspsaga.nvim#719]
Hi glepnir,

Thank you so much for the great plugin!
v0.2.3 now requires nvim 0.9 but it's not officially released yet.
I had to look into the code and find which commit broke it.
It'd be great to have version tags so that people can easily hold back on the older LspSaga.

**Comment by glepnir** [comment]
no need neovim 0.9 if you want titile you need. if not you can use stable version neovim with lspsaga

**Comment by glepnir** [comment]
you should use issue template
