### ISSUE TITLE
Question about interaction with fzf-lsp.nvim

### ISSUE THREAD

**Issue by ner0-m** [glepnir/lspsaga.nvim#72]
Hi, I would like to know how this plugin interacts with something like [fzf-lsp](https://github.com/gfanto/fzf-lsp.nvim). Can I use your plugin along side with this? I like the style of your plugin, but I would like keep the functionality of fzf.

Thanks!

**Comment by glepnir** [comment]
i don't know anything about fzf-lsp, lspsaga do lsp request and has own ui to deal the server response/
