### ISSUE TITLE
Better symbol_in_winbar defaults

### ISSUE THREAD

**Issue by nullchilly** [glepnir/lspsaga.nvim#720]
**Is your feature request related to a problem? Please describe.**
The new default is frustrating, user who don't like winbar suddenly have them and people who use winbar got greeted with white

![image](https://user-images.githubusercontent.com/56817415/212942134-b0f3de05-c0a0-41e6-b72c-517167f01b87.png)

**Describe the solution you'd like**
Change default setting to
```lua
symbol_in_winbar = {
  enable = false,
  separator = ' ',
  hide_keyword = true,
  show_file = true,
  folder_level = 2,
  respect_root = false,
  color_mode = true,
}
```

**Comment by glepnir** [comment]
what's the problem is ? if you don't like changed it to false and there is no need copy all of options into the setup 

```lua
setup( {
      symbol_in_winbar.enable = false.
})
```

**Comment by sk-tako** [comment]
I like it but I am offering a default I think the majority wants

I guess whatever

**Comment by glepnir** [comment]
you changed it enable to false so that not work in your neovim. other options you don't need config.  and i changed the color_mode to true in default. white a littile ugly.

**Comment by nullchilly** [comment]
I don't have a problem with my own config, winbar shows up just fine

I simply offered the DEFAULT setting

> i changed the color_mode to true in default. white a littile ugly.
Finally
