### ISSUE TITLE
No window berders on Nvim 0.8

### ISSUE THREAD

**Issue by craftzdog** [glepnir/lspsaga.nvim#722]
### Describe the bug

You mentioned in https://github.com/glepnir/lspsaga.nvim/issues/719 that lspsaga v0.2.3 is still compatible with 0.8 (without title support), but the HoverDoc window no longer has borders:

![image](https://user-images.githubusercontent.com/1332805/213034387-9c3b55b8-18d0-400a-959f-d62308052005.png)

### Steps to reproduce

- Configure with Packer

```lua
  use({
    'glepnir/lspsaga.nvim',
    branch = "main",
    config = function()
      require('lspsaga').setup({
        ui = {
          title = false, -- Nvim 0.8 doesn't support window titles
          winblend = 30,
          colors = {
            normal_bg = '#002b36'
          }
        }
      })
    end
  })
```

Neither `single`,`double`,`rounded`, or `solid` worked.

### Expected behavior

Float windows have the borders.

### Neovim version (nvim -v)

0.8.2

### lspsaga commit

8b683c4

### Terminal name/version

iTerm2 3.4.19 with tmux 3.3a

**Comment by glepnir** [comment]
`ui.border = your border type` i had write it in doc.

**Comment by craftzdog** [comment]
also tried manually specifying the border style but not working

```lua
      require('lspsaga').setup({
        ui = {
          title = false, -- Nvim 0.8 doesn't support window titles
          winblend = 30,
          border = 'single',
          colors = {
            normal_bg = '#002b36'
          }
        }
      })
```

**Comment by glepnir** [comment]
packer?

**Comment by craftzdog** [comment]
yes

**Comment by glepnir** [comment]
you need run`PackerCompile`  to recompile

**Comment by craftzdog** [comment]
yes I did

**Comment by glepnir** [comment]
IDK then .can't reproduce.

![image](https://user-images.githubusercontent.com/41671631/213045185-fcd33ef9-f242-4f90-9888-6a9bf5309eab.png)

**Comment by craftzdog** [comment]
you are on 0.9. I'm on 0.8. It was working fine with 0.8 but after updating lspsaga to the latest it no longer works.
It means that it's no longer compatible with 0.8.

Here is lspsaga @ b7b4777 on Nvim 0.8.2:

<img width="1006" alt="CleanShot 2023-01-18 at 09 46 18@2x" src="https://user-images.githubusercontent.com/1332805/213053378-6d3b4503-a2ff-423b-a739-5f6c63df2dd1.png">

So, it breaks somewhere in between b7b4777 and 8b683c404b21655ba9e748c1b17ad2ab1d7c326c.

**Comment by glepnir** [comment]
I test in nvim 0.8.2 works fine.

**Comment by craftzdog** [comment]
ok thanks, I'll check what's wrong with my config.

**Comment by craftzdog** [comment]
Update:

Tried it on nvim 0.9 (https://github.com/neovim/neovim/commit/0aae7f386042593aecfc8237020899d0e94fe8e4) and it works fine (no typescript highlighting though):

<img width="412" alt="CleanShot 2023-01-18 at 13 38 07@2x" src="https://user-images.githubusercontent.com/1332805/213085460-8d94b037-fb46-4173-b84a-564b4001f0b0.png">

So, it is broken on 0.8.
I suspected that it is due to my color scheme and tried to change HoverBorder like so:

```lua
local cb = require('colorbuddy.init')
local Group = cb.Group
local colors = cb.colors
local styles = cb.styles

Group.new("HoverBorder", colors.yellow, colors.red, styles.NONE)
```

It only changes the border background color and the border line still doesn't appear as yellow.

**Comment by glepnir** [comment]
`hi HoverBorder guifg=#ffffff guibg=#000000` does this work?

**Comment by craftzdog** [comment]
oh wait, I reverted back from 0.9 to 0.8.2, and it works now for some reason😇

<img width="396" alt="" src="https://user-images.githubusercontent.com/1332805/213088079-59812070-fa0f-4630-bbe4-2df4a2725118.png">

```sh
brew uninstall --force neovim
brew autoremove
brew install neovim
```

I haven't changed my config.
So, that may be caused by a nvim dependency module.
A clean install solved it.
Sorry for bothering you and thanks so much for your help.

**Comment by rodhash** [comment]
Nvim 0.10 also doesn't work w/ rounded borders

**Comment by rodhash** [comment]
Had a fresh install and faced similar issue, in my case w/ packer and nvim 0.10 .. for some reason a reinstall also worked.
