### ISSUE TITLE
Symbols option to specify custom delimeter

### ISSUE THREAD

**Issue by nagy135** [glepnir/lspsaga.nvim#727]
<img width="321" alt="image" src="https://user-images.githubusercontent.com/11056512/213170307-c8ca38ae-180c-4ae4-bba1-00b6f3b1bb71.png">

Hello, my font has these triangles big like this, I could obviously change my font but my question (or feature request) is: Can these symbols be modified? I would simply put dash there and keep my font.

Is it possible or desired to be added? Thanks for info

**Comment by glepnir** [comment]
`symbol_in_winbar.separator = your symbol`
