### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by coffebar** [glepnir/lspsaga.nvim#728]
### Describe the bug

I see this bug when switching my projects via [project.nvim](https://github.com/coffebar/project.nvim/tree/session-manager) plugin.
**Some nil value checking may fix this.**

> Error executing vim.schedule lua callback: ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:283: attempt to index a nil value
> stack traceback:
>         ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:283: in function 'handler'
>         /usr/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
>         vim/_editor.lua: in function <vim/_editor.lua:0>

### Steps to reproduce

I see this bug when switching my projects via [project.nvim](https://github.com/coffebar/project.nvim/tree/session-manager) plugin.

I can't create a env to reproduce, but you can try to load my config from script
(IT WILL OVERWRITE your nvim config and requires **yay** to be installed)
sh -c "$(wget -O- https://raw.githubusercontent.com/coffebar/dotfiles/master/fetch-nvim-conf.sh)"

### Expected behavior

Should not be error messages 

### Neovim version (nvim -v)

0.8.2

### lspsaga commit

949234a450f6dd14fc3f9e482d69a049cf1d27c2

### Terminal name/version

alacritty

**Comment by glepnir** [comment]
please create a min config . i don't work with full config. and try the latest commit.

**Comment by glepnir** [comment]
its typo i had fixed.

**Comment by coffebar** [comment]
Can confirm, thanks!

**Comment by coffebar** [comment]
I apologize, but I noticed that the problem remained. Exactly on 283 line, where `self[ctx.bufnr]` (as in stack-trace from the first message in this thread)
So I believe, before that line should be this If statement 
```lua
    if self[ctx.bufnr] == nil then
      return
    end
```
It least error message is gone after this change

**Comment by glepnir** [comment]
nope . It should initialized before callback.

**Comment by coffebar** [comment]
It's sad, because i still see spamming error messages like in first post

`Error executing vim.schedule lua callback: ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:283: attempt to index a nil value
stack traceback:
        ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:283: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>`

**Comment by glepnir** [comment]
problem is why this buf not reigster to cache table. when render. update . you can't give me a min config that can reproduce i can only do  guess and fix.

**Comment by coffebar** [comment]
I have partial success with this configuration. Sometimes it is there, and sometimes it is not.
```lua
vim.cmd([[set runtimepath=$VIMRUNTIME]])
vim.cmd([[set packpath=/tmp/nvim/site]])
local package_root = "/tmp/nvim/site/pack"
local install_path = package_root .. "/packer/start/packer.nvim"
local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			"kyazdani42/nvim-web-devicons",
			"glepnir/lspsaga.nvim",
			"neovim/nvim-lspconfig",
			"nvim-treesitter/nvim-treesitter",
			"romgrk/nvim-treesitter-context",
			"hrsh5th/cmp-nvim-lsp",
			"hrsh7th/cmp-buffer",
			"hrsh7th/cmp-path",
			"hrsh7th/cmp-nvim-lua",
			"hrsh7th/cmp-cmdline",
			"hrsh7th/nvim-cmp",
			"L3MON4D3/LuaSnip",
			"saadparwaiz1/cmp_luasnip",
			"Shatur/neovim-session-manager",
			"nvim-lua/plenary.nvim",
			{
				"nvim-neo-tree/neo-tree.nvim",
				branch = "v2.x",
				requires = {
					"nvim-lua/plenary.nvim",
					"kyazdani42/nvim-web-devicons",
					"MunifTanjim/nui.nvim",
				},
			},
			{
				"coffebar/project.nvim",
				branch = "session-manager",
			},
			{ "nvim-telescope/telescope.nvim", tag = "0.1.0", requires = { { "nvim-lua/plenary.nvim" } } },
		},
		config = {
			package_root = package_root,
			compile_path = install_path .. "/plugin/packer_compiled.lua",
			display = { non_interactive = true },
		},
	})
end
_G.load_config = function()
	local opt = vim.opt
	opt.timeoutlen = 500
	opt.errorbells = false
	opt.number = true
	opt.shiftwidth = 2
	opt.tabstop = 2
	opt.softtabstop = 2
	local lspconfig = require("lspconfig")
	local keymap = vim.keymap.set
	local saga = require("lspsaga")
	local telescope = require("telescope")

	telescope.load_extension("projects")
	saga.setup({
		lightbulb = {
			enable = false,
			enable_in_insert = false,
		},
	})

	require("project_nvim").setup({
		session_autoload = true,
		silent_chdir = false,
		exclude_dirs = {
			"~/.local/*",
			"~/.cache/*",
			"~/.cargo/*",
			"~/.node_modules/*",
			"~/lua",
		},
		ignore_lsp = {
			"sumneko_lua",
		},
	})
	keymap("n", "gd", "<cmd>Lspsaga peek_definition<CR>", { silent = true })
	keymap("n", "gh", "<cmd>Lspsaga lsp_finder<CR>", { silent = true })
	keymap({ "n", "v" }, "<leader>ca", "<cmd>Lspsaga code_action<CR>", { silent = true })
	keymap("n", "gr", "<cmd>Lspsaga rename<CR>", { silent = true })

	keymap("n", "<leader><leader>", "<cmd>Telescope projects<cr>", { silent = true })

	lspconfig.sumneko_lua.setup({
		settings = {
			Lua = {
				runtime = {
					version = "LuaJIT",
				},
				diagnostics = {
					globals = { "vim" },
				},
				workspace = {
					library = vim.api.nvim_get_runtime_file("", true),
					checkThirdParty = false,
				},
				telemetry = {
					enable = false,
				},
			},
		},
	})
end
if vim.fn.isdirectory(install_path) == 0 then
	print("Installing dependencies.")
	vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
require("packer").sync()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])

```
Meanwhile, reproducing is stable with my full configuration.
However, for reproducing you need to have at least 2 projects saved to plugin [SessionManager](https://github.com/Shatur/neovim-session-manager).  And switch from one project to another. In this config press \ button (default leader key) twice to open telescope menu "projects", than select one of projects. Hope this will help to reproduce, but not sure(

**Comment by glepnir** [comment]
thisis not min config .and did you update it?

**Comment by coffebar** [comment]
workaround for me - is to disable winbar feature
```lua
require("lspsaga").setup({
	symbol_in_winbar = {
		enable = false,
	},
})
```

**Comment by glepnir** [comment]
please create a min config like what i do 

```lua
vim.opt.runtimepath:append("~/Workspace/nvim-lspconfig/")
vim.opt.runtimepath:append("~/Workspace/lspsaga.nvim/")

local lspconfig = require("lspconfig")
lspconfig.tsserver.setup({})

require('lspsaga').setup({})

lspconfig.sumneko_lua.setup({

  settings = {
    Lua = {
      workspace = {
        library = {
          vim.env.VIMRUNTIME,
        },
        checkThirdParty = false,
      },
    },
  },
})

```
