### ISSUE TITLE
Diagnostic window has no max size

### ISSUE THREAD

**Issue by akinsho** [glepnir/lspsaga.nvim#73]
Similar to #48 the diagnostic window isn't truncated if the message is very long so it extends off screen. Please note that this only happens if using `diagnostic_next()` or `diagnostic_prev()` functions with a mapping.

![image](https://user-images.githubusercontent.com/22454918/107068741-e525f900-67d8-11eb-8f64-d0a6c33d9514.png)

Steps to reproduce:

Prereqs:

* setup diagnostic show cursorhold autocommand 

1. Find a very long error, 😓 not sure how to recommend one.
2. Use jump to next diagostic to get to it, and see  really long message.
3. Return to the error with your cursor and the size will be normal.

![lsp_saga_diagnostic](https://user-images.githubusercontent.com/22454918/107069215-857c1d80-67d9-11eb-9e46-f01a6639e8a8.gif)

**Comment by akinsho** [comment]
Sorry my GIF software is crap the second time I went back to the error the window was normal sized but it doesn't show in the GIF

**Comment by akinsho** [comment]
Ah so I misunderstood. The window show is actually different, jump to diagnostic show a different window than `show_line_diagnostics`. The `jump_to_diagnostic` window is the one that is unbounded

**Comment by glepnir** [comment]
yep need fix it.

**Comment by akinsho** [comment]
@glepnir I just tried it again after your fix and I still see the same behaviour 😢

**Comment by glepnir** [comment]
use jump diagnostic?

**Comment by glepnir** [comment]
you can add debug = true add saga conf . then use jump error it ill print output of diagnostic message ,post here Thanks.

**Comment by akinsho** [comment]
Yep this is using jump diagnostic, I'll try with debug

**Comment by akinsho** [comment]
Hmm just added the debug key but it doesn't print anything with that command
```lua
  map("n", "[c", "<cmd>lua require'lspsaga.diagnostic'.lsp_jump_diagnostic_next()<CR>")
```

**Comment by glepnir** [comment]
I test it works , this `Lspsaga diagnostic_jump_next` also your can use table to completion
![image](https://user-images.githubusercontent.com/41671631/107118131-09a5d200-68ba-11eb-9f75-b27c578eadbe.png)

**Comment by glepnir** [comment]
I mean use tab on commandline to complete the `Lspsaga |` subcommands.Using the wrap option to wrap lines does not look so good, and it can’t adapt to different window widths

**Comment by akinsho** [comment]
@glepnir I just got the latest update with the debug added for diagnostic. The full error message I'm getting that is causing the large window is
```
"The name 'LinkExceptionHandler' is defined in the libraries 'package:ferry/src/offline_mutation_typed_link.dart (via package:ferry/typed_links.dart)' and 'package:ferry_offl
ine_client/src/offline_mutation_typed_link.dart'. Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports."
```

**Comment by glepnir** [comment]
now fixed

**Comment by akinsho** [comment]
Thanks that works now 👍🏿
