### ISSUE TITLE
Seeing Error: lspsaga.nvim v0.2.3+ has breaking changes.

### ISSUE THREAD

**Issue by alwindoss** [glepnir/lspsaga.nvim#732]
### Describe the bug

I see the error when I open neovim when I use Windows terminal to access my fedora server having the neovim configured.

Error:

```
Error detected while processing /home/alwin/.config/nvim/init.lua:
lspsaga.nvim v0.2.3+ has breaking changes. Please read the docs and migrate your configuration to the new "setup" function!
```

The contents of my `init.lua` file is

```
...
require("alwindoss.plugins.lsp.lspsaga")
...
```

The contents of my 

```
-- import lspsaga safely
local saga_status, saga = pcall(require, "lspsaga")
if not saga_status then
  return
end

saga.init_lsp_saga({
  -- keybinds for navigation in lspsaga window
  move_in_saga = { prev = "<C-k>", next = "<C-j>" },
  -- use enter to open file with finder
  finder_action_keys = {
    open = "<CR>",
  },
  -- use enter to open file with definition preview
  definition_action_keys = {
    edit = "<CR>",
  },
})
```

### Steps to reproduce

Configuration of my neovim is available here: [neovim config](https://github.com/alwindoss/nvim)

### Expected behavior

Did not expect to see any error

### Neovim version (nvim -v)

0.8.2

### lspsaga commit

main

### Terminal name/version

Windows Terminal

**Comment by pedrovalido** [comment]
I'm having the exact same issue. My configuration is the same but folder structure is different. My configs are here https://github.com/pedrovalido/nvim

**Comment by pedrovalido** [comment]
@alwindoss you can check the saga.init_lsp_saga has been changed to show that error message and the new function saga.setup has been changed here (https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/init.lua)

**Comment by saman-zdf** [comment]
@alwindoss I having the same error after updating my plugins, I would appreciate if anyone could let me know how to fix this issue. tnx

**Comment by pedrovalido** [comment]
Check the above comment

**Comment by pedrovalido** [comment]
Use the saga.setup function instead

**Comment by glepnir** [comment]
I think the doc already include how to install and usage . duplicate https://github.com/glepnir/lspsaga.nvim/issues/692

**Comment by alwindoss** [comment]
@glepnir that is a backward incompatible change. Please correct me if I am wrong here. The deprecated annotation was added now, it doesn't seem to exist from early in December.
Shouldn't you have notified your users before making such a change or increment your major version?

**Comment by glepnir** [comment]
#586 had exist a long time.

**Comment by alwindoss** [comment]
@glepnir I agree with you. I am new to neovim but I will defer to you regarding this change. I am sure it was the right thing to do.
I am questioning the backward incompatible change pushed in a minor version and without notification.

**Comment by alwindoss** [comment]
@glepnir so you are saying I can put the same co figuration that existed inside `init_lsp_saga` into `setup`. Is there anything else to watch out for here?

**Comment by glepnir** [comment]
about options . i found lots of people copied all the default options into `setup` or before `init_saga` function . I don't know why do this.  you just put the options which you modifed into the setup function table params . like

```
require('lspsaga').setup({
     ui = {
          border = 'double'
     },
    finder = {
         quit = 'xxx'
   }
})
```

options you can find from usage tutorial.  it will tell you the default options is what and default value of this option, and teach you how to use some command and workflow.

**Comment by stoddart** [comment]
Here's how I fixed the breaking changes: [https://github.com/stoddart/.config-nvim/commit/73485f9654e71a3db0247ac9023f1714ea2d9f55](url)
