### ISSUE TITLE
More configuration on hover doc, like keep active when typing.

### ISSUE THREAD

**Issue by SoulAttacker** [glepnir/lspsaga.nvim#736]
**Is your feature request related to a problem? Please describe.**
Not yet, first lspsaga is verrrrrrry beautiful and useful for me, but what has always bothered me is when I still in insert mode, I want to ref doc but I have to go back to normal mode and type `K`(call hover doc), but if there is some solution about always 'pin' hover doc or just be a float term to show doc when typing?

**Describe the solution you'd like**
Maybe a ref solution like one configuration in emacs, but sorry I don't know what else plugin he use, like 
![shot](https://user-images.githubusercontent.com/49908231/213387724-1e4d46f2-ae03-4f77-a636-9064152d623b.jpg)
I think it can be configure like pinned on right top or right bottom, anyway, maybe keep hover doc more configuration! XD.

**Describe alternatives you've considered**
I didn't try other hover doc plugins, so sorry for that.

**Additional context**
pls ref to the first screen shot

by the way, best for ya, pay attention to rest and happy new year!

**Comment by glepnir** [comment]
maybe we can add some kind of hover keymap . link `normal / keep` if keep it will appeared at the right top and if you want close it press keymap twice . but if you want jump it into you must need use wincmd command like `<C-w>w` how do you feel ?

**Comment by brettmitchelldev** [comment]
Love this idea! Piggybacking off of this, maybe the usability could be better if there were keybindings to scroll the hover doc window without focusing it? Similar to the way that Telescope lets you scroll the preview window with a custom keybinding.

**Comment by glepnir** [comment]
saga options have scroll keymap. you can change that

**Comment by glepnir** [comment]
saga options have scroll keymap. you can change that

**Comment by brettmitchelldev** [comment]
Whoops, lol, ignore me then. I should RTM before I comment... :sweat_smile:

**Comment by SoulAttacker** [comment]
hello, I tried new functions, I looooove it, and I still wanna asking if there is a plan for supporting signature help? because it's very useful!

best for ya!
