### ISSUE TITLE
"height" key must be a positive integer -- hover_doc on tailwindcss

### ISSUE THREAD

**Issue by Nitesh000** [glepnir/lspsaga.nvim#737]
### Describe the bug

I have been using saga for like 2-3 months and I really appreciate you guys for doing great work. 
#### Bug:
While hovering some document the tailwindcss or some other classNames on react it always shows up:
```
Error executing vim.schedule lua callback: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/window.lua:152: 'height' key must be a positive Integ
er
stack traceback:
        [C]: in function 'nvim_open_win'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/window.lua:152: in function 'create_win_with_border'
        ...ite/pack/packer/start/lspsaga.nvim/lua/lspsaga/hover.lua:75: in function 'open_floating_preview'
        ...ite/pack/packer/start/lspsaga.nvim/lua/lspsaga/hover.lua:148: in function 'handler'
        /snap/nvim/2789/usr/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```
The hover_doc does show up the hover document...but after the error shows up.

#### Operating System:
- Ubuntu 22.04 

### Steps to reproduce

- Just create a react application and then set up the tailwind in it.
- add some tailwindcss class names and the try hovering over the class 
- The error will show up.

### Expected behavior

- Able to get the code details with hover_doc
- In my case: **Should be able to view all the detailed css style**

### Neovim version (nvim -v)

NVIM v0.8.2

### lspsaga commit

f4d1260

### Terminal name/version

gnome-terminal/ 3.44.0-1ubuntu1

**Comment by glepnir** [comment]
does `:lua vim.lsp.buf.hover()` have any output?

**Comment by Nitesh000** [comment]
> does `:lua vim.lsp.buf.hover()` have any output?

Yeah.. it shows the normal result. And working properly.

**Comment by glepnir** [comment]
what output ? I thinkt it should does not popup any window ? it mean result.content is empty

**Comment by Nitesh000** [comment]
> what output ? I thinkt it should does not popup any window ? it mean result.content is empty

It shows up an overlay of the hover details

**Comment by Nitesh000** [comment]
In my case the variable hover_docs is showing properly but if i go to the class then it is showing the error.

**Comment by Nitesh000** [comment]
Thnx man.

**Comment by val3ntin-ch** [comment]
same thing happening on my side, when i try to hover over different functions etc , i get the same issue, :lua vim.lsp.buf.hover()  it's working fine ,

Here it's the error

![Screenshot 2023-02-19 at 23 15 14](https://user-images.githubusercontent.com/25511415/219975916-b6c3985b-bb85-444c-a53c-bed6f64b655c.png)

Operating System:
macOs ventura 13.1 

Steps to reproduce
Create a Next.js app, try to hover on different function, classes on the project.
Try hovering over the function, etc
The error will show up.

NVIM
NVIM v0.9.0 

Terminal iTerm2
Build 3.4.19

**Comment by Nitesh000** [comment]
Yup, it might be a bug. You should just create a new issue and let him know?

**Comment by Nitesh000** [comment]
new version is just released, may be a bug

**Comment by glepnir** [comment]
fixed

**Comment by val3ntin-ch** [comment]
Thank you @glepnir
