### ISSUE TITLE
Winbar error when moving around

### ISSUE THREAD

**Issue by dsummersl** [glepnir/lspsaga.nvim#738]
### Describe the bug

I see this stack trace:

```
Error detected while processing CursorMoved Autocommands for "<buffer=1>":
Error executing lua callback: ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:258: Vim:E36: Not enough room
stack traceback:
        [C]: in function '__newindex'
        ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:258: in function 'render_fn'
        ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:313: in function 'init_buf_symbols'
        ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:335: in function <...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:334>
```

It seems like it triggers with the Matchup plugin shows an off screen paren match (I'm using the `matchup_matchparen_offscreen = {method= 'popup'}` setting).

### Steps to reproduce

Use nvim with the following plugins enabled (packer config here):

```
  use { 'andymass/vim-matchup', config = function()
    vim.g.matchup_matchparen_hi_background = 2
    vim.g.matchup_matchparen_offscreen = {method= 'popup'}
  end}

      require('lspsaga').setup({
        symbol_in_winbar = {
          enable = true,
          show_file = false,
        },
        lightbulb = {
          enable = false,
          saga_winblend = 20,
        }
      })

```

Open a file that has some paran matching of some kind. For instance:

```
    package "Intell 2800 - Simple Version" {
      [ComputerCommunications] -up- USB
      [ComputerCommunications] - [MainComputerProcess]
      [KinectProcessing] -down-> KINECT
      [KinectProcessing] - [MainComputerProcess]
      [VideoProcessing] -down-> Camera
      [VideoProcessing] - [MainComputerProcess]
      [ComputerCommunications2] -up- [MainComputerProcess]
      [ComputerCommunications2] -down- WiFi
      [ComputerCommunications2] -down- Bluetooth
    }
    EXTRATEXT
```

Position the cursor at EXTRATEXT and then use <Ctrl-E> to scoot the first line off screen. `j` to move to the '}' character.

The matchup off screen text is displayed (the first line), and a stack trace appears for the winbar plugin.

### Expected behavior

no stack trace.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-589+gcce736218-dirty

### lspsaga commit

79e1f5b81e9356b27e52b162dbfd1d5e242b8c7d

### Terminal name/version

wezterm

**Comment by glepnir** [comment]
does this file have lsp server? and if have which server is.

**Comment by dsummersl** [comment]
Yes...yamlls and null-ls

**Comment by glepnir** [comment]
the matchup is builtin plugin or vim-matchup ?

**Comment by dsummersl** [comment]
sorry about that - vim-matchup!

**Comment by glepnir** [comment]
does that file is yml file ? not looks like normal yaml file .  I think the reproduce step should more clear ..and I guess this is neovim bug 

![image](https://user-images.githubusercontent.com/41671631/213469884-20df9076-af89-47c0-b7da-ef7becc202b9.png)

**Comment by dsummersl** [comment]
Yeah, sorry I only have you a snippet. Its actually a yaml file that looks more like:

```yaml
---
- key: |-
    some other code {
       ...
       ...
    }
```

I've reproduced the error in a Lua and TypeScript file as well.

**Comment by glepnir** [comment]
can not reproduce i don't use that plugin

**Comment by glepnir** [comment]
I use a min config for test and it works well.

![diagnostic](https://user-images.githubusercontent.com/41671631/213510595-3ed9aea3-1346-4198-bca2-e76f28b6ca14.gif)

**Comment by eXvimmer** [comment]
This happens to me as well.

[Screencast from 01-19-2023 09:13:20 PM.webm](https://user-images.githubusercontent.com/30720669/213520907-5cd27cd4-351b-43f3-a551-c4f9c5199ea0.webm)

**Comment by glepnir** [comment]
did you read error message?

**Comment by eXvimmer** [comment]
Sorry, my bad. I just read the errors and those are identical.
