### ISSUE TITLE
control the number of lines displayed by code action

### ISSUE THREAD

**Issue by horaoen** [glepnir/lspsaga.nvim#739]
Is there any way to control the number of lines displayed by code action？
![image](https://user-images.githubusercontent.com/92006580/213516232-7864012e-2d0f-43bd-88dd-f651995bed82.png)
The experience is bad when there are too many code action lines。

**Comment by glepnir** [comment]
the window behavior had improved . the number ui  I don't have better design currently . when i have it will be rewrite.

**Comment by horaoen** [comment]
> the window behavior had improved . the number ui I don't have better design currently . when i have it will be rewrite.

I may not express what I mean clearly, I want to control the code action not to display so much that it takes up the full screen. It would be nice if I could configure it to only show up to ten lines

**Comment by glepnir** [comment]
update ?

**Comment by horaoen** [comment]
> update ?
thanks, It's pretty good
