### ISSUE TITLE
when applying this `lua require('lspsaga.rename').rename()` on non-identifiers or builtin keywords  it doesn't warn me and does nothing

### ISSUE THREAD

**Issue by rustiever** [glepnir/lspsaga.nvim#74]
I encountered this issue in gopls server,
I expected something like throw an error in status line

**Comment by glepnir** [comment]
Gopls did not return any check messages, so the rename of other lsp plugins should also behave consistently, such as the built-in codename, and it did not throw any errors.
The solution to this problem I can think of is to maintain a Go keyword table to check whether the current cursor word matches
