### ISSUE TITLE
Error when opening lsp_finder with omnisharp-mono lsp

### ISSUE THREAD

**Issue by deankinane** [glepnir/lspsaga.nvim#743]
### Describe the bug

When opening the finder I'm receiving the below error message:

![image](https://user-images.githubusercontent.com/22434814/213585645-06c24c42-2232-44da-aa28-d60f7770a79d.png)
 
This is only occurring when using C# with the omnisharp lsp.
It works perfectly fine with Lua, TypeScript and Rust with the same configuration.

### Steps to reproduce

Using basic config:

use({
    "glepnir/lspsaga.nvim",
    branch = "main",
    config = function()
        require('lspsaga').setup({})
    end,
})

Install omnisharp-mono lsp.
Open a C# project and attempt to use the finder.

### Expected behavior

Finder opens as normal

### Neovim version (nvim -v)

0.8.1

### lspsaga commit

ca5bc84

### Terminal name/version

Windows Terminal Version: 1.15.3465.0 (Running Ubuntu on WSL 2)

**Comment by glepnir** [comment]
duplicate https://github.com/glepnir/lspsaga.nvim/issues/661

**Comment by deankinane** [comment]
Apologies, I'm not sure how I didn't find this while searching.
Thanks for your help.
