### ISSUE TITLE
Code action & diagnostic jump

### ISSUE THREAD

**Issue by yunag** [glepnir/lspsaga.nvim#744]
### Describe the bug

When there is only one error/warning message with a codeaction, invoking :Lspsaga diagnostic_jump will cause this bug.

https://user-images.githubusercontent.com/94868861/213698004-c14d6dd7-1f9b-4c3d-8a0b-454644785ad6.mp4

### Steps to reproduce

$ nvim main.c
declare a variable
use this variable, but make a typo so that clangd provides a code action for it.
make sure there is only one error/warning in the file.

### Expected behavior

Don't spawn multiple code action messages

### Neovim version (nvim -v)

0.8.2 stable

### lspsaga commit

last commit

### Terminal name/version

powershell

**Comment by glepnir** [comment]
sorry I can't reproduce i tried in `nvim 0.8.2 ` and `nvim 0.9` both works fine. please try use a min config to reproduce.

![diagnostic](https://user-images.githubusercontent.com/41671631/213702564-cfdf31c6-0e58-47c4-a440-5105034310e4.gif)

**Comment by yunag** [comment]
Oh I see. Your cursor should be on the same place everytime you are calling diagnostic jump. My mistake
