### ISSUE TITLE
Highlights for 'CodeActionBg' and 'DiagnosticMsg'

### ISSUE THREAD

**Issue by iovis** [glepnir/lspsaga.nvim#747]
I recently upgraded and found out about the theme overhaul.

I managed to tweak most of the highlights to my preference, but I found out that there's no good way to override the `CodeActionBg0` and `DiagnosticMsg|DiagnosticMsgIcon`.

I actually find it helpful that they get colored based on the diagnostic, but the switch of foreground and background colors is a bit too much for me (with my current theme I also find it a bit hard to read myself).

Any plans on allowing for direct overrides of those highlights? I tried defining the highlights (at least for `CodeActionBg{N}`, but they get overridden anyway. Although I'd be happy with just not inverting the colors in these cases.

This screenshot should showcase both highlights (there also seems to be a bit of inconsistent padding on the code actions section). Btw, great idea adding the "fixes" section there!

![Screenshot 2023-01-20 at 13 06 58](https://user-images.githubusercontent.com/6660202/213774549-638d5641-1058-4467-acea-9db7f5fa3340.png)

**Comment by glepnir** [comment]
codeactionbg number is random .you can change the color code in ui.colors.  diagnostic relate color is follow the diagnostic type.

**Comment by iovis** [comment]
I guess I didn't explain myself correctly. My point was not about the colors themselves, it's about them being inverted (using fg as bg). 

I've already tweaked UI colors and highlights to match what I wanted, but these two don't seem to be customizable to not use a color as background and it's hard to read for me

**Comment by glepnir** [comment]
`DiagnosticMsg`  if you already defined it will linked it to your defined.

**Comment by iovis** [comment]
> `DiagnosticMsg` if you already defined it will linked it to your defined.

I'm not seeing this behavior, so I'm guessing I'm doing something wrong:
```lua
vim.api.nvim_set_hl(0, "DiagnosticMsg", { fg = "#00ff00" })
vim.api.nvim_set_hl(0, "DiagnosticMsgIcon", { fg = "#0000ff" })
```

Then I check to confirm those highlights were defined:
```
:hi DiagnosticMsg                                                                                         
DiagnosticMsg  xxx guifg=#00ff00
```

Then I force a diagnostic error and navigate to it with `:Lspsaga diagnostic_jump_prev`

Observe that the highlights were redefined:
```
:hi DiagnosticMsg                                                                                         
DiagnosticMsg  xxx guifg=#1c1c19 guibg=#ab4642
```
---

For context, I actually love the idea of the colors being redefined to match the diagnostic, I just have a hard time reading with the `bg` being set to the color.

If you decide to expose an option to not invert colors (fg swap with bg), I'll likely use that one. If you decide to allow for the highlight to not be preserved, I'll probably use it to hide the message instead.

**Comment by glepnir** [comment]
diagnostic message text is `DiagnosticText`
