### ISSUE TITLE
Error E5248: Invalid character in group name when using lsp_finder or definition

### ISSUE THREAD

**Issue by refactor-this** [glepnir/lspsaga.nvim#748]
### Describe the bug

When using `Lspsaga lsp_finder` command (and others like `goto_definition`), I get `E5248: Invalid character in group name`
I can hit `enter` until the floating window finally displays, amount of times depends on how many references there are displayed in floating window.

If I cause error to happen again and hit `esc` I get:
```
Error executing vim.schedule lua callback: vim/_meta.lua:0: Expected lua string
stack traceback:
        [C]: in function 'nvim_get_option_info'
        vim/_meta.lua: in function '__index'
        vim/_meta.lua: in function ''
        vim/_meta.lua: in function '__index'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:692: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Tested in Nvim v0.8.2 and Nvim 0.9

### Steps to reproduce

Use `Lspsaga lsp_finder` on anything, tried in JS and Go code.

### Expected behavior

No error should come up, just the floating window

### Neovim version (nvim -v)

NVIM v0.8.2 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@Ventura-arm64.local

### lspsaga commit

latest main branch

### Terminal name/version

Iterm v3.4.19

**Comment by glepnir** [comment]
provide a more detail reproduce step I don't what do you mean and I can't reproduce.

**Comment by refactor-this** [comment]
If I try to run the `Lspsaga lsp_finder` command while the cursor is hovered over any part of my code. Whether it's vars, objects, functions, anything, I get that error. I can continuously hit `enter` and eventually the Lspsaga floating window shows with the correct definition and other info.

**Comment by glepnir** [comment]
it works fine for me .  `E5248: Invalid character in group name` this mean some highlight group have a invalid character.
please try the min config. thanks.

![image](https://user-images.githubusercontent.com/41671631/213842759-2a0f2ea1-0f24-4311-9d9c-87fcaebee186.png)

**Comment by refactor-this** [comment]
Tried again with min config except for using `lazy` and doesn't work. Is there a dependency with the lazy plugin? I will keep trying other things as well

**Comment by glepnir** [comment]
need `nvim-web-devicons` in some where.

**Comment by intxff** [comment]
@refactor-this  Same issue after updating yesterday. Today find this issue and glepnir is right. I am using `packer` and then run `PackerStatus` find `nvim-web-devicons` is not loaded. You should check its status by `lazy`. Maybe I should not reply to a closed issue. Hope this info can help you.

**Comment by HendrikPetertje** [comment]
I tried to fix the issue on my end (Packer) by doing the following in my plugins definition:

```lua
  use {
    "glepnir/lspsaga.nvim",
    branch = "main",
    requires = { 'nvim-tree/nvim-web-devicons' }
  }
```

But adding that require didn't do too much sadly.
I was still getting these `E5248: Invalid character in group name` errors.

But then I did :PackerStatus and noticed that my devicons hadn't loaded yet (said not-loaded) meaning that none of that had been initialized yet.

So that made me add this little line in my plugins (and re-run packersync)

```lua
  -- Global require dev icons
  use {
    'nvim-tree/nvim-web-devicons',
    config = function()
      require'nvim-web-devicons'.setup {}
    end
  }
```

And low and behold, now everything works like it should. So it seems that LSPSaga doesn't execute a `setup({})` when the plugin hasn't been loaded yet, and just manually doing that before loading lspsaga does the trick :)

**Comment by HendrikPetertje** [comment]
It looks like nvim-tree and other plugins that use devicons attempt to run a setup call on it to boot it up:

```lua
  if M.config.renderer.icons.show.file and pcall(require, "nvim-web-devicons") then
    require("nvim-web-devicons").setup()
  end
```
(https://github.com/nvim-tree/nvim-tree.lua/blob/96506fee49542f3aedab76368d400a147fea344e/lua/nvim-tree.lua#L845-L847)

It looks like this plugin doesn't call a setup. I'll see if i can make a pull request to address it!

POI: https://github.com/glepnir/lspsaga.nvim/blob/ca5bc84ef68f18c6dc99962791f08dbc0163dce8/lua/lspsaga/libs.lua#L27-L33
