### ISSUE TITLE
Diagnostic pop-up overwrites hovered character

### ISSUE THREAD

**Issue by rensftw** [glepnir/lspsaga.nvim#750]
Whenever the diagnostic pop-up appears **above** a line the current character gets overwriten with `┃`
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/22574186/213886267-16d0de08-75e1-4e49-b979-ef52eb4c528c.png">

```
nvim v0.8.2
tmux v3.3a
Alacritty v0.11.0
lspsaga commit #57a29c028
```

**Comment by glepnir** [comment]
I can't reprodue your issue . it's not override the char in another window

**Comment by glepnir** [comment]
which commit ?

**Comment by glepnir** [comment]
in my test it works fine you config some markdown server . i did not use that.

![image](https://user-images.githubusercontent.com/41671631/213916142-de93f46a-1323-41f4-820c-29cfefac6ec1.png)

**Comment by glepnir** [comment]
i can't reproduce . you may need use a min config to reproduce it .

![image](https://user-images.githubusercontent.com/41671631/213916674-3cec8993-ab68-4045-9eed-5d4e0e69d5d8.png)


![image](https://user-images.githubusercontent.com/41671631/213916706-5672eac5-72a2-42a6-b729-daef6d0350bd.png)

**Comment by glepnir** [comment]
output of `:echo winwidth` and with a min config if you can reproduce.

**Comment by glepnir** [comment]
should be fixed.
