### ISSUE TITLE
Support transparency

### ISSUE THREAD

**Issue by rensftw** [glepnir/lspsaga.nvim#751]
**Is your feature request related to a problem? Please describe.**
It would awesome for lspsaga to support transparency in floating windows/pop-ups (such as diagnostic messages, terminal, etc)
Currently diagnostic pop-ups look like this:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/22574186/213886566-6b87dcd3-ceab-450d-9c01-b146ee2e8985.png">

**Describe the solution you'd like**
An example of a plugin that supports transparency is Telescope:
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/22574186/213886584-06846c73-229d-4e63-a9fc-17a8669dc54a.png">
It would be awesome if lspsaga pop-ups looks similar to that in terms of transparency

**Comment by Tantol** [comment]
Try this:

```
saga.setup({
  ui = {
    colors = {
      normal_bg = "NONE",
      title_bg = "NONE"
    }
  }
})
```

**Comment by glepnir** [comment]
does you used the latest version ? I had add a patch for this window it should work for transparency background

**Comment by glepnir** [comment]
please update

**Comment by glepnir** [comment]
no problem then.
