### ISSUE TITLE
Lspsaga ui and keystrokes completely buggy

### ISSUE THREAD

**Issue by diegoulloao** [glepnir/lspsaga.nvim#753]
### Describe the bug

From one day to another (after package updates) Lspsaga is not working anymore as expected. All ui looks without borders, sometimes I get errors in the statusline and defined keybindings are not working...

https://user-images.githubusercontent.com/45423661/213888503-ae794e78-07f6-4402-a0ca-ece3586de587.mp4

```lua
-- require lspsaga
local status, saga = pcall(require, "lspsaga")
if not status then
  return
end

-- custom setup
saga.setup({
  move_in_saga = { prev = "<C-k>", next = "<C-j>" },
  finder_action_keys = { open = "<CR>" },
  definition_action_keys = { edit = "<CR>" },
  symbol_in_winbar = {
    enable = true,
    separator = " › ",
    hide_keyword = true,
    show_file = false,
    folder_level = 2,
    respect_root = false,
    color_mode = true,
  },
})
```

### Steps to reproduce

-

### Expected behavior

See borders, keybinding workings, no errors.

### Neovim version (nvim -v)

0.8.2

### lspsaga commit

latest (I have updated)

### Terminal name/version

iterm2 3.4.19

**Comment by glepnir** [comment]
please read doc

**Comment by glepnir** [comment]
ui.border

**Comment by diegoulloao** [comment]
I already tried it before open this issue. Anyway all was working good before the update without having defined borders.
I'm having the same issues.

**Comment by diegoulloao** [comment]
https://user-images.githubusercontent.com/45423661/213894350-6f391993-c3a1-4d7e-a916-0cac32b4a605.mov

What about those issues when renaming?

Before when I opened peek_definition and pressed enter it took me into the file, now isn't working even with the keybinding defined.

**Comment by glepnir** [comment]
solid border is default doc had said this. what is solid? it use space character fill `:h nvim_open_win` . all options in doc usage tutoriail you used old options which already removed. please see  usage tutorial.
