### ISSUE TITLE
broken line number jump/navigation starting with 1

### ISSUE THREAD

**Issue by juanpprieto** [glepnir/lspsaga.nvim#754]
### Describe the bug

As the title shows, I am getting an error whenever I try to execute a line number navigation starting with 1. eg - `1j`, `12k`...

All other movements are fine `2j`, `3k`, but I do get the error from time to time with some of these too.

I saw this issue a week or so ago, but then one of your updates seems to have fixed it.

It seems to have returned these last couple of days.

```
E5108: Error executing lua: ...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:280: attempt to index field 'action_tuples' (a nil value)
stack traceback:
	...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:280: in function 'do_code_action'
	...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:212: in function <...ack/packer/start/lspsaga.nvim/lua/lspsaga/codeaction.lua:208>
```

### Steps to reproduce

Sorry don't have small repro.

### Expected behavior

Jump navigation should not create an error

### Neovim version (nvim -v)

nightly

### lspsaga commit

https://github.com/glepnir/lspsaga.nvim/commit/57a29c0286bf16ea3c4f20d5938fc6680a198940

### Terminal name/version

Alacritty

**Comment by mgramigna** [comment]
@juanpprieto It is resolved now. In case you're curious of the repo, I think this is the same as #741

**Comment by juanpprieto** [comment]
thanks for the heads up @mgramigna
