### ISSUE TITLE
No information available on status bar when calling hover_docs

### ISSUE THREAD

**Issue by diegoulloao** [glepnir/lspsaga.nvim#755]
### Describe the bug

Every time I call hover_docs I get a message:
> No information available

I'm using vim-notify so I'm getting the message through this plugin

Capture:

https://user-images.githubusercontent.com/45423661/213901180-75419150-1687-4b0b-b18f-c0555c44ba7a.mov

### Steps to reproduce

call hover_docs?

### Expected behavior

See none notification.

### Neovim version (nvim -v)

0.8.2

### lspsaga commit

latest

### Terminal name/version

iterm2 3.4.19

**Comment by glepnir** [comment]
++quiet argument
