### ISSUE TITLE
code action action_tuples bug

### ISSUE THREAD

**Issue by TheSafdarAwan** [glepnir/lspsaga.nvim#757]
### Describe the bug

after doing the the `:Lspsaga diagnostic_jum_prev|next` this error pops in if i try to go to lines using the numbers(relative line numbers) in normal mode
```
E5108: Error executing lua: .../pack/packer/opt/lspsaga.nvim/lua/lspsaga/codeaction.lua:280: attempt
to index field 'action_tuples' (a nil value)
stack traceback:
        .../pack/packer/opt/lspsaga.nvim/lua/lspsaga/codeaction.lua:280: in function 'do_code_action'

        .../pack/packer/opt/lspsaga.nvim/lua/lspsaga/codeaction.lua:212: in function <.../pack/packer
/opt/lspsaga.nvim/lua/lspsaga/codeaction.lua:208>

```

### Steps to reproduce

`

### Expected behavior

`

### Neovim version (nvim -v)

`

### lspsaga commit

`

### Terminal name/version

`

**Comment by glepnir** [comment]
which commit ? you should fill issue template. i can't reproduce your issue.
