### ISSUE TITLE
jump to next prev diagnostic throws an error

### ISSUE THREAD

**Issue by yeseongmoon** [glepnir/lspsaga.nvim#758]
### Describe the bug

https://user-images.githubusercontent.com/20822372/213921686-12d461be-8be1-432a-a1cc-cb3707aaec04.mov

Jump to next or prev diagnostic gives me an error message.

### Steps to reproduce

in video

### Expected behavior

go to where the diagnostics come from without an error.

### Neovim version (nvim -v)

0.8.2

### lspsaga commit

goto_next, goto_prev error

### Terminal name/version

kitty 0.26.5

**Comment by glepnir** [comment]
if you use diagnostic function to jump now you.need use diagnostic:goto_next. command no need change

**Comment by yeseongmoon** [comment]
> if you use diagnostic function to jump now you.need use diagnostic:goto_next. notice not dot symbol. command no need change

I don't quite get what you're saying. My keymap for goto_next, goto_prev. what is the dot symbol you meant by?
`keymap.set("n", "[d", function()
	require("lspsaga.diagnostic").goto_prev({ severity = vim.diagnostic.severity })
end)
`
`
	keymap.set("n", "]d", function()
		require("lspsaga.diagnostic").goto_next({ severity = vim.diagnostic.severity })
	end)
`

**Comment by yeseongmoon** [comment]
> if you use diagnostic function to jump now you.need use diagnostic:goto_next. notice not dot symbol. command no need change

Oh okay I found the problem. I think you need to change the doc on " :Lspsaga diagnostic_jump_next " section.
<img width="746" alt="Screenshot 2023-01-23 at 12 31 53 AM" src="https://user-images.githubusercontent.com/20822372/213924406-dcc587f2-0c4a-46f3-99c8-ce88b6ec583b.png">
I kept looking at this code, so I couldn't find the difference from mine.
It is correct on " Example Configuration "
<img width="741" alt="Screenshot 2023-01-23 at 12 31 40 AM" src="https://user-images.githubusercontent.com/20822372/213924447-63814b47-9ec5-402a-9142-cbb2a3df9402.png">
