### ISSUE TITLE
Error suddenly appears when picking definition

### ISSUE THREAD

**Issue by diegoulloao** [glepnir/lspsaga.nvim#759]
### Describe the bug

When I press the keys for display the peek_definition float window sometimes crashes, randomly.

https://user-images.githubusercontent.com/45423661/213924531-da75fda0-0808-4605-9a7d-404e0d4e77bc.mov

```
Error executing vim.schedule lua callback: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/window.lua:152: non-float cannot have 'row'
stack traceback:
        [C]: in function 'nvim_open_win'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/window.lua:152: in function 'create_win_with_border'
        ...ack/packer/start/lspsaga.nvim/lua/lspsaga/definition.lua:230: in function 'callback'
        ...w/Cellar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp.lua:1951: in function 'handler'
        ...w/Cellar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps to reproduce

open peek_definition one and one time again until crashes (floating window mode).

### Expected behavior

not crash

### Neovim version (nvim -v)

0.8.2

### lspsaga commit

latest

### Terminal name/version

iterm2 3.4.19

**Comment by Hamm-J** [comment]
Experiencing the same error after a recent update.
