### ISSUE TITLE
Floating windows getting stuck when jumping to the next diagnostic

### ISSUE THREAD

**Issue by diegoulloao** [glepnir/lspsaga.nvim#760]
### Describe the bug

When pressing the keybind for jump to the next diagnostic the floating windows are getting stuck around the buffer.

https://user-images.githubusercontent.com/45423661/213929249-d11b7c5f-da83-4c71-aec2-d2d5165aba5c.mov

### Steps to reproduce

Jump to the next diagnostic

### Expected behavior

Floating windows should disappear when moving the cursor

### Neovim version (nvim -v)

0.8.2

### lspsaga commit

latest

### Terminal name/version

iterm2 3.4.19

**Comment by glepnir** [comment]
cannot reproduce。 you  should test it with min config

**Comment by arminveres** [comment]
Happens to me as well. It is not just diagnostic windows. Outgoing/Incoming calls and hovers etc. all get stuck from time to time.

**Comment by glepnir** [comment]
`Outgoing/Incoming calls` reproduce step ? i am not god. I can't imageine what you happened
