### ISSUE TITLE
Lspsaga hoverdoc

### ISSUE THREAD

**Issue by stonewall1901** [glepnir/lspsaga.nvim#761]
The code'keymap("n", "K", "cmd>Lspsaga hover docCR>") used to work properly, but now when I click "K" it says "[Lpsaga.nvim] please install markdown parser in nvim-treesitter"

Can you give me some advice on how to fix this?

**Comment by glepnir** [comment]
nvim-treesitter install  markdown parser

**Comment by MiuKaShi** [comment]
> nvim-treesitter install markdown parser

but I use pandoc-syntax for highlighting markdown file，not use treesitter. Once install markdown parser，I lost pandoc-synyax highlight
