### ISSUE TITLE
The lsp_finder will cause a extra null modification

### ISSUE THREAD

**Issue by leonasdev** [glepnir/lspsaga.nvim#763]
### Describe the bug

If you use the feature of lsp_finder (e.g. go to definition or etc.) and jump to the same file, then press `u` to undo, you will undo a null action.

### Steps to reproduce

1. open a Lua file
2. modify the file with anything
3. lsp_find at any local variable
4. press enter to go to definition
5. press `u` to undo
6. you will undo nothing
7. press `u` to undo again
8. undo the change of `2.` correctly

Moreover, if you repeat 3. & 4. multiple times, you will get more than one extra null action of undo.

### Expected behavior

undo works without any extra null action.

### Neovim version (nvim -v)

0.8.1

### lspsaga commit

89f4079

### Terminal name/version

kitty 0.26.5

**Comment by glepnir** [comment]
can't reproduce . check your neovim config. if you want test it as lspsaga bug .use min config which only include lspaga.nvim and nvim-lspconfig

**Comment by leonasdev** [comment]
> can't reproduce . check your neovim config. if you want test it as lspsaga bug .use min config which only include lspaga.nvim and nvim-lspconfig

I have tested it using this config: [nvim-lua/kickstart](https://github.com/nvim-lua/kickstart.nvim) with nvim 0.8.1

I clone this config and install the Lspsaga, but the issue still can reproduce.

Could you try again with this config?

**Comment by glepnir** [comment]
it is not min config . min config works well I don't think it's bug of lspsaga
