### ISSUE TITLE
lsp_finder will cause write the file

### ISSUE THREAD

**Issue by leonasdev** [glepnir/lspsaga.nvim#765]
### Describe the bug

If you use lsp_finder and jump to definition or reference, the current buffer will be written.

(look the status line)

https://user-images.githubusercontent.com/39915562/214117102-20bfd93a-3d35-4d63-be6e-8d97fc43167b.mp4

### Steps to reproduce

1. Clone this config: [nvim-lua/kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim)
2. Install lspsaga with packer
3. Open any Lua file
4. Make some changes and do not save it
5. Move your cursor on a local variable
6. Enter command: `Lspsaga lsp_finder`
7. Go to the definition of this variable
8. You will see the file has been written

### Expected behavior

Go to definition or reference will not cause write file, work like built-in `vim.lsp.buf.definition`.

### Neovim version (nvim -v)

0.8.1

### lspsaga commit

749f7fc

### Terminal name/version

kitty 0.26.5

**Comment by glepnir** [comment]
lspsaga just handle lsp . there is no vim behavior i did.   can't reproduce. please check your config ?
