### ISSUE TITLE
Winbar background incosistency when displaying symbols

### ISSUE THREAD

**Issue by diegoulloao** [glepnir/lspsaga.nvim#766]
### Describe the bug

Not sure if this is really a bug coming from lspsaga, but sometimes when the cursor is in the root of the file (not inside a function or anything), the winbar background becomes lighter, then when entering into some function or any symbol, the background changes to the theme background.

https://user-images.githubusercontent.com/45423661/214205303-8fce9016-7ab5-44a7-9a4b-46afe13d7bd9.mov

I can see this is because when displaying the file root + symbols the winbar content width is 100% of the available space, but when is just the file root, it is not.

Maybe a fix would be to always fit the 100% of the winbar width, or nvim available space.

### Steps to reproduce

using theme: nightfly
not sure if is happening for others themes

### Expected behavior

See always the same background color in the winbar no matter if the cursor is in the file root or inside a element/symbol, etc.

### Neovim version (nvim -v)

0.8.2

### lspsaga commit

latest

### Terminal name/version

iterm2 3.4.19

**Comment by diegoulloao** [comment]
If is not a bug from lspsaga, I would appreciate any clue or idea on how to fix this, is kind of annoying.

**Comment by glepnir** [comment]
`:h Winbar` `:h WinbarNC`

**Comment by Racle** [comment]
> `:h Winbar` `:h WinbarNC`

Got same problem, and cannot get this to work, any ideas?

```
vim.cmd[[hi WinBar guibg=#313131]]
vim.cmd[[hi WinBarNC guibg=#313131]]
```
Result:

When hovering over normal text, guigb is not applied to every lsp saga element:
![lspsaga_1](https://user-images.githubusercontent.com/759091/214246368-b3485bb8-96d3-4ef9-9f94-1896a10e07b3.png)

when hovering over keymap, guibg is ignored for full width on right:
![lspsaga_2](https://user-images.githubusercontent.com/759091/214246441-58256c57-b35d-4aaa-b49c-35ed6a61f75d.png)

**Comment by glepnir** [comment]
update then test.

**Comment by Racle** [comment]
> update then test.

@glepnir same problem with same config, at least for me.

And when changing all LspSagaWinbar highlights, not every symbol still have correct background. 
Rest of the winbar seems to be OK with this massive configuration
![image](https://user-images.githubusercontent.com/759091/214289975-9fada571-8e50-49f4-a908-55e0223f656b.png)

```lua
vim.cmd [[hi WinBar guibg=red]]
vim.cmd [[hi WinBarNC guibg=red]]
vim.cmd [[hi LspSagaWinbarObject guibg=red]]
vim.cmd [[hi LspSagaWinbarClass guibg=red]]
vim.cmd [[hi LspSagaWinbarSep guibg=red]]
vim.cmd [[hi LspSagaWinbarKey guibg=red]]
vim.cmd [[hi LspSagaWinbarEnum guibg=red]]
vim.cmd [[hi LspSagaWinbarFile guibg=red]]
vim.cmd [[hi LspSagaWinbarNull guibg=red]]
vim.cmd [[hi LspSagaWinbarText guibg=red]]
vim.cmd [[hi LspSagaWinbarUnit guibg=red]]
vim.cmd [[hi LspSagaWinbarWord guibg=red]]
vim.cmd [[hi LspSagaWinbarArray guibg=red]]
vim.cmd [[hi LspSagaWinbarEvent guibg=red]]
vim.cmd [[hi LspSagaWinbarField guibg=red]]
vim.cmd [[hi LspSagaWinbarMacro guibg=red]]
vim.cmd [[hi LspSagaWinbarValue guibg=red]]
vim.cmd [[hi LspSagaWinbarFolder guibg=red]]
vim.cmd [[hi LspSagaWinbarMethod guibg=red]]
vim.cmd [[hi LspSagaWinbarModule guibg=red]]
vim.cmd [[hi LspSagaWinbarNumber guibg=red]]
vim.cmd [[hi LspSagaWinbarString guibg=red]]
vim.cmd [[hi LspSagaWinbarStruct guibg=red]]
vim.cmd [[hi LspSagaWinbarBoolean guibg=red]]
vim.cmd [[hi LspSagaWinbarPackage guibg=red]]
vim.cmd [[hi LspSagaWinbarSnippet guibg=red]]
vim.cmd [[hi LspSagaWinbarConstant guibg=red]]
vim.cmd [[hi LspSagaWinbarFunction guibg=red]]
vim.cmd [[hi LspSagaWinbarOperator guibg=red]]
vim.cmd [[hi LspSagaWinbarProperty guibg=red]]
vim.cmd [[hi LspSagaWinbarVariable guibg=red]]
vim.cmd [[hi LspSagaWinbarInterface guibg=red]]
vim.cmd [[hi LspSagaWinbarNamespace guibg=red]]
vim.cmd [[hi LspSagaWinbarParameter guibg=red]]
vim.cmd [[hi LspSagaWinbarTypeAlias guibg=red]]
vim.cmd [[hi LspSagaWinbarEnumMember guibg=red]]
vim.cmd [[hi LspSagaWinbarFolderName guibg=red]]
vim.cmd [[hi LspSagaWinbarConstructor guibg=red]]
vim.cmd [[hi LspSagaWinbarStaticMethod guibg=red]]
vim.cmd [[hi LspSagaWinbarTypeParameter guibg=red]]
```

**Comment by glepnir** [comment]
I just get the file highlight group from devicon and set it in this area. use color will solve this.

**Comment by Racle** [comment]
> use color will solve this. 

@glepnir got an example how to do this?

And isn't icon (in my screenshot) before require (icon: `{}`) also from devicons?
Just wondering why does it work just fine but not filetype icon?

**Comment by glepnir** [comment]
update then you can use `LspsagaWinbarFileIcon` to modified the icon background color

**Comment by diegoulloao** [comment]
Using hi Winbar guibg=#color worked for me (with root folder hidden)

**Comment by Racle** [comment]
@glepnir 
Works like a charm after adding LspSagaWinbarFileIcon to my massive list
```lua
vim.cmd [[hi LspSagaWinbarFileIcon guibg=red]]
```

**Comment by Racle** [comment]
@glepnir this commit removed new `LspSagaWinbarFileIcon` and broke one icon again.
Any workaround for this?
![image](https://user-images.githubusercontent.com/759091/215489455-536eb662-e3a0-48bf-8ea1-a7c4d72574c8.png)


https://github.com/glepnir/lspsaga.nvim/commit/2db894653bfbb97ce528ae15e5fb74363fa937ff#diff-69c3e638425c98fb3690d488b2c76f1837d6b73f49c2c18a9a1770e914aff35dL59

**Comment by glepnir** [comment]
could you readd it back.  work on neovim core process.
