### ISSUE TITLE
'width' key must be a positive Integer when goto diagnostic to an empty line.

### ISSUE THREAD

**Issue by karunsiri** [glepnir/lspsaga.nvim#767]
### Describe the bug

When executing `Lspsaga diagnostic_jump_next` or `diagnostic_jump_prev` to an empty line. The error with

    window.lua:152: 'width' key must be a positive Integer

occurs.

Please see the attached video for more detailed behavior:

https://user-images.githubusercontent.com/1308495/214222793-c72a8b37-0887-42fc-af34-3f7c0100c2fe.mp4

### Additional Info

- This error doesn't happen with official Neovim's lsp `goto_prev` nor `goto_next`
- The show line diagnostic; `Lspsaga show_line_diagnostics` works properly on an empty line.
- If I add some whitespace characters, I can jump to next diagnostic with no errors. Please see near the end of attached video.

### Steps to reproduce

1. Make diagnostic appears on an empty line (See line 16 in the attached video)
2. Execute `Lspsaga diagnostic_jump_next` to that line (Line 16)
3. The error appears

### Expected behavior

The jump to next/previous diagnostic works properly on an empty line without errors.

### Neovim version (nvim -v)

0.8.2

### lspsaga commit

749f7fc7e01e35bc1cde87181050af45f31b448c

### Terminal name/version

Gnome Terminal

**Comment by yeseongmoon** [comment]
I get the same error even after updating the plugin.
