### ISSUE TITLE
Error when using 'Lspsaga diagnostic_jump_prev/next'

### ISSUE THREAD

**Issue by gonviegas** [glepnir/lspsaga.nvim#768]
### Describe the bug

When using  'Lspsaga diagnostic_jump_prev/next', in some diagnostics I get the following error:

![2023-01-24-144935_1485x193_scrot](https://user-images.githubusercontent.com/47750371/214326873-3e80f7c9-8f9a-4185-bbc3-28de25e06f89.png)

### Steps to reproduce

:Lspsaga diagnostic_jump_prev 
:Lspsaga diagnostic_jump_next 

### Expected behavior

Not throw the error

### Neovim version (nvim -v)

v0.8.2 Build type: Release

### lspsaga commit

cabb2a5

### Terminal name/version

alacritty 0.12.0-dev (d92a8a0e)

**Comment by glepnir** [comment]
your lspsaga config should call setup function . read doc.

**Comment by gonviegas** [comment]
But I am calling the setup function...

**Comment by glepnir** [comment]
duplicate #769 I will fix all
