### ISSUE TITLE
jump_next, jump_prev error

### ISSUE THREAD

**Issue by yeseongmoon** [glepnir/lspsaga.nvim#769]
### Describe the bug

https://user-images.githubusercontent.com/20822372/214333827-0a52a827-6fea-4fc8-8e01-b2bbb1993125.mov

https://user-images.githubusercontent.com/20822372/214333839-934c8ceb-8574-4ba6-918b-a1c2d4d63920.mov

require("lspsaga.diagnostic"):goto_prev({ severity = vim.diagnostic.severity })
require("lspsaga.diagnostic"):goto_next({ severity = vim.diagnostic.severity })
these two commands throw errors. (attempt to index field theme, width key must be a positive integer)

### Steps to reproduce

in the video with lspsaga config file.

### Expected behavior

no error

### Neovim version (nvim -v)

0.8.2

### lspsaga commit

jump_next, jump_prev throw error

### Terminal name/version

kitty 0.26.5

**Comment by gonviegas** [comment]
Yes, I have the same error.

**Comment by jakeschurch** [comment]
confirmed same error

**Comment by octagony** [comment]
Similar mistake. On command _<cmd>Lspsaga diagnostic_jump_next<cr>_ and _<cmd>Lspsaga diagnostic_jump_prev<cr>_ gives an error _attempt to index field 'theme' (a nil value)_

**Comment by ZeljkovicIgor** [comment]
Same error.
