### ISSUE TITLE
Interactive show_buf_diagnostics

### ISSUE THREAD

**Issue by rensftw** [glepnir/lspsaga.nvim#770]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, just an idea. It would be useful to have the option to navigate diagnostic and jump to any one of them.

**Describe the solution you'd like**
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/22574186/214392596-3aa91fa5-806c-4e76-9447-4d3e99b7493b.png">

1. `:Lspsaga show_buf_diagnostics`
2. Focus diagnostic diagnostics window (`CTRL-W W`?)
3. Navigate lines as a normal vim buffer
4. When you hit `<CR>` on one of the lines the diagnostics window closes and the cursor is thrown at that diagnostic message's location (adding a new entry to the jumplist)

**Describe alternatives you've considered**
[`trouble.nvim`](https://github.com/folke/trouble.nvim), personally this is my only usecase for `trouble.nvim` right now 🤷‍♀️ 

**Additional context**
This feature might be useful for people who mainly use `trouble.nvim` for jumping to diagnostic on just the current buffer.

**Comment by glepnir** [comment]
will support

**Comment by glepnir** [comment]
support in next version see pr

**Comment by glepnir** [comment]
version pr will break at any time until it' complete . so you should take careful if you want using version pr daily

**Comment by glepnir** [comment]
closed merged.
