### ISSUE TITLE
When I have disabled title it still shows in some windows

### ISSUE THREAD

**Issue by mariansimecek** [glepnir/lspsaga.nvim#775]
### Describe the bug

First, thank you for the amazing plugin I really love it. 

I have in my config `ui.title = false` but it still shows in:

-  diagnostic_jump_next, diagnostic_jump_prev
-  show_diagnostic in all windows

![image](https://user-images.githubusercontent.com/5357955/214799048-ed2b43bf-0104-45c8-9116-597d5939c11d.png)

### Steps to reproduce

Call
`:Lspsaga diagnostic_jump_next`
`:Lspsaga diagnostic_jump_prev`
`:Lspsaga show_diagnostic`

### Expected behavior

Don't show the title

### Neovim version (nvim -v)

NVIM v0.9.0-dev-763+ge86d2734a

### lspsaga commit

ac13404

### Terminal name/version

kitty

**Comment by mariansimecek** [comment]
The **Msg** and **Fix** aren't titles? It would be nice to hide them too.

![image](https://user-images.githubusercontent.com/5357955/214833419-f4208a9e-cc5a-4e92-bd85-dc2a11f9630f.png)

**Comment by glepnir** [comment]
it's hardcoded.  about ui  I will do some change in next version.
