### ISSUE TITLE
Blank float terminal in Windows

### ISSUE THREAD

**Issue by pluma9** [glepnir/lspsaga.nvim#776]
### Describe the bug

`:LspSaga term_toggle` displays a blank float window

Blank window:
![blank](https://user-images.githubusercontent.com/16544647/214799178-af424a0e-678e-465e-8706-5556683db580.gif)

I can open terminal using `:split | terminal`:
![split-terminal](https://user-images.githubusercontent.com/16544647/214799190-1c933210-c3f4-4b9a-935e-b65c95fddfe6.gif)

### Steps to reproduce

nvim --clean -u init.vim
:Lspsaga term_toggle

init.vim:

```vim
call plug#begin()
  Plug 'glepnir/lspsaga.nvim'
call plug#end()

lua <<EOF
  require('lspsaga').setup({})
EOF
```

### Expected behavior

The float terminal should display initial text like current working directory, etc. and I should be able to type in commands.

### Neovim version (nvim -v)

NVIM v0.8.1

### lspsaga commit

ac134041da57f7592a46775f235ed84880bc0b27

### Terminal name/version

cmd.exe 10.0.19041.746

**Comment by glepnir** [comment]
windows shell command is what ? looks like windows does not have `$SHELL`

**Comment by glepnir** [comment]
does `termopen('cmd.exe')` can  work ?

**Comment by pluma9** [comment]
Yes, `termopen('cmd.exe')` works. You made me realize that using `$SHELL` envar or `:Lsp term_toggle cmd.exe` will work.

Thanks.
