### ISSUE TITLE
Highlights for code actions

### ISSUE THREAD

**Issue by ciza99** [glepnir/lspsaga.nvim#777]
Iam configuring my own colors following the highlight.lua file for a colorscheme. Everything was fine but now Iam unable to find a highlight group for most of the elements in code actions popup window and diagnostics window. Here is an image:

![highlights](https://user-images.githubusercontent.com/54907476/214891666-9322f427-d035-4eac-be00-8847a8cbfb51.png)

I think its quite clear what I would like to change. Is it possible to change the colors and if so, how?

**Comment by glepnir** [comment]
message text is `DiagnsoticText` other highlight color in ui.colors . and there will change some ui in next version
