### ISSUE TITLE
key repeat interaction with ts-rainbow parenthesis

### ISSUE THREAD

**Issue by klooj** [glepnir/lspsaga.nvim#78]
This only happens when I scroll to quickly through the popup, and only for the lsp_finder not preview. 

 When the cursor is in the menu and first stops moving, that is a hang and I keep holding down key repeat during the hang. So it's not as bad as it looks, I just wanted to accentuate the issue for demonstration.  After the async errors catch up, I only have to hit enter once and everything returns to normal. 

https://user-images.githubusercontent.com/57016271/107140003-31faf400-68ed-11eb-97e2-daa9a91b5f52.mov

Let me know if you think I should post this as an issue in that [repo](https://github.com/p00f/nvim-ts-rainbow).

**Comment by glepnir** [comment]
If you disable `nvim-ts-rainbow`. the move in finder works well right?

**Comment by klooj** [comment]
This time, the hang was still there but without all error messages.  The hang lasted a lot longer but only produced this output. The file mentioned in the second error is handled by astronauta so I'm looking around there now. 
<img width="2225" alt="image" src="https://user-images.githubusercontent.com/57016271/107140458-13e2c300-68f0-11eb-9910-c2438d78d2f8.png">

**Comment by glepnir** [comment]
What did you do in finder window  then trigger it?

**Comment by klooj** [comment]
same as the first time. just held down the j key.

**Comment by glepnir** [comment]
I can't reproduce your problem. you need  post min vim conf here .maybe something wrong in your config.

**Comment by glepnir** [comment]
![finder](https://user-images.githubusercontent.com/41671631/107140599-1a0f8880-695e-11eb-947d-c5f1741625f1.gif)
