### ISSUE TITLE
Make code actions numbers and diagnostics icons colors configurable

### ISSUE THREAD

**Issue by joeveiga** [glepnir/lspsaga.nvim#781]
**Is your feature request related to a problem? Please describe.**
Because the number colors seem to be hardcoded, they can look funky depending on the color scheme. Same with the "Msg" and "Fix" pills (see screenshots below).

**Describe the solution you'd like**
It'd be nice to have the ability to config those colors (or alternatively an option to go back to no colors at all). Maybe add highlight groups for those (both fg and bg) so the different colorscheme plugins can set the colors themselves. 

I'm personally not a fan of having one color per option. It looks too... rainbowy :). I get it might be kinda helpful to differentiate them somewhat, but you still need to read the number in order to press the key, right? 

So I'd suggest adding highlight groups for "code action number", "code action section title..?", and "msg text" since in my case it looks blueish.

**Additional context**
![image](https://user-images.githubusercontent.com/19226858/215129111-28138002-8851-46ff-832f-b0b41e302309.png)
![image](https://user-images.githubusercontent.com/19226858/215129348-790ab4d0-41ba-4fc3-93f2-1f09d7c4bb36.png)

**Comment by glepnir** [comment]
ui will improve in next version see pr

**Comment by joeveiga** [comment]
> ui will improve in next version see pr

@glepnir Got it, thanks. I glanced over the PR before opening the feature request but didn't see any changes related to the colors issue. Maybe I missed it or peehaps there is more work in flight?

**Comment by glepnir** [comment]
in process.  window behavior improve just done. then is color and highlight

**Comment by joeveiga** [comment]
> in process.  window behavior improve just done. then is color and highlight

Awesome!

**Comment by HeyChobe** [comment]
> in process. window behavior improve just done. then is color and highlight

I searched for a problem like this, I was thinking if it's possible to change some font colors and border colors without branching, because some themes make modal windows a bit weird.

I was thinking of a default color option (like the current palette but without putting the bg of the current theme) and something more custom.

I will wait for the pr, thank you very much for your work, it is incredible

**Comment by glepnir** [comment]
all highlight group in highlight.lua  then you can defined them in your colorscheme or config. no pr already done.

**Comment by HeyChobe** [comment]
Thanks, I will try it
