### ISSUE TITLE
`aedef7f` breaks automatic filetype detection

### ISSUE THREAD

**Issue by xfzv** [glepnir/lspsaga.nvim#782]
### Describe the bug

I'm using Lazy:

```lua
return {
    "glepnir/lspsaga.nvim",
    event = "BufRead",
    dependencies = { "kyazdani42/nvim-web-devicons" },
    config = function()
        require("lspsaga").setup({})
    end,
}
```

After updating to today's commits (the issue occurs from https://github.com/glepnir/lspsaga.nvim/commit/aedef7f4d10442a40808ca984131813a53ec372a), the current file type is no longer detected automatically. Which means no more automatic syntax highlighting with nvim-treesitter, `:Lspsaga lsp_finder` no longer works either for example.

Sticking to https://github.com/glepnir/lspsaga.nvim/commit/842bdddcd34ddff370aa71984370b9cc6dfba6ef with the following fixes the issue for me:

```lua
return {
	"glepnir/lspsaga.nvim",
	commit = "842bddd",
	event = "BufRead",
	dependencies = { "kyazdani42/nvim-web-devicons" },
	config = function()
		require("lspsaga").setup({})
	end,
}
```

### Steps to reproduce

1. Use my config mentioned above while sticking to https://github.com/glepnir/lspsaga.nvim/commit/842bdddcd34ddff370aa71984370b9cc6dfba6ef
2. Open a file: the file type is correctly detected
3. Remove `commit = "842bddd",` from Lazy config and update lspsaga to latest commit
5. Open the same file: the file type isn't detected

### Expected behavior

file type detection is still working as expected

### Neovim version (nvim -v)

NVIM v0.8.2 Build type: Release LuaJIT 2.1.0-beta3

### lspsaga commit

https://github.com/glepnir/lspsaga.nvim/commit/aedef7f4d10442a40808ca984131813a53ec372a

### Terminal name/version

kitty 0.26.5

**Comment by glepnir** [comment]
I don't know what the bug you get ? I don't think i can handle the filetype detect and there no relate code i think and it woks fine on my test

**Comment by glepnir** [comment]
update
