### ISSUE TITLE
Lspsaga Rename doesn't work

### ISSUE THREAD

**Issue by radvil2** [glepnir/lspsaga.nvim#785]
### Describe the bug

Hi, When I typed "Lspsaga rename". This errors occurs, idk why, can you help me please ?
this is my very light saga setup from lazy.nvim
```shell
{
		"glepnir/lspsaga.nvim",
		event = "BufRead",
		dependencies = { "kyazdani42/nvim-web-devicons" },
		config = function()
			require("lspsaga").setup({
			      ui = {
                                      theme = "round",
                                      title = true,
                                      border = "solid",
                                      winblend = 0,
                              },
                              rename = {
                                  quit = "<C-c>",
                                  exec = "<CR>",
                                  mark = "x",
                                  confirm = "<CR>",
                                  in_select = true,
                                },
                             })
		end
}
```
`**Error executing Lua callback: vim/keymap.lua:0: lhs: expected string, got table**
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/keymap.lua: in function 'set'
        ...ocal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/rename.lua:36: in function 'apply_action_keys'
        ...ocal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/rename.lua:189: in function 'lsp_rename'
        ...cal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/command.lua:14: in function <...cal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/command.lua:13>
        ...cal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/command.lua:60: in function 'load_command'
        ...l/.local/share/nvim/lazy/lspsaga.nvim/plugin/lspsaga.lua:8: in function <...l/.local/share/nvim/lazy/lspsaga.nvim/plugin/lspsaga.lua:7>
**Press ENTER or type command to continue**
`

### Steps to reproduce

I hovered my cursor into one variable, then I press "**gr**" which set to `**Lspsaga rename**`, then this error occurred, then I tried by using the command line instead of my custom binding **gr,** but the same error still occurred.

### Expected behavior

This should work as the demo hemmp, what did I do wrong ??

### Neovim version (nvim -v)

Nightly

### lspsaga commit

Idk, I follow the main branch

### Terminal name/version

Kitty

**Comment by glepnir** [comment]
wired i can't reproduce with a min config

**Comment by glepnir** [comment]
something wrong in your local . need clean your local. looks like have other config ?

**Comment by glepnir** [comment]
the error message 

```
Error executing Lua callback: vim/keymap.lua:0: lhs: expected string, got table
```
mean there has a table as key passed into the `vim.keymap.set` in rename `apply_action_keys` function. please try the min config .should some wrong in you local
