### ISSUE TITLE
can't move my cursor in lspsaga finder as a colemak user

### ISSUE THREAD

**Issue by zzLinus** [glepnir/lspsaga.nvim#786]
### Describe the bug

Hi!As the title said,I'm a colemak and i use 
```
        ^     
        u     
  < n        i >  
        e                      
        v
```       
to move in vim,in previous lspsaga version i use move_in_saga to map my keys,and i update saga today and i can use 'u' 'e' to move up and down in most component by remap 'u' and 'e' to other key but can't do 'e' with finder.I currently just remove 'e' in `keys` at `libs.disable_move_keys` function (libs.lua). is there any better way to map my keys in saga?

### Steps to reproduce

1.be a colemak user

### Expected behavior

move my cursor using 'u' and 'e'

### Neovim version (nvim -v)

NVIM v0.8.2

### lspsaga commit

f281c050aa85550ce9e60b33d082428d2b0a3ef1

### Terminal name/version

alacritty 0.11.0

**Comment by glepnir** [comment]
```lua
vim.api.nvim_create_automcmd('FileType, {
        pattern = 'lspsagafinder',
        callback = function()
              vim.keymap.set('n', 'e', '<Up>')
         end
```
