### ISSUE TITLE
outline fold will not work preperly with part of the fold

### ISSUE THREAD

**Issue by rhcher** [glepnir/lspsaga.nvim#789]
### Describe the bug

outline fold will not work preperly with part of the fold

### Sources to reproduce
test.lua
```lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "glepnir/lspsaga.nvim",
    event = "BufRead",
    config = function()
      require("lspsaga").setup({})
    end,
    dependencies = {
      { "nvim-tree/nvim-web-devicons" },
      { "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        config = function()
          require("nvim-treesitter.configs").setup {
            ensure_installed = { "cpp" }
          }
        end
      }
    }
  },
  {
    "neovim/nvim-lspconfig",
    config = function()
      require("lspconfig")["clangd"].setup {}
    end
  }
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here
```

mini.cc
```cpp
#include <iostream>

namespace test {
int gobal;
int inc(int a) { return a + 1; }
int add(int a, int b) { return a + b; }
} // namespace test

int main() {}
```

### Steps to reproduce

1. nvim --clean -u test.lua mini.cc
2. :Lspaga outline
![image](https://user-images.githubusercontent.com/50723480/215326098-653c1a25-43a6-4f03-bd2e-ac537ee33f69.png)

3. enter `u` trigger first fold
![image](https://user-images.githubusercontent.com/50723480/215326125-c9abd0ef-b1a8-4082-a539-7f4d74369e9c.png)

4. then try to enter `u` trigger second fold, will failed
![image](https://user-images.githubusercontent.com/50723480/215326140-0fafbb89-45b0-4b94-b34b-3ac99ac8a05a.png)

### Expected behavior

outline work properly

### Neovim version (nvim -v)

NVIM v0.9.0-dev-835+g8144deb09-dirty

### lspsaga commit

2c1da79522a7221f0e85e891b1cb5c162f03fc2f

### Terminal name/version

coutour 3.9

**Comment by rhcher** [comment]
Thanks for fix, but it still have some issues

**Comment by glepnir** [comment]
what's it

**Comment by rhcher** [comment]
use same test.lua and mini.cc, just fold all and expand all, than try to fold all again

**Comment by glepnir** [comment]
where is test.lua ?

**Comment by glepnir** [comment]
should be fixed.

**Comment by rhcher** [comment]
you may forget to push your fix commit :)

**Comment by glepnir** [comment]
how about now ?

**Comment by rhcher** [comment]
working outside...will test tonight

**Comment by glepnir** [comment]
no problem then. any feedback welcome

**Comment by rhcher** [comment]
fold and expand function works properly now, thanks for your work
