### ISSUE TITLE
Automatic enabling (hover)

### ISSUE THREAD

**Issue by BigfootN** [glepnir/lspsaga.nvim#79]
Hello,

First of all, to be honest, I'm not sure if what I am looking for is one of the features of this.

I really love this plugin, thank you, but I was wandering if it would be possible to automatically enable it when hovering over a symbol (then just binding it to a key).

Thank you very much in advance.

**Comment by glepnir** [comment]
these should be enable in gui ..in tui if use CursorHold autocmd .it will execute many times.

**Comment by glepnir** [comment]
If you like this you can use CurosrHold and call lspsaga hover

**Comment by BigfootN** [comment]
Thank you for your quick response.
