### ISSUE TITLE
'Height' key must be a positive Integer

### ISSUE THREAD

**Issue by Ghasak** [glepnir/lspsaga.nvim#790]
### Describe the bug

I have a problem with the new configurations, It seems that I can jump to definitions for some keywords, and cannot for others. 

```lua
Error executing vim.schedule lua callback: ...site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/window.lua:250: 'height' key must be a positive Integer
stack traceback:
        [C]: in function 'nvim_open_win'
        ...site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/window.lua:250: in function 'create_win_with_border'
        ...site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/finder.lua:370: in function 'render_finder_result'
        ...site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/finder.lua:240: in function 'render_finder'
        ...site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/finder.lua:161: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0> 
```

### Steps to reproduce

in init.lua file 
jump on a definition for `pcall` for example 
I use also `neodev` plugin with the `lua-language-server` if that can help! 

### Expected behavior

to get jump to definition window instead of the error message

### Neovim version (nvim -v)

NVIM v0.9.0-dev-626+g42afa0369

### lspsaga commit

b1e6000   ->  outline: fix expand collapse bug close #789

### Terminal name/version

iTerm2 Build 3.4.19

**Comment by gilitos92** [comment]
Can confirm same behavior on Nvim v0.8.2

**Comment by glepnir** [comment]
don't what do you mean your reproduce step I can't understand. my test is works fine. i only use lua-language-server

![hover](https://user-images.githubusercontent.com/41671631/215377009-ef0d91d6-a263-47a3-b43f-875e5111e164.gif)

**Comment by glepnir** [comment]
please provide a clear reproduce step then i can test this.

**Comment by NachoNievaG** [comment]
Same behavior here, can't seem to find a way to exactly reproduce it.
Maybe helps to add that it happens to me while working in a Go project.
Nvim 0.8.0

**Comment by shinzui** [comment]
This happens sporadically, but it's pretty bad that it corrupts the plugin and forces me to restart neovim. 

<img width="1018" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/519/87d4c0ae-a216-4b75-ac92-d78d1ee19aa1">

I am using `nvim 0.9.0` with lspsaga `b45579fa4f2a4548125781e144d58361b70261f0`

**Comment by glepnir** [comment]
provide repreode step like i said.

**Comment by shinzui** [comment]
> provide repreode step like i said.

I tried, but I can't reproduce it in isolation on a small project. I stopped using lspsaga for now.
