### ISSUE TITLE
Skip initializing winbar value when customizing winbar's position

### ISSUE THREAD

**Issue by Jint-lzxy** [glepnir/lspsaga.nvim#793]
**Is your feature request related to a problem? Please describe.**
After https://github.com/glepnir/lspsaga.nvim/commit/ec561ca914bb7ae4b4ba65c10229e24a798a34a8 if we use `require('lspsaga.symbolwinbar'):get_winbar()` to get the content of `winbar` and render this in another place _(e.g., statusline)_, due to the existence of initial winbar value, the default winbar will still be rendered at the top of the screen, as follows:
![issue1](https://user-images.githubusercontent.com/50296129/215407019-54d7ed46-ee8e-4e0f-a3f0-0a996f0cb773.png)

I admit to achieve this effect I used some tricks:
```lua
symbol_in_winbar = {
    in_custom = true,
      ^^^^^
    enable = false,
    show_file = false,
},
```
As:
```lua
if saga.config.symbol_in_winbar.enable or saga.config.symbol_in_winbar.in_custom then
                                                                          ^^^
  require('lspsaga.symbolwinbar'):symbol_autocmd()
end
```

**Describe the solution you'd like**
Allow users to set `symbol_in_winbar.in_custom`, and skip setting initial winbar value when this option is `true` like:
```lua
function symbar:symbol_autocmd()
  api.nvim_create_autocmd('LspAttach', {
    group = api.nvim_create_augroup('LspsagaSymbols', { clear = false }),
    callback = function(opt)
      -- .....
      if config.show_file then
        api.nvim_set_option_value(
          'winbar',
          bar_file_name(opt.buf),
          { scope = 'local', win = winid }
        )
      elseif [perform checks here] then
                 ^^^^^^^^^^^
      else
        api.nvim_set_option_value(
      -- ......
end
```

**Comment by glepnir** [comment]
Don't know what do you mean . if you are using the api from lspsaga symbolwinbar it does not set the winbar . just give you winbar string .

**Comment by Jint-lzxy** [comment]
Sorry for the vague explanation. The point is when I set `in_custom` in the config _(which is not exposed to user)_, it will also trigger the function of setting autocmd (`symbar:symbol_autocmd`). The default winbar value will be set in this function:
```lua
else
    api.nvim_set_option_value(
    'winbar',
    bar_prefix().prefix .. ' #',
    { scope = 'local', win = winid }
    )
end
```
as this value is non-empty, it enables the window bar. I want to be able to unset this value when `in_custom` is set

**Comment by glepnir** [comment]
just add winbar.enable is enough . using api you can set this to false .

**Comment by Jint-lzxy** [comment]
Got it. Thanks very much :)

**Comment by Jint-lzxy** [comment]
IMO `saga.config.symbol_in_winbar.in_custom` could be removed as it is deprecated:
```lua
if saga.config.symbol_in_winbar.enable or saga.config.symbol_in_winbar.in_custom then
                                                                          ^^^
  require('lspsaga.symbolwinbar'):symbol_autocmd()
end
```

**Comment by glepnir** [comment]
good catch. removed.
