### ISSUE TITLE
goto_prev function did not work

### ISSUE THREAD

**Issue by MeiWagatsuma** [glepnir/lspsaga.nvim#794]
### Describe the bug

```lua
require("lspsaga.diagnostic").goto_prev({ severity = vim.diagnostic.severity.ERROR })
```
error
```
E5108: Error executing lua: .../pack/packer/opt/lspsaga.nvim/lua/lspsaga/diagnostic.lua:480: attempt to call method 'move_cursor' (a nil value)
```

It used to work before.

### Steps to reproduce

Just run it with a command
`: lua require("lspsaga.diagnostic").goto_prev({ severity = vim.diagnostic.severity.ERROR })`

### Expected behavior

jump to error

### Neovim version (nvim -v)

0.8.1

### lspsaga commit

HEAD^

### Terminal name/version

alacrity

**Comment by glepnir** [comment]
`require("lspsaga.diagnostic"):goto_prev({ severity = vim.diagnostic.severity.ERROR })` read doc
