### ISSUE TITLE
Lspsaga outline : unknown option `src` 

### ISSUE THREAD

**Issue by Ghasak** [glepnir/lspsaga.nvim#796]
### Describe the bug

Dear Glepnir Sir 
Sorry to bother you a lot with some bugs that I failed to show you correctly how to reproduce. I am new at this, so please don't flame me out lol.  So I am not an artist I just enjoy your art, and it is certainly perfect now, though,  I've faced this problem with your recent implementations.  It seems the `:<cmd>Lspsaga outline<CR>` is not working anymore!! 

```lua 
‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
Error executing vim.schedule lua callback: vim/_meta.lua:0: unknown option 'stc'
stack traceback:
        [C]: in function 'nvim_get_option_value'
        vim/_meta.lua: in function '__index'
        ...ite/pack/packer/opt/lspsaga.nvim/lua/lspsaga/outline.lua:61: in function 'set_local'
        ...ite/pack/packer/opt/lspsaga.nvim/lua/lspsaga/outline.lua:154: in function 'create_outline_window'
        ...ite/pack/packer/opt/lspsaga.nvim/lua/lspsaga/outline.lua:463: in function 'render_outline'
        ...ite/pack/packer/opt/lspsaga.nvim/lua/lspsaga/outline.lua:214: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1388: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps to reproduce

:<cmd>Lspsaga outline<CR> for a given buffer/window is not working. 
I mapped <leader>o as you can see below: 

```lua 
vim.keymap.set("n", "<leader>o", "<cmd>Lspsaga outline<CR>", { silent = true })

```

### Expected behavior

Should show the `Lssaga outline` sidebar (buffer) same as before. 

### Neovim version (nvim -v)

NVIM v0.9.0-dev-626+g42afa0369

### lspsaga commit

705a8e9 - (HEAD -> main, origin/main, origin/HEAD) symbolwinar: remove unused code (6 hours ago) <Raphael>

### Terminal name/version

iTerm: Build 3.4.19

**Comment by glepnir** [comment]
update your neovim version

**Comment by Ghasak** [comment]
Oh, thank you very much for your support, 
May I ask which version are you using?

**Comment by Ghasak** [comment]
Thank you very much, you rock! 
I will work on it now, btw, the previous bug was resolved with your tremendous fix
keep up the good work, I am a big fan.

**Comment by glepnir** [comment]
lol  many bugs :)

**Comment by Ghasak** [comment]
I confirm it works flawlessly on `NVIM v0.9.0-dev-840+g21257d858`
![image](https://user-images.githubusercontent.com/27670946/215496556-757618bc-2926-49a1-8c65-d4ec0bc7a5ae.png)
