### ISSUE TITLE
Visual issue when rendering next diagnostic

### ISSUE THREAD

**Issue by Xyven1** [glepnir/lspsaga.nvim#799]
### Describe the bug

When calling `:Lspsaga diagnostic_jump_*`  the following is rendered when the text of the diagnostic result overflows and wraps around.
![lspsaga visual bug](https://user-images.githubusercontent.com/35360746/215540778-f96aa638-ef3a-4605-9322-7d9df8ced504.png)
Note the extra and unnecessary vertical bar.

### Steps to reproduce

Call `:Lspsaga diagnostic_jump_*` with a relatively narrow window with a relatively long diagnostic message. 

### Expected behavior

![image](https://user-images.githubusercontent.com/35360746/215540641-d63f25ea-93ed-4b0d-b4eb-6faed8eb4729.png)
Here it is rendered properly, as there is no text wrapping.

### Neovim version (nvim -v)

0.9.0-dev-833+gb4c4c232b

### lspsaga commit

e698de51356eeda94907c179789f5c2f0112c185

### Terminal name/version

Windows Terminal

**Comment by glepnir** [comment]
it auto adjust according your win width

**Comment by glepnir** [comment]
`diagnostic.max_width`
