### ISSUE TITLE
Cursor/highlighting off-by-one with lsp_finder

### ISSUE THREAD

**Issue by levouh** [glepnir/lspsaga.nvim#80]
With a directory structure like so:

```
.
├── .git
├── client.py
├── main.py
└── server.py
```

and some dummy files to test the finder:

_client.py_
```
class Client(object):
    def __init__(self):
        self.payload = 'Client'

    def show(self, name='client'):
        """ Show stuff about this client """
        print(name, ':', self.payload)
```

_server.py_
```
class Client(object):
    pass


class Server(object):
    def __init__(self):
        self.payload = 'Server'

    def show(self, name='server'):
        """ Show stuff about this server """
        print(name, ':', self.payload)
```

_main.py_
```
from client import Client
from server import Server


class Main(object):
    def __init__(self, arg):
        self.payload = None

        if arg == 'server':
            self.worker = Server()
        else:
            self.worker = Client()

        self.worker.show()


if __name__ == '__main__':
    m = Main(arg='server')
```

I get the following with `:Lspsaga lsp_finder`:

![image](https://user-images.githubusercontent.com/31262046/107161031-1e847300-6957-11eb-8957-5bbe6c4848cf.png)

with the main problem being the positioning of the cursor. Note where it is in the above screen shot, it should be one line down from there. Further, when pressing `j`/`k`, I can never position my cursor over the first selection, `[1] test/python_test/server.py`, nor the last, `[3] test/python_test/server.py`. I've tried a few things, like running `noau Lspsaga lsp_finder`, etc. but with no luck.

I've tried this with the following minimal setup, replicating mostly what I've got in my main setup, and still get the same error:

_lsp.lua_: Place somewhere that it is loaded based on filetype, or `require` it manually, etc.
```
local int_on_attach = function()
      require('lspsaga').init_lsp_saga {
          error_sign = '·',
          error_header = '· Error',
          warn_sign = '·',
          warn_header = '· Warning',
          hint_sign = '·',
          hint_header = '· Hint',
          infor_sign = '·',
          infor_header = '· Info',
          definition_preview_icon = '· ',
          finder_definition_icon = '· ',
          finder_reference_icon = '· ',
      }
      
      vim.api.nvim_buf_set_keymap(0, 'n', '<C-]>', '<Cmd>Lspsaga lsp_finder<CR>', { noremap = true })
end

local lspc = function()
      local lspconfig = require('lspconfig')
  
      -- `$ pip install --user python-language-server`
      lspconfig.pyls.setup{
          on_attach = int_on_attach,
          root_dir = function(fname)
              return lspconfig.util.find_git_ancestor(fname) or vim.loop.os_homedir()
          end,
      }
  ```
  
Has anyone else seen this error, or is anyone else able to reproduce it with the above configuration? If what is put above isn't easy to duplicate, I can make a repo. or a _Docker_ image, or something. Whatever is easiest.

**Comment by levouh** [comment]
Same thing with `clangd` instead of the original example, which was `python-language-server`:

![image](https://user-images.githubusercontent.com/31262046/107162067-fd735080-695d-11eb-86ea-4d592939e382.png)

Still messing around with settings, etc. on my end to see if it's something with me, or a bug.

**Comment by levouh** [comment]
Disabled all of my own custom configuration, so just calling `require('lspsaga').init_lsp_saga()` with no overrides, and this still happens.

**Comment by levouh** [comment]
Resetting to [5e6d26a](https://github.com/glepnir/lspsaga.nvim/commit/5e6d26a4d38efa2ab7352974daec176a8e93958a) has fixed the problem, so it appears to be something with [f860d54](https://github.com/glepnir/lspsaga.nvim/commit/f860d543e6a36b5c8f2c812426732c253f613454).

**Comment by levouh** [comment]
Now looks like this @glepnir 

![image](https://user-images.githubusercontent.com/31262046/107169844-1db20800-697c-11eb-8951-598d63fc1a4d.png)

**Comment by glepnir** [comment]
fixed .

**Comment by levouh** [comment]
Fastest bug fix in the west? Looks good @glepnir, wonderful plugin as well. Keep it up.

**Comment by glepnir** [comment]
Thanks :)
