### ISSUE TITLE
无法像文档上那样配置多个按键,否则报错

### ISSUE THREAD

**Issue by liaohui5** [glepnir/lspsaga.nvim#800]
### Describe the bug

无法配置多个按键, 像文档上这样 https://github.com/glepnir/lspsaga.nvim#lspsaga-lsp_finder

## 这样配置是没有问题的

```lua
require("lspsaga").setup({
    finder = {
      edit = "<CR>",
      vsplit = "s",
      split = "i",
      tabe = "t",
      quit = "<ESC>",
    },
});
```

## 这样配置就会报错

```lua
require("lspsaga").setup({
    finder = {
      edit = { "<CR>", "o" },
      vsplit = "s",
      split = "i",
      tabe = "t",
      quit = { "<ESC>", "q" },
    },
});

```

## 报错截图

<img width="997" alt="image" src="https://user-images.githubusercontent.com/29266093/215717438-8e123344-fd47-4ff1-a48a-56cd81d4da30.png">

### Expected behavior

希望可以向文档上那样, 配置多个按键

### Neovim version (nvim -v)

NVIM v0.9.0-dev-844+gb649a96fc-dirty

### lspsaga commit

990be59c4ec904ff5c7d980cb0d067dfa806848e

### Terminal name/version

alacritty 0.11

**Comment by glepnir** [comment]
报错是outline 你配的是finder。

**Comment by liaohui5** [comment]
> 报错是outline 你配的是finder。

额, 我只是举个例子看下报错, 配置 finder 也是一样的

**Comment by glepnir** [comment]
你确定吗？ 为什么我重现不了？ 而且文档写的很清楚把 带table就是支持table 。 outline的可以都没带就是不支持。

**Comment by liaohui5** [comment]
> 你确定吗？ 为什么我重现不了？ 而且文档写的很清楚把 带table就是支持table 。 outline的都没带就是不支持。

好吧, 我知道了, 我还以为都是支持 table 的, 我理解错了, 非常感谢
