### ISSUE TITLE
finder window issue

### ISSUE THREAD

**Issue by YuCao16** [glepnir/lspsaga.nvim#802]
### Describe the bug

[Screencast from 31-01-23 11:33:31.webm](https://user-images.githubusercontent.com/62466929/215749116-b3bb7e1f-2b91-4e26-9894-b5b4517935ed.webm)

### Steps to reproduce

For me, every file has this problem.

### Expected behavior

Behave like yesterday version.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-720+gf6929ea51

### lspsaga commit

ffddb6242cd8e9f26e95c8f625ad4266636d8ef8

### Terminal name/version

kitty 0.26.5

**Comment by YuCao16** [comment]
@glepnir 
I got this error after updating:
``` error
Error executing vim.schedule lua callback: ...site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/window.lua:250: 'height' key must be a positive Integer                                                                      
stack traceback:                                                                                                                                                                                                         
        [C]: in function 'nvim_open_win'                                                                                                                                                                                 
        ...site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/window.lua:250: in function 'create_win_with_border'                                                                                                            
        ...site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/finder.lua:363: in function 'render_finder_result'                                                                                                              
        ...site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/finder.lua:234: in function 'render_finder'                                                                                                                     
        ...site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/finder.lua:155: in function ''                                                                                                                                  
        vim/_editor.lua: in function <vim/_editor.lua:0> 
```

**Comment by YuCao16** [comment]
Apart from that, if I escape finder using `<c-w><c-w>`, the finder window won't close itself.

**Comment by YuCao16** [comment]
And the two windows of finder are linked together, previously there was a gap between them, is this a new design or a bug?

**Comment by glepnir** [comment]
> And the two windows of finder are linked together, previously there was a gap between them, is this a new design

design work like vscode

**Comment by glepnir** [comment]
I had revert to preview version . looks show actual file will have some bugs I will fixed it in a new branch.

**Comment by glepnir** [comment]
improve the window behavior now will looks better.

**Comment by YuCao16** [comment]
Looks better, but still sometimes got `'height' key must be a positive Integer` error, commits ac134041 works fine.

**Comment by YuCao16** [comment]
[Screencast from 31-01-23 13:27:32.webm](https://user-images.githubusercontent.com/62466929/215773259-2b9ddf71-8b81-4934-bb6d-0f59c0fc84e7.webm)
The first window is not closed.

**Comment by glepnir** [comment]
how to reproduce this error ?

**Comment by YuCao16** [comment]
> how to reproduce this error ?

Sorry, can't reproduce either...

**Comment by glepnir** [comment]
so that mean works fine ?

**Comment by glepnir** [comment]
added a patch to make sure close preview window before create new.

**Comment by YuCao16** [comment]
> so that mean works fine ?

Yes. And about the height error, it may related to the number of reference. For those variable who has plenty of references, the height error appears. It seems that the finder works fine without the scrollbar being triggered.

**Comment by glepnir** [comment]
any repo can reproduce ?

**Comment by YuCao16** [comment]
> any repo can reproduce ?

I'm using [lightning](https://github.com/Lightning-AI/lightning), for class such as `Callback` finder works fine, but for those `Trainer`, height error appear.
[Screencast from 31-01-23 13:46:27.webm](https://user-images.githubusercontent.com/62466929/215777449-26a59663-1d3f-488a-bf16-4884fb441d73.webm)
Here is the code:
``` python
from pytorch_lightning import Trainer
from pytorch_lightning import Callback, LightningDataModule, LightningModule
```

**Comment by glepnir** [comment]
it outside the screen ?

**Comment by glepnir** [comment]
a debug print ..

```diff
diff --git a/lua/lspsaga/finder.lua b/lua/lspsaga/finder.lua
index 286db1a..ee3fc3d 100644
--- a/lua/lspsaga/finder.lua
+++ b/lua/lspsaga/finder.lua
@@ -336,6 +336,7 @@ function finder:render_finder_result()

   local max_height = vim.o.lines * 0.5
   opt.height = #self.contents > max_height and max_height or #self.contents
+  print(opt.height)
   if opt.height <= 0 or not opt.height then
     opt.height = max_height
   end
```

**Comment by YuCao16** [comment]
> a debug print ..
> 
> ```diff
> diff --git a/lua/lspsaga/finder.lua b/lua/lspsaga/finder.lua
> index 286db1a..ee3fc3d 100644
> --- a/lua/lspsaga/finder.lua
> +++ b/lua/lspsaga/finder.lua
> @@ -336,6 +336,7 @@ function finder:render_finder_result()
> 
>    local max_height = vim.o.lines * 0.5
>    opt.height = #self.contents > max_height and max_height or #self.contents
> +  print(opt.height)
>    if opt.height <= 0 or not opt.height then
>      opt.height = max_height
>    end
> ```

`print` won't work, I use `vim.notify()` instead, hope this help.
[Screencast from 31-01-23 14:06:26.webm](https://user-images.githubusercontent.com/62466929/215782499-9f80c5be-fae3-4395-8055-23745b32e7ab.webm)

**Comment by YuCao16** [comment]
> a debug print ..
> 
> ```diff
> diff --git a/lua/lspsaga/finder.lua b/lua/lspsaga/finder.lua
> index 286db1a..ee3fc3d 100644
> --- a/lua/lspsaga/finder.lua
> +++ b/lua/lspsaga/finder.lua
> @@ -336,6 +336,7 @@ function finder:render_finder_result()
> 
>    local max_height = vim.o.lines * 0.5
>    opt.height = #self.contents > max_height and max_height or #self.contents
> +  print(opt.height)
>    if opt.height <= 0 or not opt.height then
>      opt.height = max_height
>    end
> ```

I got it, you forget to convert height to integer.

**Comment by glepnir** [comment]
print you can use message command to see.

**Comment by glepnir** [comment]
I can't open it in phone… check it tomorrow
