### ISSUE TITLE
Finder auto close buffer

### ISSUE THREAD

**Issue by YuCao16** [glepnir/lspsaga.nvim#807]
### Describe the bug

[Screencast from 31-01-23 20:43:38.webm](https://user-images.githubusercontent.com/62466929/215879483-b3edcbe3-ff2d-414d-930c-3f79d9130db7.webm)

### Steps to reproduce

1. Clone [repo](https://github.com/ashleve/lightning-hydra-template)
2. Open `src/train.py` and `src/eval.py`.
3. Split screen, make sure left screen and right screen are different file.
4. Move cursor to class `DictConfig` or `LightningDataModule` and open finder.

### Expected behavior

No buffer be deleted.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-720+gf6929ea51

### lspsaga commit

 9c2111a

### Terminal name/version

kitty 0.26.5

**Comment by glepnir** [comment]
sry I can not reproduced ... I will try one more if you can reproduce with a min config ..

**Comment by YuCao16** [comment]
> sry I can not reproduced ... I will try one more if you can reproduce with a min config ..

It's pretty easy to reproduce on my desktop, maybe because of the environment. Do you have any clue about this issue, I can test on my machine.

**Comment by glepnir** [comment]
just use lspsaga code is simply

**Comment by YuCao16** [comment]
This issue happens all the time. I can reproduce using `lspsaga.nvim`.
1. Open two files `outline.lua` and `window.lua`.
2. Split window, make sure left window and right window are different.
3. Toggle finder on function `vim.fn.winline()` at   [local lines_above = vim.fn.winline() - 1](https://github.com/glepnir/lspsaga.nvim/blob/f514660f65983d33613bf605bfd0adf583c06a8b/lua/lspsaga/window.lua#L126)

[Screencast from 01-02-23 09:52:29.webm](https://user-images.githubusercontent.com/62466929/216009864-52917b7d-03ee-44f1-86e2-fe85acc72efd.webm)

**Comment by glepnir** [comment]
can't reproduce . notice i'm on finder branch. 

![jump](https://user-images.githubusercontent.com/41671631/216183279-d02beee3-f6aa-4638-933c-71e26def41e9.gif)

**Comment by YuCao16** [comment]
> can't reproduce . notice i'm on finder branch.
> 
> ![jump](https://user-images.githubusercontent.com/41671631/216183279-d02beee3-f6aa-4638-933c-71e26def41e9.gif) [ ![jump](https://user-images.githubusercontent.com/41671631/216183279-d02beee3-f6aa-4638-933c-71e26def41e9.gif) ](https://user-images.githubusercontent.com/41671631/216183279-d02beee3-f6aa-4638-933c-71e26def41e9.gif) [ ](https://user-images.githubusercontent.com/41671631/216183279-d02beee3-f6aa-4638-933c-71e26def41e9.gif)

Hmm, you have to toggle on function `vim.fnwinlines()`, but finder branch works fine for me now.

**Comment by glepnir** [comment]
> but finder branch works fine for me now.

you can do more test on finder branch  with finder. if works fine for you I will merge then.  finder branch finder not only show preview. it's not preview a true file buffer that mean you can jump to it by jump_to keymap it's `p` default. and do some edit. . can you test this new feature?

**Comment by YuCao16** [comment]
> > but finder branch works fine for me now.
> 
> you can do more test on finder branch with finder. if works fine for you I will merge then. finder branch finder not only show preview. it's not preview a true file buffer that mean you can jump to it by jump_to keymap it's `p` default. and do some edit. . can you test this new feature?

Sure

**Comment by farzadmf** [comment]
> you can jump to it by jump_to keymap it's p default. and do some edit.

@glepnir question: is there a way to jump "back" to the list? I think in the finder showcase, it's shown that we jump and edit something, and then come back to the list, but I'm not sure how we can do that

**Comment by glepnir** [comment]
just wq

**Comment by farzadmf** [comment]
> just wq

Right ... it's a normal buffer! Thank you for the quick response @glepnir
