### ISSUE TITLE
Provide overview of purpose of this plugin in the readme

### ISSUE THREAD

**Issue by jam1015** [glepnir/lspsaga.nvim#809]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
This seems like a great plugin.  People on reddit seem to love it.  But to someone new to it, I'm not exactly sure of its purpose.

There is the description 'A lightweight LSP plugin based on Neovim's built-in LSP with a highly performant UI.'  That sounds great.  I look at the example configuration to see what it can do

one example is:

```
-- Go to definition
keymap("n","gd", "<cmd>Lspsaga goto_definition<CR>")
```
but in the main [neovim lspconfig repo](https://github.com/neovim/nvim-lspconfig) we have the keymap:

```
vim.keymap.set('n', 'gd', vim.lsp.buf.definition, bufopts)
``` 

leaving me puzzling over the best way to use this package.  Should I unset the lspconfig keybindings? What is the overlap between what this plugin does and what lspconfig does? What do they respectively do that the other doesn't? Does it use the built-in lsp client or does it do something separate like coc does?
 
I know that this is a big task, but some sort of summary with compare and contrast to the built in lsp client and the suggested base lspconfig would be great.

Right now the readme is kind of like the  Arch Wiki: accurate but sparse;  in contrast I find the install instructions of the Gentoo wiki to be more helpful; it does repeat itself, but it gives a lot of context and pointers to people who are just at an intermediate level and looking for context. 

But don't call me ingrateful, this looks like a great plugin, thanks for writing it!

**Comment by glepnir** [comment]
I can tell from your comment that you are new to this. nvim-lspconfig is just server configuration and doesn't provide any functionality. I am currently maintaining lspconfig. Of course, I am also doing related work in neovim as a member. .vim.lsp.buf.* is a function provided by neovim. To replace or not to replace is up to you. Have you figured out what the plugin is doing? lspsaga has been around for a long time. Many people on reddit know this plugin. I'm just releasing some version with new features

**Comment by jam1015** [comment]
Hi! Thanks for your response.  I am indeed new to this. Forgive my imprecise language, I of course meant 'the binding of the base neovim functions as suggested in the lspconfig readme'.  

> lspsaga has been around for a long time. Many people on reddit know this plugin. 

you may have seen [this image](https://en.wikipedia.org/wiki/Survivorship_bias#/media/File:Survivorship-bias.svg) that illustrates survivorship bias as explored by the [actual work](https://en.wikipedia.org/wiki/Survivorship_bias#Military) of statistician Abraham Wald.  Using the many people who have figured out your plugin might be like someone saying 'look at all these planes coming back from the war, they are so well protected!'.  

I re-read the readme and now I have a better understanding now.  I just think a three to four sentence summary describing the overall motivation would provide a 90% ease of use increase to absolute beginners without being too verbose.  I remember coming across this a year ago and being completely lost.

A template for an example that can help.

> A lightweight LSP plugin based on Neovim's built-in LSP with a highly performant UI. Overall the goal of this plugin is to provide a user interface that goes beyond that implemented by the functions in the module `vim.lsp.buf` and is easier to interact with. Right now improvements include: [list them here] .  See below for more detailed examples and suggested keybindings.  Set or unset these keybindings along with those suggested in the main nvim-lspconfig readme to suit your preferences.
 This plugin also re-implements a couple of these functions [list them here], but with the advantages that [....]. I also provide a [feature] which can also be found in [x popular neovim plugin], but with [list another advantage here].

Of course this is your plugin, you don't owe me anything! Just getting my final thoughts out.  Ok that's all I have to say!
