### ISSUE TITLE
Cursor jumps into hoverdoc automatically

### ISSUE THREAD

**Issue by trevarj** [glepnir/lspsaga.nvim#81]
### Description

I turned on hoverdocs as so:
```
autocmd CursorHold * lua vim.defer_fn(function() require('lspsaga.hover').render_hover_doc() end, 5000)
```
After the 5 seconds the doc appears, as expected, but then my cursor jumps into it automatically...

Here is a clip of the problem happening:
https://asciinema.org/a/dMrqq4RQVy0lJc9CAatbn6QUI

**Expected Behavior**

**Actual Behavior**

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: 
- lspsaga commit: 

</details>

**Comment by Asterovim** [comment]
Hello. @trevarj  i would like to have hoverdoc with cursorHold.

I have the same problem with : 
`autocmd CursorHold * lua vim.defer_fn(function() require('lspsaga.hover').render_hover_doc() end, 5000)`

I use the lastest version.

Could you please explain how to fix the cursor jump ?

**Comment by trevarj** [comment]
Sorry @Asterovim, I am not using lspsaga anymore 😞. Perhaps your version is not including https://github.com/glepnir/lspsaga.nvim/commit/e9eff8f85375a9f963b68435170fd2ab9ab2e3a1(where the fix was introduced) ?
