### ISSUE TITLE
Not enough room Error

### ISSUE THREAD

**Issue by gandhiShepard** [glepnir/lspsaga.nvim#812]
### Describe the bug

When moving around a file I get this error below. I've Googled around and I haven't found any info on this error yet. Could it be a conflict with the nvim BarBar plugin (similar to WinBar).Please advise. Much respect!

```
Error detected while processing CursorMoved Autocommands for "<buffer=1>":
Error executing lua callback: ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:262: Vim:E36: Not enough room
stack traceback:
        [C]: in function 'nvim_set_option_value'
        ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:262: in function 'render_fn'
        ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:327: in function 'init_buf_symbols'
        ...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:349: in function <...k/packer/start/lspsaga.nvim/lua/lspsaga/symbolwinbar.lua:348>
```

Currently, I'm setting `symbol_in_winbar = { enable: false}` to prevent this error from showing.

### Steps to reproduce

symbol_in_winbar = {
  enable: true
}

### Expected behavior

Being able to move around without the Error popping up.

### Neovim version (nvim -v)

0.8.1

### lspsaga commit

f514660f65983d33613bf605bfd0adf583c06a8b

### Terminal name/version

Allacrity 0.11.0

**Comment by glepnir** [comment]
it's tabline plugin. i think not relate.  did you used matchparen  or something else plugin ？

**Comment by gandhiShepard** [comment]
yes. nvim-ts-autotag and nvim-autopairs.

**Comment by glepnir** [comment]
auto pairs just a pairs complete plugin i also used. no relate.

**Comment by gandhiShepard** [comment]
ok. I don't use tabline. Here's the list of plugins that I use:
 • Comment.nvim
 • LuaSnip
 • cheatsheet.nvim
 • cmp-buffer
 • cmp-cmdline
 • cmp-nvim-lsp
 • cmp-nvim-lua
 • cmp-path
 • cmp_luasnip
 • emmet-vim
 • filetype.nvim
 • gitsigns.nvim
 • hop.nvim
 • lualine.nvim
 • nnn.nvim
 • null-ls.nvim
 • nvim-cmp
 • nvim-colorizer.lua
 • nvim-lspconfig
 • nvim-neoclip.lua
 • nvim-treesitter
 • nvim-ts-autotag
 • nvim-web-devicons
 • packer.nvim
 • playground
 • plenary.nvim
 • popup.nvim
 • prettier.nvim
 • telescope-changes.nvim
 • telescope-fzf-native.nvim
 • telescope.nvim
 • trouble.nvim
 • vim-closetag
 • vim-easy-align
 • vim-markdown
 • vim-projectionist
 • vim-surround
 • vim-test
 
Do you know of any conflicts with any of these?

**Comment by glepnir** [comment]
https://github.com/neovim/neovim/issues/19464

caused by some float window plugin maybe ?  not lspsaga problem

**Comment by glepnir** [comment]
https://github.com/neovim/neovim/issues/19464

caused by some float window plugin maybe ?  not lspsaga problem

**Comment by gandhiShepard** [comment]
k. thanks! much respect!

**Comment by gandhiShepard** [comment]
At the moment, I've narrowed down the issue to a conflict with the Mason plugin. Not sure what the conflict is yet.

**Comment by gandhiShepard** [comment]
However, with out Mason, it turns the LSP servers off and LSPsaga wont work. It's ok. I'm just going to disable `symbol_in_winbar`.

```
symbol_in_winbar = {
enable: false
}
```

**Comment by menghuu** [comment]
hi, I have the same issue, it seems that: [option `matchup_matchparen_offscreen` of `vim-matchup` is set to `popup`](https://github.com/andymass/vim-matchup#c3-display-matches-off-screen).

**Comment by glepnir** [comment]
https://github.com/neovim/neovim/pull/23176
