### ISSUE TITLE
Moving down outline window throws `Invalid buffer id`

### ISSUE THREAD

**Issue by SichangHe** [glepnir/lspsaga.nvim#813]
### Describe the bug

Moving down in the window opened by `:Lspsaga outline` throws errors:

```vim
   Error  10:36:25 msg_show.lua_error Error executing vim.schedule lua callback: ...neovim/0.8.2/share/nvim/runtime/lua/vim/lsp/codelens.lua:166: Invalid buffer id: <BUFFER_ID>
stack traceback:
	[C]: in function 'nvim_buf_attach'
	...neovim/0.8.2/share/nvim/runtime/lua/vim/lsp/codelens.lua:166: in function 'save'
	...neovim/0.8.2/share/nvim/runtime/lua/vim/lsp/codelens.lua:229: in function 'handler'
	...w/Cellar/neovim/0.8.2/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps to reproduce

Using this `init.lua`:

```lua
require('packer').startup(function(use)
    use {
        'glepnir/lspsaga.nvim',
        event = 'VimEnter',
        requires = { 'nvim-tree/nvim-web-devicons' },
        config = function()
            require('lspsaga').setup {
                lightbulb = {
                    enable_in_insert = false,
                    virtual_text = false,
                },
                symbol_in_winbar = {
                    enable = false,
                },
                ui = {
                    border = 'none',
                },
            }
        end,
    }

    use {
        'mhanberg/elixir.nvim',
        ft = { 'elixir' },
        config = function()
            local ex = require('elixir')
            ex.setup {
                cmd = 'elixir-ls',
                settings = ex.settings {
                    enableTestLenses = true,
                    suggestSpecs = true,
                },
            }
        end
    }
end)
```

(I suspect that it does not have to be an Elixir LS, but any LS.)

Open up a new Neovim session and `:PackerCompile`.

Reopen Neovim in a project so that the buffer has LSP attached. It seems that the buffer needs to have functions.

Run `:Lspsaga outline`.

Press down <kbd>j</kbd> for a little while.

See demo video below:
[![demo video](https://asciinema.org/a/lu9i5hOD1m1WOH2oNpbLH3QOX.svg)](https://asciinema.org/a/lu9i5hOD1m1WOH2oNpbLH3QOX)

### Expected behavior

No error should occur.

Also, the floating window should be above the outline window, but that is another bug.

### Neovim version (nvim -v)

NVIM v0.8.2

### lspsaga commit

54725e87bdc3adf6cd609a5f54c03ef08091b1f2

### Terminal name/version

alacritty 0.11.0 (8dbaa0b)

**Comment by SichangHe** [comment]
After a little more testing, it seems to have something to do with movement speed. If I move too quickly, this error shows p; if I wait until the popup window to show up and then move, I do not see the error.

**Comment by glepnir** [comment]
did you see the error `.neovim/0.8.2/share/nvim/runtime/lua/vim/lsp/codelens.lua:166: Invalid buffer id: <BUFFER_ID>` ?

your codelen config have some problem. not lspsaga

**Comment by SichangHe** [comment]
I did not configure codelen. So, I suppose this is an issue with `elixir.nvim`?

**Comment by glepnir** [comment]
not sure.  `au CursorMoved ` to check which plugin

**Comment by SichangHe** [comment]
Thank you. I will try it later.
