### ISSUE TITLE
outline jump error

### ISSUE THREAD

**Issue by SmithJson** [glepnir/lspsaga.nvim#814]
### Describe the bug

首次按 o 跳转到对应的变量位置，然后返回到 outline 面板，继续按 o 提示错误

case url（https://www.veed.io/view/56246543-a740-462b-867a-99f910db891e?panel=share）

### Steps to reproduce

1. 打开 outline 面板
2. 按钮 o跳转
3. 返回 outline 面板
4. 按钮 o 再次进行跳转

### Expected behavior

按 o 能正常跳转到对应的变量

### Neovim version (nvim -v)

0.8.0 1210-gd367ed9b2

### lspsaga commit

f514660f65983d33613bf605bfd0adf583c06a8bf514660f65983d33613bf605bfd0adf583c06a8b

### Terminal name/version

kitty 0.20.3

**Comment by glepnir** [comment]
can't reproduce with min config . looks like the keymap is missed after you first jump ? config the `jump` to other key then try it . when the key not take effect use `verb nmap jump_key` to see output.

**Comment by SmithJson** [comment]
> can't reproduce with min config . looks like the keymap is missed after you first jump ? config the `jump` to other key then try it . when the key not take effect use `verb nmap jump_key` to see output.

![image](https://user-images.githubusercontent.com/40036121/216261229-f3feb83c-cc67-43d5-855c-fc8a90e0b6dd.png)
谢谢，是这个插件的默认键位绑定，把 o 占用了

**Comment by glepnir** [comment]
`outline.keys.jump` 不是占用 我就是把它remap了在这个buffer 它会以只生效。 跳转后再进去失效了。大部分你配置问题。那里restore了。 最小配置是无法重现的。
