### ISSUE TITLE
Rename failed.

### ISSUE THREAD

**Issue by nkta3m** [glepnir/lspsaga.nvim#815]
### Describe the bug

when rename get error, *nix is ok, but windows 10 ,neovim 0.82 get error.
![2023-02-02 13_00_34-Window](https://user-images.githubusercontent.com/13484700/216235901-8b8fae5c-52c3-498c-bf7b-06ffd7332e24.png)

### Steps to reproduce

nvim test.py
:Lspsaga rename

### Expected behavior

normal run

### Neovim version (nvim -v)

NVIM 0.82

### lspsaga commit

f514660f65983d33613bf605bfd0adf583c06a8b

### Terminal name/version

Alacritty

**Comment by glepnir** [comment]
neovim bug I think. try `lua vim.lsp.buf.rename` still have same error
