### ISSUE TITLE
lsp_finder doesn't work in Elixir project

### ISSUE THREAD

**Issue by scottming** [glepnir/lspsaga.nvim#816]
### Describe the bug

<img width="978" alt="image" src="https://user-images.githubusercontent.com/12830256/216284348-23154bf3-ca16-4ee8-8447-8e2c756cbb2c.png">

I think maybe this issue is related to #516 .

### Steps to reproduce

same as 516

### Expected behavior

show the result

### Neovim version (nvim -v)

2c5906b55bb6092121f4d3b032d5449da7675c2b

### lspsaga commit

017bad7edfe69ffcf25c91db319332fa3d977dfc

### Terminal name/version

allacritty

**Comment by glepnir** [comment]
fixed in #810  wait for merge. thanks
