### ISSUE TITLE
Pattern matching in elixir crashes lsp saga (symbolwinbar)

### ISSUE THREAD

**Issue by hnguyen94** [glepnir/lspsaga.nvim#818]
### Describe the bug

Creating a method that takes an argument and performs a pattern matching with a struct breaks LSP Saga somehow.

```
def change_user(%User{} = user)
```

Moving in insert mode seems to be fine. It only happens in normal mode.

When I was checking the source file where the error came from, I saw the TODO. Could has something to do with that?
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/8395044/216361254-69615e85-8335-47fa-a816-62b50969395d.png">

### Steps to reproduce

Create a file in `test.ex`

Add content with

``` 
defmodule Repo.Accounts do
  defstruct Use
  def list_users(user = %User{}) do
    Repo.all(User)
  end
end
```

Cursor movement in normal mode crashes LSP Saga 

### Expected behavior

Normal movement while in normal mode

### Neovim version (nvim -v)

NVIM v0.8.2

### lspsaga commit

017bad7

### Terminal name/version

iTerm 3.4.19

**Comment by glepnir** [comment]
because % is need %% in stl or winbar a escape character. fix tomorrow sleep time
