### ISSUE TITLE
Line number not appers when open in split or new tab using peek_definition

### ISSUE THREAD

**Issue by Fedex159** [glepnir/lspsaga.nvim#821]
### Describe the bug

When I use peek_definition and open the file in a new tab or in split mode, the lines number disappers.

In the mode finders works fine.

Video: 

https://user-images.githubusercontent.com/44141208/216477482-458e9cf7-d7b8-4893-9a65-0ea64eb4104a.mp4

### Steps to reproduce

- Open a file
- Select a constant, function for example
- Use :Lspsaga peek_definition
- Use the combination to open in split or new tab, for exampe <C-c>v
- See the lines numbers disappers

### Expected behavior

- Open a file
- Select a constant, function for example
- Use :Lspsaga peek_definition
- Use the combination to open in split or new tab, for exampe <C-c>v
- The lines numbers needs to show in boths files

### Neovim version (nvim -v)

0.8.2

### lspsaga commit

9c2111aeeabaee94e6e5c8c0af13e3b1ebbe174a

### Terminal name/version

Kitty 0.26.5

**Comment by glepnir** [comment]
fixed in #810 will merge today
