### ISSUE TITLE
Lspsaga goto_definition error

### ISSUE THREAD

**Issue by wintermonth2298** [glepnir/lspsaga.nvim#826]
### Describe the bug

Lspsaga goto_definition returns 

Error executing vim.schedule lua callback: ...ack/packer/start/lspsaga.nvim/lua/lspsaga/definition.lua:282: attempt to concatenate local 'link' (a nil value)
stack traceback:
        ...ack/packer/start/lspsaga.nvim/lua/lspsaga/definition.lua:282: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:1383: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

### Steps to reproduce

run "Lspsaga goto_definition" on any function

### Expected behavior

go to definition

### Neovim version (nvim -v)

v0.8.2

### lspsaga commit

a2e3f7cf76f4cb102d3fc165bd8c9a565053e84f

### Terminal name/version

alacritty

**Comment by eXvimmer** [comment]
Same here
