### ISSUE TITLE
Winbar no longer shows symbols

### ISSUE THREAD

**Issue by kingedward35** [glepnir/lspsaga.nvim#827]
### Describe the bug

I don't know if this is a bug or a removal of a feature, but since I have upgraded to the latest version of `lspsaga`, I no longer get the symbols in the winbar. If this is expected behavior, feel free to close this (hopefully with an explanation). Just curious. Thanks

### Steps to reproduce

Install the latest version of `lspsaga`.
Go to a function or some value inside the function. 
No symbol appears in the winbar.

### Expected behavior

Symbol appears in the winbar.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-771+g18fb669b9

### lspsaga commit

2afe6de953b76d43822cf8377c019ff831a7c73b

### Terminal name/version

Kitty 0.26.5

**Comment by glepnir** [comment]
your file in multiple Window which include float window right? the normal window  should display winbar

**Comment by kingedward35** [comment]
So I do get the winbar to display. Here is a picture. 
<img width="298" alt="image" src="https://user-images.githubusercontent.com/12418717/216740539-6df7262e-be1f-4a44-b045-5de861b7bea7.png">

But if I go inside a function, I no longer get the different symbols to display. I hope that makes sense.
Here is a picture of my cursor inside a function. Previously, I would see a symbol in the winbar alerting me of where my cursor was located.
<img width="712" alt="image" src="https://user-images.githubusercontent.com/12418717/216740644-facdc466-b156-4cda-acd8-6d2d52dcdd26.png">

**Comment by glepnir** [comment]
no any float window?

**Comment by kingedward35** [comment]
I am not sure what you mean. If you are asking can I get a hover window or a floaterm, then yes and I don't have any issues with those. It is only at the top where I used to get the symbols to display when I was in different function/class etc. context that I am missing.

**Comment by kingedward35** [comment]
Here is an example of what it used to look like before I upgraded. 
<img width="872" alt="image" src="https://user-images.githubusercontent.com/12418717/216741132-09bcbeff-de09-4f45-aa40-ea7fbdcab006.png">

**Comment by glepnir** [comment]
I think buwinid doesn't  always give me first window id? wired check it later

**Comment by kingedward35** [comment]
Thanks. Appreciate the work you do. Have a good weekend and take care of yourself.

**Comment by glepnir** [comment]
thanks. new idea is just display winbar on the first window which display this buffer at first. then even the buffer in float window after that. it not display on float window. looks like this way not correct

**Comment by kingedward35** [comment]
Appreciate the response. Thanks again.

**Comment by kingedward35** [comment]
Also, please don’t work in this over the weekend. While I like the winbar
functionality, don’t want you losing sleep over. If there is a solution,
that is cool. But take care of yourself. Have a good one.

**Comment by kingedward35** [comment]
Just updated to latest version and now the symbols show up again. Don't know what you did, but much appreciated. Thanks again.
