### ISSUE TITLE
Improve "Ugly UI"

### ISSUE THREAD

**Issue by Roiqk7** [glepnir/lspsaga.nvim#838]
First of all I really love your plugin, you are doing a great job.

**Is your feature request related to a problem? Please describe.**

That being said I really don't like this: (the red arrows)

<img width="1000" alt="Screenshot 2023-02-05 at 9 18 50" src="https://user-images.githubusercontent.com/112021405/216808791-9fcd3cc1-ff30-4ceb-a68d-8d7b484512df.png">

<img width="155" alt="Screenshot 2023-02-05 at 9 32 36" src="https://user-images.githubusercontent.com/112021405/216809332-2f4e52fb-bbab-4b4b-a385-773be39d9aa8.png">

**Describe the solution you'd like**

Could the red arrow have a space in front of it so it's not all "glued" together? Also the arrow itself is way too big. Some people may like it but could there be at least some was to modify it? When I looked into your UI settings there was everything except for this. 

It's a small thing and I bet fixing it takes just a while.

**Describe alternatives you've considered**

Making it customisable (best), giving better default (convenient), new design altogether (unnecesary)
 
**Additional context**

I've said everything I wanted. I really thing you are doing a great job and are very active (everyday I sync my Packer, I see several comments from Lspsaga which I think is admirable).

**Comment by glepnir** [comment]
First you used a mono nerd font that's why it so big . second read doc there has `symbol_in_winbar.seperator` that you can used to change this symbol.

**Comment by Roiqk7** [comment]
Thanks a lot!
