### ISSUE TITLE
Cannot disable whitespace highlighting when using vim-better-whitespace

### ISSUE THREAD

**Issue by farzadmf** [glepnir/lspsaga.nvim#844]
### Describe the bug

I'm using [vim-better-whitespace](https://github.com/ntpeters/vim-better-whitespace) to highlight trailing whitespaces in a buffer.

When I open `lspsaga`'s finder, whitespaces are highlighted, and I don't seem to be able to disable them:
![image](https://user-images.githubusercontent.com/5768792/216987198-1d44b505-b219-4b79-b6d4-12e1b60adb3f.png)

`vim-better-whitespace` allows "black listing" some filetypes using `g:better_whitespace_filetypes_blacklist`, which I _am_ using and it works for other filetypes.

I tried adding `lspsagafinder` to the blacklist, but it's not working, and whitespaces are still highlighted

Also, if I manually disable the whitespace plugin by doing `:DisableWhitespace`, the highlights are gone

### Steps to reproduce

Sorry, since a minimal config requires enabling LSP and everything, Please let me know if that's necessary, and I can try to create one.

### Expected behavior

I expect the whitespaces to not be highlited similar to the other filetypes I have blacklisted

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

4623173

### Terminal name/version

WezTerm

**Comment by glepnir** [comment]
read that plugin doc add lspfinder filetype into list

**Comment by farzadmf** [comment]
Thank you @echasnovski for your comment here, just to add a bit of context, originally I was having issues with `vim-better-whitespace` (as mentioned in the issue), but then I thought maybe it's not compatible with how the newer Lua plugins do things, so I'm trying `mini.trailspace` now

**Comment by glepnir** [comment]
maybe set a buftype name instead of filetype

**Comment by echasnovski** [comment]
> maybe set a buftype name instead of filetype

Not sure what you mean.

The way it works (at least in 'mini.trailspace') is through doing some bookkeeping inside appropriate autocommand. The usual way of doing this is for `FileType` event. How do you propose to change that?

As far as I can tell, the buffer for 'lspsagafinder' is created an managed *before* it is shown in target window. So, there seems to be no way of knowing in which window it will be shown, but this information is needed to disable highlighting (as it is done per window).
