### ISSUE TITLE
Escape sequence remains in python hover_doc

### ISSUE THREAD

**Issue by pysan3** [glepnir/lspsaga.nvim#845]
### Describe the bug

First of all, thank you so much for this amazing plugin!!

When I `:Lspsaga hover_doc` in a python file, the output in the popup has escape sequence of markdown remaining.
For example the `\_` or `\[\]` in the screenshot.

![Screenshot_20230207_050123-1](https://user-images.githubusercontent.com/41065736/217076038-aa158844-4fa6-4913-be6f-338c094d71a3.png)

When I at least tested it with lua, it seems to be working as expected.

![Screenshot_20230207_051343](https://user-images.githubusercontent.com/41065736/217076169-88d9c66a-9786-40f0-b6e8-96647a441fcd.png)

*I do have treesitter markdown installed.

Interestingly, when I install markdown-inline, the color of `\_` changes (to a light-blue-ish color?).

![Screenshot_20230207_052521](https://user-images.githubusercontent.com/41065736/217077608-7a45693d-9c2f-4203-9726-0d33097cee5d.png)

### Steps to reproduce

- Open a python file.
- `:Lspsaga hover_doc` on a function which has `_` etc in its doc.

Here is the code I tested with.

```python
def lm_user_loader(user_token: str) -> Optional[LMUsers]:
    """Returns a LMUser instance of the given token

    Args:
        user_token (str): user_token specified in cookie

    Returns:
        Optional[LMUsers]: instance of LMUser or None(if error)
    """
    pass
```

### Expected behavior

No escape sequence shown.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-964ae205a (nightly)

### lspsaga commit

8bd402a (Latest)

### Terminal name/version

Linux / Wezterm / tmux

**Comment by glepnir** [comment]
fixed.

**Comment by pysan3** [comment]
Thank you @glepnir for your fast response.

Unfortunately, now the `\[` `\]` disappears as in `Optional[LMUsers]` on the last line.

![Screenshot_20230207_222802](https://user-images.githubusercontent.com/41065736/217258024-0f62bfd8-2e15-4399-8f79-76177825a9a4.png)

**Comment by glepnir** [comment]
looks like there has something known issue in treesitter markdown.

**Comment by pysan3** [comment]
Could you guide me to that issue?

**Comment by glepnir** [comment]
i had add a patch for this. should be works

**Comment by pysan3** [comment]
I noticed the update and now it works great!

Thank you so much.
