### ISSUE TITLE
Line number not appers when open in split or new tab using lsp_finder

### ISSUE THREAD

**Issue by Fedex159** [glepnir/lspsaga.nvim#846]
### Describe the bug

When I use lsp_finder and open the file in a new tab or in split mode, the lines number disappers.

In the mode peek_definition works fine.

https://user-images.githubusercontent.com/44141208/217108554-f0a55d4d-f169-40db-b6a9-a89f1b3a2967.mp4

### Steps to reproduce

- Open a file
- Select a constant, function for example
- Use :Lspsaga lsp_finder
- Use the combination to open in split or new tab, for exampe **s**
- See the lines numbers disappers

### Expected behavior

- Open a file
- Select a constant, function for example
- Use :Lspsaga lsp_finder
- Use the combination to open in split or new tab, for exampe **s**
- The lines numbers needs to show in boths files

### Neovim version (nvim -v)

0.8.2

### lspsaga commit

8bd402ad4f138af23948115dc380319069b79a01

### Terminal name/version

Kitty 0.26.5

**Comment by glepnir** [comment]
you opened it before in finder right?
