### ISSUE TITLE
Configuration outline show_detail is not used

### ISSUE THREAD

**Issue by mikehaertl** [glepnir/lspsaga.nvim#848]
I tried to find out what `show_detail` in `outline` config does. 

It is not used at all in the code. Can it be removed?

**Comment by glepnir** [comment]
does anyone need this also can add also can remove :)

**Comment by glepnir** [comment]
looks like this conflict with preview ?

**Comment by mikehaertl** [comment]
Sorry, I don't understand. The setting has no effect.

It's only used here:

```
$ rg show_detail
README.md
421:    show_detail = true,
452:    show_detail = false,

lua/lspsaga/init.lua
100:    show_detail = true,
112:    show_detail = false,

doc/lspsaga.nvim.txt
488:        show_detail = true,
517:        show_detail = false,
```

So it is not used in 'outline.lua' at all.

**Comment by glepnir** [comment]
I mean this option implement had removed. and the behavior of this option just set the text of detail as virtual text after the outline item.  if someone need this i can reimplement it . but it looks like conflict with preview.

**Comment by mikehaertl** [comment]
I would say, if it is not implemented, then the configuration should also be removed from documentation (and from init config). Don't you think so?

**Comment by glepnir** [comment]
I forget removed this option
