### ISSUE TITLE
Lsp Finder throws error on open

### ISSUE THREAD

**Issue by akinsho** [glepnir/lspsaga.nvim#85]
### Description

When opening the finder I get an error. The window contents are correctly highlighted, the previewer doesn't open and the selected highlight replaces my cursorline
```
Error executing vim.schedule lua callback: ...site/pack/packer/start/lspsaga.nvim/lua/lspsaga/libs.lua:46: Expected lua string
````

![image](https://user-images.githubusercontent.com/22454918/107343637-6d4a1e00-6ab9-11eb-893a-c229f14504d9.png)

**Expected Behavior**

It should open as normal

**Actual Behavior**

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. run finder mapping on a variable or function call in lua file 
</details>

<details><summary>Environment</summary>

```
 saga.init_lsp_saga {
    debug = true,
    use_saga_diagnostic_sign = false,
    finder_action_keys = {
      open = "o",
      vsplit = "v",
      split = "s",
      quit = {"q", [[\<ESC>]]}
    }
  }

  map("n", "gh", [[<cmd>lua require'lspsaga.provider'.lsp_finder()<CR>]])
```

- nvim --version output: 

```
Error executing vim.schedule lua callback: ...site/pack/packer/start/lspsaga.nvim/lua/lspsaga/libs.lua:46: Expected lua string
NVIM v0.5.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-tTsPN6/neovim-0.5.0+ubuntu2+git202102090237-38ea2ce34-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-tTsPN6/neovim-0.5.0+ubuntu2+git202102090237-38ea2ce34-d569569c9/build/config -I/build/neovim-tTsPN6/neovim-0.5.0+ubuntu2+git202102090237-38ea2ce34-d569569c9/src -I/build/neovim-tTsPN6/neovim-0.5.0+ubuntu2+git202102090237-38ea2ce34-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-tTsPN6/neovim-0.5.0+ubuntu2+git202102090237-38ea2ce34-d569569c9/build/src/nvim/auto -I/build/neovim-tTsPN6/neovim-0.5.0+ubuntu2+git202102090237-38ea2ce34-d569569c9/build/include
Compiled by buildd@lgw01-amd64-038

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

- Operating system: Ubuntu 20.10
- lspsaga commit: 

</details>

**Comment by akinsho** [comment]
I've tried with `debug = true` but that doesn't print anything. This issue only started a few days ago when I think there was a change/refactor of the `finder`. Also should mention that I use `sumneko_lua` with `efm` so there are multiple lsps active in most of my buffers

**Comment by glepnir** [comment]
@akinsho   `quit = {"q", '<ESC>}`  change like this

**Comment by akinsho** [comment]
@glepnir unfortunately that didn't fix the issue. Do you need more info from me? are you able to see the same issue? for me it happens even if I use `LspSaga finder` etc. as if I map the `lua` function although that's to be expected probably

**Comment by glepnir** [comment]
hmm `quit = {'q','<ESC>'}`  quit key like this

**Comment by akinsho** [comment]
I tried just now removing the `quit` key as well as using it the way you show in the example above. To be clear the error isn't when I try to quit, the error is *immediately* I open a finder window it throws this error

**Comment by glepnir** [comment]
the libs.lua :46 is create keymap of finder . so you got error because of your quit key.

**Comment by glepnir** [comment]
![image](https://user-images.githubusercontent.com/41671631/107355867-07868200-6b0b-11eb-91d8-b17c5ef3ee26.png)

**Comment by akinsho** [comment]
Ok I tested removing that configuration completely and it works fine. I managed to work out what is wrong, if you specify `finder_action_keys` you have to specify the complete table and all it's keys. So I previously had that table but there didn't use to be a `scroll_down` and `scroll_up` key. Since I didn't specify them there seems to be no fallback so it was causing errors on open

**Comment by glepnir** [comment]
OK i will enhance this .seems like should extend custom keymaps.

**Comment by glepnir** [comment]
Now you do not need set all keymaps in finder .just set you need to change.

**Comment by akinsho** [comment]
Thanks @glepnir that works now. Sorry to be burying you in issues 😅 , looking at your screenshot it seems you aren't seeing the finder window sizing and highlighting bugs. With the config above which I posted (or with 0 config) I'm seeing the highlighting doesn't reach the `references` section/ it seems to break as well.

#### Broken highlighting 
![lsp_saga_finder](https://user-images.githubusercontent.com/22454918/107362313-7befff80-6ad0-11eb-8406-77c52bfa0ce8.gif)

#### Missing highlighting
![image](https://user-images.githubusercontent.com/22454918/107362493-bbb6e700-6ad0-11eb-9f13-446a7b9b28c0.png)

I didn't post this earlier since I thought maybe you were already aware and working on it

**Comment by glepnir** [comment]
why there has two definitions?

**Comment by akinsho** [comment]
I don't really know there is only one function in that file, it's just what I get I tried it on another local function and I'm seeing two definitions as well 🤷🏿

**Comment by glepnir** [comment]
I had fix height problem. but i test your config I don't have two definitions seems like you start two lua server?
![image](https://user-images.githubusercontent.com/41671631/107363830-ad3eee80-6b15-11eb-903a-2bc407aaf054.png)

**Comment by akinsho** [comment]
@glepnir thanks for the quick height fix, I'm not sure how I could have 2 lsps running, looking at `LspInfo` I get

![image](https://user-images.githubusercontent.com/22454918/107364847-e0f92480-6ad3-11eb-999f-48393a493f38.png)

**Comment by glepnir** [comment]
hmmm now still exist ? I can't reproduce it in my config.

**Comment by akinsho** [comment]
I think maybe it might be the version of `sumneko_lua` I'll try and debug more soon and report back, I actually have two functions called `map` but one is local but that isn't the issue since when I check a bunch of different definitions (local) I get `0 definitions` and then some references

**Comment by glepnir** [comment]
ok if can reproduce with min config. post here I will test it.

**Comment by akinsho** [comment]
@glepnir I've been testing with a minimal `init.lua`, with the latest version of `sumneko_lua` and I'm getting `server returns wrong response`, I think the newest server has some incompatible changes in neovim that might be causing this issue. I'll try downgrading later today to see if that helps

```lua
vim.cmd "packadd nvim-lspconfig"
vim.cmd "packadd lspsaga.nvim"

local lspconfig = require("lspconfig")

local sumneko_path = string.format("%s/lua-language-server", "<Path-to-install>")
local sumneko_binary = sumneko_path .. "/bin/Linux/lua-language-server"

lspconfig.sumneko_lua.setup {
  cmd = {sumneko_binary, "-E", sumneko_path .. "/main.lua"},
  settings = {
    Lua = {
      diagnostics = {globals = {"vim"}},
      completion = {keywordSnippet = "Both"},
      runtime = {
        version = "LuaJIT",
        path = vim.split(package.path, ";")
      },
      awakened = {cat = true},
      workspace = {
        maxPreload = 1000,
        preloadFileSize = 1000
      }
    }
  }
}

require("lspsaga").init_lsp_saga {
  use_saga_diagnostic_sign = false,
  finder_action_keys = {
    vsplit = "v",
    split = "s",
    quit = {"q", "<ESC>"}
  }
}

vim.api.nvim_set_keymap("n", "gh", [[<cmd>lua require'lspsaga.provider'.lsp_finder()<CR>]], {})

```

**Comment by glepnir** [comment]
I test it with last commit neovim with this min config. works fine.

```vim
set rtp+=~/workstation/vim/lspsaga.nvim
set rtp+=~/.cache/vim/dein/repos/github.com/neovim/nvim-lspconfig

lua <<EOF

require('lspsaga').init_lsp_saga()

require('lspconfig').sumneko_lua.setup {
  cmd = {
    "/Users/bitcoder/workstation/lua-language-server/bin/macOS/lua-language-server",
    "-E",
    "/Users/bitcoder/workstation/lua-language-server/main.lua"
  };
  settings = {
    Lua = {
      diagnostics = {
        enable = true,
        globals = {"vim"}
      },
      runtime = {version = "LuaJIT"},
      workspace = {
        library = vim.list_extend({[vim.fn.expand("$VIMRUNTIME/lua")] = true},{}),
      },
    },
  }
}
EOF

```


https://user-images.githubusercontent.com/41671631/107373878-f5fca480-6b21-11eb-8624-3eae24ed2212.mov

**Comment by akinsho** [comment]
@glepnir are you using the latest `sumneko_lua` language server version from today?

**Comment by glepnir** [comment]
Ohh ..no  update now and test.

**Comment by glepnir** [comment]
reproduce with latest ..

**Comment by glepnir** [comment]
seems like something wrong in latest lua-language server. check the default handler of neovim
```lua
vim.lsp.buf.definition() got noting happened..
```

**Comment by akinsho** [comment]
Ok in which case that doesn't have to do with this plugin then 👍🏿 , I did just try another lsp client just to check and using in a `dart` project I see.

![image](https://user-images.githubusercontent.com/22454918/107381025-54a42d00-6ae6-11eb-80a6-3f2e48863dfa.png)

Looking in the code in `provider.lua` it looks like `opts.height` expects some values and there is no fallback so `opts.height` can be `nil` and so tries to compare `nil` with `max_height`. The references and definitions look fine so think this isn't an lsp error

**Comment by glepnir** [comment]
I also get it. but I am thinking about why get nil ..

**Comment by glepnir** [comment]
fixed bug of nil value . but finder still not work in lua-language-server last commit

**Comment by glepnir** [comment]
Damn the last commit of lua-language-server. it works slowly...

**Comment by akinsho** [comment]
I think probably the change in `lua-language-server` is maybe incompatible with neovim somehow, I don't know much about the internals but seems the author is more focused on vscode so they might have broken in by mistake. Yeah also noticed it's really slow as well

**Comment by glepnir** [comment]
yep. the author use vscode ..so I need rollback.
