### ISSUE TITLE
Outline auto_refresh does not work with Java core API files

### ISSUE THREAD

**Issue by mikehaertl** [glepnir/lspsaga.nvim#851]
### Describe the bug

`auto_refresh` does not update the outline if the target buffer contains a Java source file.

### Steps to reproduce

* Use "goto definition" with a Java API import like:
```java
import java.util.Comparator;
```
the source class file for `Comparator.class` is opened in a new buffer.
* Open the outline with `:Lspsaga outline`. The outline is correctly opened for `Comparator.class`
* Switch to another buffer.  The outline will refresh.
* Switch back to `Comparator.class`. The outline will not refresh.

### Expected behavior

Java API source files on Linux are kept in a `.zip` file (i.e. `/usr/lib/jvm/openjdk-17/lib/src.zip`). I think extraction of this file is handled by the LSP server automatically. The unpacked file is not a real file. The file path for the `Comparator.class` looks like 

` jdt://contents/java.base/java.util/Comparator.class?=app/%5C/usr%5C/lib%5C/jvm%5C/java-17-openjdk-amd64%5C/lib%5C/jrt-fs.jar%60java.base=/javadoc_location=/https:%5C/%5C/docs.oracle.com%5C/en%5C/java%5C/javase%5C/17%5C/docs%5C/api%5C/=/%3Cjava.util(Comparator.class`.

The buffer with `Comparator.class` therefore has the `nofile` flag set. And this is excluded in the `outline.lua`:

https://github.com/glepnir/lspsaga.nvim/blob/1d56a915d42a79242ef1237dba63836fcf3c7307/lua/lspsaga/outline.lua#L301-L308

I'm not sure, how this could be fixed without breaking other `nofile` buffers that should be ignored. Maybe check the file path for `jdt://`?

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

1d56a91

### Terminal name/version

Gnome Terminal 3.44.0

**Comment by glepnir** [comment]
the class file buftype and filetype output is what.

**Comment by mikehaertl** [comment]
* filetype: `java`
* buftype: `nofile`

**Comment by glepnir** [comment]
so there need a double check ?

**Comment by mikehaertl** [comment]
Yes, that should work I think. Or maybe only check for `filetype=='java'` and then skip ignore?

**Comment by glepnir** [comment]
just thinking auto refresh should be work inside lspattach. then no need these check.

**Comment by mikehaertl** [comment]
I don't understand. Is this something I should test? Where/how?

**Comment by mikehaertl** [comment]
Hmm, the fix doesn't work. Now `auto_refresh` does not work at all anymore.

**Comment by glepnir** [comment]
damn it  only work  when first open . .. wait

**Comment by mikehaertl** [comment]
Better - but not perfect yet:

* Open file 1
* Open `:Lspsage outline`
* Open file 2

File 2 is visible in the active buffer but outline is not updated.

It only works if the order is reversed:

* Open file 1
* Open file 2
* Open `:Lspsage outline`

**Comment by glepnir** [comment]
works for lua file  i had test this way before update

**Comment by glepnir** [comment]
also tested in c c++ go rust.

**Comment by mikehaertl** [comment]
I added a `print`:

```lua
function ot:auto_refresh()
  api.nvim_create_autocmd('BufEnter', {
    group = self.group,
    callback = function(opt)
      print('bufenter', api.nvim_get_current_buf())
```
* Open file 1
* Open :Lspsage outline
* Open file 2


```
[Lspsaga.nvim] there is no server attatched this buffer
bufenter 1
bufenter 12
bufenter 1
bufenter 13
[lspsaga.nvim] there is already a request for outline please wait
```

Outline is only updated if i switch to file 1 then back to file 2.

**Comment by mikehaertl** [comment]
I tested also with PHP: Does not work there either.

**Comment by mikehaertl** [comment]
Wait, it only happens if I open the file via nvim-fzf. It works with `:e file2.php`.

**Comment by glepnir** [comment]
![min](https://user-images.githubusercontent.com/41671631/217785810-b05c6c74-60e1-4a8e-a921-9865c6ebe812.gif)

**Comment by mikehaertl** [comment]
Yes, it only fails with https://github.com/junegunn/fzf.vim. I use this in a custom function to fuzzy search files.

I will investigate further.

**Comment by glepnir** [comment]
it use the actually buffer number in that window ? not sure .

**Comment by mikehaertl** [comment]
Hmm, when a file is openen with my fzf plugin it first goes back to the initial buffer, then switches to the new buffer:

So what happens is this:
```
[Lspsaga.nvim] there is no server attatched this buffer
bufenter 1
<--- fzf is opened here
bufenter 12  <-- buffer for fzf select
<--- file is selected in fzf here
bufenter 1 <-- triggers outline request
bufenter 13 <-- ... request for 1 is still active
[lspsaga.nvim] there is already a request for outline please wait
```

I don't know, why it first goes back to buffer `1` before going to the new buffer `13`. Hmm.

**Comment by glepnir** [comment]
buffer 1 has outline ?

**Comment by mikehaertl** [comment]
Yes.

After 2nd file is opened I'm in buffer 13 and see outline of buffer 1. Then I do `:bp` and `:bn`. Now the outline for buffer 13 works.

**Comment by glepnir** [comment]
i had update some patch for outline. you can test it.

**Comment by mikehaertl** [comment]
It almost works now, thank you! 👍🏻 

Minor issue:

* `:e file1`
* `:Lspsaga outline`
* `:e file2`
* `:bd`

I'm in an empty buffer now and have to `:bp` to get back to file1.

Note: I use nvim-dap which seems to create a couple of hidden buffers, even if inactive. Here's the output of `:buffers1` after `:bd`:

```
:buffers!
  1 #h   "models/EventParticipant.php"  Zeile 30
  2u h   "[Notizen]"                    Zeile 0
  3u%a-  "DAP Breakpoints"              Zeile 1
  4u h-  "DAP Scopes"                   Zeile 0
  5u h-  "DAP Stacks"                   Zeile 0
  6u h   "DAP Watches"                  Zeile 0
  7u h-  "DAP Hover"                    Zeile 0
  8u h   "[dap-repl]"                   Zeile 0
 14u     "models/Event.php"             Zeile 1
 15u h   "[Notizen]"                    Zeile 0
```

So active buffer is 3 which is unlisted.

**Comment by glepnir** [comment]
when you use bd the outline will close ? and I don't use that plugin.

**Comment by mikehaertl** [comment]
Yes, outline closes. Only the wrong buffer is active (3 in the list above instead of 1). Shouldn't it ignore `unlisted` buffers?
