### ISSUE TITLE
Can I close the the hover window by just typing q?

### ISSUE THREAD

**Issue by scottming** [glepnir/lspsaga.nvim#853]
Currently, we close the finder and peek_definition by typing `q`, and we close the hover window by typing the moving key(h|j|k|l) or typing `kq`.

Is there a way to let these three window types close in one way: just type `q`. But these code show me the closing hover logic that needs the cursor in the hover window.

https://github.com/glepnir/lspsaga.nvim/blob/598efc98320d01713eba2c1c8d77577b23abd827/lua/lspsaga/hover.lua#L116-L121

**Comment by glepnir** [comment]
don't get you point . in fact you don't need close the hover window by manually . it will auto close when trigger some autocommand events. 

you want use `q` to close hover when you not in hover?

**Comment by scottming** [comment]
> you want use q to close hover when you not in hover?

Yes.

**Comment by glepnir** [comment]
when you move cursor or insert enter it will auto close. the situation is what ? why you wan to close it manually ?

**Comment by scottming** [comment]
Because I wanted to have a consistent experience, consistent with closing finder and peek_definition.

**Comment by glepnir** [comment]
but in fact the hover window no need you close it by manually .  i don't want support it in built-int but i can provide an api that you can used to define q map in rhs function.

**Comment by scottming** [comment]
> but in fact the hover window no need you close it by manually .

Yes, I know this, But sometimes when I open hover, after reading the doc I have forgotten whether I opened hover or definition, so I hope I don't need to **think** or **read** the title, but just hit q and exit.

> i can provide an api that you can used to define q map in rhs function.

Thank you so much.

**Comment by glepnir** [comment]
> I opened hover or definition

hover is doc , definition is the source code. if you both use lspsaga. it's different.
i need notify you that the q is macro keymap  if you want remap q in a normal buffer.

**Comment by scottming** [comment]
I don't really understand this

> i need notify you that the q is macro keymap if you want remap q in a normal buffer.

If this is not easy to implement, can you tell me how to get the last open float window, then it should be hover if its filetype is markdown, can I use nvim_create_autocmd to close it?

**Comment by glepnir** [comment]
i mean i can provide an api that you can  use to check there has hover window or not.  what i mean is `q` is keymap of vim macro. so you need remap = true i think in opts of vim.keymap.set

**Comment by scottming** [comment]
Ok, I understand what you mean. I'll try. thank you.

**Comment by glepnir** [comment]
`require('lspsaga.hover'):has_hover()` true or false

**Comment by scottming** [comment]
```
	-- make the hover window close when pressing q
	vim.keymap.set("n", "q", function()
		local hover = require("lspsaga.hover")
		if hover:has_hover() then
			vim.api.nvim_win_close(hover.preview_winid, true)
			hover:remove_data()
		end
	end, { silent = true })

``

It works, thank you again.
