### ISSUE TITLE
Error using hover_doc

### ISSUE THREAD

**Issue by hnguyen94** [glepnir/lspsaga.nvim#854]
### Describe the bug

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/8395044/217818791-02adf305-f871-49e0-9949-fefca37256b8.png">

Tried to use `:Lspsaga hover_doc`

### Steps to reproduce

:Lspsaga hover_doc`

### Expected behavior

Seeing the usual hover doc

### Neovim version (nvim -v)

NVIM v0.8.2

### lspsaga commit

598efc9

### Terminal name/version

iterm 3.4.19

**Comment by glepnir** [comment]
because you have some error before .the actual error not hover.

**Comment by pablopunk** [comment]
@glepnir can you explain a bit more? I'm also getting this error today I (think) haven't changed anything regarding LSP

**Comment by itsjoeoui** [comment]
I am getting the same thing, and I also haven't changed anything, I just did a PackerSync and it broke,

**Comment by andres-gr** [comment]
found the fix

apparently we now need to install treesitter parsers for markdown, markdown_inline

> You should install the [treesitter](https://github.com/nvim-treesitter/nvim-treesitter) markdown parser so Lspsaga can use it to render the hover window. You can press the keyboard shortcut for `:Lspsaga hover_doc` twice to enter the hover window.

that said, @glepnir you could have at least mentioned to check the docs

**Comment by zsmatrix62** [comment]
it does not solve this issue by ts install markdown and markdown_inline in my today's update. I just did PakcerSync and didn't change anything else.

I got the same error.

**Comment by andres-gr** [comment]
@zsmatrix62 that's unfortunate

I was getting an error related to missing those ts parsers and also the same error from OP

And both were resolved when I installed the missing parsers

Don't think it would make a difference but I'm using lazy.nvim instead of packer

**Comment by glepnir** [comment]
install `markdown` and `markdown-line` parser make sure  load nvim-treesitter before lspsaga.

**Comment by zsmatrix62** [comment]
thanks, this is working from packer:

```lua
use({
	"glepnir/lspsaga.nvim",
	branch = "main",
	after = "nvim-treesitter",
	config = function()
		require("lspsaga").setup({
```

**Comment by pablopunk** [comment]
> install markdown and markdown-line parser make sure load nvim-treesitter before lspsaga.

Hi, if I understand correctly these are the changes that I need to make:

```diff
use {
  "glepnir/lspsaga.nvim",
  branch = "main",
+ after = "nvim-treesitter"
}
```
```diff
require("nvim-treesitter.configs").setup {
  ensure_installed = {
    "markdown",
+   "markdown-line",
  },
  auto_install = true,
}
```

If I do that it doesn't find the markdown-line parser:
```diff
- Installation not possible: ...er/start/nvim-treesitter/lua/nvim-treesitter/install.lua:75:
- Parser not available for language "markdown-line"
```

**Comment by glepnir** [comment]
lazy load lspsaga by after = 'nvim-lspconfig' , nvim-treesitter load by `event = 'BufRead'` . install markdown will also install makdown-inline

**Comment by pablopunk** [comment]
@glepnir if I do that I get `module 'nvim-treesitter.configs' not found`

Check out this screencast with my changes in case it helps:

[![asciicast](https://asciinema.org/a/558815.svg)](https://asciinema.org/a/558815)

**Comment by andres-gr** [comment]
> ```diff
> use {
>   "glepnir/lspsaga.nvim",
>   branch = "main",
> + after = "nvim-treesitter"
> }
> ```
> 
> ```diff
> require("nvim-treesitter.configs").setup {
>   ensure_installed = {
>     "markdown",
> -  "markdown-line",
>+  "markdown_inline",
>   },
>   auto_install = true,
> }
> ```

@pablopunk it should be `markdown_inline`

**Comment by pablopunk** [comment]
@andres-gr 🙏🏻  yeah I tried that too

![CleanShot 2023-02-10 at 18 53 20](https://user-images.githubusercontent.com/4324982/218161740-7b9eaec5-4304-493f-9ed1-91988ba9ab57.png)

But I still get an error on hover:

![CleanShot 2023-02-10 at 18 53 11](https://user-images.githubusercontent.com/4324982/218161744-dc464059-0f0c-49ef-b411-21f38e2d948d.png)

**Comment by hungnguyen1503** [comment]
Hi, I also got the same error.

**Comment by glepnir** [comment]
please read doc you need invoke `require('lspsaga').setup` in `config`

**Comment by pablopunk** [comment]
Ok, adding this to my Packer setup worked.

```lua
    config = function()
        require("lspsaga").setup({})
    end,
```

Although I don't like it. All plugins I have, I can put the config [in separate files](https://github.com/pablopunk/dotfiles/tree/master/nvim/lua/pablopunk/plugins), with their config on each file. This doesn't allow that

**Comment by glepnir** [comment]
I don't know what do you mean. but i think you need learn lua.
