### ISSUE TITLE
Giving an error after treesitter update.

### ISSUE THREAD

**Issue by nevzatseferoglu** [glepnir/lspsaga.nvim#858]
### Describe the bug

I got an error after several updates. Then, it ended up with lacking features dependency in lspsaga side.

<img width="1487" alt="Screen Shot 2023-02-10 at 17 49 52" src="https://user-images.githubusercontent.com/43863606/218131887-4f6f4206-30c8-4ff3-b22c-d12fd75b175d.png">

### Steps to reproduce

You can reproduce it by applying:

`<cmd>Lspsaga hover_doc<CR>"`

### Expected behavior

I guess It should have worked without that dependency.

### Neovim version (nvim -v)

NVIM v0.8.3

### lspsaga commit

the last commit

### Terminal name/version

alacritty

**Comment by andres-gr** [comment]
@nevzatseferoglu `hover_doc` needs treesitter parsers for `markdown` and `markdown_inline` to be installed

check this [thread](https://github.com/glepnir/lspsaga.nvim/issues/854#issuecomment-1425720160)
