### ISSUE TITLE
An error occurred while using the hover_doc 

### ISSUE THREAD

**Issue by wwweww** [glepnir/lspsaga.nvim#859]
### Describe the bug

Error executing Lua callback: ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:17: loop or previous error loading module 'lspsaga.hover'
stack traceback:
        [C]: in function 'require'
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:17: in function <...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:16>
        ...e/pack/packer/start/lspsaga.nvim/lua/lspsaga/command.lua:60: in function 'load_command'
        ...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:8: in function <...m/site/pack/packer/start/lspsaga.nvim/plugin/lspsaga.lua:7>

### Steps to reproduce

An error is reported during normal use

### Expected behavior

Open the document view window

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

lspsaga

### Terminal name/version

alacritty 0.11.0

**Comment by glepnir** [comment]
can't reproduce the error mean you have error before.

**Comment by yeseongmoon** [comment]
I don't know if this relates you the same, but I also have this problem. When I first try hover_doc, it throws an error related to treesitter that I do not have a parser for markdown_inline language. Whenever I try to hover_doc again, it throws exactly the same error of yours. I added the error for treesitter to treesitter's bug report, so hopefully something changes.
