### ISSUE TITLE
Add toggle_floaterm command

### ISSUE THREAD

**Issue by vpeopleonatank** [glepnir/lspsaga.nvim#86]
I need function like `:FloatermToggle` in `vim-floaterm` because when I use lazygit in floaterm and push repo to github, i can use `:FloatermToggle` to hide lazygit in floaterm. Is it easy to implement or will make `lspsaga.vim` bloated ?

**Comment by glepnir** [comment]
lspsag floaterm is just to show how to use lspsaga window api to build some functions.It seems that it is not difficult to implement it, just hide it and wake up the window interface again. PR Welcome.

**Comment by vpeopleonatank** [comment]
After trying to implement it, I can't still do. I 'm new to neovim api and plugin development. Can you suggest me some api or ways such as how to check if Float terminal opened, if yes then how to re-open it and hide it when it 's opened?

**Comment by elianiva** [comment]
```lua
vim.g.is_saga_term_open = false
function FloatermToggle()
  if vim.g.is_saga_term_open then
    require("lspsaga.floaterm").close_float_terminal()
    vim.g.is_saga_term_open = false
  else
    require("lspsaga.floaterm").open_float_terminal()
    vim.g.is_saga_term_open = true
  end
end
```

try this, bind it to something

**Comment by vpeopleonatank** [comment]
This doesn't meet my need. What I want is "hiding" terminal instance and reopen it. Anw, thanks for your help.

**Comment by nkhlmn** [comment]
@glepnir I may be up for putting together a PR to implement this From what I've looked into so far I think it would involve the following:

- Adding a config option that allows for creating persist-able terminal windows
- Modifying some window.lua functions to accept some options that will allow for creating non-scratch buffers (and probably also set `buflisted`?)
- Updating floaterm.lua functions to handle the new config option

Would also be useful to allow for persisting multiple terminals and being able to toggle them selectively. Let me know what you think. Thanks!
