### ISSUE TITLE
Optimizing colors via themes

### ISSUE THREAD

**Issue by leaxoy** [glepnir/lspsaga.nvim#861]
Some theme support both light and dark mode.

In dark mode, lspsaga looks well.
<img width="691" alt="image" src="https://user-images.githubusercontent.com/8556349/218238156-9e916709-b68c-4696-9fa4-9e6b79648425.png">

But in light mode, lspsaga's some colors are hard to distinguish
<img width="735" alt="image" src="https://user-images.githubusercontent.com/8556349/218238154-77008782-2cd4-42e2-bdb0-c8d030154151.png">

So using theme colors may be a better choice.

**Comment by glepnir** [comment]
```lua

local kinds = require('lspsaga.kind').get_kind()
for _, kind in pairs(kinds) do
  api.nvim_set_hl(0, 'LspsagaWinbar' .. kind[1], { fg = you colorscheme color})
end
```

**Comment by nullchilly** [comment]
@leaxoy https://github.com/catppuccin/nvim/blob/4606b68140ee7003d32892fc297bce66e2348df2/lua/catppuccin/groups/integrations/lsp_saga.lua#L32

Pretty sure I "fixed" it?
