### ISSUE TITLE
Lspsaga error hover

### ISSUE THREAD

**Issue by bobbyrahmanda13** [glepnir/lspsaga.nvim#863]
![image](https://user-images.githubusercontent.com/69358107/218268818-4c08ced2-2907-4239-b36e-08d26edf11eb.png)

why the error even though previously it was safe

**Comment by Hamm-J** [comment]
getting same bug

**Comment by glepnir** [comment]
don't know how you config it please use config in doc.

**Comment by glepnir** [comment]
maybe you need install markdown parser in treesitter

**Comment by Hamm-J** [comment]
I have the config from the README and have every treesitter parser installed. This bug happened when I updated lspsaga this morning. I haven't updated it in a few days. Still having this bug.

**Comment by glepnir** [comment]
I can't get any useful information from this error it means you have some error before .and it works fine for me always.

![image](https://user-images.githubusercontent.com/41671631/218288032-57a8085a-e2c9-4c37-8583-4b3dd84e29f0.png)

**Comment by Hamm-J** [comment]
My apologies. I reinstalled my tree-sitter and then reinstalled all of my parsers and it worked. Thanks for the help and for this amazing plugin :)

**Comment by glepnir** [comment]
no need apologies :)

**Comment by bobbyrahmanda13** [comment]
> My apologies. I reinstalled my tree-sitter and then reinstalled all of my parsers and it worked. Thanks for the help and for this amazing plugin :)

great, this method works, Thanks
![image](https://user-images.githubusercontent.com/69358107/218290269-408b2124-4d44-4d5d-a30a-85abad533c71.png)
