### ISSUE TITLE
Bufload error when calling Lspsaga goto_definition

### ISSUE THREAD

**Issue by oieeaaaa** [glepnir/lspsaga.nvim#866]
### Describe the bug

![Screenshot 2023-02-13 125625](https://user-images.githubusercontent.com/37941956/218374009-c764ed80-8f4a-408f-8438-e68113a152b6.png)

Upon observation the above error occurs only when it's the first time jumping on that definition... The error would suddenly go away after i call `:Lspsaga goto_definition` the second time.

### Steps to reproduce

Run `:Lspsaga goto_definition()`

### Expected behavior

Should just jump straight to the definition

### Neovim version (nvim -v)

0.9.0

### lspsaga commit

n/a

### Terminal name/version

n/a

**Comment by glepnir** [comment]
sorry i revert this commit .. can you provide a  reproduce step?

**Comment by itzcodex24** [comment]
<img width="1440" alt="image" src="https://github.com/nvimdev/lspsaga.nvim/assets/70026038/7724c139-a7b7-423e-a152-e217e58f35b6">

I am experiencing a similar issue. Is there a fix for this?

**Comment by glepnir** [comment]
not same. looks like caused by a highlight match pair plugin ?
