### ISSUE TITLE
Missing colon in packer install config

### ISSUE THREAD

**Issue by Batleram** [glepnir/lspsaga.nvim#868]
### Describe the bug

There is a missing colon after the line

 `{"nvim-tree/nvim-web-devicons"}` 

This  causes neovim to be unable to parse the file

### Steps to reproduce

Copy the config into the Packer plugins file

### Expected behavior

Should not throw errors wen opening vim

### Neovim version (nvim -v)

0.8

### lspsaga commit

e6ec4991246a950882b70ab37dcde100e1457668

### Terminal name/version

kitty

**Comment by glepnir** [comment]
fixed
