### ISSUE TITLE
Module 'gitsigns' not found

### ISSUE THREAD

**Issue by thescripted** [glepnir/lspsaga.nvim#871]
### Describe the bug

Running latest version:

<img width="1183" alt="image" src="https://user-images.githubusercontent.com/58235869/218593265-cecaf7ab-87d1-4965-9b9b-53ce5681725c.png">

Installing this: https://github.com/lewis6991/gitsigns.nvim resolved my problem, but I think that needs to be called out

### Steps to reproduce

Install lspsaga.

Run `:Lspsaga code_action`

### Expected behavior

Expect code actions to work with default configurations

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

7a25446

### Terminal name/version

xterm 3.1

**Comment by glepnir** [comment]
codeaction.extend_gitsigns to false

**Comment by thescripted** [comment]
Can we make it false by default?

**Comment by glepnir** [comment]
do we need set it default to false? gitsigns is more popular git plugin in neovim

**Comment by glepnir** [comment]
it's better to false for people not use gitsigns

**Comment by thescripted** [comment]
I prefer false, one less dep to worry about.

If true, it should be required just like `nvim-web-devicons`

**Comment by glepnir** [comment]
there has pcall .so wired why it though an error
