### ISSUE TITLE
Visual mode mappings cause issues with rename

### ISSUE THREAD

**Issue by joeveiga** [glepnir/lspsaga.nvim#872]
Visual mappings (e.g. `s` for hop.nvim) causes issues when `config.rename.in_select` is enabled. In my example, trying to rename a symbol with anything starting with `s...` will conflict with my visual mode mapping for hop.

I do like the select mode functionality for the rename input, though, for easy replace. I wonder if we could disable visual mode mappings for the rename window? 

## Steps to reproduce

1. Define a visual mode mapping. In the example I have `vim.keymap.set({ 'n', 'v' }, 's', '<cmd>HopChar2<cr>')` defined.
2. Call `:Lspsaga rename` and, when the rename window pops up, try to type a new name starting with the letter `s`.

### Actual result
V mode mapping gets activated.

![Kapture 2023-02-13 at 21 48 19](https://user-images.githubusercontent.com/19226858/218626370-2449af16-e923-45b0-a27b-b554ede5e416.gif)

### Expected result
I'm able to rename without V mode mappings getting in the way. I'm not sure if could do something like `:vmapclear` just for the rename window 🤷

**Comment by glepnir** [comment]
provide reproduce step thx

**Comment by joeveiga** [comment]
> provide reproduce step thx

Edited. Sorry about that, was on the phone app and couldn't create a proper issue.

**Comment by joeveiga** [comment]
@glepnir I could just change my mapping mode from 'v' to 'x' to exclude select mode. I'll close this since it was an issue on my end. Thanks!
