### ISSUE TITLE
Can install with vim-plug ?

### ISSUE THREAD

**Issue by BillyLiou** [glepnir/lspsaga.nvim#874]
**Is your feature request related to a problem? Please describe.**

1. I see the installation about lazy and Packer , can this version installed by vim-plug?

2. I use the old way lspsaga.init_lsp_saga()
but it deprecated in v0.2.3. So, I want to realize how to config,thanks.

**Comment by BillyLiou** [comment]
Sorry I find the doc, it works with vim-plug,so I close this issue.

**Comment by kaspergrubbe** [comment]
If anyone else comes looking, the change is going from:

```vim
lua <<EOF
  local saga = require 'lspsaga'
  saga.init_lsp_saga {
    -- custom
  }
EOF
```

to this:

```vim
lua <<EOF
  require('lspsaga').setup({})
EOF
```
