### ISSUE TITLE
Github Sponsor

### ISSUE THREAD

**Issue by zsmatrix62** [glepnir/lspsaga.nvim#875]
Please start GitHub sponsor in order to get more sponsors .. 🎉 I don't have a PayPal account ...hmm

**Comment by glepnir** [comment]
sry github sponsor does not support China.

**Comment by scottming** [comment]
Hi, Raphael, To be honest, I really appreciate your work. lspsaga should now be my most inseparable lsp tool.

I just tried to buy you a coffee with paypal, but I couldn't finish the payment.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/12830256/219828003-5dcdd668-33a3-4a99-ac7d-a9b6706cc630.png">


My personal suggestion is that if the github sponsor is not convenient, you can provide bitcoin address or Alipay code, etc.

**Comment by glepnir** [comment]
I will try to register the github sponsor if i can.

paypal and wechat https://github.com/glepnir/nvim/issues/61

**Comment by glepnir** [comment]
my github sponsor had created thanks
