### ISSUE TITLE
CursorHold show_cursor_diagnostics keeps the window open

### ISSUE THREAD

**Issue by phantomion** [glepnir/lspsaga.nvim#876]
### Describe the bug

After updating after quite some time, using an autocommand for cursor diagnostics keeps the diagnostic window open even after moving to another line.

### Steps to reproduce

        vim.api.nvim_create_autocmd("CursorHold", {
            group = general,
            pattern = "*",
            command = 'Lspsaga show_cursor_diagnostics ++unfocus',
        })

On lsp-setup config

### Expected behavior

Moving to another line should close the floating window.

### Neovim version (nvim -v)

0.8.3 and nightly

### lspsaga commit

397201abffa681419a610ecbfd5d3c0fed45d20a

### Terminal name/version

alacritty

**Comment by glepnir** [comment]
can't reproduce with min config

![min](https://user-images.githubusercontent.com/41671631/218994968-4e1d2e70-b876-4f28-9d40-36fb23bdca2f.gif)

**Comment by protiumx** [comment]
I have the same issue
![image](https://user-images.githubusercontent.com/43855513/219509102-b8dc94fe-788f-4b67-ab65-92cacb7d7c2d.png)
It's hard to tell what triggers it, so far I can confirm that if the float is open and I switch to another window it will stay there, and any new float also stays on screen.

My config for the float
```
  vim.cmd [[autocmd CursorHold * Lspsaga show_cursor_diagnostics ++unfocus ]]
```
Terminal: WezTerm
NVIM v0.8.3
Installed via packer: 
```
     use {
        'glepnir/lspsaga.nvim',
        branch = 'main',
      }
```

**Comment by glepnir** [comment]
have a split win right?

**Comment by phantomion** [comment]
In my case I had in the on_attach function in the lsp-setup. When I moved it outside of the function it worked fine.

**Comment by glepnir** [comment]
no need in attach. if not lsp it does not popup.
