### ISSUE TITLE
Small colored box appearing at top-level of file

### ISSUE THREAD

**Issue by avegancafe** [glepnir/lspsaga.nvim#879]
### Describe the bug

Hi, it appears in my current configuration that there's a small little box with a different background color at the end of the winbar, does anyone know how to either disable this or what highlight group it is or something? I'd imagine it's not supposed to be there

<img width="592" alt="image" src="https://user-images.githubusercontent.com/2652762/219705730-15f2da30-8695-4175-af8a-ea95fec8cc25.png">

### Steps to reproduce

- Install lspsaga
- enable symbols in winbar
- navigate to file that has lsp support
- go to top level of file so no symbol is highlighted after the file name
- see colored box thing in the winbar

### Expected behavior

there should be no colored box after the filename 

### Neovim version (nvim -v)

NVIM v0.8.3

### lspsaga commit

397201a

### Terminal name/version

kitty

**Comment by avegancafe** [comment]
For some more context here, I was able to fix this by finishing the winbar string and trying to apply a highlight group that's the same as my editor background https://github.com/avegancafe/lspsaga.nvim/commit/451101aee3f056bc2feefd4357cc907231ac60be

**Comment by glepnir** [comment]
should be fixed.

**Comment by avegancafe** [comment]
Hmm I just pulled the latest update and still seems to be there. Does it make a difference that I'm rendering it in my statusline instead of the winbar? Let me try rendering normally in the winbar and seeing if it's also a problem up there for me. Here's my config, if it helps at all https://github.com/avegancafe/Juliet/blob/main/nvim/lua/plugins.lua#L50-L58

<img width="553" alt="image" src="https://user-images.githubusercontent.com/2652762/220169263-cfeb557b-8917-471f-ae6d-30b27065552f.png">

**Comment by avegancafe** [comment]
Interesting, yeah it's specifically a problem in my statusline. This is I guess not a bug in this project but maybe in lualine, idk it's unclear. Maybe the statusline and winbar render text differently or trim extra spaces or something. In any case, I updated my config [here](https://github.com/avegancafe/Juliet/blob/main/nvim/lua/plugins.lua#L460) to accommodate for this in the statusline since it's non-standard. I'll open an MR updating the documentation to suggest doing this as well if people are using this method as well
