### ISSUE TITLE
peek_definition bug: non-float cannot have 'row'

### ISSUE THREAD

**Issue by scottming** [glepnir/lspsaga.nvim#880]
### Describe the bug

After `peek_definition`, then go to another definition(by vim.lsp.buf.definition()) in `peek_definition` window, then use `ctrl+o` back, then will encountered this bug: we cannot use `q` to close the window; we can only use `:q` to close the window, and use `peek_definition` again, it will show me this error:

```
Error executing vim.schedule lua callback: ...ocal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/window.lua:251: non-float cannot hav
e 'row'
stack traceback:
        [C]: in function 'nvim_open_win'
        ...ocal/share/nvim/lazy/lspsaga.nvim/lua/lspsaga/window.lua:251: in function 'create_win_with_border'
        .../share/nvim/lazy/lspsaga.nvim/lua/lspsaga/definition.lua:243: in function 'callback'
        ...r/neovim/HEAD-371a74e/share/nvim/runtime/lua/vim/lsp.lua:2010: in function 'handler'
        ...r/neovim/HEAD-371a74e/share/nvim/runtime/lua/vim/lsp.lua:1390: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```
I think the main problem should be due to the use of `ctrl + o`

### Steps to reproduce

`

### Expected behavior

1. can use `q` close the definition window after `ctrl+o`
2. can continue use `peek_definition`

### Neovim version (nvim -v)

nightly

### lspsaga commit

cb65c10254d53ac4790b5499bcb267d5905e0411

### Terminal name/version

alacritty

**Comment by glepnir** [comment]
this way will break  the data in definition window. you can do peek again in this window.
