### ISSUE TITLE
'Width' key must be a positive Integer

### ISSUE THREAD

**Issue by AQuoc98** [glepnir/lspsaga.nvim#882]
### Describe the bug

When executing Lspsaga lsp_finder over 3 times (in my case) . The error with "'width' key must be a positive Integer" occurs.

Additional Info: 
- I met error when working with reactjs project 

### Steps to reproduce

1. Open multiple file on a window (float window)
2. Use Lspsaga lsp_finder
3. Get a error about nvim_open_win()

### Expected behavior

the lsp_finder will be used over 3 times 

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

no commit

### Terminal name/version

iterm 2

**Comment by glepnir** [comment]
can't reproduce.

**Comment by AQuoc98** [comment]
https://user-images.githubusercontent.com/41674339/219850632-d3f712d2-2553-44ec-83a0-72d2b1e2fedc.mov

Hi @glepnir, this is video demo for the bug. Please help me review it. Thank you.

**Comment by glepnir** [comment]
you should tell me which commit you used.

**Comment by AQuoc98** [comment]
Hi, How to find the commit which used ?

This is my config for Lspsaga. Sorry for the inconvenience.

<img width="941" alt="image" src="https://user-images.githubusercontent.com/41674339/219852052-2cfe6f0d-c3eb-423e-8ff8-4f52f1806262.png">

**Comment by glepnir** [comment]
I think you need  try to update it first.

**Comment by AQuoc98** [comment]
Can you give me more information about the way to update. I have update it with Packer, but all my project by React JS still meet this error.

**Comment by AQuoc98** [comment]
Hi @glepnir

After testing , I recognize the root cause of the error that when I open lsp_finder window on a small window, it will show this error  'Width' key must be a positive Integer'.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/41674339/219865564-6cc655a4-4d00-4aeb-9d33-b2dd87db405a.png">
