### ISSUE TITLE
lspsaga的winbar和noice.nvim的lsp-process消息冲突

### ISSUE THREAD

**Issue by JuanZoran** [glepnir/lspsaga.nvim#883]
### Describe the bug

使用lspsaga的winbar, 和lualine使用, 会造成lsp-process消息异常, 我尝试向noice.nvim询问解决, 貌似是lspsaga造成的冲突...

使用`nvim-navic`貌似一切正常
[相关noice.nvim的讨论](https://github.com/folke/noice.nvim/discussions/334)

### Steps to reproduce

使用lua_ls, lualine, lspsaga的winbar组件, 打开相对大一点的项目时(lsp加载的时间相对久一点)

### Expected behavior

不要出现奇怪的信号

### Neovim version (nvim -v)

neovim-nightly

### lspsaga commit

latest

### Terminal name/version

kitty release

**Comment by glepnir** [comment]
我不用你说的那几个插件。 对于我自己的异步状态栏 progress消息并不频繁显示。我不知道lualine是怎么实现的。neovim/diagnostic.lua 2000多行不知道够不够你说的大。 progress消息我用spinner替换了。 只有开始有消息。

![test](https://user-images.githubusercontent.com/41671631/219871098-ecbdaa4a-2b24-4231-ac93-1cb0312281fb.gif)

**Comment by JuanZoran** [comment]
好吧, 我看看能不能自己解决吧,感谢
