### ISSUE TITLE
show_buf_diagnostics unable to focus floating window

### ISSUE THREAD

**Issue by edward-s** [glepnir/lspsaga.nvim#885]
### Describe the bug

Flloating window created by `show_buf_diagnostic` should be focusable

### Steps to reproduce

:Lspsaga show_buf_diagnostics
floating window appears
unable to focus the window with `<C-w>w` or mouse click

### Expected behavior

`<C-w>w` does not focus on floating window for `show_buf_diagnostics`, it does work for hover_doc

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

latest (133bf4b06f109da0cae9ab61a6dd8e29e62c90d3)

### Terminal name/version

iTerm 2

**Comment by glepnir** [comment]
had fixed in #867

**Comment by edward-s** [comment]
you are amazing
