### ISSUE TITLE
Error on first diagnostic check after launch

### ISSUE THREAD

**Issue by tannerellen** [glepnir/lspsaga.nvim#886]
After the latest update to 0.2.7 I get an error the first time LSP saga evaluates a diagnostic issue. Once I dismiss the message everything works as expected and the error will no longer show until I quit neovim and relaunch. This does not happen in older versions of lspsaga.

Neovim 0.8.3 on Ubunutu.

The way I can reproduce this every time is launch neovim, then open a file and type something that is not allowed syntax. For example “$” in a lua file. The error will show immediately. As I said before, once the error is dismissed it will no longer show until neovim is relaunched.

![Screenshot 2023-02-19 at 1 05 27 PM](https://user-images.githubusercontent.com/930897/219975323-f152541f-0860-4b7b-bdfb-3e3838ee89f8.png)

**Comment by gonviegas** [comment]
Yes. I'm getting the same error and it also gives me the same visual glitches that you're having near the top right corner.

**Comment by tannerellen** [comment]
> Yes. I'm getting the same error and it also gives me the same visual glitches that you're having near the top right corner.

That's my column width indicator in my screenshot at the top right. So it's expected to be there. Haven't dug any further if I'm experiencing more issues than the error message.

**Comment by brendencallahan** [comment]
![image](https://user-images.githubusercontent.com/47364240/219980085-c718b51e-af8d-4f6d-a559-cde5e406f8ed.png)

Along with that error, I am getting these visual glitches. I believe that may be what @gonviegas was referring to.
(You would expect this text to be near the error not in the upper right hand corner)

**Comment by noisyBrain** [comment]
I'm getting the same error as well

**Comment by brendencallahan** [comment]
I am able to consistently reproduce this by opening a .lua file, waiting for the lus_lsp to finish loading, and entering any character on a new line i.e. "t". 

![image](https://user-images.githubusercontent.com/47364240/219980474-3d1f1545-20d9-4b7a-8478-2af8b8a654a8.png)

**Comment by gonviegas** [comment]
> ![image](https://user-images.githubusercontent.com/47364240/219980085-c718b51e-af8d-4f6d-a559-cde5e406f8ed.png)
> 
> Along with that error, I am getting these visual glitches. I believe that may be what @gonviegas was referring to. (You would expect this text to be near the error not in the upper right hand corner)

After I get those glitches, it leaves a visual trail, a column with different background color and characters are not shown. It's like the highlight was deleted for that particular spot.

**Comment by itsjoeoui** [comment]
second time this week lspsaga breaks after pulling down new updates 😢

**Comment by brendencallahan** [comment]
@itsjoeoui if you are feeling frustrated by this it is not too difficult to solve. You can either use a package manager like packer to take 'snapshots' of the current plugin's commits or do it manually. In fact, if you would like to solve this issue right now you can go to `~/.local/share/nvim/site/pack/packer/start/lspsaga.nvim` and just `git checkout commithash`. I know this isn't ideal but it's just the cost of using plugins.

**Comment by glepnir** [comment]
first why do not read doc and update pr? set  diagnostic.on_insert to false before I fixed

**Comment by itsjoeoui** [comment]
> @itsjoeoui if you are feeling frustrated by this it is not too difficult to solve. You can either use a package manager like packer to take 'snapshots' of the current plugin's commits or do it manually. In fact, if you would like to remedy this issue right now you can go to `~/.local/share/nvim/site/pack/packer/start/lspsaga.nvim` ,or wherever you have lspsaga installed, and just `git checkout commithash`. I know this isn't ideal but it's just the cost of using plugins.

Good idea, thanks!

**Comment by brendencallahan** [comment]
> first why do not read doc and update pr? set  diagnostic.on_insert to false before I fixed 

Ah, my apologies. I see that now. Thank you.

**Comment by brendencallahan** [comment]
So it appears you need to either disable diagnostic.on_insert or set DiagnosticInsertDisable. Read more about it from pull request #867

**Comment by noisyBrain** [comment]
> first why do not read doc and update pr? set diagnostic.on_insert to false before I fixed

I tried to solve it by myself, but I guess I'm too noob for that now. 
When you've fixed how could I figure out how did you solve it? Reading commit diffs maybe?
