### ISSUE TITLE
peek definition won't work after upgrade.

### ISSUE THREAD

**Issue by scottming** [glepnir/lspsaga.nvim#887]
### Describe the bug

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/12830256/219987158-ed96f86b-67cf-432b-9012-75bf21a80c06.png">

### Steps to reproduce

`Lspsaga peek_type_definition` or `Lspsaga peek_definition`

### Expected behavior

`

### Neovim version (nvim -v)

v0.9.0-dev-987+g371a74e4e-dirty

### lspsaga commit

b5ff9a3d05dab914df2bc6284179e3a5b9b0c7c4

### Terminal name/version

alacritty

**Comment by horaoen** [comment]
I have the same error

**Comment by pablolagreca** [comment]
Same here

**Comment by zsmatrix62** [comment]
another error on hover:

```
Error executing vim.schedule lua callback: .../site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/hover.lua:102: E474: Invalid argument
stack traceback:
        [C]: in function 'nvim_set_option_value'
        .../site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/hover.lua:102: in function 'open_floating_preview'
        .../site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/hover.lua:208: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1389: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by farzadmf** [comment]
Same here

**Comment by LoneExile** [comment]
My workaround solution

```lua
{
    'glepnir/lspsaga.nvim',
    commit = '707c9399b1cbe063c6942604209674edf1b3cf2e',
}
```

**Comment by scottming** [comment]
I think we should write some tests for lspsaga to protect some important features from being broken by changes, I know the author is busy, but others may not know much about the important behavior inside lspsaga, so I hope someone can list the important behavior inside and then the community can add tests.

**Comment by zsmatrix62** [comment]
> I think we should write some tests for lspsaga to protect some important features from being broken by changes, I know the author is busy, but others may not know much about the important behavior inside lspsaga, so I hope someone can list the important behavior inside and then the community can add tests.

True, I've encountered several times of breaking changes i think it's lack of tests before releasing .. i have to fix the commit hash to prevent my config being panic during daily `PackerSync` 😢

**Comment by kidp2h** [comment]
same issue :(

**Comment by dev-737** [comment]
> another error on hover:
> 
> ```
> Error executing vim.schedule lua callback: .../site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/hover.lua:102: E474: Invalid argument
> stack traceback:
>         [C]: in function 'nvim_set_option_value'
>         .../site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/hover.lua:102: in function 'open_floating_preview'
>         .../site/pack/packer/opt/lspsaga.nvim/lua/lspsaga/hover.lua:208: in function 'handler'
>         /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1389: in function ''
>         vim/_editor.lua: in function <vim/_editor.lua:0>
> ```

Still facing this issue now.

**Comment by glepnir** [comment]
fixed .because that option not work on 0.8
