### ISSUE TITLE
This bug is back 

### ISSUE THREAD

**Issue by scottming** [glepnir/lspsaga.nvim#888]
### Describe the bug

#880 

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/12830256/220032128-efce31de-5547-4047-b6c1-e195a25471ca.png">

I noticed that you have a revert: https://github.com/glepnir/lspsaga.nvim/commit/af4e524bcaa226f22802619aef86adf850c81b93.

However, the previous solution of revert does have some problems. For example, `q` can only close the first level of windows; the rest can only be closed with `:q`

### Steps to reproduce

same as #880

### Expected behavior

`

### Neovim version (nvim -v)

nightly

### lspsaga commit

574f21d92f297a022de86333f0f59ab8974fa679

### Terminal name/version

alacritty

**Comment by glepnir** [comment]
`peek_defintion` then do it agin in `peek_defintion` now you have two definition window `press q` on each not closed ?

**Comment by scottming** [comment]
> 
peek_defintion then do it agin in peek_defintion now you have two definition window press q on each not closed ?

for 2f0dfe5834b41ff790eb1e00daf201afced0ed5a, when peek_definition, and peek_definition, then ctrl o, then I can't use q to close the second window.

for 574f21d92f297a022de86333f0f59ab8974fa679 , if I peek_definition, and peek_definition, then ctrl o, I can't use q to close any window, and I can't use peek_defnition any more.

**Comment by glepnir** [comment]
like i said you can't use these wincmd in `peek_definition` window it break the store data.

**Comment by scottming** [comment]
Is there any way to force me to avoid wincmd in `peek_definition` window, instead of just remember this rule.

**Comment by glepnir** [comment]
just `<C-w>w`  to select the window which create by `peek_definition`.

**Comment by glepnir** [comment]
you can do `peek_defintion` recusive . peek 1 --> peek 2 --> peek3  it' allowed. if you want go back `<C-w>w` select .or we can provide a better navagition for multiple peek windows. then support quick select.

**Comment by scottming** [comment]
Ctrl-o has not only the function to navigate between windows but also the function to navigate in the same window.

Not only this use case, but also a practical use case.

For example: I want to use `peek_definition` to look at the source code of a place, and then I find out that this place calls a different function, I use go to definition to navagite the new function, and then I use ctrl-o to go back.

So it's really very hard to disable `ctrl-o` completely.

**Comment by scottming** [comment]
Of course our problem occurs in the case of multiple peek_definition windows using ctrl-o

**Comment by glepnir** [comment]
maybe can create a stack for the first place that you open peek window

**Comment by scottming** [comment]
Can you give me more details about the `stack`? and how to do that?

**Comment by glepnir** [comment]
nope. i think i can create a back map then you can bind this to <C-o>

**Comment by scottming** [comment]
hello, if I bind these keys:

```
	definition = {
		back = "<C-o>",
    next = 'gd',
	},

```

I can no longer use these two keys in the normal window after opening a definition window and using these keys.

**Comment by glepnir** [comment]
close all definition window the key will restore

**Comment by scottming** [comment]
yes, I make sure I already have, but still not works.

**Comment by scottming** [comment]
On this issue, I have found a simpler solution.

That is, when we can't close the peek_definition window with `q`, we can use `ctrl-i` to move on and until we can use `q` to close it that way, as long as we use `q` instead of `:q`, it won't cause the non-float window **error**.

I'm very sorry to make you take the time to support the stack, but you can always revert this commit if you want to reduce the code complexity.

**Comment by glepnir** [comment]
I have a new idea to refactor
