### ISSUE TITLE
Customise the ui.kind

### ISSUE THREAD

**Issue by scottming** [glepnir/lspsaga.nvim#889]
Sorry to bother you again, I try to customize the ui.kind. First, I get the kind by `lua = require('lspsaga.lspkind').get_kind()`:

<img width="806" alt="image" src="https://user-images.githubusercontent.com/12830256/220095462-e398498b-9b79-4627-b474-73920606af62.png">
 
and I try to set the ui.kind by:

```
local status_ok, saga = pcall(require, "lspsaga")
if not status_ok then
	return
end

-- change the lsp symbol kind

-- use default config
saga.setup({
	ui = {
		kind = {
			{ [302] = { "Folder", " ", "#f7bb3b" } },
		},
	},
})
```

after save and open again, it gives me an error:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/12830256/220095792-c148e3fc-8aca-436f-b9dd-53394539aba0.png">

Did I do something wrong?

**Comment by glepnir** [comment]
highlight group not color  hex code now.

**Comment by scottming** [comment]
I get the same error if I use a string:

```
	ui = {
		kind = {
			{ [302] = { "Folder", " ", "@parameter" } },
		},
	},

```

**Comment by glepnir** [comment]
```lua
kind = {  ['Folder'] = {icon ,group} }
```

**Comment by scottming** [comment]
Thanks very much, it works.
