### ISSUE TITLE
Code action exec doesn't work

### ISSUE THREAD

**Issue by gutyina70** [glepnir/lspsaga.nvim#890]
### Describe the bug

I get the error *no action number choice* when selecting a code action item with `<cr>`. Selecting it with numbers work.

Looks like the regex is failing at https://github.com/glepnir/lspsaga.nvim/blob/5922fc31f0d630d54dd90ef49cbf15d840442d13/lua/lspsaga/codeaction.lua#L261.

### Steps to reproduce

Reproducible with minimal config:
```
require 'lspsaga'.setup {}
```

Do `:Lspsaga code_action` and press `<cr>` after the code action loaded. You will see a warning message: *[Lspsaga] no action number choice*. And the code action won't be executed.

### Expected behavior

The code action should be executed and no warning should be shown.

### Neovim version (nvim -v)

v0.9.0-dev-874+g5c4b503d3

### lspsaga commit

5922fc3

### Terminal name/version

st 0.8.5

**Comment by gutyina70** [comment]
This bug is caused by a UI redesign: a few days ago a code action row looked like this for example: ` 1  Invert if` and now it looks like: `[1] Invert if`. The regex is expecting a space after the number, but now there are square brackets instead.

**Comment by bigduu** [comment]
The fix PR, please review
https://github.com/glepnir/lspsaga.nvim/pull/891

**Comment by dzintars** [comment]
Same. PR patch seams to fix it for me.

**Comment by glepnir** [comment]
merged
