### ISSUE TITLE
Is there a way to make finder float window border shadows consistent?

### ISSUE THREAD

**Issue by scottming** [glepnir/lspsaga.nvim#893]
**Is your feature request related to a problem? Please describe.**

Is there a way to make the top and bottom border shadows consistent with the left and right?

<img width="778" alt="image" src="https://user-images.githubusercontent.com/12830256/220234716-59243b5f-0d36-4116-a50e-c44d103cc15d.png">

Looking at the three circled areas, you will see that the three shaded areas are not the same size.

**Describe the solution you'd like**

Make them consistent with the blue area.

**Comment by glepnir** [comment]
`ui.border` to `solid` or set the highlight of finder border and finder preview border.

**Comment by scottming** [comment]
I actually tried this configuration, but their widths still had some inconsistencies

<img width="714" alt="image" src="https://user-images.githubusercontent.com/12830256/220282512-7d08eaf0-0900-4710-a4db-1d61c4cc7cad.png">

**Comment by glepnir** [comment]
so the problem should be neovim side. and you can set the highlight finder normal and preview normal to same .

**Comment by scottming** [comment]
By searching the code base, I could only find these:

```lua
  local content_opts = {
    contents = {},
    buftype = 'nofile',
    border = 'solid',
    highlight = {
      normal = 'finderNormal',
      border = 'finderBorder',
    },
    enter = false,
  }
```

and 

```lua
    highlight = {
      border = 'finderBorder',
      normal = 'finderNormal',
    },
```

I still do not know how to do the config. Can you give me more details?

**Comment by glepnir** [comment]
oh maybe i think i know where is the problem

**Comment by glepnir** [comment]
can you try this on cmd `hi FinderBorder guibg=NONE`

**Comment by scottming** [comment]
Yes, I tried, but that way, the white line is too bright; I wonder if there is a way to keep only the purple line without shadows.

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/12830256/220296273-913426a9-496c-4532-bc6b-dc1213126400.png">

**Comment by glepnir** [comment]
idk what you mean you can set the border fg to every color you want bg same as your normal background color .

![image](https://user-images.githubusercontent.com/41671631/220298041-75577264-5a21-457d-a571-2d319ca8162c.png)

**Comment by scottming** [comment]
Yes, that's it. thank you.

**Comment by scottming** [comment]
> so it's already to none ? and this file is finder.lua not definition.lua. if you want test try change fg

In the interest of not being confusing, I decided to keep the questions here.

I already changed the FinderBorder and FinderPreviewBorder by:

```lua
vim.cmd('highlight! FinderBorder guifg=#9F70A9 guibg=none')
vim.cmd('highlight! FinderPreviewBorder guifg=#9F70A9 guibg=none')
```
It works, but I want to change the definition border too. and I use `vim.cmd('highlight! DefinitionBorder guifg=#9F70A9 guibg=none')`, but it doesn't work.

**Comment by glepnir** [comment]
update to main branch should work
