### ISSUE TITLE
Inconsistent Spacing in Diagnostic Window

### ISSUE THREAD

**Issue by AlexvZyl** [glepnir/lspsaga.nvim#896]
### Describe the bug

I am unsure if this is an issue with the kitty terminal or with lspsaga.  I suspect it is with the latter.

Some of the glyphs from Nerd Fonts requires two characters to be displayed correctly.  However, kitty handles this differently.  When there is only one character available, kitty makes this glyph smaller.  When two are available, it is the regular size.

It *seems* like lspsaga is inconsistent with its spacing, leading to this happening (notice the arrows and warning signs):
![image](https://user-images.githubusercontent.com/81622310/220279113-866baca9-e1db-4ba6-9a30-0c5746a733ba.png)

### Steps to reproduce

- Run neovim in kitty.
- Show any diagnostic.

### Expected behavior

Each glyph should be the same size.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-838+gc9ac4e4877 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### lspsaga commit

17adfef

### Terminal name/version

kitty 0.27.1

**Comment by glepnir** [comment]
can you try it on other terminal ? i know some terminal evalutor use two space make icon big. but some icon code not support by some terminals. i am not usre. for my sign it works fine. so idk.

**Comment by glepnir** [comment]
damn really ugly ui . i can't accept it ... i need do some change on line/cursor diagnostic ui

**Comment by glepnir** [comment]
i will implement  a new ui for them tomorrow.

**Comment by glepnir** [comment]
currently show window and jump window still have this problem?

**Comment by AlexvZyl** [comment]
As far as I can tell, this is very specific to the kitty terminal.  Kitty renders glyphs based on the available white space.  So when windows are set to be transparent, the glyph behind the window can be seen and the two-character wide glyph only has one character to be rendered, according to kitty.  This issue has nothing to do with lsp-saga.  I just wanted to add the link in case someone came across this issue.

**Comment by glepnir** [comment]
but I wonder how you config transparent use winblend or config background.

**Comment by glepnir** [comment]
another choice wezterm lol..

**Comment by AlexvZyl** [comment]
I will give it a shot!
