### ISSUE TITLE
Break float window highlight

### ISSUE THREAD

**Issue by yehuohan** [glepnir/lspsaga.nvim#897]
I think I have confirmed it's true of the comment here 
https://github.com/glepnir/lspsaga.nvim/blob/17adfefbb1af9afc22576ec22b1a325a9b03e87a/lua/lspsaga/diagnostic.lua#L703.

When on_insert = true, all my other plugins(nvim-cmp, popc, lsp_signature) float window's background are changed.

**Comment by glepnir** [comment]
i just think a new way to do this. will fix.
