### ISSUE TITLE
Option to not overwrite signs

### ISSUE THREAD

**Issue by weilbith** [glepnir/lspsaga.nvim#9]
Hey,
thanks for this great looking plugin. It is really an eye catcher.

I was just about to configure this plugin for my own setup. Unfortunately I must recognize that this is overwriting the diagnostics signs. I do set them somewhere else and I would prefer to not redefine them here via copy-paste or rely on this plugin for setting the signs.
I was already about to come up with my own implementation and open a PR. But I recognized it might be not that easy. So my initial idea was to check if the sign is already defined before setting it here. But as there are default diagnostic sign definitions by NeoVim itself, this does not help.
So the next obvious approach would be to make these configuration options to lspsaga.nvim optional and only set signs if the user explicitly asks the plugin to do so? You don't have optional options yet, that's why I haven't yet just implemented it and open a PR. I would like to ask you first for your opinion to this whole topic and what you think would be the best solution for the problem.

Thanks!

**Comment by glepnir** [comment]
Yes, every configuration option should be optional

**Comment by glepnir** [comment]
Now use `use_saga_diagnostic_sign` to enable or disable. 
To be honest, I am not sure  I understand what you mean. If this option does not solve your problem, please reopen it

**Comment by weilbith** [comment]
Thank you very much! :pray: 
Question out of curiosity: why do you use numbers for toggle options instead of booleans? Wouldn't booleans be more expressive/correct? Also in terms of code readability, as you must not use ` == 1` comparison, but just have the option variable, which makes the code just read like `if use_sage_diagnostic_sign then do_something...`. But just as a side note. Sorry for bothering you. I'm very thankful for all your quick adjustments! :hugs:
