### ISSUE TITLE
Code Action not working when multiple LSP are attached

### ISSUE THREAD

**Issue by lucax88x** [glepnir/lspsaga.nvim#90]
### Description
The default LSP handler works fine.

the lspsaga one and also telescope do not work for the same error.

**Expected Behavior**
I expect to see a list of actions

**Actual Behavior**
I get a error

### Details

So, this is what I can see in the LSP logs

[ ERROR ] 2021-02-10T16:35:32+0100 ] ...nt_nvimrAVbQs/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"/home/lucatrazzi/.cache/nvim/lspconfig/efm-langserver/efm-langserver"	"stderr"	'2021/02/10 16:35:32 jsonrpc2 handler: notification "$/cancelRequest" handling error: jsonrpc2: code -32601 message: method not supported: $/cancelRequest\n'

I wonder, if I have more than one LSP attached servers (efm and ts) and both have capability to give code_action, who is gonna answer to the json request? Is plugin gonna request both?

PS: I love how efm is giving capability and then saying "method not supported"
PS2: if I comment efm, it works.

**Comment by zelphir** [comment]
I think we are having the same issue ( #64 ), using `efm` and `tsserver`

**Comment by lucax88x** [comment]
I also created a [reddit post](https://www.reddit.com/r/neovim/comments/lgwg28/q_nvimlsp_and_multiple_lsp), because I don/t think it's a plugin issue.

**Comment by glepnir** [comment]
@lucax88x  need provide a min vim conf

**Comment by glepnir** [comment]
I want to know if remove efm works for you ? I test it in my local works fine because I don't use efm. now I think I need debug it ..

**Comment by lucax88x** [comment]
Yep, if I remove EFM it works fine.

It's enough to have 2 LSP attached to a file, if they both have codeAction, but one fails, we won't see the others LSP actions, easy as that.

That's more a "neovim" issue, I think, but the "default" lsp handler works corretly, so i think it's behaving differently there..

**Comment by lucax88x** [comment]
And to be honest, now with EFM is working, [I forced codeAction to EFM capability wrongly](https://github.com/lucax88x/configs/commit/d4ae5fb2a94790a60ff63567b8764117fc1ac627#diff-b6e2d927f5742315bd4536b70234127d52de694f4035d6e67d4e1cbe59fbc3c3L38)

However, I still think that the issue is a real one, if one LSP fails, we don't get the other LSP actions.

**Comment by glepnir** [comment]
Yes, I think we should make an rpc request for each active lsp client and then merge the results, but I am not sure if multiple lsp clients will return the same result, which will cause some noise

**Comment by lucax88x** [comment]
[https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp.lua#L1083-L1103](they already do it)

So the failure handler maybe should be done in "neovim" level.

Dunno why the default handler works, we should analyze its source code.

**Comment by glepnir** [comment]
can you provide a min vim conf?

**Comment by lucax88x** [comment]
Just add another language server which do not support codeAction, like EFM, install it, force the codeAction like I did 

```lua
init_options = {	       
          codeAction = true	
        }
```

and you should be able to debug

**Comment by lucax88x** [comment]
[check this](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/lsp.lua#L1141)

So me, looks like that buf_request_sync returns a table with client_id.

I assume in this case we have ts and efm client ids, one has errors, the other has results, maybe you should just skip the "error" ones ?

**Comment by glepnir** [comment]
I will test it.
