### ISSUE TITLE
More documentation on "Custom Highlighting"

### ISSUE THREAD

**Issue by etherrorcode404** [glepnir/lspsaga.nvim#900]
Before recent updates, it was really easy to change the colors of  "special groups"
```
vim.cmd([[highlight LspSagaWinbarFileName gui=NONE, guifg=#7c6f64]])
vim.cmd([[highlight LspSagaWinbarFileIcon gui=NONE, guifg=#7c6f64]])
vim.cmd([[highlight LspSagaWinbarSep gui=NONE, guifg=#7c6f64]])
```

After updates, its unclear how to apply these custom highlights using the api.
It would be wiser to add an example.

**Comment by glepnir** [comment]
by using api you can do it in a for loop .

**Comment by glepnir** [comment]
```lua
local res = require('lspsaga.lspkind').get_kind_group()
for i , group in pairs(res) do
  if group:find("FileName') then
     api.nvim_hi_set_hl(0,group , { fg = xxx, bg=xxx})
  end
  if i == #res then
      group is winbarsep
      api.nvim_hi_set_hl(0,group , { fg = xxx, bg=xxx})
  end
end

**Comment by etherrorcode404** [comment]
> ```lua
> local res = require('lspsaga.lspkind').get_kind_group()
> for i , group in pairs(res) do
>   if group:find("FileName') then
>      api.nvim_hi_set_hl(0,group , { fg = xxx, bg=xxx})
>   end
>   if i == #res then
>       group is winbarsep
>       api.nvim_hi_set_hl(0,group , { fg = xxx, bg=xxx})
>   end
> end
> ```

```
local res = require('lspsaga.lspkind').get_kind_group()
for i , group in pairs(res) do
  if group:find("FileName") then
     vim.api.nvim_hi_set_hl(0,group , { fg = "#3c3c3c", bg="#3c3c3c"})
  end
  if i == #res then
      group is winbarsep
      vim.api.nvim_hi_set_hl(0,group , { fg = "#3c3c3c", bg="#3c3c3c"})
  end
end
```

i fixed the " and ' and also the vim.api* but it still throws on error on line-3 
``group is winbarsep`` {Unexpected <exp>}

**Comment by etherrorcode404** [comment]
even then, neovim will throw an error, ```lua:1: attempt to index field 'config' (a nil value``

**Comment by glepnir** [comment]
run this after lspasga.setup . if i == #res is wibarsep no need do find

**Comment by etherrorcode404** [comment]
> run this after lspasga.setup . if i == #res is wibarsep no need do find

nope :/

**Comment by etherrorcode404** [comment]
does it locally work for you?

**Comment by glepnir** [comment]
you have typo it's `nvim_set_hl`

**Comment by etherrorcode404** [comment]
```
local res = pcall(require, 'lspsaga.lspkind').get_kind_group()
for i, group in pairs(res) do
  if group:find("FileName") then
    vim.api.nvim_set_hl(0, group, { fg = "#3c3c3c", bg = "#3c3c3c" })
  end
  -- group is winbarsep
  if group:find("winbarSep") then
    vim.api.nvim_set_hl(0, group, { fg = "#3c3c3c", bg = "#3c3c3c" })
  end
end
```

**Comment by etherrorcode404** [comment]
no typos

**Comment by etherrorcode404** [comment]
can you reproduce ```E5113``` on your side?

**Comment by glepnir** [comment]
```lua
local res = pcall(require, 'lspsaga.lspkind').get_kind_group()
```
I don't think this line is correct ? you do pcall here ? it return two value .

**Comment by etherrorcode404** [comment]
> ```lua
> local res = require('lspsaga.lspkind').get_kind_group()
> ```

yes that was the issue, no more errors but colors are not applying

**Comment by etherrorcode404** [comment]
maybe using ```vim.api``` like in the docs, isn't a good solution

**Comment by glepnir** [comment]
it works fine in min config. i already test it . and new group is `SagaWinbarxxxx` you can also do it like before what you do .

**Comment by glepnir** [comment]
read #867

**Comment by glepnir** [comment]
this is api for some vimer want custom some groups or some colorscheme authors.

**Comment by etherrorcode404** [comment]
Awesome! Thanks man..
