### ISSUE TITLE
Feat: Expose max width and max height config for all float windows 

### ISSUE THREAD

**Issue by protiumx** [glepnir/lspsaga.nvim#901]
**Is your feature request related to a problem? Please describe.**
Currently I'd like to adjust the width of the float window for docs `hover`

**Describe the solution you'd like**
It'd be nice to be able to configure this from the setup, as I see the width is hardcoded here https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/hover.lua#L62

**Describe alternatives you've considered**
I didn't find any other alternatives

**Additional context**
-

**Comment by glepnir** [comment]
it respect the max content len first second is max width.
