### ISSUE TITLE
With LSPSaga enabled in Neovim's recent version there is an annoying diagnostic pane at the right top of the buffer

### ISSUE THREAD

**Issue by HendrikPetertje** [glepnir/lspsaga.nvim#905]
### Describe the bug

This morning I built Neovim to the latest version (https://github.com/neovim/neovim/commit/649742821a640c47c3934e7366676efc03153a28) and with LSPSaga enabled I am now noticing an annoying diagnostic window in the top-right corner of the screen that persists and throws stuff at me as long as I am in insert mode.

Here is a video of the events happening:
https://youtu.be/r7LPJbx2xYE

Disabling lspsaga gets rid of the problem.

The problem happens with the following configurations:

```
local has_lspsaga, lspsaga = pcall(require, 'lspsaga')
if (not has_lspsaga) then return end

lspsaga.setup()
```

```
local has_lspsaga, lspsaga = pcall(require, 'lspsaga')
if (not has_lspsaga) then return end

lspsaga.setup({
  ui = {
    theme = 'round',
    title = true,
    -- border type can be single,double,rounded,solid,shadow.
    border = 'rounded',
    winblend = 0,
    expand = '',
    collaspe = '',
    preview = '🔎 ',
    code_action = '💡',
    diagnostic = '🐞',
    incoming = ' ',
    outgoing = ' ',
    colors = {
      --float window normal bakcground color
      normal_bg = '#26233a',
      --title background color
      title_bg = '#26233a', -- i don't like title background colors, so this is just normal overlay

      red = '#eb6f92', -- lines and icons at top -- is now love from rose-pine
      magenta = '#b33076', -- headers. I'm fine with this
      orange = '#FF8700', -- is ok
      yellow = '#f7bb3b', -- is ok
      green = '#afd700', -- is ok
      cyan = '#31748f', -- Header -- is now pine blue from rose-pine
      blue = '#9ccfd8', -- other lightblue -- is now foam from rose-pine
      purple = '#c4a7e7', -- headers? -- is now iris from rose-pine
      white =  '#e0def4', --  '#d1d4cf' -- is ok
      black = '#d1d4cf', -- black text on bright header.- I don't like bright headers, so this is white now
    },
    kind = {},
  },
  diagnostic = {
    twice_into = false,
    show_code_action = true,
    show_source = true,
    keys = {
      exec_action = '<CR>',
      quit = 'q',
    },
  },
  code_action = {
    num_shortcut = true,
    keys = {
      quit = 'q',
      exec = '<CR>',
    },
  },
  -- I don't want lightbulb ever!
  lightbulb = {
    enable = false,
    enable_in_insert = false,
    -- cache_code_action = true,
    sign = false,
    sign_priority = 40,
    virtual_text = false,
  },
  preview = {
    lines_above = 0,
    lines_below = 10,
  },
  scroll_preview = {
    scroll_down = '<C-f>',
    scroll_up = '<C-b>',
  },
  request_timeout = 2000,
  finder = {
    edit = { 'o', '<CR>' },
    vsplit = 's',
    split = 'i',
    tabe = 't',
    quit = { 'q', '<ESC>' },
  },
  definition = {
    edit = '<C-c>o',
    vsplit = '<C-c>v',
    split = '<C-c>i',
    tabe = '<C-c>t',
    quit = 'q',
    close = '<Esc>',
  },
  rename = {
    quit = '<C-c>',
    exec = '<CR>',
    mark = 'x',
    confirm = '<CR>',
    in_select = true,
    whole_project = true,
  },
  symbol_in_winbar = {
    enable = false,
    separator = ' ',
    hide_keyword = true,
    show_file = true,
    folder_level = 2,
  },
  outline = {
    win_position = 'right',
    win_with = '',
    win_width = 30,
    show_detail = true,
    auto_preview = true,
    auto_refresh = true,
    auto_close = true,
    custom_sort = nil,
    keys = {
      jump = 'o',
      expand_collaspe = 'u',
      quit = 'q',
    },
  },
  callhierarchy = {
    show_detail = false,
    keys = {
      edit = 'e',
      vsplit = 's',
      split = 'i',
      tabe = 't',
      jump = 'o',
      quit = 'q',
      expand_collaspe = 'u',
    },
  },
  server_filetype_map = {},
})

-- #########################################
-- Native NVIM sign & diagnostic overrides #
-- #########################################
-- Fancy signs in the Gutter (space left of row numbers)
local signs = {
  Error = '🐛',
  Warn = '🦋',
  Info = '💡',
  Hint = '✨',
}

for type, icon in pairs(signs) do
  local hl = 'DiagnosticSign' .. type
  vim.fn.sign_define(hl, { text = icon, texthl = hl, numhl = hl })
end

-- Diagnostic config
vim.diagnostic.config({
  signs = true,
  update_in_insert = false,
  underline = true,
  severity_sort = true,
  virtual_text = false
})
```

### Steps to reproduce

```
brew upgrade neovim --fetch-HEAD
```

- Open neovim, maybe do a packerSync or lazy update
- Enter any file with LSP
- top-right diagnostics show up

### Expected behavior

I would like the pesky diagnostic to not be there, it's mildly distracting

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1023+g649742821-dirty

### lspsaga commit

bd55b175a4546334a197821cd4bfc19ba94e1a82

### Terminal name/version

Alacritty 79ea8b9482ec07b894ea9f6a0a79712751fe151c

**Comment by glepnir** [comment]
`diagnostic.on_insert` read #867

**Comment by HendrikPetertje** [comment]
ow okay sorry I had completely missed this. 

>  I have received a lot of unsatisfactory feedback

I'm sorry about that, I realize that I too made some comments about color in the past. 
At the end of the day I think this is still your plugin and your awesome work, I hope you don't take the criticism given by others personally.

**Comment by HendrikPetertje** [comment]
Other note, now that I'm slightly more educated on what has happened in the last couple of days:

the on_insert diagnostic is not bad, I think a lot of people will like it and use it in their workflows. I like to keep my editor a little bit more toned down, so besides an underline and a little emoji in the number-column i have nothing interrupting the buffer itself with  bells and whistles. I've gone as far as removing folding lines, separator-lines and the likes to get to the clean buffer ascetic. (I absolutely love the winbar by the way, it is a geeky, neat and handy little thing that has come in handy a bunch of times while i had to work in long sample files)

So please, knowing that the top-right diagnostic is a feature now, i can see it being useful and a nice ad-on for a lot of people :)

Love your work, sorry for opening a bug ticket

**Comment by glepnir** [comment]
because other editor has this. so i implement it . better than other editor i implement `on_insert_follow` it will appear in the line which you edit.
