### ISSUE TITLE
LSP finder window gets too narrow in vertically split window

### ISSUE THREAD

**Issue by craftzdog** [glepnir/lspsaga.nvim#909]
### Describe the bug

The preview window not showing when the parent window was narrow.

<img width="481" alt="Screenshot 2023-02-23 at 13 37 09" src="https://user-images.githubusercontent.com/1332805/220822379-b81f03da-a19f-4290-b099-c314a0ce6f0a.png">

If I press <kbd>o</kbd> to open a file on the preview window, it causes an error:

```
E5108: Error executing lua: ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:808: Expected Lua number
stack traceback:
        [C]: in function 'nvim_win_get_buf'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:808: in function 'open_link'
        ...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:545: in function <...te/pack/packer/start/lspsaga.nvim/lua/lspsaga/finder.lua:544>
```

The issue is here:

https://github.com/glepnir/lspsaga.nvim/blob/bd55b175a4546334a197821cd4bfc19ba94e1a82/lua/lspsaga/finder.lua#L635-L639

### Steps to reproduce

- Split windows vertically several times
- Run `Lspsaga lsp_finder`

### Expected behavior

The window width shouldn't be limited just like hover doc:

<img width="900" alt="Screenshot 2023-02-23 at 13 36 38" src="https://user-images.githubusercontent.com/1332805/220822364-27e64cfe-a1f6-4d22-aefe-086d91074272.png">

### Neovim version (nvim -v)

0.8.2

### lspsaga commit

bd55b175a4546334a197821cd4bfc19ba94e1a82

### Terminal name/version

iTerm2 3.4.19 with tmux 3.3a

**Comment by qizeng19** [comment]
the same problem with my nvim , when i set the nvim window to full screen，it bacame ok
