### ISSUE TITLE
SagaLightBlub highlight not themeable

### ISSUE THREAD

**Issue by uloco** [glepnir/lspsaga.nvim#910]
### Describe the bug

I set my code_action config to a nerdfont light bulb icon.
When I specify SagaLightBlub highlight it doesn't get applied to the icon.

### Steps to reproduce

1. set light bulb icon (not emoji)
```
ui = {
  code_action = "",
}
```
2. run `:hi SagaLightBlub guifg=#ff0000 guibg=#00ff00`
3. light bulb does not change color

### Expected behavior

should be themeable like before the lspsaga update

### Neovim version (nvim -v)

NVIM v0.8.3

### lspsaga commit

latest (bd55b175a4546334a197821cd4bfc19ba94e1a82)

### Terminal name/version

iterm 3.5.0beta10

**Comment by uloco** [comment]
@glepnir Your recent change only fixed the sign column but not the virtual text. I am only using the virtual text and have sign_column disabled.

**Comment by glepnir** [comment]
fixed
