### ISSUE TITLE
Open again previous buffer loses lines numbers

### ISSUE THREAD

**Issue by Fedex159** [glepnir/lspsaga.nvim#914]
### Describe the bug

When I open a buffer for first time with lsp_finder is works ok, but If I open again the same buffer, this loses the lines numbers.

Video:

https://user-images.githubusercontent.com/44141208/221304973-6ba816ac-4582-444f-8a7e-4da9d91a6529.mp4

Image:

![imagen](https://user-images.githubusercontent.com/44141208/221305058-6114826c-45e8-4033-a67a-0d6ade6084a1.png)

### Steps to reproduce

- Open a clean buffer
- Open lsp_finder
- Select a reference and open in a new tab
- Close the buffer opened
- Open again with lsp_finder the same buffer
- Check

### Expected behavior

Don't lose the lines numbers if I open again the same buffer

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

e79653a

### Terminal name/version

Kitty 0.26.5

**Comment by glepnir** [comment]
can't reproduce.

![lsp](https://user-images.githubusercontent.com/41671631/221341290-2e470dfb-31d1-43a3-bbb5-970fac5d5e30.gif)

**Comment by Fedex159** [comment]
> can't reproduce.
> 
> ![lsp](https://user-images.githubusercontent.com/41671631/221341290-2e470dfb-31d1-43a3-bbb5-970fac5d5e30.gif) [ ![lsp](https://user-images.githubusercontent.com/41671631/221341290-2e470dfb-31d1-43a3-bbb5-970fac5d5e30.gif) ](https://user-images.githubusercontent.com/41671631/221341290-2e470dfb-31d1-43a3-bbb5-970fac5d5e30.gif) [ ](https://user-images.githubusercontent.com/41671631/221341290-2e470dfb-31d1-43a3-bbb5-970fac5d5e30.gif)

I see you are using **bd** to close the buffer, and with that works ok, but try using **q** and is failing

**Comment by glepnir** [comment]
q is normal macro keymap ?

**Comment by Fedex159** [comment]
> q is normal macro keymap ?

q is :quit

**Comment by Fedex159** [comment]
here a video

https://user-images.githubusercontent.com/44141208/221359852-9bc8a167-0d9a-4bf4-8a1d-53feadbac269.mp4
