### ISSUE TITLE
Diagnostic Icons

### ISSUE THREAD

**Issue by dantearaujo1** [glepnir/lspsaga.nvim#915]
### Describe the bug

Installed lspsaga and setup with defaults, but there's no diagnostic sign modified, only 'H', 'W', etc..

Ps: i read thru the docs.

I should set them manually or this is a bug?

### Steps to reproduce

Use Lazy, install lspsaga

### Expected behavior

Set Diagnostics Icons and Colors

### Neovim version (nvim -v)

Nvim v0.9,0-dev

### lspsaga commit

?

### Terminal name/version

Ubuntu using Wsl2 inside Windows Terminal

**Comment by glepnir** [comment]
`:h vim.diagnostic.config`
