### ISSUE TITLE
float window is not close when leave buffer

### ISSUE THREAD

**Issue by NavePnow** [glepnir/lspsaga.nvim#918]
when you click buffers to switch them, the float window is not close.

https://user-images.githubusercontent.com/39482599/221352877-89b47e89-983c-49bc-913f-d3770ed96217.mov

_Originally posted by @NavePnow in https://github.com/glepnir/lspsaga.nvim/issues/917#issuecomment-1445053312_

**Comment by glepnir** [comment]
use `++unfocus` or use buffer  jump command bnext bprev . i don't use mouse.
