### ISSUE TITLE
Diagnostic float line doesn't extend the entire width all the time.

### ISSUE THREAD

**Issue by ckipp01** [glepnir/lspsaga.nvim#92]
### Description
At times if you have a diagnostic that has a short message, the line that seperates the title from the message doesn't extend the entire window.

<img width="303" alt="Screenshot 2021-02-11 at 11 38 35" src="https://user-images.githubusercontent.com/13974112/107626182-b63ad780-6c5d-11eb-9e5c-f47334a4531c.png">

**Expected Behavior**
I would expect that no matter the length of the message that the divider extends. Like how it does when it's longer.

<img width="303" alt="Screenshot 2021-02-11 at 11 39 27" src="https://user-images.githubusercontent.com/13974112/107626271-d4083c80-6c5d-11eb-9dc9-f57029b1aa3e.png">

### Details

You can reproduce this using the `sumneko_lua` server. Here is a minimal file:

```
local cmd = vim.cmd

cmd [[packadd packer.nvim]]
require('packer').startup(function(use)
  use {'wbthomason/packer.nvim', opt = true}

  use {'glepnir/lspsaga.nvim'}
  use {'neovim/nvim-lspconfig'}
end)

local saga = require 'lspsaga'
saga.init_lsp_saga()

map('n', ']c', '<cmd>lua require"lspsaga.diagnostic".lsp_jump_diagnostic_next()<CR>')

local lsp_config = require 'lspconfig'

lsp_config.sumneko_lua.setup {
  cmd = {
    '/your-path-here/lua-language-server', '-E',
    '/your-path-here/lua-language-server/main.lua'
  },
  settings = {
    Lua = {
      runtime = {
        version = 'LuaJIT',
        path = vim.split(package.path, ';')
      },
      diagnostics = {globals = {'vim', 'it'}},
      workspace = {
        -- Make the server aware of Neovim runtime files
        library = {
          [vim.fn.expand('$VIMRUNTIME/lua')] = true,
          [vim.fn.expand('$VIMRUNTIME/lua/vim/lsp')] = true
        }
      }
    }
  }
}
```

Then just have an unused local variable that is a single letter or something.

- nvim --version output: `v0.5.0-dev+1aec5ba85`
- Operating system: Mac
- lspsaga commit: `985bcf31ad7b4fe955b02ce17bb844efb712aa22`

**Comment by glepnir** [comment]
I know this bug. I am rewrite diagnostic now in my local .had fixed it . commit when I rewrite done
