### ISSUE TITLE
Diagnostic unexpected behaviour

### ISSUE THREAD

**Issue by etherrorcode404** [glepnir/lspsaga.nvim#921]
### Describe the bug

![2023-02-27-01:42:47](https://user-images.githubusercontent.com/88607362/221433221-bf3c020c-27c1-4f41-8b2a-39c27145b1a0.png)
![2023-02-27-01:43:48](https://user-images.githubusercontent.com/88607362/221433251-6175f1b9-fc45-4ca1-9a51-f621bba3f4b1.png)

### Steps to reproduce

```
  diagnostic = {
    on_insert = true,
    on_insert_follow = true,
    insert_winblend = 0,
    show_code_action = true,
    show_source = true,
    jump_num_shortcut = true,
    --1 is max
    max_width = 1,
    custom_fix = nil,
    custom_msg = nil,
    text_hl_follow = true,
    border_follow = true,
    keys = {
      exec_action = 'o',
      quit = 'q',
      go_action = 'g',
    },
  },
```

### Expected behavior

Show full text

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

7e693ad

### Terminal name/version

Alacritty

**Comment by etherrorcode404** [comment]
Btw great implementation on the color coded diagnostics!
It would also be nice to have an option to allow the user to just use the float diagnostic, since this trying to replicate similar behaviour.

On diagnostics;
```
lua vim.diagnostic.open_float()
```

Add an option in the diagnostics section;
```
diagnostic = {
   enable_float = true,
   ...
  },
```

**Comment by glepnir** [comment]
you mean `on_insert` to false or true?
