### ISSUE TITLE
Lsp finder window overlapping

### ISSUE THREAD

**Issue by edward-s** [glepnir/lspsaga.nvim#922]
### Describe the bug

<img width="1408" alt="Screenshot 2023-02-27 at 1 50 24 PM" src="https://user-images.githubusercontent.com/237278/221485109-e1c9cef9-19a7-4b27-97c4-36bdf183037e.png">

After the latest update, the lsp finder window UI is overlapping

### Steps to reproduce

:Lspsaga lsp_finder

### Expected behavior

windows should not overlap, like previous version

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

9e58b1a

### Terminal name/version

kitty

**Comment by glepnir** [comment]
provide the reproduce step. i can't reproduce it.

**Comment by glepnir** [comment]
provide the reproduce step. i can't reproduce it.

**Comment by Kazimazi** [comment]
@glepnir Issue persists, even after 79f5a08. I can reliably reproduce by opening 3 vertical splits and sending sending lsp_finder in the middle split.

**Comment by glepnir** [comment]
fix in tomorrow
