### ISSUE TITLE
"Action Preview" gets stuck

### ISSUE THREAD

**Issue by TheodorRene** [glepnir/lspsaga.nvim#929]
### Describe the bug

Hello, thank you for the great library. The hover terminal especially has become a part of my daily routine. 

My problem now is that whenever at "Action Preview" is shown for a code action it never goes away. Is there a way to disable the action preview? I'm not in a position to give a super detailed bug report atm, but maybe do it some other time. 

### Steps to reproduce

Initate code_action where Action preview is available. 
Exit code action
Action preview is still visible

![image](https://user-images.githubusercontent.com/36312737/222726574-7b24aac7-5f5d-4b20-b1e6-bab0c1405af5.png)

### Expected behavior

Action Preview is dismissed when code_action is. 

### Neovim version (nvim -v)

NVIM v0.9.0-dev-843+g860fea1a3

### lspsaga commit

Newest at this time (03-03-2023)

### Terminal name/version

Alacritty

**Comment by glepnir** [comment]
how you quit the code action window.

**Comment by TheodorRene** [comment]
> how you quit the code action window.

with `:q`

**Comment by TheodorRene** [comment]
Ah, it goes away by using just `q`

**Comment by glepnir** [comment]
just press `q`

**Comment by TheodorRene** [comment]
Thank u 👍
