### ISSUE TITLE
feature request: diagnostic jump show more informations

### ISSUE THREAD

**Issue by 2nthony** [glepnir/lspsaga.nvim#930]
Can lspsaga diagnostic_jump_next/prev shows all message in `title` ? I know `Lspsaga show_line_diagnostics` can show all message.

if worth to do, may provide an option to enable would be better I think, e.g. `lspsaga.diagnostic.show_more_information`, defaults to `false`

---

`vim.diagnostic.goto_next`

![image](https://user-images.githubusercontent.com/19513289/222784506-de072a7c-4e34-410a-90a3-e13d3549273a.png)

`lspsaga diagnostic_jump_next`

![image](https://user-images.githubusercontent.com/19513289/222784651-4137e8a9-feec-4530-9bbc-e0469df84593.png)

**Comment by glepnir** [comment]
make sense. will support next version

**Comment by glepnir** [comment]
I had implement this. 

![image](https://user-images.githubusercontent.com/41671631/226165756-138159c6-45ba-4115-8a20-7ebbe3c60b7a.png)

**Comment by 2nthony** [comment]
> I had implement this.
> 

🤔 seems it is not what I expected, maybe this feature request is a bad idea.

**Comment by glepnir** [comment]
can you show me a image or  painting a sketch  what do you expect ?

**Comment by 2nthony** [comment]
![image](https://user-images.githubusercontent.com/19513289/226175005-a4cf3663-7238-4323-ab65-478637e4b6b3.png)

Assume this is the `diagnostic_jump_next` popup.

---

and I felt it is a bad idea because I missed the `code_actions` area, so many similar items look weird, even with JS eslint.
![image](https://user-images.githubusercontent.com/19513289/226175164-ba0e0bbf-8405-485f-b3e4-ff8dc2aebffb.png)

**Comment by glepnir** [comment]
if you don't want show codeaction in jump window you can disable it .

**Comment by 2nthony** [comment]
> if you don't want show codeaction in jump window you can disable it .

I know there has an option to disable 😃

just feel little weird if so many similar code actions, maybe this is not a problem.

**Comment by 2nthony** [comment]
## recap

my expected like this

![image](https://user-images.githubusercontent.com/19513289/226175005-a4cf3663-7238-4323-ab65-478637e4b6b3.png)

**Comment by glepnir** [comment]
currently i have no idea with some ui .. so if you have some great ui you can post here  if i feel great I will implement it .

**Comment by glepnir** [comment]
you mean the windows is not combine ?  two windows for each others?

**Comment by glepnir** [comment]
so you mean the many code actions make you feel not comfortable ?

**Comment by 2nthony** [comment]
> so you mean the many code actions make you feel not comfortable ?

just a few, but it is OK,

**Comment by glepnir** [comment]
it's not depend on me ..server return these actions . close then ?

**Comment by 2nthony** [comment]
the list of code actions is OK now,

if I feel uncomfortable, i can close the list via `lspsaga.diagnostic .show_code_action`
