### ISSUE TITLE
There's a definition, but I can't jump or preview it

### ISSUE THREAD

**Issue by scottming** [glepnir/lspsaga.nvim#934]
### Describe the bug

<img width="912" alt="image" src="https://user-images.githubusercontent.com/12830256/223045973-7a45ffb4-3c98-4ca1-aa44-a36fc76f4698.png">
<img width="998" alt="image" src="https://user-images.githubusercontent.com/12830256/223046111-5157a9f8-6dd1-498b-8e7c-63d5b9a5bac1.png">

It seems to happen only in the `test` directory, and I'm not sure if it's because LSP doesn't return enough data.

### Steps to reproduce

this is the log data:

```
[DEBUG][2023-03-06 15:36:16] .../vim/lsp/rpc.lua:284	"rpc.send"	{  id = 52,  jsonrpc = "2.0",  method = "textDocument/definition",  params = {    position = {      character = 4,      line = 12    },    textDocument = {      uri = "file:///Users/scottming/Code/recode/test/fixtures/rename/exp/import_no_change.ex"    }  }}
[DEBUG][2023-03-06 15:36:16] .../vim/lsp/rpc.lua:387	"rpc.receive"	{  id = 52,  jsonrpc = "2.0",  result = {    range = {      ["end"] = {        character = 6,        line = 1      },      start = {        character = 6,        line = 1      }    },    uri = "file:///Users/scottming/Code/recode/test/fixtures/rename/exp/import_no_change.ex"  }}
```

But I don't see how this is different from normal results.

Here is an example of a normal result(not in the test folder):

```
{  id = 73,  jsonrpc = "2.0",  result = {    range = {      ["end"] = {        character = 7,        line = 39      },      start = {        character = 7,        line = 39      }    },    uri = "file:///Users/scottming/Code/recode/lib/recode/config.ex"  }}
```

### Expected behavior

`

### Neovim version (nvim -v)

0.9

### lspsaga commit

63b35723d0a1ae01446e1645d567fb4d9f1831f4

### Terminal name/version

alacritty

**Comment by glepnir** [comment]
quickly fix is disable beacon `beacon.enable = false ` . can you test it ?

**Comment by glepnir** [comment]
the response looks right something wrong in beacon looks like. you can do the debug print . i need this result .

```diff
  git diff
Found existing alias for "git". You should use: "g"
diff --git a/lua/lspsaga/libs.lua b/lua/lspsaga/libs.lua
index 41577a9..d4c30b1 100644
--- a/lua/lspsaga/libs.lua
+++ b/lua/lspsaga/libs.lua
@@ -313,6 +313,7 @@ function libs.jump_beacon(bufpos, width)
   }

   local window = require('lspsaga.window')
+  print(vim.inspect(opts))
   local _, winid = window.create_win_with_border({
     contents = { '' },
     noborder = true,

```

**Comment by scottming** [comment]
First, disable doesn't report errors anymore, but it still doesn't preview and jump

Then the log doesn't have valuable information.

<img width="958" alt="image" src="https://user-images.githubusercontent.com/12830256/223052200-e7be68a9-2767-49e7-a87f-16d04071dff8.png">

**Comment by glepnir** [comment]
can you post this  exli repo ? then i can test it .

**Comment by scottming** [comment]
sure, this is the repo: https://github.com/hrzndhrn/recode.git

and the code is the baz of this line: https://github.com/hrzndhrn/recode/blob/114ca9ac7c90dded88769ae9c0d2f73b902190c1/test/fixtures/rename/lib/import_no_change.ex#L13

**Comment by scottming** [comment]
And I think after cloning that repo, you should run `asdf install`  first(to install erlang and elixir).

**Comment by glepnir** [comment]
what is the asdf a pacakge manager of elixir ?

**Comment by glepnir** [comment]
emm do you have a min repo of elixir can reproduce this ?

**Comment by scottming** [comment]
A smaller repo may have limited benefits, as it is already a small repository. And all elixir code runs on  the erlang VM, so both erlang and elixir are required.

**Comment by glepnir** [comment]
I can reproduce .but it most the problem of this server .. lots of the response of this server not follow the lsp spec....very fucking sad.. i can fix it ...

**Comment by scottming** [comment]
> I can reproduce .but it most the problem of this server .. lots of the response of this server not follow the lsp spec....very fucking sad.. i can fix it ...

**Comment by scottming** [comment]
> I can reproduce .but it most the problem of this server .. lots of the response of this server not follow the lsp spec....very fucking sad.. i can fix it ...

I've been doing some lsp work recently and we're getting it more consistent.

And the goto definition is migrated by me, haha, I just returned `Location`, I think I've already followed the spec: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_definition

the spec said we can return: result: [Location](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#location) | [Location](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#location)[] | [LocationLink](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#locationLink)[] | null

**Comment by glepnir** [comment]
can you update and test ? on my local it works.

**Comment by scottming** [comment]
it works, thank you.

**Comment by glepnir** [comment]
glad to hear that .

**Comment by scottming** [comment]
If you don't mind, I'd be happy to add some unit tests to lspsaga, I think it would be great for easing your maintenance burden and for the long-term development of the project.

I may not be very familiar with Lua, but I am familiar with unit testing, and I enjoy doing it, and I have the time these days.

I know lsp has a lot of state dependencies, but there's also a lot of decision logic in there, so we can start with that part, similar to my neotest example in this [PR](https://github.com/jfpedroza/neotest-elixir/pull/23/files#diff-cfac17e35de1af2e4b624628a96621e3c3207cb555bb221c62a4c395334a39a0), where I only tested the core decision logic.

But I'm not really familiar with the details of the lspsaga implementation, so it might take some time to explain it to me first.
