### ISSUE TITLE
Floating windows don't go away

### ISSUE THREAD

**Issue by trevarj** [glepnir/lspsaga.nvim#94]
### Description

Sometimes if I have a popup/floating window, it will stay on the screen. I think it happens when I move out of the floating window, but I'm not sure. The text goes away when I hit 'q' but the outline stays...
**Expected Behavior**

Is there a way to redraw quickly?
**Actual Behavior**

![image](https://user-images.githubusercontent.com/5448324/107784242-419a9280-6d5c-11eb-9d89-22f758f05a9e.png)

### Details

<details><summary>Reproduce</summary>

1. nvim -u test.vim the min config that only lspsaga
2. post your program language min code snippet that can reproduce your issue
3. 
</details>

<details><summary>Environment</summary>

- nvim --version output: 
- Operating system: 
- lspsaga commit: 

</details>

**Comment by glepnir** [comment]
which command？

**Comment by trevarj** [comment]
Sorry, it's with code actions when you get inside code action then click with the mouse outside. Popup doesn't go away on click

**Comment by glepnir** [comment]
How to reproduce this ?

**Comment by trevarj** [comment]
1. Make code action pop up
2. Click outside code action floating window
3. Notice code action floating window stays.
4. Click back into floating window, do :q to close 😕
