### ISSUE TITLE
[Finder Ui] better window behavior

### ISSUE THREAD

**Issue by alextrastero** [glepnir/lspsaga.nvim#940]
I have a small screen, and when using `Lspsaga lsp_finder`, the _preview_ section is really small (see screenshot).

Would it be possible to add a feature to move the preview window under the list of files? Or/and maybe edit the list of files so that they get truncated or something...

![image](https://user-images.githubusercontent.com/4152819/224006446-f331b2f5-dd2b-491f-b1a5-64ec637eaef8.png)

**Comment by glepnir** [comment]
I want fix this in next version. because next version i want do more job on ui.  this issue not relate bug

**Comment by alextrastero** [comment]
thanks for the info, and thanks for this amazing plugin :)

**Comment by glepnir** [comment]
no need close this issue :)

**Comment by glepnir** [comment]
i had change the title then i can mention this issue in 0.2.9 pr

**Comment by glepnir** [comment]
had fixed in next version pr.

**Comment by alextrastero** [comment]
in the next version, will it be possible to change preview position? or for now only fix sizes?

**Comment by glepnir** [comment]
about it size now it will whole screen. not only current window.
