### ISSUE TITLE
finder 窗口宽度不够时显示错误

### ISSUE THREAD

**Issue by Jinl-k** [glepnir/lspsaga.nvim#941]
### Describe the bug

窗口宽度不够时显示错误

### Steps to reproduce

<img width="880" alt="image" src="https://user-images.githubusercontent.com/39037760/224282852-34ec95c2-9d3f-49c7-8284-7e0f8df6e904.png">

红线代表窗口宽度

### Expected behavior

<img width="1092" alt="image" src="https://user-images.githubusercontent.com/39037760/224283387-b4bacc1c-38cb-4beb-9433-ced51519671e.png">

加长宽度后显示正常

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

db6cdf51bf5ae45e4aa65760e597cf0d587c66ee

### Terminal name/version

neovide/ 0.10.0

**Comment by glepnir** [comment]
this is finder not code action .. the finder window behavior will improve in next version.

**Comment by Jinl-k** [comment]
哈哈 不好意思说错了，

**Comment by glepnir** [comment]
已经在 pr 下个版本修复了。
