### ISSUE TITLE
Set preview width for `outline`

### ISSUE THREAD

**Issue by goodshort** [glepnir/lspsaga.nvim#943]
**Is your feature request related to a problem? Please describe.**
When using `:Lspsaga outline`, if the indentation is more than a few tabs, the preview is not wide enough to provide enough context. In the screenshot below, the preview window does not help me in any way.

![image](https://user-images.githubusercontent.com/33832653/224700981-ff4c827a-faa1-4b2c-a26c-ae3d90e22be1.png)

**Describe the solution you'd like**
A paramater to configure the preview width through the `outline` config. 
#556 mentioned this, but I could not find the solution implemented for this issue.

**Describe alternatives you've considered**
I did not find a way to set the preview width.

**Comment by glepnir** [comment]
that's easy support . but i want make it in next version 0.2.9 i develop it in #935

**Comment by glepnir** [comment]
supported.
