### ISSUE TITLE
peak_definition -> enter no longer goes to the file neovim 0.8.3 

### ISSUE THREAD

**Issue by kaykhan** [glepnir/lspsaga.nvim#944]
I recently updated lspsaga to the latest version (main branch) and a few things i noticed broke.

One of them was the following command

```
vim.keymap.set("n", "gd", "<cmd>Lspsaga peek_definition<CR>", opts
```

Ive used this feature in preivous versions to look at the function in a floating window and when pressing "Enter" it would take me to that function. But that no longer works

The original still does

```
vim.keymap.set("n", "gd", vim.lsp.buf.definition, bufopts)
```

> NVIM v0.8.3

**Comment by glepnir** [comment]
`peek_defintion` not goto file. `lspsaga goto_definition` is go to file. read doc /.

**Comment by kaykhan** [comment]
Sorry maybe you miss understand my problem, in previous verison of lsp_saga you could `Lspsaga peek_definition` + `ENTER` to go to definition.

In the latest version, `ENTER` after `Lspsaga peek_definition` does not go to definition

**Comment by kaykhan** [comment]
> does `C-c o` work?

Yes that works, what is happening here?

**Comment by kaykhan** [comment]
> before it just preview now support edit in this floatwindow like normal buffer read doc.

Okay, i used `Lspsaga peek_definition` + `ENTER` a lot before so sad to see it no longer works

**Comment by glepnir** [comment]
there has new command `Lspsaga goto_definition`

**Comment by kaykhan** [comment]
> there has new command `Lspsaga goto_definition`

 but you cannot "peek" at definition before entering

**Comment by glepnir** [comment]
please look at doc, you also can config the defintion keys `<C-c>o` to enter if you want.

**Comment by kaykhan** [comment]
Ok this is a change in functionality to `peek_definition` i prefer old functionality, just my suggestion

**Comment by glepnir** [comment]
finder also show `definition` and easy to config it.
