### ISSUE TITLE
Uncessary padding in lsp_hoverdoc floating window neovim 0.8.3

### ISSUE THREAD

**Issue by kaykhan** [glepnir/lspsaga.nvim#945]
I recently updated to the latest version of lspsaga and noticed when i use the following command:

```
vim.keymap.set("n", "K", "<cmd>Lspsaga hover_doc<CR>", opts)
```

The floating window now has some unnecessary `top` and `bottom` padding that was not there in previous versions. 

(left preivous, right new)

![image](https://user-images.githubusercontent.com/5202527/224775510-727b9b45-8ad3-4e39-9084-3d3785a19961.png)

Is there a way i can remove this padding for now?

> NVIM v0.8.3

**Comment by glepnir** [comment]
default of neovim  use regex syntax file. now lspsaga use treesitter markdown render.  we can't hide this line of codeblock ````xxx`
