### ISSUE TITLE
tresitter-parser error when using finder

### ISSUE THREAD

**Issue by bryantchan** [glepnir/lspsaga.nvim#946]
### Describe the bug

<img width="951" alt="CleanShot 2023-03-15 at 02 28 15@2x" src="https://user-images.githubusercontent.com/1303409/225016449-8c5e243c-c9d9-439e-8718-c1012f65113a.png">

I've re-installed the tsserver using TSInstall 

### Steps to reproduce

:Lspsaga lsp_finder

### Expected behavior

No errors happens when using finder

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

main

### Terminal name/version

iterm2

**Comment by glepnir** [comment]
install tsx parser through treesitter

**Comment by SilverMira** [comment]
Facing this issue, but the situation is a little different. for my case it is the Dart treesitter parser, which has a parser issue that occasionally falls into an infinite loop https://github.com/UserNobody14/tree-sitter-dart/issues/40, freezing Neovim. Keeping the parser around is not an option so I had to uninstall it. But doing so made lsp_finder product this same error.

I know users are expected to install the parsers they use, but there are occasions where it isn't available or cannot be used. Can this error be handled gracefully by lspsaga? Currently it just continues to spit out error while navigating in lsp_finder

**Comment by glepnir** [comment]
yep I think can fallback to default syntax highlight  when parser not found.
