### ISSUE TITLE
[Question or feature request] Ability to change the color of winbar text

### ISSUE THREAD

**Issue by KritPaoIn** [glepnir/lspsaga.nvim#947]
<img width="279" alt="Screenshot 2023-03-15 at 7 08 59 PM" src="https://user-images.githubusercontent.com/92923965/225304792-a3c115c9-e266-4728-bd47-b1a328a231a4.png">
How do you change the text color of "PlayerMovement" and "Start" without changing the color of the icons beside them?
</br>
</br>
This is what I want it to look like
<img width="208" alt="Screenshot 2023-03-15 at 7 13 01 PM" src="https://user-images.githubusercontent.com/92923965/225305693-e8846598-5ea6-4561-98a8-fb1a0eaf10f3.png">

**Comment by glepnir** [comment]
first `symbol_in_winbar.color_mode = false` , then set `vim.cmd(' hi SagaWinbarWord guifg=your color hex code')`
