### ISSUE TITLE
Diagnostic message showing up in right corner of my screen

### ISSUE THREAD

**Issue by kaykhan** [glepnir/lspsaga.nvim#949]
After updating lspsaga i noticed i am receiving an extra diagnostic message on the right corner of my screen.

Is this a feature of lsp saga i can disable?

![Screenshot from 2023-03-17 11-23-22](https://user-images.githubusercontent.com/5202527/225893766-0a0bb6aa-e617-4c8c-9df7-a5ba0e7e9cb4.png)

**Comment by glepnir** [comment]
`diagnsotic.on_insert = false`
