### ISSUE TITLE
Omnisharp Definition Issues

### ISSUE THREAD

**Issue by michael-duren** [glepnir/lspsaga.nvim#950]
### Describe the bug

Trying to access definitions for any Omnisharp System types fails. I get Cursor position outside buffer stack traceback, as well as E79: Cannot expand wildcards.

I have Omnisharp installed globally, on my computer. I know the metadata should be available. 

No problem accessing definitions in other IDE's. 

### Steps to reproduce

Lsp go_to_definition on any system types like int System.Console, Dictionary, etc, in .NET 6/7 using C#. 

### Expected behavior

Show metadata information about that type. 

### Neovim version (nvim -v)

NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3

### lspsaga commit

commit db6cdf5

### Terminal name/version

iTerm2 Build 3.4.16

**Comment by michael-duren** [comment]
LSP
installed version v1.39.6                                       
      homepage          https://github.com/OmniSharp/omnisharp-roslyn 
      languages         C#                                            
      categories        LSP                                           
      executables       omnisharp

**Comment by michael-duren** [comment]
<img width="1358" alt="Screenshot 2023-03-17 at 6 52 06 PM" src="https://user-images.githubusercontent.com/100647362/226071419-129f7dae-c680-4792-8b0d-41ef5a26c9cf.png">
Where it tries to find the definition

**Comment by glepnir** [comment]
looks like open C sharp file in finder right ?

**Comment by michael-duren** [comment]
So it doesn't open the definition, which is what I'm after. It works for finding references in other areas of the project. 
<img width="1301" alt="Screenshot 2023-03-17 at 5 23 06 PM" src="https://user-images.githubusercontent.com/100647362/226172001-08237763-48ce-4325-8208-3dade453ca9f.png">

**Comment by glepnir** [comment]
can you get the response of definition handler ?

**Comment by michael-duren** [comment]
How would I do that?

**Comment by glepnir** [comment]
```diff
diff --git a/lua/lspsaga/definition.lua b/lua/lspsaga/definition.lua
index 344fd88..251da95 100644
--- a/lua/lspsaga/definition.lua
+++ b/lua/lspsaga/definition.lua
@@ -276,6 +276,7 @@ function def:goto_definition(method)
     if not result or vim.tbl_isempty(result) then
       return
     end
+    print(vim.inspect(result))
     local res = {}

     if type(result[1]) == 'table' then
```

**Comment by michael-duren** [comment]
Where is it supposed to print this though I don't understand

**Comment by glepnir** [comment]
no worry ..I will try to reproduce it on my local and fix in next version. currently most of bug fix in version pr.

**Comment by michael-duren** [comment]
Okay, thank you. Sorry, I'm new to the world of NeoVIm/Vim.

**Comment by glepnir** [comment]
it's okay :)
