### ISSUE TITLE
FeatureRequest: allow keys array config on quit operation

### ISSUE THREAD

**Issue by linrongbin16** [glepnir/lspsaga.nvim#951]
**Is your feature request related to a problem? Please describe.**
Some `quit` keys only accept a string value. But I want both `q` and `Esc` working.

**Describe the solution you'd like**
Please allow strings array to define multiple keys for quit.

**Comment by glepnir** [comment]
will support in next version.

**Comment by linrongbin16** [comment]
thanks!
