### ISSUE TITLE
UI failure when using `:Lspsaga diagnostic_jump_next` as a `hydra` mapping

### ISSUE THREAD

**Issue by luiz00martins** [glepnir/lspsaga.nvim#952]
### Describe the bug

The UI displayed upon executing `:Lspsaga diagnostic_jump_next` fails when you run it under [`hydra`](https://github.com/anuvyklack/hydra.nvim).

The popup permanently sticks on the foreground, the highlight does not fade, and the actions don't appear.

Here's an example with a normal mapping:
https://user-images.githubusercontent.com/43142209/226087241-680de6a1-b71a-45c7-a63b-d3774c0c0888.mp4

And, an example with a hydra mapping:
https://user-images.githubusercontent.com/43142209/226087234-642f21a7-f98d-4145-a9ad-b9c51c77776d.mp4

### Steps to reproduce

Use the following configs:
```lua
-- Substitute 'using' with you package loader.

using {
	'neovim/nvim-lspconfig',
	config = function()
		local lsp = require('lspconfig')
		lsp.lua_ls.setup{}
	end
}

using {
	'glepnir/lspsaga.nvim',
	config = function()
		require('lspsaga').setup{}
	end
}

using {
	'anuvyklack/hydra.nvim',
}
```

Then, with the following mappings, you get the normal behaviour:
```lua
vim.keymap.set('n', ' ll', '<cmd>Lspsaga diagnostic_jump_next<cr>', {})
vim.keymap.set('n', ' lh', '<cmd>Lspsaga diagnostic_jump_prev<cr>', {})
```

However, with the following mappings, you get the abnormal behaviour:
```lua
require('hydra') {
	mode = 'n',
	body = ' l',
	heads = {
		{'l', '<cmd>Lspsaga diagnostic_jump_next<cr>'},
		{'h', '<cmd>Lspsaga diagnostic_jump_prev<cr>'},
	},
}
```

### Expected behavior

Match the behaviour of the standard mapping method.

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1219+g773febc46

### lspsaga commit

db6cdf5

### Terminal name/version

Windows Terminal 1.16.10261.0

**Comment by glepnir** [comment]
hmm so why problem is there .. without hydra it works fine right ?

**Comment by luiz00martins** [comment]
Yes, but it fails under hydra. That's clearly a problem.

I just don't know from which party it is. I've posted bug reports on both repos. See https://github.com/anuvyklack/hydra.nvim/issues/80

**Comment by luiz00martins** [comment]
Yes, which is why I've opened bug reports on both repos. See https://github.com/anuvyklack/hydra.nvim/issues/80

You might have more insight on why it's failing, as you know the internals of `lspsaga`. So you may be able to give an idea of why the UI is not being updated.

**Comment by glepnir** [comment]
no idea. i don't use that plugin.
