### ISSUE TITLE
peek_definition jump list problem

### ISSUE THREAD

**Issue by jacek-kurlit** [glepnir/lspsaga.nvim#953]
### Describe the bug

When I use peek_definition and press `q` to close floating window then `<C-o>` and `<C-i>` (jump list navigation)  stops to work. I know documentation says I can press <C-t> but why <C-o> & <C-i> are being broken?
Is this bug or a feature?

### Steps to reproduce

1. With rust lsp attached use `Lspsaga peek_definition` command to peek function definition
2. Press `q` to close popup
3. Use `Lspsaga goto_definition` or default lsp goto_definition command on that function
4. Try press <C-o> - it doesn't move cursor back to position from step 3

### Expected behavior

<C-o> and <C-i> should work 

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

peek_definition

### Terminal name/version

kitty 0.27.1

**Comment by glepnir** [comment]
had fix in next version .wait for merge thanks.
