### ISSUE TITLE
Navigate links inside `hover_doc`

### ISSUE THREAD

**Issue by sorashi** [glepnir/lspsaga.nvim#955]
Make it possible to navigate links inside `hover_doc`, like in image:

![](https://user-images.githubusercontent.com/6270283/226170266-2b5c8dbd-d47a-42f4-9f75-eb806e5393ea.png)

**Comment by glepnir** [comment]
had implement 



https://user-images.githubusercontent.com/41671631/226177896-9a234c2c-8554-4a21-87f2-bd5b47193cc7.mp4

**Comment by sorashi** [comment]
Very cool! Does it also work with *symbols*? For example, in [tsdoc](https://tsdoc.org/pages/tags/link/), doing this
```
/** Directions of the anchor that are enabled to be picked by the user.
* Pre-defined combinations available through {@link enabledAnchorsCombinations}. */
```
Generates the screenshot
![](https://user-images.githubusercontent.com/6270283/226170266-2b5c8dbd-d47a-42f4-9f75-eb806e5393ea.png)

This command
```lua
:lua vim.lsp.buf_request(0, 'textDocument/hover', vim.lsp.util.make_position_params(), function(_, result, ctx) if not result then return end print(result.contents.value end)
```

Produces (note the link)
````markdown
```typescript
(property) AnchorPickerProps.enabled?: Anchor[] | undefined
```
Directions of the anchor that are enabled to be picked by the user.
Pre-defined combinations available through [enabledAnchorsCombinations](file:///home/sorashi/Projects/bp/schemcat/src/components/AnchorPicker.tsx#L13%2C14).
````

**Comment by glepnir** [comment]
support
