### ISSUE TITLE
Without nvim-web-devicons installed, this plugin constantly blocks the UI with warnings

### ISSUE THREAD

**Issue by samtgarson** [glepnir/lspsaga.nvim#958]
### Describe the bug

Hey, thanks for the amazing OSS effort!

It seems that with a recent release of this plugin, the web dev icons are now a mandatory requirement?

I don't like viewing the icons, and previous releases I was able to disable them, but it seems that in the current release, not only can I not seem to remove them from the UI (there seems to be no way of removing `kind` icons from the symbol winbar), but more importantly the constant warnings from [this function](https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/libs.lua#L25) block my workflow consecutively.

Would you accept a PR for a `ui.icons = false` config option to bail out of that devicons method early? If so I can submit one.

### Steps to reproduce

Run this plugin without the nvim-web-devicons plugin installed.

### Expected behavior

Icons should not be displayed, and the plugin should continue silently.

### Neovim version (nvim -v)

NVIM v0.8.3

### lspsaga commit

44ae62d

### Terminal name/version

iTerm2, Build 3.4.19

**Comment by glepnir** [comment]
I will support this in next version pr.
