### ISSUE TITLE
Question: Disable line Highlight on goto_definition

### ISSUE THREAD

**Issue by tannerellen** [glepnir/lspsaga.nvim#959]
When using the command :Lspsaga goto_defninition the target line highlights with an animated fade. This is really jarring to me and sometimes obscures the view of the target code until the color fades a bit. Is there any way to disable that fade line highlight or maybe make fade time quicker?

 Ideally I would like to disable that all together because the function itself is already a highlighted term at that point so the additional highlight color doesn't seem necessary. 

I looked in the docs and couldn't find anything.

**Comment by glepnir** [comment]
does this not introduced in doc ? maybe i forget. you can config this field
```lua
  beacon = {
    enable = true,
    frequency = 7,
  },
```
