### ISSUE TITLE
Allows opt-in to enable `disable_move_keys` behavior

### ISSUE THREAD

**Issue by sxyazi** [glepnir/lspsaga.nvim#961]
**Is your feature request related to a problem? Please describe.**

I'm using the Colemak layout, and remapped most of keys in the keyboard, so the preset keys in [`disable_move_keys`](https://github.com/glepnir/lspsaga.nvim/blob/04617d1f5b1cfbdd2a99d9765ef04fc6ae415622/lua/lspsaga/libs.lua#L165) don't make sense but conflict with my existing navigation keys.

The same issue occurs here: https://github.com/glepnir/lspsaga.nvim/issues/786

**Describe the solution you'd like**

Add a new option of `disable_move_keys = true`, to allow for opt-out while having consistent behavior.

**Comment by glepnir** [comment]
I will support it in next version.

**Comment by sxyazi** [comment]
Thanks, I am willing to submit a PR for this, it should be easy. 😆

**Comment by glepnir** [comment]
removed this .
