### ISSUE TITLE
Triggers code_action even if diagnostics popup already closed

### ISSUE THREAD

**Issue by wr9dg17** [glepnir/lspsaga.nvim#964]
### Describe the bug

Hello, I would like to thank you for this amazing plugin, it makes my work more efficient but I found some strange behavior. 

When jump between diagnostics (`diagnostics_jump_next / diagnostics_jump_prev`) and select one of provided code_action by index (for example 1 index) popup window is closing and lspsaga executing selected code_action, this works great but when later after executing `code_action` I click some number, for example 12-j for jumping 12 lines down lspsaga executing one of `code_action`, because of number 1. 

### Steps to reproduce

`diagnostics_jump_next()`
select one of `code_action`, for example first one by clicking 1
after diagnostics popup closed type 1 again

### Expected behavior

when diagnostics popup closed it should not trigger `code_action` any more

### Neovim version (nvim -v)

0.8

### lspsaga commit

??

### Terminal name/version

iterm2

**Comment by wr9dg17** [comment]
Here is example video

https://user-images.githubusercontent.com/19671564/227341101-ed79509b-63e3-469c-8d4e-be08c80a90d6.mov

**Comment by glepnir** [comment]
fix in next version if i can reproduce it.

**Comment by wr9dg17** [comment]
@glepnir thank you 🙏
