### ISSUE TITLE
[Feature Request] Allow to use the same key for expand_collapse + open in outline

### ISSUE THREAD

**Issue by mikehaertl** [glepnir/lspsaga.nvim#965]
In the outline  want to use `<CR>` for both:
 * Expand/collapse when on a headline
 * Open when on a method, prop, etc.

Right now that's not possible. 

But both situations can never interfere so I think it makes sense to use the same key.

If you used `<CR>` you'd get the same behavior as with e.g. nvim-tree: expand/collapse when on a directory and open when on a file.

**Comment by glepnir** [comment]
support in next version
