### ISSUE TITLE
Lspfinder showing error

### ISSUE THREAD

**Issue by edward-s** [glepnir/lspsaga.nvim#968]
### Describe the bug

after updating, when using LSP finder, encountered the following error
<img width="1178" alt="Screenshot 2023-03-27 at 10 47 02 AM" src="https://user-images.githubusercontent.com/237278/227828488-c190dba7-cc22-4c1c-8044-f2bf963feff9.png">

### Steps to reproduce

:Lspsaga lsp_finder

### Expected behavior

should show the lsp finder window

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

70f863a

### Terminal name/version

kitty

**Comment by noisyBrain** [comment]
Same bug here, using alacritty

**Comment by glepnir** [comment]
provide reproduce step

**Comment by tannerellen** [comment]
This bug happens to me when trying to invoke lsp finder on something that would normally produce no result. For example go to a blank line in your code or an object property in javascript, invoke lsp finder and that error will appear.

**Comment by tannerellen** [comment]
Just wanted to update... my above statement is only true for lua files. I have now tried this in javascript and svelte files and I get the error reported every time.

**Comment by glepnir** [comment]
IDK how to reproduce it ..

![image](https://user-images.githubusercontent.com/41671631/227850677-b108e8f2-616e-469c-95cd-75e791b66731.png)

**Comment by glepnir** [comment]
can you update and test ?  I fixed some bug in cursormoved .

**Comment by edward-s** [comment]
tried with latest commit, still having the same error

**Comment by glepnir** [comment]
some min code that can reproduce it ?

**Comment by glepnir** [comment]
i tried in c lua typescript go rust ..both work.

![image](https://user-images.githubusercontent.com/41671631/227852677-36435d48-52ec-48d2-999a-338eaf59949c.png)

**Comment by edward-s** [comment]
not sure if this will help

im using default setup
```
require("lspsaga").setup()
```

`:Lspsaga lsp_finder` anywhere in any javascript code

worked using last friday's lspsaga commit

**Comment by glepnir** [comment]
a min js code /

**Comment by edward-s** [comment]
```
const test = () => {
  console.log('hello world');
};
```
:Lspsaga lsp_finder over `test`

**Comment by obmutescences** [comment]
same as me in go.

**Comment by glepnir** [comment]
hmm.. 
![image](https://user-images.githubusercontent.com/41671631/227857536-7ded2649-2444-40f3-b3a0-4ed4a3d1b6da.png)

**Comment by glepnir** [comment]
can you update and test again .. it works for me ..wired.

**Comment by edward-s** [comment]
thanks for the quick update! just updated to newest commit and tried again, getting the same error
`'width' key must be a positive Integer`

**Comment by glepnir** [comment]
I tried a min config can't reproduce it.

**Comment by Gitfz810** [comment]
Same bug in rust; lspsaga version: b5b7c13966fd4b977fb261b6d3fa26bafe3ec6e2

## Configuration of lspsaga
```lua
local status, saga = pcall(require, "lspsaga")
if not status then
  return
end

saga.setup({
  -- keybinds for navigation in lspsaga window
  scroll_preview = { scroll_up = "<C-k>", scroll_down = "<C-j>" },
  -- when there has code action it will show a lightbulb
  lightbulb = {
    enable_in_insert = true,
    sign = false,
  },
  ui = {
    colors = {
      --float window normal bakcground color
      normal_bg = "#1c1c19",
      --title background color
      title_bg = "#afd700",
    },
  },
  beacon = {
    enable = false,
  },
})
```

**Comment by glepnir** [comment]
`colors` has been removed in `0.2.8`. and i tried in rust.

![image](https://user-images.githubusercontent.com/41671631/227859601-d9b01e56-3f22-4c0f-818b-ebebb9b8cd12.png)

**Comment by 0x00-ketsu** [comment]
I 

> some min code that can reproduce it ?

local api = vim.api

api.nvim_command('set nu')
api.nvim_command('set relativenumber')

-- Plugins
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system(
      {
        'git', 'clone', '--filter=blob:none', 'https://github.com/folke/lazy.nvim.git',
        '--branch=stable', -- latest stable release
        lazypath
      }
  )
end
vim.opt.rtp:prepend(lazypath)

-- Example using a list of specs with the default options
vim.g.mapleader = ',' -- Make sure to set `mapleader` before lazy so your mappings are correct

require('lazy').setup(
    {
      -- LuaFormatter off
      {
        'neovim/nvim-lspconfig',
        config = function()
          require'lspconfig'.pyright.setup {}
          require'lspconfig'.gopls.setup {}
        end
      },
      {
        'williamboman/mason.nvim',
        config = function()
          require('mason').setup()
        end
      },
      {'williamboman/mason-lspconfig.nvim'},
      -- LuaFormatter on
      {
        'jose-elias-alvarez/null-ls.nvim',
        config = function()
          local null_ls = require('null-ls')
          local diagnostics = null_ls.builtins.diagnostics
          null_ls.setup {sources = {diagnostics.golangci_lint}}
        end,
        dependencies = {{'nvim-lua/plenary.nvim'}}
      },
      {
        'glepnir/lspsaga.nvim',
        event = 'BufRead',
        config = function()
          require('lspsaga').setup({})
        end,
        dependencies = {{'nvim-tree/nvim-web-devicons'}, {'nvim-treesitter/nvim-treesitter'}}
      }
    }
)

**Comment by glepnir** [comment]
I mean the language code that can reproduce this error.

**Comment by Gitfz810** [comment]
> Same bug in rust; lspsaga version: [b5b7c13](https://github.com/glepnir/lspsaga.nvim/commit/b5b7c13966fd4b977fb261b6d3fa26bafe3ec6e2)
> 
> ## Configuration of lspsaga
> ```lua
> local status, saga = pcall(require, "lspsaga")
> if not status then
>   return
> end
> 
> saga.setup({
>   -- keybinds for navigation in lspsaga window
>   scroll_preview = { scroll_up = "<C-k>", scroll_down = "<C-j>" },
>   -- when there has code action it will show a lightbulb
>   lightbulb = {
>     enable_in_insert = true,
>     sign = false,
>   },
>   ui = {
>     colors = {
>       --float window normal bakcground color
>       normal_bg = "#1c1c19",
>       --title background color
>       title_bg = "#afd700",
>     },
>   },
>   beacon = {
>     enable = false,
>   },
> })
> ```

I remove the `ui.colors` configuration; the bug still here and neovim version is 0.8.3

### Code

```rust
fn main() {
    let name = "lspsaga";
    println!("Hello, {}", name);
}
```

### Configuration

```lua
-- import lspsaga safely
local status, saga = pcall(require, "lspsaga")
if not status then
  return
end

saga.setup({
  -- keybinds for navigation in lspsaga window
  scroll_preview = { scroll_up = "<C-k>", scroll_down = "<C-j>" },
  -- when there has code action it will show a lightbulb
  lightbulb = {
    enable_in_insert = true,
    sign = false,
  },
  beacon = {
    enable = false,
  },
})
```

**Comment by glepnir** [comment]
do you have `null-ls` ?

**Comment by Gitfz810** [comment]
> do you have `null-ls` ?

yes～ 

### Configuration

```lua
-- import null-ls plugin safely
local setup, null_ls = pcall(require, "null-ls")
if not setup then
  vim.notify("null-ls not found")
  return
end

-- for conciseness
local formatting = null_ls.builtins.formatting -- to setup formatters
-- local code_actions = null_ls.builtins.code_actions -- to setup code actions
-- local completion = null_ls.builtins.completion -- to setup completion
local diagnostics = null_ls.builtins.diagnostics -- to setup linters

-- to setup format on save
local augroup = vim.api.nvim_create_augroup("LspFormatting", {})

-- configure null_ls
null_ls.setup({
  -- debug = true, -- enable debug mode and get debug output
  -- setup builtins sources for null-ls
  sources = {
    -- to disable file types use
    -- "formatting.prettier.with({disabled_filetypes = {}})" (see null-ls docs)
    formatting.goimports, -- golang imports
    formatting.gofumpt, -- golang formatter
    formatting.stylua, -- lua formatter
    formatting.buf, -- protocol buffer formatter
    -- formatting.yamlfmt, -- yaml formatter
    formatting.sql_formatter, -- sql formatter
    formatting.jq, -- json formatter
    -- code_actions.cspell, -- spell checker
    -- diagnostics.cspell, -- spell checker
    diagnostics.shellcheck, -- shell script static analysis tool
    -- a tool to verify with .editorconfig, need install ec command
    -- see release: https://github.com/editorconfig-checker/editorconfig-checker/releases
    diagnostics.editorconfig_checker.with({
      disabled_filetypes = { "erlang" }, -- disable in erlang file
    }),
    -- configuration of yamllint: https://yamllint.readthedocs.io/en/stable/configuration.html
    diagnostics.yamllint, -- yaml linter
    diagnostics.buf, -- working with Protocol Buffers
    diagnostics.fish, -- basic linting is available for fish scripts
  },
  -- configure format on save
  on_attach = function(current_client, bufnr)
    if current_client.supports_method("textDocument/formatting") then
      vim.api.nvim_clear_autocmds({ group = augroup, buffer = bufnr })
      vim.api.nvim_create_autocmd("BufWritePre", {
        group = augroup,
        buffer = bufnr,
        callback = function()
          vim.lsp.buf.format({
            filter = function(client)
              --  only use null-ls for formatting instead of lsp server
              return client.name == "null-ls"
            end,
            bufnr = bufnr,
          })
        end,
      })
    end
  end,
})
```

**Comment by noisyBrain** [comment]
So, do you think lspsaga fails becauls null-ls? Why do you think is that?

**Comment by glepnir** [comment]
？  I had fixed this issue
