### ISSUE TITLE
hover navigation doesn't work with preview_definition 

### ISSUE THREAD

**Issue by tami5** [glepnir/lspsaga.nvim#97]
### Description

Hover navigation doesn't work with preview_definition 

**Expected Behavior**

when calling `require'lspsaga.provider'.preview_definition()`, 
`require('lspsaga.hover').smart_scroll_hover(-1/1)` should work, and better yat we should have a config for field for it like find_action_keys

**Actual Behavior**

`require('lspsaga.hover').smart_scroll_hover(-1/1)` navigates the current pages

### Details

<details><summary>Environment</summary>

- nvim --version output: v0.5.0-dev+1085-g52397aaa0
- Operating system: arch
- lspsaga commit: last

</details>

**Comment by glepnir** [comment]
should be improve it. implement it later.

**Comment by tami5** [comment]
Thanks @glepnir

**Comment by hungrybirder** [comment]
The same issue. 
I use 333178b4e.
It doesn't work for navigating  with preview_definition. 

NVIM v0.5.0-dev+a129887c0
MacOS 11.2.3
