### ISSUE TITLE
lsp finder error

### ISSUE THREAD

**Issue by obmutescences** [glepnir/lspsaga.nvim#971]
### Describe the bug

![Snipaste_2023-03-27_15-41-14](https://user-images.githubusercontent.com/29330637/227873900-91c4b090-e095-4fff-9740-465d640a91cc.png)

### Steps to reproduce

lsp finder in golang file with struct method.
```go
type TestStruct struct {}

func (Test *TestStruct) {

}

```
lsp finder in Test key word.
not reproducible in every go file. some has some not, don`t know why

### Expected behavior

nomal

### Neovim version (nvim -v)

0.9.0-dev-1291+gbad218cd6-dirty

### lspsaga commit

last commit 

### Terminal name/version

kitty

**Comment by glepnir** [comment]
lspsaga commit ? in latest it works fine.

**Comment by obmutescences** [comment]
> lspsaga commit ? in latest it works fine. and your code is not correct method name missing.

方法名我漏了，我测试了简单的方法是没有问题的，我项目里有些struct方法，会出现图片上这个报错

**Comment by glepnir** [comment]
in latest commit it will output `no data to show` not throw an error. if your method is not correct. lsp can't parse your code.

**Comment by glepnir** [comment]
update then test.

**Comment by obmutescences** [comment]
> update then test.

我在单独的简单go文件中像这样测试是没有问题的，在我的项目代码中，我在 1 和 2 的位置上 使用 lsp finder 就会出现
![Snipaste_2023-03-27_16-58-18](https://user-images.githubusercontent.com/29330637/227893770-8ae960d1-c617-4b2a-b79e-6b246ccbd6e5.png)
我刚刚拉了最新代码，现在是这个错误
![err2](https://user-images.githubusercontent.com/29330637/227894893-76129067-117d-4b88-80b8-ec73c2aa9e6d.png)

**Comment by glepnir** [comment]
你nvim的窗口有多大。 照着提示做 调整 `finder.min_width`  默认是30 你编辑器窗口小了。 错误这里我修了

**Comment by obmutescences** [comment]
> 你nvim的窗口有多大。 照着提示做 调整 `finder.min_width` 默认是30 你编辑器窗口小了。 错误这里我修了

是窗口大小的问题，现在没有报错了，但是我设置 min_width 有些struct 实现的方法参数太长，导致界面上只能看到匹配的结果，预览的窗口被挤出屏幕外，然后有些struct 实现的方法查看时，只有预览的窗口了，没有结果的窗口

**Comment by glepnir** [comment]
截个图我看下。是finder主窗口太大了 ？预览代码太长了会导致主窗口变宽。 preview能用得久回变少。 但是主要看你nvim的窗口。 整个屏幕是没有问题。 你要是什么tmux分割nvim窗口小 就是这样。

**Comment by obmutescences** [comment]
> 截个图我看下。是finder主窗口太大了 ？预览代码太长了会导致主窗口变宽。 preview能用得久回变少。 但是主要看你nvim的窗口。 整个屏幕是没有问题。 你要是什么tmux分割nvim窗口小 就是这样。

![err2](https://user-images.githubusercontent.com/29330637/227900321-3c2012fd-c514-4710-807d-d1aaff2f7671.png)
![err4](https://user-images.githubusercontent.com/29330637/227900336-a0421b24-d695-4a99-8095-a265db134d34.png)
这是横屏正常屏幕宽度，在竖屏上就是只会显示搜索结果，不会显示预览

**Comment by obmutescences** [comment]
> > 截个图我看下。是finder主窗口太大了 ？预览代码太长了会导致主窗口变宽。 preview能用得久回变少。 但是主要看你nvim的窗口。 整个屏幕是没有问题。 你要是什么tmux分割nvim窗口小 就是这样。
> 
> ![err2](https://user-images.githubusercontent.com/29330637/227900321-3c2012fd-c514-4710-807d-d1aaff2f7671.png) ![err4](https://user-images.githubusercontent.com/29330637/227900336-a0421b24-d695-4a99-8095-a265db134d34.png) 这是横屏正常屏幕宽度，在竖屏上就是只会显示搜索结果，不会显示预览
这两个截图是 横屏上，竖屏就跟第二张图一样

**Comment by glepnir** [comment]
预览代码太长了。。我看能不能缩短一下。。。这些lsp返回的都是准确的单词范围。。vscode是取整行。。我看看写一些正则能不能弄短

**Comment by obmutescences** [comment]
> 预览代码太长了。。我看能不能缩短一下。。。这些lsp返回的都是准确的单词范围。。vscode是取整行。。我看看写一些正则能不能弄短

好的，大佬辛苦了，大佬喝阔乐

**Comment by obmutescences** [comment]
> 更下试试。

可以了，大佬辛苦了
