### ISSUE TITLE
Lsp finder - line number outside range error

### ISSUE THREAD

**Issue by edward-s** [glepnir/lspsaga.nvim#972]
### Describe the bug

Lsp finder, frequent `Line number outside range` errors

![finder](https://user-images.githubusercontent.com/237278/227934122-3c27fda7-79cc-4d63-9dce-280696971413.gif)

### Steps to reproduce

LSP finder often throws out error: `Line number outside range`

Codebase used: https://github.com/devslopes-learn/simple-express-server

### Expected behavior

less errors

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

f62dfcf

### Terminal name/version

kitty

**Comment by glepnir** [comment]
![image](https://user-images.githubusercontent.com/41671631/227935439-9188164a-d047-4d63-a395-ada63b8f6e7f.png)


![image](https://user-images.githubusercontent.com/41671631/227935672-ad79f285-528b-4498-a699-68023225e0d8.png)

**Comment by glepnir** [comment]
please use the min config.

**Comment by glepnir** [comment]
lnum out side not min_width error. and i can't reproduce it .what i mean is please try the min config. only lspsaga and nvim-lspconfig.

**Comment by glepnir** [comment]
lnum out side not min_width error. and i can't reproduce it .what i mean is please try the min config. only lspsaga and nvim-lspconfig.

**Comment by glepnir** [comment]
lnum out side not min_width error. and i can't reproduce it .what i mean is please try the min config. only lspsaga and nvim-lspconfig.

**Comment by edward-s** [comment]
ok, i get it, thanks!
will try and post a solution here if I find out

**Comment by glepnir** [comment]
if you can provide a min config that can reproduce it i will fix.

**Comment by edward-s** [comment]
I found the root cause. The lsp finder is conflicting with another plugin, "neoscroll"

```
use({
  "karb94/neoscroll.nvim",
  config = function()
	  require("neoscroll").setup()
  end,
})
```

after uninstalling neoscroll, i dont get the "line number outside range error",
tried and tested a few times with consistent results, unfortunately i do not know lua enough to help debug the issue
re-opening the issue if you are able to fix, else feel free to close

thanks!

**Comment by glepnir** [comment]
why need i fix ? it's problem of `neoscroll` and  it last update is jan ?

**Comment by edward-s** [comment]
understood, thanks boss
just to help out anyone who's facing the same errors with neoscroll and still want to use lspsaga, switch to another smooth scroll plugin: https://github.com/declancm/cinnamon.nvim
