### ISSUE TITLE
Window is not transparent

### ISSUE THREAD

**Issue by PaoGon** [glepnir/lspsaga.nvim#973]
### Describe the bug

I need to source config first to make the window transparent.
![image](https://user-images.githubusercontent.com/82503757/227942826-af984549-99cb-4cdb-b543-c44e23450000.png)

after sourcing:
![image](https://user-images.githubusercontent.com/82503757/227942923-4fca1be8-ed47-41b1-80d1-fb3ea33f2dbc.png)

### Steps to reproduce

config: 
```lua
require("lspsaga").setup({
  ui = {
    title = true,
    border = "rounded",
    winblend = 0,
    expand = "",
    collapse = "",
    code_action = "💡",
    incoming = " ",
    outgoing = " ",
    hover = ' ',
    kind = {},
  },
})
```

### Expected behavior

I should not need to source the config to get the transparent window

![image](https://user-images.githubusercontent.com/82503757/227943831-015c6a76-7837-4690-b924-b3587d42ce9a.png)

### Neovim version (nvim -v)

NVIM v0.9.0-dev-1291+gbad218cd6

### lspsaga commit

3ae79a1

### Terminal name/version

alacritty 0.9.0

**Comment by glepnir** [comment]
hi normal float
