### ISSUE TITLE
Call hierarchy preview stays open when navigation window is closed

### ISSUE THREAD

**Issue by mikehaertl** [glepnir/lspsaga.nvim#976]
### Describe the bug

When closing the call hierarchy with `:bd` the preview window is left open and can't be closed:

![image](https://user-images.githubusercontent.com/675062/228007977-0b706379-075a-431c-83bd-9b70551d2192.png)

After `:bd`:

![image](https://user-images.githubusercontent.com/675062/228008092-2b64fa40-12a1-48c0-a697-f07d4ca119de.png)

### Steps to reproduce

* `Lspsaga incoming_calls`
* `:bd`

### Expected behavior

The preview window should always close when the navigation window is closed.

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

3ae79a1

### Terminal name/version

Gnome Terminal 3.44.0

**Comment by glepnir** [comment]
just use `q` not use `:bd`

**Comment by mikehaertl** [comment]
I have a shortcut for `:bd` (`<leader>d`) and my fingers are sometimes faster than I can think. I usually can close *every* window with `:bd`. This also works fine in the finder. But not in the caller hierarchy.

**Comment by glepnir** [comment]
fine, support now.

**Comment by mikehaertl** [comment]
Sorry, it still doesn't work. The preview stays open.

**Comment by glepnir** [comment]
can't reproduce.

**Comment by glepnir** [comment]
update .

**Comment by mikehaertl** [comment]
Works, thank you! 👍🏻
