### ISSUE TITLE
Call hierarchy preview coverd by navigation when limited space

### ISSUE THREAD

**Issue by mikehaertl** [glepnir/lspsaga.nvim#977]
### Describe the bug

When the call hierarchy is opened with e.g. nvim-tree open the navigation window will cover the preview window:

Correct:

![image](https://user-images.githubusercontent.com/675062/228008883-a5fc78b8-b37a-4325-b1ea-19b28fb292ff.png)

With nvim-tree open on the left:

![image](https://user-images.githubusercontent.com/675062/228009016-df45fc83-196f-47ae-b861-653c5107a470.png)

### Steps to reproduce

* Open nvim-tree
* `:Lspsaga incoming_calls`

### Expected behavior

Preview should not be covered.

### Neovim version (nvim -v)

0.8.3

### lspsaga commit

3ae79a1

### Terminal name/version

Gnome Terminal 3.44.0

**Comment by glepnir** [comment]
how about now ?

**Comment by mikehaertl** [comment]
Looks good! Thank you.

![image](https://user-images.githubusercontent.com/675062/228214356-d8b5bb1e-3c3f-4fec-ac37-0f199311a56d.png)

**Comment by glepnir** [comment]
maybe it's better it only in code window ?

**Comment by glepnir** [comment]
okay let me think about it .
