### ISSUE TITLE
table of a code_action_keys key doesn't work

### ISSUE THREAD

**Issue by tami5** [glepnir/lspsaga.nvim#98]
### Description

I'm trying to map quite to esc, q and sd :laughing:  due to my musle memory is a bit week. I read somewhere in the code base that this is possible I think it even worked but not for `code_action_keys`

**Expected Behavior**

passing a dict to one of the keys collection should just work.

**Actual Behavior**

Error: trying to concatenate a table

**Comment by tami5** [comment]
Oh i think its only applied in `function Finder:apply_float_map`

**Comment by glepnir** [comment]
now support table type

**Comment by tami5** [comment]
Oh I was about to fix it, nice thanks

**Comment by tami5** [comment]
btw @glepnir this stuff you did is out of this world. Very creative

**Comment by tami5** [comment]
Oh wait I might have a better impl for you , one sec

**Comment by tami5** [comment]
```lua
local function apply_keys(func, keys)
  keys = type(keys) == "string" and {keys} or keys
  vim.tbl_map(function (key)
    api.nvim_command(string.format("nnoremap <buffer><nowait><silent>%s <cmd>lua require('lspsaga.codeaction').%s()<CR>", key,func))
  end, keys)
end

function Action:apply_action_keys()
  local actions = {
    ['quit_action_window'] = config.code_action_keys.quit,
    ['do_code_action'] = config.code_action_keys.exec
  }
  for func, keys in pairs(actions) do
    apply_keys(func, keys)
  end
end

```

**Comment by tami5** [comment]
I think this should be located in the lib with extra param to apply_keys that accept namespace

**Comment by glepnir** [comment]
It looks good, yes, there is a part of the code that is repeated in saga. It is the Chinese New Year recently, so I don’t have time to optimize it.

**Comment by tami5** [comment]
If you accept a pr I can quickly do it

**Comment by tami5** [comment]
oh and happy new year

**Comment by glepnir** [comment]
Thanks . PR welcome.
