### ISSUE TITLE
Lightbulb icon looks strange, maybe font is missing

### ISSUE THREAD

**Issue by janbaer** [glepnir/lspsaga.nvim#997]
### Describe the bug

I just wonder why the icon which should notify me about a possible code action looks a bit strange.

![lightbulb](https://user-images.githubusercontent.com/528331/229892653-11bd229c-f2ba-4917-b7f5-386db59d6384.png)

Which font do I need to install to display it correctly? Thanks!

### Steps to reproduce

Just select a line with possible code action

### Expected behavior

Icon should be shown correctly

### Neovim version (nvim -v)

0.8.0

### lspsaga commit

fb476086012e18e0001c3dcc5b18fd34a847e5fe

### Terminal name/version

Kitty

**Comment by glepnir** [comment]
config kitty symbol font code.

**Comment by janbaer** [comment]
I'm sorry, but I don't get the answer. I have another PC with similar installation where kitty is running with the same configuration, but there the icon is shown correctly.

**Comment by glepnir** [comment]
by default is a emoji so there is nothing i can do. or you can change that icon. and kitty has `symbol_map` for config symbol font.
